### ISSUE TITLE
Multiple selection doesn't start automatically after selecting the first one

### ISSUE THREAD

**Issue by milo-** [cibernox/ember-power-select#100]
I've just started using your addon today. So far it's been pretty awesome!

I've just run into an issue however with the multiple selections. Once you make a choice with the keyboard (pressing enter) the dropdown doesn't reappear after typing further, until you press enter again or backspace.

A video of this is here: https://vid.me/Q3o2

Additionally where I've been using it with async search functionality pressing enter again doesn't make the the results appear. Instead only back space works to make the dropdown reappear.

**Comment by cibernox** [comment]
Yeah, it's pretty tricky to distille the perfect select behavior, I might not have considered that.

At the moment I'm a bit overwhelmed. The component was more or less secret until last week and now suddenly lots of people is using it and bug reports come faster than I can squash them.

If you could have the time to create a failing test cases in https://github.com/cibernox/ember-power-select/blob/master/tests/integration/components/power-select-test.js for those situations then do the actual fix shouldn't take much time.

**Comment by milo-** [comment]
No problem, I'll try and get a failing test put together tomorrow. Hopefully I can also send a PR with a fix for it :)

Thanks!

**Comment by mike183** [comment]
I've been experiencing this issue but just updated from v0.3.5 to v0.5.2 and the issue seems to have been resolved.

**Comment by cibernox** [comment]
Perhaps I fixed on one refactor recently. One of those happy accidents. 

@milo- can you confirm?

**Comment by milo-** [comment]
@cibernox Awesome, it is fixed now. Thanks!
