### ISSUE TITLE
How to use composability

### ISSUE THREAD

**Issue by jrock2004** [cibernox/ember-power-select#1001]
So I need to alter the item that is selected in the dropdown. I thought I would just Add an action in the component js file `selectedItemComponent` but its not firing. Am I misunderstanding how to use?

**Comment by cibernox** [comment]
I need more information about what you want to do and how are you doing it. The main components of the select are covered here: http://www.ember-power-select.com/docs/architecture

**Comment by jrock2004** [comment]
So I have this following dropdown and I want to, on selection of an item, show ` groupname - selecteditem`

![image](https://user-images.githubusercontent.com/655716/31890481-488c7e1c-b7d1-11e7-88d3-11a3ee6127ba.png)

**Comment by cibernox** [comment]
yeah, you should be able to do that with 
```hbs
{{#power-select options=opts selected=selected onchange=(action (mut selected)) selectedItemComponent="my-own-custom-component" as |opt|}}
  {{opt}}
{{/power-select}}
```

**Comment by jrock2004** [comment]
So would this replace whats in the input? So would this replace the text `Licensed Cotten Pizza`?

**Comment by cibernox** [comment]
yes, that component determines what is displayed inside the trigger

**Comment by jrock2004** [comment]
Just to make sure what is highlighted is what is being replaced?

![image](https://user-images.githubusercontent.com/655716/31891564-c611beb2-b7d4-11e7-8e0f-2da4fd7f23ff.png)

**Comment by cibernox** [comment]
yes

**Comment by cibernox** [comment]
@jrock2004 Check the docs about the publicAPI object receive by every component: http://www.ember-power-select.com/docs/api-reference

**Comment by jrock2004** [comment]
Thank you for pointing me to documentation
