### ISSUE TITLE
ember-power-select to large

### ISSUE THREAD

**Issue by hdehaan01** [cibernox/ember-power-select#1008]
I use the power-select component in Ember to provide a select option to the user.
One power select has many options. Initially the list is shown above the component, where the first items of this list are way out of my browser.
If I add the option verticalPosition='below', indeed the list is below the component, but still way to long. There is a scroll bar, but the amount of items in this list visible is to many. I would expect from the variables the amount should be 7, but it is many more.
Attached is screen dump.

Is this a bug, or is there a possibility to define how many items in this list will be visible,

![power_select](https://user-images.githubusercontent.com/11521803/32275580-1312c0ba-bf0c-11e7-9e6c-da1a32b0a6bd.png)

Thanks in advance.
Hans de Haan

**Comment by cibernox** [comment]
By default the number of options should be limited by CSS: https://github.com/cibernox/ember-power-select/blob/master/app/styles/ember-power-select.scss#L196-L199

I don't know why it's displaying all the options. Can you investigate if there is any style overriding that max-height?

**Comment by cibernox** [comment]
Closing this, as I think it's just a CSS issue.
