### ISSUE TITLE
Detect scroll in ember-power-select

### ISSUE THREAD

**Issue by g8anush** [cibernox/ember-power-select#1010]
Hi,

Is there any way to detect / trigger an action when the dropdown is scrolled?

I tried scrollTo but doesn't work.

Thanks in advance!

**Comment by cibernox** [comment]
It's not built in, but since you can replace the `optionsComponent` with your own, you can do:

```hbs
{{#power-select 
  options=opts 
  selected=selected 
  onchange=(action (mut selected)) 
  optionsComponent=(component "my-custom-options" onScroll=(action "doSomething"))
  as |opt|
  {{opt}}
{{/power-select}}
```

Your custom component only has to extend from the default one:
```js
import PowerSelectOptions from 'ember-power-select/components/power-select/options";
export default PowerSelectOptions.extend({
  // do something here to handle scroll
})
```

**Comment by g8anush** [comment]
Hi, thank you! But I get numerous errors like, scrollTop is undefined.. Do I need to send options to the component or anything? I tried to send but still not getting. And, I got an error initially that the action I gave on onScroll is not present in the current component. So, I declared that action method in the parent component as well.

Please help.

**Comment by g8anush** [comment]
It breaks in scrollTo method of power-select, where optionElement is null. What am I missing?
