### ISSUE TITLE
Working with the Data Store

### ISSUE THREAD

**Issue by namack** [cibernox/ember-power-select#102]
Can you please elaborate in the docs about how to use this with data that is in the store? It is great so far to follow along and build an example using static arrays set in the controller, but when it comes to more real world usage where the array is coming from the store, things get blurry fast (especially for those of us who are still getting used to Ember!).

Let me know if there is anything I can do to help! This project already has stellar docs, so it'd be great to make them even better.

Thanks!

**Comment by cibernox** [comment]
One of the goals of this addon was to be able to use collections of ember data (like the result of operations like `store.findAll()` and `store.query()`) transparently, so that's why there is no special chapter for them.

Are you facing any issue in particular?

**Comment by namack** [comment]
Yes, I am having trouble loading data into the component from the route. My router is loading the initial set data using the `model()` hook. This part works perfectly fine, and I am able to filter through all of the records in the store at the time the `model()` hook is called.

The trouble comes in when I try to use the `search` to query my API. When I implement the `search` parameter, I have it calling an action in my controller that makes requests to the API. The response from the API is loaded successfully in the `store`, however these records do not appear in the dropdown (likely because this array was already set using `findAll()` in the original `model()` hook.

I assume I am loading the data from the `store` incorrectly in the `search controller, but it

**Comment by namack** [comment]
Also, one part that has been tough to decipher what to do with is the `options` argument. In the beginning of the docs, it is stated that this is the only required argument. However, in the `asynchronous-search` example, where the `search` argument is used, there is not `options` argument. I assume there is some freedom to control what the array is through the `search` argument and its associated action, however this is difficult to decipher.

**Comment by cibernox** [comment]
Ok, so let see if I can clarify the situation.

The component requires either `options` or `search` to be provided, but you can provide both.

* When providing only `options` I guess that it's clear already, because is the most straightforward case.

* When providing a `search` function, that function will be invoked when the user types, and whatever it's returned from that function becomes the new collection of options. The result can be a collection or a promise that resolves to a collection and should be handled automatically (otherwise there is a bug). Results from operations like `store.findAll` or `store.query` fall in this latter category (they are "thenables").

* When providing both `options` and `search` is mostly like only providing `search` with exception that the collection inside `options` is used as the initial list of results, but as soon as the user forms a searches that takes precedence.

Does this explanation help?

**Comment by namack** [comment]
Ok, thanks for the explanation. That mostly fits what I assumed is happening.

The original issue that the search action/query puts more records into the store, however the list is not being refreshed on screen with the new data. 

The only way to show the new data that as been inserted as a result of the search query is to click out of the select component and then click it again. Now, the new records do show up in the list, however they are not filtered as the user types (even the original list initialized by `options` is not filtering out).

It seems that the new array being returned by `search` is not actually being used in the component. Am I returning the array incorrectly?

_Template_
```handlebars
{{#power-select
    options=countries
    selected=selected
    onchange=(action (mut selected))
    search=(action 'searchCountries')
    as |country|
}}
  {{country}}
{{/power-select}}
```

_Controller_
```javascript
countries: ["america", "canada", "mexico"],

actions: {
  searchCountries(term) {
    var countries = this.get('countries');
    countries.push(term);
    this.set('countries', countries);
    return countries;
  },
}
```

This is a simple example of how it is failing for me. Am I doing something incorrectly here?

**Comment by cibernox** [comment]
Hmm, I don't get what you're trying to do with that action, but you're doing more than just returning the new array of results. 

Try this quicky:

```js
countries: ["america", "canada", "mexico", "france"],

actions: {
  searchCountries(term) {
    // return the array with the new results
    return this.get('countries').filter(country => country.indexOf(term) > -1);
  },
}
```

**Comment by cibernox** [comment]
My guess is that since you're both returning an array and also updating the collection at the same time some race condition happens and I'm not sure which one takes precedence.

**Comment by namack** [comment]
Ah ok that makes sense, I'll try that. That example was just a simplified version of what I'm really doing with the search action:
```javascript
searchRetailers(term) {
  this.store.filter('retailer', { q: term }, function(model) {
    return model.get('q');
  });
}
```
So now I'll return the new array based on those filter results.

**Comment by cibernox** [comment]
Hmm, actually `store.filter` **might** be a problem. I haven't considered it because it was removed from ember-data long time ago. The problem is that new data added to the store will be added to this collection but I'm not sure if the addon will keep track of that.

I know because [I tested it](https://github.com/cibernox/ember-power-select/blob/master/tests/integration/components/power-select-test.js#L1901-L1943) that `findAll`, `query`,  and `hasMany` relationships work, but I haven't tested `store.filter`.

**Comment by namack** [comment]
Oh ok... I don't necessarily need to use `store.filter`. Honestly, it was just the first thing that worked successfully to send query requests to the API.

**Comment by cibernox** [comment]
In that case `store.query` is what you're looking for. I should investigate what happens with `store.filter` anyway. It's not in ember-data anymore but still a fair amount of people uses it.

**Comment by cibernox** [comment]
Either way, if from this you've extracted any idea that you feel wasn't clear enough in the guides, I do care about good docs.

**Comment by namack** [comment]
Has `store.filter` been removed from ember-data? I still see it in the [API docs](http://emberjs.com/api/data/classes/DS.Store.html#method_filter), and it is really providing the functionality we are looking for. 

The main goal is to send a request to the API that queries for `term` while then returning a filtered array of the data already in the `store`. Ideally, once the response is received from the API, the `store` will contain the new record and it can then be considered for filtering.

Returning the result of `store.query` only relies on the API to do the filtering. This means we have to wait for a network request between every keystroke, even if the desired record is already in the `store`.

Is this desired functionality possible with `ember-power-select`?

**Comment by namack** [comment]
In order to get the desired functionality described above, we came up with the following code:
```javascript
searchRetailers(term) {
  var retailers = this.store.peekAll('retailer');
  if (Ember.isBlank(term)) { return this.store.peekAll('retailer') }

  var request = this.store.query('retailer', { q: term });

  var localRetailers = new Promise((resolve, reject) => {
    resolve(this.store.peekAll('retailer'));
  });

  return request.then(() => {
    return localRetailers.then(function(retailers) {
      return retailers.filter(function(retailer) {
        var nameMatches = retailer.get('name').toLowerCase().indexOf(term.toLowerCase()) > -1;
        var sortNameMatches = retailer.get('sortName').toLowerCase().indexOf(term.toLowerCase()) > -1;
        return nameMatches || sortNameMatches;
      })
    }).then(function(array) {
      return array;
    });
  }).catch((reason) => {
    return this.store.peekAll('retailer').filter(function(retailer) {
      var nameMatches = retailer.get('name').toLowerCase().indexOf(term.toLowerCase()) > -1;
      var sortNameMatches = retailer.get('sortName').toLowerCase().indexOf(term.toLowerCase()) > -1;
      return nameMatches || sortNameMatches;
    });
  });
},
```
However this seems overly verbose - is this the only way to make this work since `store.filter()` is not supported? (the `.catch()` takes into account a total loss of network connectivity while searching).

**Comment by cibernox** [comment]
I certainly need to ensure that `store.filter` works. Regardless of the fact that it was extracted into an addon, this problem would affect also to regular arrays to which elements are added/removed without replacing the array.

I will investigate a way of keep track of additions/removals to collections, and that should make filter work too.

**Comment by namack** [comment]
Sounds good - otherwise the docs are great and very easy to follow. I'd love to contribute to them if possible, just let me know if there is anything I can do to help.

Thanks for being so responsive.
