### ISSUE TITLE
(select.selected || []).slice is not a function

### ISSUE THREAD

**Issue by bkl1989** [cibernox/ember-power-select#1033]
Upon rendering a form, I am getting the following console error

```
power-select-multiple.js:82 Uncaught TypeError: (select.selected || []).slice is not a function
    at Class.buildSelection (power-select-multiple.js:82)
```

From my power-select-multiple shown below:

```
{{#power-select-multiple
  options=options
  searchField="name"
  selected=selected
  placeholder="Type or select a group (Required)"
  onchange=onchange
  disabled=false
  as |group|
}}
  {{group.name}}
{{/power-select-multiple}}
```

`options` is an array of Ember Data records. `selected` is an Ember mutable array of length zero.

This was all previously working before I updated my node modules. I can provide more detail if asked, but I am not sure where to begin. It just stopped working.

**Comment by cibernox** [comment]
i'll need more information to know what is going on. Can you create a reproduction?

**Comment by bkl1989** [comment]
Darn. I was hoping you'd just recognize it right away. Will do. 

I can give you a template file which alone will reproduce the issue in my project, but I'm not sure that's sufficient, as there are other variables at play in that case. How would it be best for me to go about creating the reproduction?

**Comment by jgelens** [comment]
This occurred when selected was not an array in my case. Easy to fix, difficult to spot.

**Comment by cibernox** [comment]
That makes sense. `selected` **must** be an array in multiple selects, even when there is only one item.
