### ISSUE TITLE
trigger onkeydown in acceptance testing

### ISSUE THREAD

**Issue by ashrafhasson** [cibernox/ember-power-select#1041]
In one acceptance test that uses [ember-page-object](http://ember-cli-page-object.js.org/docs/v1.12.x/), I've been trying to simulate hitting the "enter" key while the search box of a select menu is open but could not get it right. I have something similar to the [onkeydown action handling example](https://ember-power-select.com/docs/action-handling) and it's working fine but in test I couldn't get it to trigger the `keypress` event.

In the page-object, I defined two functions to populate a value and hit enter:

```javascript
  fillinPowerSelectSearch(account) { selectSearch('.account-number', account); return this; },
  triggerPowerSelectSearchBoxEnter: triggerable('keypress', '.ember-power-select-search-input', { eventProperties: { keyCode: 13 } }),
```
The search box gets populated with the value but this doesn't seem to trigger enter afterwards.
Any idea how to get this to work please?

Thanks,

**Comment by cibernox** [comment]
I'm not very familiar with ember-page-object, but I'd use the `keyEvent` helper from `ember-native-dom-helpers` to do it:

```js
keyEvent('.ember-power-select-search-input', 'keydown', 13)
```

There is nothing particular about the way this is handled in EPS really.

**Comment by ashrafhasson** [comment]
`keyEvent` works well if used directly in the acceptance test. If I include it in ember-page-object, I can't chain the function that uses it for some reason (possibly my lack of understanding on how to do this) but that's not related to EPS.

Thanks for the quick response and thanks for your awesome addon!
