### ISSUE TITLE
Add Click Action to `afterOptionsComponent`

### ISSUE THREAD

**Issue by donaldwasserman** [cibernox/ember-power-select#1047]
I'm trying to create a pagable select list but I can't figure out how a way to get actions out of the `afterOptionsComponent`. 

I don't know if there's a way to do it currently, or if the best way is to add additional contextual actions, or if there's a path forward with ember-scrollable to add an `scrolledToBottom` event to load more.

**Comment by mattmcginnis** [comment]
I'm seeing this issue as well.  How do actions get passed into the afterOptionsComponent if neither of the following works?
`
{{#power-select
  afterOptionsComponent='some-component'
  someAction=(action 'someAction')
  ...
}}

{{#power-select
  afterOptionsComponent='some-component'
  someAction='someAction'
  ...
}}
`
Maybe I'm missing something here.

**Comment by mattmcginnis** [comment]
I'll answer my own question and possibly OP's.  Here's how to pass actions to the afterOptionsComponent:
```
  afterOptionsComponent=(
    component 'some-component'
    someAction=(action 'someAction')
  )
```

**Comment by mattmcginnis** [comment]
Similarly, you can get access to the public API from within the afterOptionsComonent like this:
```
{{#power-select
  registerAPI=(action (mut selectRemoteController))
  afterOptionsComponent=(
    component 'some-component'
    selectRemoteController=selectRemoteController
  )
  as |name|
}}
```
```
// some-component
actions: {
    close() {
      this.get('selectRemoteController').actions.close();
    }
}
```

**Comment by donaldwasserman** [comment]
Wow - I didn't realize that was possible. I assume that's an component helper thing. Is there somewhere that's documented @mattmcginnis?
