### ISSUE TITLE
onblur/onfocus events fired after selecting item from dropdown

### ISSUE THREAD

**Issue by n8n8baby** [cibernox/ember-power-select#1050]
Intuitively, the onfocus event should fire only when the trigger is entered the first time, and the onblur event should fire only when the trigger is unfocused for an external focus (not for dropdown select).

This behavior occurs on the main docs page: http://ember-power-select.com/docs/action-handling

**Comment by cibernox** [comment]
I know it might seem a bit unintuitive, but the focus/blur event are fired when many things inside the select gets focused or blurred. When you select an item by clicking on it you are focusing the option (that is what clicking on something does) but immediately after the trigger is focused again when the component closes.

The docs kind of warn about this:
> Note that this action will be fired when the component or another element inside, like the searchboxes, gain the focus, and sometimes you need which one triggered the focus/blur event. Since the FocusEvent is received as last argument, you can check event.target to know what element gets the focus, and event.relatedTarget to know the element that had the focus before.

You can use the event and see the `target` and `relatedTarget` to know from where does the focus originally come from and detect when the focus is coming from the outside.

**Comment by cibernox** [comment]
I'll close it for now, let me know if you need further help.

**Comment by shankarsridhar** [comment]
My workaround: 
use `event.stopImmediatePropagation();` inside the action passed to `onclose`
