### ISSUE TITLE
perform is not a helper

### ISSUE THREAD

**Issue by arturalkaim** [cibernox/ember-power-select#1054]
Hi, 

I'm having `perform is not a helper` error which is blocking the usage of my app.

Anyone has seen this issue before?

My code:

```
  {{#power-select
    search=(perform search)
    selected=selected
    onchange=(action 'select')
    renderInPlace=true
    disabled=disabled
    placeholder=placeholder
    allowClear=false
  as |item select|}}
```

Thanks!

**Comment by cibernox** [comment]
This is unrelated with ember-power-select really. Perform is a helper provided by `ember-concurrency`. You must install it to use it. 

I mentioned it in the docs because it's very popular, but it's completely optional.
