### ISSUE TITLE
Options with a `length` property may cause unnecessary iteration on selection

### ISSUE THREAD

**Issue by timmorey** [cibernox/ember-power-select#1064]
I have a set of pojo options that represent database fields, they have properties like `name`, `type`, and `length`.

Upon selecting one of the options, the `power-select` component performs some unnecessary iteration, mistaking the option for an array.  This can cause noticeable lag when the `length` is very large.

The code that does the iteration: https://github.com/cibernox/ember-power-select/blob/bf68b2d280fd080e7f65fab270e5569b6ea341e4/addon/helpers/ember-power-select-is-selected.js#L10-L17

Edit: an easy workaround to this was to simply rename `length` to `fieldLength`, or to omit properties not needed for rendering the option.

**Comment by cibernox** [comment]
This is tricky as it's the default behavior of `isEmberArray`, a built-in ember construct to detect thinks like Ember.A or ember-data collections. Since those are relatively common, I think I prefer to leave things as they are, and force people to make the workaround that you mentioned.
