### ISSUE TITLE
How to focus on input after power-select-multiple is rendered?

### ISSUE THREAD

**Issue by rayjcwu** [cibernox/ember-power-select#1070]
I want to be able to search right after the webpage is rendered, instead of click on the search box then start typing.
However when I trying to mimic `focusInput` in original source code, it doesn't work.

It could be reproduced by visit 
https://ember-power-select.com/docs/multiple-selection
and run `document.querySelector('.ember-power-select-trigger-multiple-input').focus()` which is focus on an `input` tag.

I expected to see something like this
![screen shot 2018-02-28 at 1 44 06 pm](https://user-images.githubusercontent.com/4761728/36814827-9d9b0fce-1c8d-11e8-98d5-36038dcf6477.png)

and could start typing, but nothing happened.

I also tried to `.click()` on all parent html elements of that `input`, but nothing happened

Any help?

**Comment by cibernox** [comment]
That is normal. 
`document.querySelector('.ember-power-select-trigger-multiple-input').focus()` does work and the input gets focused. If you type something results will appear.

If focusing is not enough and you also want to open it, please note that the select is not opened on "click", but on "mousedown" (like native selects do). So you need to trigger a mousedown event:

```js
    let input = document.querySelector('.ember-power-select-trigger-multiple-input');
    input.dispatchEvent(new MouseEvent('mousedown', { bubbles: true }));
```

**Comment by rayjcwu** [comment]
thank you 👍
