### ISSUE TITLE
Uncaught TypeError: Cannot read property 'addEventListener' of undefined

### ISSUE THREAD

**Issue by bedrosenator** [cibernox/ember-power-select#1076]
It happens after transition to a page, where power-select was rendered before.
Uncaught TypeError: Cannot read property 'addEventListener' of undefined
    at Class.stopTextSelectionUntilMouseup (trigger.js:206)
    at Class.handleMouseDown (trigger.js:114)
    at Class.send (ember.debug.js:43117)
    at Class.superWrapper [as send] (ember.debug.js:42834)
    at HTMLDivElement.<anonymous> (trigger.js:223)

**Comment by mehanika** [comment]
I'm having the same issue, Im using ember-power-select inside a component (could be that the issue?).
What I've see is that `self.document` is `undefined` and it crash when calls `addEventListener`

```
stopTextSelectionUntilMouseup: function stopTextSelectionUntilMouseup() {
      self.document.addEventListener('mouseup', this._mouseupHandler, true);
      self.document.body.classList.add('ember-basic-dropdown-text-select-disabled');
    },
```

**Comment by cibernox** [comment]
weird. Could make a PR removing the `self.` part? At the end, it's just redundant. `document` is a global that should be everywhere (except fastboot obviously)

**Comment by mehanika** [comment]
@cibernox Is there any reason why it was used `self.document` or `self.window`?

**Comment by cibernox** [comment]
Honestly, no. 
I think that at some point in the past I setup a linter that disallowed any global, even things like window and document so I added `self.` to make it happy.

**Comment by mehanika** [comment]
I've created the first pull request to `ember-basic-dropdown`, given that the error occurs in trigger.js [#402](https://github.com/cibernox/ember-basic-dropdown/pull/402)

**Comment by cibernox** [comment]
@mehanika I've published a new beta of EBD. Since the dependency of EPS in EBD is `^`, if you update your dependencies you should get the new version. 

Let me know of the bug seems fixed and I'll close this.

**Comment by mehanika** [comment]
@cibernox Well, all the errors related to trigger.js are fixed now. But EPS also uses `self.window` and `self.document` and I get the following errors:

```
ember.debug.js:26513 TypeError: Cannot read property 'querySelector' of undefined
    at Class.focusInput (before-options.js:44)
    at Class.didInsertElement (before-options.js:17)
    at Class.superWrapper [as didInsertElement] (ember.debug.js:45374)
    at Class.trigger (ember.debug.js:47407)
    at Class.superWrapper [as trigger] (ember.debug.js:45374)
    at CurlyComponentManager.didCreate (ember.debug.js:19505)
    at Transaction.commit (ember.debug.js:6252)
    at Environment.commit (ember.debug.js:6427)
    at Environment.commit (ember.debug.js:16526)
    at InteractiveRenderer._renderRoots (ember.debug.js:18805)
```

I will create a pull request for removing `self.window` and `self.document` from EPS.

**Comment by mehanika** [comment]
After changing the log the `self` was added again on EBD as you can see in this commit [930d2ea](https://github.com/cibernox/ember-basic-dropdown/commit/930d2ea550f8d71db6619c3f14c6c0c49f522b47) @cibernox . So it won't work yet
