### ISSUE TITLE
Add lifecycle (and maybe other) hooks to API?

### ISSUE THREAD

**Issue by jcaffey** [cibernox/ember-power-select#1084]
I'm stuck on a problem at the moment where all I really need is access to `select/publicAPI` on init. Other than extending power select, is there a way to access the public API on init or didInsertElement without extending power select?

I think it would be a great addition to the API, especially for addon developers. At least things like `afterInit`, `afterDidInsertElement`, etc... and just fallback if undefined. Are addon developers expected to extend power select in these cases?

Is that silly?

**Comment by jcaffey** [comment]
@cibernox a penny for your thoughts, sir.

**Comment by cibernox** [comment]
Sorry, I missed this completely.
I assume you mean that you need access to the public APi _from the parent component_, correct?
There is a `registerAPI=` argument you can use to store the public API of the select, and IIRC it is called upon initialization of EPS. 

I'm pretty sure that if you invoke EPS from another component the `init` of your component will happen before the `init` of EPS, but by the time your parent components receives `didInsertElement` you should have access to it.
