### ISSUE TITLE
error ember-power-select-requires-onchange-function-errror

### ISSUE THREAD

**Issue by NodeMario** [cibernox/ember-power-select#109]
I am not sure if its a bug with ember power select. I posted this on stackover flow with no luck
http://stackoverflow.com/questions/33553070/ember-power-select-requires-onchange-function-errror

**Comment by cibernox** [comment]
It's because of a bug in Ember. This component requires a newer version of ember:

From the readme:

> Ember Power Select works in Ember 1.13.9+ or 2.0+, including beta and canary, with no deprecations whatsoever.

**Comment by cibernox** [comment]
Just update to 1.13.10 should fix your problem :smile:

**Comment by NodeMario** [comment]
thanks :). It works
