### ISSUE TITLE
Error with ember 3.1

### ISSUE THREAD

**Issue by Titinux** [cibernox/ember-power-select#1094]
Hi, I recently updated ember to version 3.1 and now ember-power-select is not working if I use the selected option.

```htmlbars
{{#power-select options=layouts
    selected=selectedLayout
    onchange=(action (mut selectedLayout)) as |layout|}}
  {{layout.name}}
{{/power-select}}
```

layouts is the result of
```javascript
this.get('store').findAll('layout')
```
The error message is 

```
Error: Assertion Failed: You attempted to access the `then` property (of <(unknown mixin):ember757>).
Since Ember 3.1, this is usually fine as you no longer need to use `.get()`
to access computed properties. However, in this case, the object in question
is a special kind of Ember object (a proxy). Therefore, it is still necessary
to use `.get('then')` in this case.

If you encountered this error because of third-party code that you don't control,
there is more information at https://github.com/emberjs/ember.js/issues/16148, and
you can help us improve this error message by telling us more about what happened in
this situation.
```

it seems to come from this line
https://github.com/cibernox/ember-power-select/blob/97621afa0284a2034a52684d80bbf766a981bb43/addon/components/power-select.js#L141

**Comment by cibernox** [comment]
Yeah, someone reported it in https://github.com/emberjs/ember.js/issues/16148#issuecomment-380671426 but I don't have a clear understanding of what the fix is. I'll try to allocate some time to investigate it, but if you have time by all means, go for it.

**Comment by cibernox** [comment]
Released in 2.0.0-beta.4

**Comment by huberts** [comment]
I tried to pindown this bug, but I have no working (simple) example. I have spotted this in my application, but it was so deep down nested it could not work as a snippet. I will take the beta.4 version and check it. Thanks!

**Comment by andrewtimberlake** [comment]
This is still a problem with ember-power-select@2.0.1
If I remove the `selected=` the error goes away.

It happens after the above mentioned  `if(selected && selected.then)`, which is changed.
It happens within the call to `this.get('_updateSelectedTask').perform(selected);`

Error:
```
Error: Assertion Failed: You attempted to access the `then` property (of <(unknown mixin):ember1188>).
Since Ember 3.1, this is usually fine as you no longer need to use `.get()`
to access computed properties. However, in this case, the object in question
is a special kind of Ember object (a proxy). Therefore, it is still necessary
to use `.get('then')` in this case.
```

**Comment by cibernox** [comment]
If you're in the latest version it means you still have an old version of ember-concurrency installed. Can you update EC and see how it goes?

**Comment by andrewtimberlake** [comment]
Updated, still an error with ember-concurrency@0.8.19

**Comment by donaldwasserman** [comment]
Strange - I use this all over my app and don't really see this error. Is it on Ember 3.1?

**Comment by cibernox** [comment]
What would help. Perhaps that's the problem and it just happens that I haven't exercised that code.

**Comment by cibernox** [comment]
Just in case I release a new version in which I which I replaced `if (obj.then)` by `if (get(obj, 'then')`. Check if that helps.

**Comment by andrewtimberlake** [comment]
@cibernox, That didn’t change things.

I have put up a test repo that reproduces a similar issue. I am running my model through Ember Changeset which seems to be the cause of the problem. I don’t know if the problem is with Ember Changeset or with the fact that EC returns a proxy object.
The repo is at https://github.com/andrewtimberlake/ember-power-select-test-1094

**Comment by donaldwasserman** [comment]
I think it's because the relationship returns as `DS.PromiseObject` can you try making the relationship `DS.BelongsTo('user', {async: false})` and then make sure the record is loaded into the store?

**Comment by andrewtimberlake** [comment]
Thanks everyone for the help.
`{async: false}` and preloading was the answer
