### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by velrest** [cibernox/ember-power-select#1103]
![screenshot](https://user-images.githubusercontent.com/15276514/39372241-1ef5b338-4a44-11e8-9e0c-5706ecf20266.png)

In the last sentence on this [page](https://ember-power-select.com/docs/test-helpers) is a typo. I guess it should mean `complex` instead of `complec`.

Thank you for this addon!

**Comment by cibernox** [comment]
Fixed. Thanks!
