### ISSUE TITLE
Error: power-select + changeset + relationship

### ISSUE THREAD

**Issue by huberts** [cibernox/ember-power-select#1109]
Hello!

I recently tried to pinpoint an error in this project, and I think I have got a test case.
When I try to use power-select to select a belongTo relationship on changeset-ed object, it gives me an error message, pointing me to [the issue from EmberJS about new getters and setters](https://github.com/emberjs/ember.js/issues/16148).
[Here](https://github.com/huberts/ember-power-select-test) is my repository of a new Ember app that presents this error.
If you want to see the case, you have to change the model file parent.js (comment one line, uncomment the other).
Is this a bug in power-select, or I should change the way I use my changesets?
Best regards,

HubertS

**Comment by huberts** [comment]
After further investigations I must say the problem lies in relationships mixed with changesets. The ember-power-select addon is not the issue - it is just the place where I clearly noticed the problem with others.

**Comment by csprocket777** [comment]
@huberts What was your ultimate solution to this issue? I'm running into the same currently.
