### ISSUE TITLE
Set `min-width` dynamically like `width`?

### ISSUE THREAD

**Issue by threecleartones** [cibernox/ember-power-select#1112]
I'm poking at EPS (and my JS is not strong), and I'm wondering if it's possible to set `min-width` on the dropdown in the same way that `top`, `left` and `width` are currently set. It looks like, by default, `width` is set inline on the dropdown element and uses `matchTriggerWidth` to match the width of the dropdown to the trigger width (makes sense).

Here's what I'm trying to achieve:

If one or more of the dropdown options exceeds the width of the trigger, I want the dropdown width to be as wide as the longest option. I'm currently achieving this by overriding the inline `width` value with `width: auto !important;` in my CSS.

However, when I reset `width` to `auto` this way, then if all the dropdown options are shorter (less wide) than the trigger width, the dropdown width is less wide than the trigger, which looks weird.

So what I think would work (hopefully not missing something) is if I could somehow configure EPS to set `min-width` inline on the element to `matchTriggerWidth`, the way it currently does for `width`, and set `width` to `auto` (or just omit `width`, since that's the default). That would allow the dropdown width to expand if any of the options are wider than the trigger, but the dropdown width would still match the trigger width if the options are all shorter than the trigger width.

The only thing I'd need to think about then would be how to handle options that are really really really wide - I'd probably set a `max-width` on the dropdown and either wrap or ellipse the options if they exceed that width (we're trying to avoid scrolling).

Thanks!

**Comment by cibernox** [comment]
Someone had this need recently I made some changes to accomodate it. Let me see if I can find the issue.

**Comment by cibernox** [comment]
This is the PR in that allows that to happen: https://github.com/cibernox/ember-basic-dropdown/pull/394

Essentially, if you want to apply styles on the dropdown that need to be calculated dynamically you need to pass a `calculatePosition=myOwnFunction`. You can read more about that in http://ember-basic-dropdown.com/docs/custom-position

Everything you put inside `style` (p.e. `{ style: { 'min-width': 300px } }` will be applied to the dropdown.
If the default behaviour is correct and you only want to **add** that, you can reuse the original function like:

```js
import { calculatePosition } from 'ember-basic-dropdown/utils/calculate-position'

export default Controller.extend({
  calculatePosition() {
    let originalValue = calculatePosition(...arguments);
    originalValue.style['min-width'] = 123px; // add only extra info, reuse the rest
    return originalValue;
  }
});
```

**Comment by threecleartones** [comment]
This looks like exactly what I'm looking for - I'll give it a try, thanks!

**Comment by cibernox** [comment]
I'm closing it for now. Reopen it if you have problems.
