### ISSUE TITLE
Spelling mistake on "The List" page

### ISSUE THREAD

**Issue by acorncom** [cibernox/ember-power-select#112]
On http://www.ember-power-select.com/docs/the-list just above "The empty state" header, the word dropdown is misspelled.

![screen shot 2015-11-10 at 8 53 57 pm](https://cloud.githubusercontent.com/assets/802505/11083493/5f5a40e0-87ed-11e5-88cd-a9c6a3f0dfc4.png)

**Comment by cibernox** [comment]
Fixed. Thanks!
