### ISSUE TITLE
IE11 gives all multi-select triggers focus by default

### ISSUE THREAD

**Issue by blamens** [cibernox/ember-power-select#1127]
I have a issue with our app (which we just upgraded to `ember-source: 3.2.2`) and I noticed all the `ember-power-select-multiple` components are getting focus after render in IE11. 

So I figured id check the demo site and http://ember-power-select.com/docs/multiple-selection/ opens up the demo dropdown aswell. 

Can anyone verify this? Im using Internet Explorer 11.0.9600.19036.

**Comment by goo32** [comment]
I'm on the same version of IE 11 and I'm not seeing that behavior. However I am seeing the placeholder render temporarily and then disappear.

**Comment by nightire** [comment]
I'm seeing this as well, only on the multiple-selection component.
