### ISSUE TITLE
Using power-select with belongsTo

### ISSUE THREAD

**Issue by psteininger** [cibernox/ember-power-select#1131]
Hi,

I am having the hardest time getting power-select with ember-bootstrap working. I want to be able to type in a string and have power select run a task, which sets the `filteredItems` property.

Here's the form:
```hbs
{{#bs-form formLayout='horizontal' model=changeset as |form|}}
      {{form.element
        controlType="text"
        property="name"
        label=(t 'attributes.flow.name')
      }}
      {{form.element
        controlType="power-select"
        property="firstItem"
        label=(t 'attributes.flow.first_item')
        search=(action "searchItems")
        options=filteredItems
      }}
 {{/bs-form}}
```
Here is the component:
```javascript
export default Component.extend({

  flow: null,

  init() {
    this._super(...arguments);
    // set(this, 'filteredItems', []);
    set(this, 'changeset', new Changeset(get(this,'flow'), lookupValidator(FlowValidations), FlowValidations));
  },

  searchItems: task(function* (term) {
    yield timeout(DEBOUNCE_MS);
    let items = yield get(this, 'store').query('item', {filter: {'text': term}});
    set(this, 'filteredItems', items);

  }).restartable(),

  actions:{
    searchItems(searchTerm) {
      get(this, 'searchItems').perform(searchTerm);
    }
  }
});
```
and finally the model:
```javascript
export default Model.extend({
  firstItem: belongsTo('item'),
  name: attr('string'),
  .... more stuff here ....
});
```
When I type a definite match the search does not fire and I see no list. If I use a block form, and move the search into the control, then search works, but selection doesn't. Any ideas what could be wrong?

**Comment by goo32** [comment]
Not sure if this will help but try calling your search function with perform directly and get rid of the corresponding action . Also your search action should return the filtered list. Then wire up the onchange property to the belongsTo attribute.

```
search=(perform "searchItems")
onchange=(action (mut property))
```

**Comment by psteininger** [comment]
I discovered that this is an issue with ember-changeset. I tried the buffered proxy and it all worked as expected.
