### ISSUE TITLE
Error accessing the `length` property directly with Ember 3.1 or more recent

### ISSUE THREAD

**Issue by jpsirois** [cibernox/ember-power-select#1133]
The error I get :

![screen shot 2018-07-12 at 11 10 37](https://user-images.githubusercontent.com/151262/42642561-1e417ae6-85c5-11e8-948a-070ba487edea.png)
![screen shot 2018-07-12 at 11 11 30](https://user-images.githubusercontent.com/151262/42642567-203c546a-85c5-11e8-87cb-4a4cfb7f77c4.png)

The `power-select` implementation that cause the issue:

![screen shot 2018-07-12 at 11 38 11](https://user-images.githubusercontent.com/151262/42643923-4e6ecbe4-85c8-11e8-8bd3-897eb60e211d.png)

It only happen when there’s an `hasMany` relation : 

![screen shot 2018-07-12 at 11 41 33](https://user-images.githubusercontent.com/151262/42644207-01662d00-85c9-11e8-90c5-cf05e9f5bacf.png)

Here’s the version of the packages I’ve tried it with, with always the same results
`ember-cli`: `~3.2.0`
`ember-data`: `^3.2.0`
`ember-source`: `~3.2.2`
`ember-changeset`: `1.4.1` and `1.5.0-beta.0`
`ember-power-select`: `1.9.10` and `2.0.4`
`ember-power-select-with-create`: `^0.5.1` and `^0.6.0`

**Comment by jpsirois** [comment]
Turn out the issue came from `ember-changeset@1.4.2` that is included by `ember-changeset-validations@1.2.11`. 

If I keep an older version of `ember-changeset-validations@1.2.8` it work.

**Comment by abobwhite** [comment]
@jpsirois What's the status of this issue for you? 

I am using 

`ember-cli: 3.6.0 `
`ember-data: 3.6.0 `
`ember-source: 3.6.0 `
`ember-changeset: 1.6.0 `
`ember-changeset-validations: 1.3.3 `
`ember-power-select: 2.2.1` (and `master`)

And seeing the exact same issue (hasMany on a changeset)
