### ISSUE TITLE
Power Select Multiple Crashes Ember Inspector

### ISSUE THREAD

**Issue by hadiwina** [cibernox/ember-power-select#1139]
First of all, thanks for the great work on this Addon!

We're currently implementing `{{power-select-multiple}}` in one of our component and currently seeing some maximum call stack when opening the Ember Inspector.

![screen shot 2018-07-27 at 4 19 38 pm](https://user-images.githubusercontent.com/5366783/43344775-f4240e86-91b8-11e8-88f8-6b8adbbbd07e.png)

To be honest, I'm not entirely sure where this is coming from. I tried removing stuff that I added but even in the bare minimum below, we're still seeing this crash in Ember Inspector.

```hbs
{{#power-select-multiple search=(action "searchUser") onchange=(action "selectUser") as | user |}}
    <div class="user-option">
        {{option}}
    </div>
{{/power-select-multiple}}
```

The current version we use is "1.10.0" as we're in Ember 2.8 still right now.

Is there any idea where to look first to debug this?

**Comment by hadiwina** [comment]
This is no longer an issue for me. Closing this! Thanks!

**Comment by cluis13915** [comment]
@hadiwina How do you fixed it bro ? I have same issue for a long time, but I haven't had time to investigate. I'am on Ember 2.9.1.
