### ISSUE TITLE
Default click behavior breaks in Chrome when upgrading from Ember 2.18 to 3.1

### ISSUE THREAD

**Issue by goo32** [cibernox/ember-power-select#1141]
The default behavior in Ember 2.18 when clicking on the trigger: the search input is displayed, focused and ready to start typing.

After upgrading to Ember 3.1 and only in Chrome (I've only tested in Chrome and IE 11) the input does not focus so you can't just start typing.

You can see this in the first example in the [How to use it](https://ember-power-select.com/docs/how-to-use-it) docs.

**Comment by nickschot** [comment]
I think I'm also seeing this issue (ember 3.4 e-p-s 2.0.8). Hope to be able to debug it later in the week.

**Comment by cibernox** [comment]
I missed this initially. I can also reproduce the bug. I'll try to find a moment to debug it.
