### ISSUE TITLE
Make Highlight on mouseover optional

### ISSUE THREAD

**Issue by cah-danmonroe** [cibernox/ember-power-select#1152]
in `options.js` please make the following line optional so when the user mouses over options in the list, they won't be automatically highlighted/selected.  

If they happen to have the cursor below the control and tab through the fields on a form, they will accidentally change the selected value when perhaps they didn't intend to change it.

`this.element.addEventListener('mouseover', (e) => findOptionAndPerform(this.get('select.actions.highlight'), e));`

**Comment by petermoore14** [comment]
Fairly certain the addition of `highlightOnHover` addresses this.

**Comment by cah-danmonroe** [comment]
Yup, I did that PR.  Closing.
