### ISSUE TITLE
Problems getting data in powerselect dropdown, fine on the rest of the template..

### ISSUE THREAD

**Issue by ChristopherJohnson25** [cibernox/ember-power-select#1153]
I'm having some issues with Ember Power Select. I'm able to deal with my data properly alone on the template, but for some reason power select won't let me get to any of the data from the fetch call in my component code below...

components/flight-search.js

    import Component from '@ember/component';
    
    export default Component.extend({
      flightResults: null,
      airResults: null,
      actions: {
        searchIATA(term) {
          let query = `https://iatacodes.org/api/v6/autocomplete?api_key=e7c1b7cf-62fb-440c-a0ef-4facebe1ab86&query=${term}`;
          return fetch(query).then(function(response) {
            return response.json();
          }).then(results => {
            this.set('airResults', results);
          });
        },
      }
    });

components/flight-search.hbs

    {{#each airResults.response.airports as |airport|}}
      {{airport.name}} - {{airport.code}}
    {{/each}}
    
    {{#power-select-typeahead
      search=(action "searchIATA")
      triggerClass="bootstrap-theme-trigger"
      dropdownClass="slide-fade bootstrap-theme-dropdown"
      selected=selectedType
      loadingMessage="Searching..."
      placeholder="e.g. New York, NY"
      onchange=(action (mut selectedType))
      as |result|
    }}
    <div class="-detail">
      {{result.response.airports.name}}
    </div>
    {{/power-select-typeahead}}

Also tried this alternative 
```
{{#power-select-typeahead
  search=(action "searchIATA")
  triggerClass="bootstrap-theme-trigger"
  dropdownClass="slide-fade bootstrap-theme-dropdown"
  selected=selectedType
  loadingMessage="Searching..."
  placeholder="e.g. New York, NY"
  onchange=(action (mut selectedType))
  as |airResults|
}}
<div class="-detail">
  {{airResults.response.airports.name}}
</div>
{{/power-select-typeahead}}
```
Notice above and outside of power select I've illustrated that I can get my data as needed.

Much appreciated, thanks!

**Comment by cibernox** [comment]
The problem is that your search action must return a collection of results or a promise that resolves to it. The promise chain that you are returning resolves to undefined. Try adding a return before the `this.set('airResults', results);`
