### ISSUE TITLE
Options component broken in fastboot

### ISSUE THREAD

**Issue by nickschot** [cibernox/ember-power-select#1154]
https://github.com/cibernox/ember-power-select/blob/7ffe3f0a3d2fdc7132b3bf991245d93610f0ef7c/addon/components/power-select/options.js#L6-L23

The above polyfill results in an infinite rendering invalidation in a fastboot environment.

The basic error:
`TypeError: Cannot read property 'prototype' of undefined`

I think we could just wrap it in a:
```
if(typeof FastBoot === undefined){
    ... polyfill ...
}
```

**Comment by sbflynn** [comment]
This PR breaks the polyfill when run in IE11 - it looks like it is not applied. EPS works fine when using 2.0.5 but upgrading to 2.0.7 produces a "Object doesn't support property or method 'closest'" error at this line here (in IE11 only) ...

https://github.com/cibernox/ember-power-select/blob/4d7297dca3cb3f876bb328c832e5cddc32db6f08/addon/components/power-select/options.js#L41

**Comment by nickschot** [comment]
@sbflynn my mistake, #1157 should fix it.

**Comment by cibernox** [comment]
@sbflynn Fixed in 2.0.8
