### ISSUE TITLE
Requesting Assistance: How to use selected with partial value...

### ISSUE THREAD

**Issue by melriffe** [cibernox/ember-power-select#1171]
Sorry for hijacking the Issues for a request for help. If there's a better place for this please let me know where. However, until then...

I have the following in my template:
```
{{#power-select
searchField="value"
selected=model.claim.patient.country
options=model.patientCountries
onchange=(action "choosePatientCountry") as |patientCountry|}}
  {{patientCountry.value}} - {{patientCountry.description}}
{{/power-select}}
```

In my `patient` model I have the value 'US' stored in the `country` attribute. But my list of is comprised of entries that contain "US - UNITED STATES". I believe this is why there is no value selected.

I'm new to all of this so I'm not sure what options I have available to me. Is there something I can do to help power-select match on the first 2 characters of the options?

Thanks, in advance, for any assistance.

**Comment by akursat** [comment]
Just create a substring [helper](https://guides.emberjs.com/release/templates/writing-helpers/) and use  like selected=(substring "model.claim.patient.country" 2)

**Comment by melriffe** [comment]
@akursat Thank you for the suggestion. I hadn't thought about it because I'm new to Ember, and Javascript, development. I will try to implement what you suggested. Thanks, again.

**Comment by lougreenwood** [comment]
@melriffe you should check out the Ember Discord Community, you'll find lots of help there:

https://discordapp.com/invite/zT3asNS

**Comment by melriffe** [comment]
Thanks for the suggestion @lougreenwood

**Comment by cibernox** [comment]
Glad to see that the community answers question faster than myself 😃
