### ISSUE TITLE
Write "directly" into the dropdown?

### ISSUE THREAD

**Issue by flyrev** [cibernox/ember-power-select#1184]
Is it possible to make it look like one is typing directly into the dropdown?

See "Search Selection" on https://semantic-ui.com/modules/dropdown.html for an example

**Comment by flyrev** [comment]
It seems that `power-select-multiple` allows this.

**Comment by Bouke** [comment]
@flyrev did you manage to customize the component to match semantic's style? I think their dropdown looks good and would like to replicate that design with this component.
