### ISSUE TITLE
Check "selected" according to condition

### ISSUE THREAD

**Issue by Ivan-Uspensky** [cibernox/ember-power-select#1186]
Hi! For some reasons cannot create separate value for "selected" state and I need to set "selected" based on condition result.  

```
{{#power-select
  options=reviewers
  searchField="label"
  searchPlaceholder="Type to search..."
  allowClear=true
  selected=(if (eq translation.reviewer item.value) true)
  placeholder="Select Reviewer"
  onchange=(action "reviewerChange" translation.reviewer) as |item|}}
    {{item.label}}
{{/power-select}}
```
What happens here: I render list of reviewers inside some parent component, where I have `translation.reviewer` data. Every reviewer is object from two params - `value` and `label`. I need to take current item from `reviewers` and check its `value` with `translation.reviewer` data. If they are equal - set `selected` to `true` for current item.
I did this approach to basic Select and it worked OK, but I need to to this also to PowerSelect component, and I don't understand how.
How can I achieve this?

**Comment by cibernox** [comment]
I think you've missunderstood the public API of the component. `selected` is not supposed to be a boolean value, but the selected value. In this case, it should be one of the `reviewers`.

**Comment by Ivan-Uspensky** [comment]
Okay, how can I choose appropriate item based on condition?

**Comment by Ivan-Uspensky** [comment]
Unfortunately no

**Comment by cibernox** [comment]
Then I'd need an example to grasp what you're trying to do. Maybe in ember-twiddle can be used for that.

**Comment by Ivan-Uspensky** [comment]
<div style="position: relative; height: 0px; overflow: hidden; max-width: 100%; padding-bottom: 56.25%;"><iframe src="https://ember-twiddle.com/02e4d8ce54ccd215bcefb2f901e8e3a5?fullScreen=true" style="position: absolute; top: 0px; left: 0px; width: 100%; height: 100%;"></iframe></div>

**Comment by Ivan-Uspensky** [comment]
https://ember-twiddle.com/02e4d8ce54ccd215bcefb2f901e8e3a5?fullScreen=true

**Comment by Ivan-Uspensky** [comment]
I've got "Share twiddle" link:
https://ember-twiddle.com/916680af6ea6440c5f9b87e5d820682f?openFiles=controllers.application.js%2C

**Comment by cibernox** [comment]
I'm not sure I understood what you want to do, but maybe this? https://ember-twiddle.com/3215198cfb5897f4f21385ffe08e58a9?openFiles=styles.app.css%2C

**Comment by Ivan-Uspensky** [comment]
Yes, I've just wanted to do this one. Didn't know about 'find-by' helper. Thank you!

**Comment by cibernox** [comment]
@Ivan-Uspensky the `find-by` helper is not a default helper, but as you see in the twiddle it's a one-liner. Super easy to implement.
