### ISSUE TITLE
Nothing is rendered when I click the select

### ISSUE THREAD

**Issue by ivanhueso** [cibernox/ember-power-select#1187]
I've used the plugin for a very long time without a problem. 

However since over last two weeks I've notice that the plugin stop working on my LIVE environment. Still works on localhost. 

When I start debugging I find out that Nothing is rendered on "ember-basic-dropdown-wormhole" when I click the select.

 I've try the renderInPlace=true and manually add "ember-basic-dropdown-wormhole" in application.hbs but the issue still persist.

I've also notice that on mobile by touching it works just fine on live. Also I've  the typeahead plugin which also works fine.

I'm using the latest Ember CLI and I'm not getting back any warning or issues So I'm clueless of what could be the issue.

**Comment by ivanhueso** [comment]
This just happen when I want to click to open the dropdown. 
However on mobile when I touch it it opens. and Also I've the typeahead plugin which also works. It's very strange.. I get no errors at all!

**Comment by ivanhueso** [comment]
I've also tried the renderInPlace=true and it doesn't work either. 

On my localhost when I ember serve all works, on live it doesn't.

**Comment by cibernox** [comment]
I haven't seen any report like that before. What happens if you run `ember s -e production` locally?

**Comment by ivanhueso** [comment]
Ok I've download the live version and now it the same issue over my localhost. Check it out live I'm using it many places for instance on top right "the dropdown to change languages".
http://www.ivanhueso.com

**Comment by cibernox** [comment]
Something weird is going on there. Clicking it doesn't open it, but clicking on it (so the trigger gets the focus) and pressing enter/space does open it. Super weird. There must be something else at play there.

**Comment by kboucher** [comment]
I too am experiencing this same issue (works fine in a local development environment, but fails in a production build). Unlike cibernox's report above, however, I cannot activate the dropdown with the spacebar/enter key (though I do see the arrow change direction and can occasionally fill the field with one of the values sent to the component).

Ember: 3.28.9
ember-power-select: 5.0.4
