### ISSUE TITLE
selectChoose helper breaks because of basic-dropdown [aria-owns] update

### ISSUE THREAD

**Issue by Pixelik** [cibernox/ember-power-select#1191]
Hi @cibernox,

ember-basic-dropdown was recently [updated](https://github.com/cibernox/ember-basic-dropdown/commit/ea6a03d6979fe2de840f3d6d5b9399ee1a9e4f23) and now `aria-owns` will not exist in the trigger unless the dropdown is opened

However, the **selectChoose** power-select test-helper [still assumes](https://github.com/cibernox/ember-power-select/blob/master/addon-test-support/index.js#L28) that `aria-owns` will always be there so the latest combination of the two addons breaks in our codebase.

**Comment by cibernox** [comment]
@Pixelik It has just been fixed. Update EPS.
