### ISSUE TITLE
class constructors must be invoked with |new| TaskProperty

### ISSUE THREAD

**Issue by esbanarango** [cibernox/ember-power-select#1192]
After upgrading to `"ember-source": "~3.6.0":

<img width="874" alt="screen shot 2018-12-11 at 10 58 44 am" src="https://user-images.githubusercontent.com/1156865/49812608-c7ad8f80-fd33-11e8-9952-e5261f645877.png">

![image 2018-12-11 at 11 06 33 am](https://user-images.githubusercontent.com/1156865/49813424-6b4b6f80-fd35-11e8-9f73-7767fe5195e7.png)

We need to upgrade  `ember-concurrency`, current version is `^0.8.19`

This issue was solved on [ember-concurrency 0.8.24](https://github.com/machty/ember-concurrency/releases/tag/0.8.24) (https://github.com/machty/ember-concurrency/issues/261#issuecomment-445608528)

**Comment by belgoros** [comment]
The same after upgrading Ember to `3.7.1`.

**Comment by cibernox** [comment]
I believe the problem lies in the version of ember-concurrency, and EPS just happens to hit that bug. Updating ember-concurrency should fix it.
