### ISSUE TITLE
Option to fallback to native select in mobile

### ISSUE THREAD

**Issue by cibernox** [cibernox/ember-power-select#12]
Not all selects can be transformed into native selects, but for those that can it might be a nice addition. Obviously as an opt-in behaviour.

**Comment by sandstrom** [comment]
I think this is easier to solve via `{{#if isMobile}} {{! render plain select}} {{else}} {{ember-power-select ...}} {{/if}}`. (just my opinion, I understand if you feel different)

**Comment by cibernox** [comment]
Oh, yes, the basics are that simple. I was thinking in creating a `{{power-select-native-fallback}}` component that basically knows how to detect certain criteria (iOS/Android/blind reader) and fallbacks intelligently, and also has some assertions/warnings to warn the user that when something is not possible to fallback, like per example async searches.

I haven't had the need myself.

**Comment by cibernox** [comment]
There is already an addon `ember-power-select-with-fallback` for this, so this can be closed.
