### ISSUE TITLE
New release for updated dependencies

### ISSUE THREAD

**Issue by williamhaley** [cibernox/ember-power-select#1202]
Sorry if I'm off track on this, but...

It seems `ember-concurrency` version `^0.8.19` is not compatible with Ember 3.6 due to this issue: https://github.com/machty/ember-concurrency/issues/271 (see here too - https://github.com/machty/ember-concurrency/issues/275) 

```
Uncaught TypeError: Class constructor ComputedProperty cannot be invoked without 'new'
    at new TaskProperty
    at task
```

Seems the latest `ember-concurrency` resolves that issue.

I see that `ember-power-select` was updated from `ember-concurrency` `^0.8.19` here, https://github.com/cibernox/ember-power-select/commit/df6564fbf785bcd29fe9770661176d0ef1ddef8d

However, I don't think there's been a release of `ember-power-select` since then. The yarn pkg registries still have power select using the old concurrency addon, and so power select latest isn't working for me on my newly updated Ember app.

Would a new `ember-power-select` release resolve that? In the meantime I updated my dependency like so `    "ember-power-select": "cibernox/ember-power-select#df6564fbf785bcd29fe9770661176d0ef1ddef8d"` as a workaround in `package.json` and that's working for the interim.

**Comment by Krzyrok** [comment]
If you use yarn, you can try to remove the record (`ember-concurrency` for `ember-power-calendar`) from `yarn.lock` (or equivalent in npm `package-lock.json`) and reinstall `ember-power-select` - it should install newer version (compatible with new ember). In my case it helped: https://github.com/machty/ember-concurrency/issues/275#issuecomment-459752376

**Comment by BobrImperator** [comment]
I second that, in my case it did the work too.
It looked like this:
```
ember-concurrency
Found: 0.8.19, 0.9.0
Project
├── ember-concurrency@0.9.0
├─┬ 
│ └─┬ 
│   ├─┬ ember-power-calendar
│   │ └── ember-concurrency@0.8.19
│   └─┬ ember-power-select
│     └── ember-concurrency@0.8.19
└─┬ 
  ├─┬ ember-power-calendar
  │ └── ember-concurrency@0.8.19
  └─┬ ember-power-select
    └── ember-concurrency@0.8.19
```

In yarn.lock I've removed:
```
ember-concurrency@^0.8.1, ember-concurrency@^0.8.19:
  version "0.8.19"
  resolved "https://npm2.ac-project.net/repository/registry.yarnpkg.com-proxy/ember-concurrency/-/ember-concurrency-0.8.19.tgz#71b9c175ba077865310029cb4bdb880e17d5155e"
  integrity sha1-cbnBdboHeGUxACnLS9uIDhfVFV4=
  dependencies:
    babel-core "^6.24.1"
    ember-cli-babel "^6.8.2"
    ember-maybe-import-regenerator "^0.1.5"
```
then `yarn install`

and it was swapped to:
```
ember-concurrency@^0.8.1, ember-concurrency@^0.8.19:
  version "0.8.27"
  resolved "https://registry.yarnpkg.com/ember-concurrency/-/ember-concurrency-0.8.27.tgz#6dd1b9928cf5d13d5ae9c8cd3d5869f6ff81a9a9"
  integrity sha512-2IujJ0Y79a+sHvEOPhUtZ7Ga8HDrwjbQqO7aZ88b0KCsXPro7birQFB508njQSQ0mxrsR9qzDv/KS5V67Cy5dA==
  dependencies:
    babel-core "^6.24.1"
    ember-cli-babel "^6.8.2"
    ember-maybe-import-regenerator "^0.1.5"
```
Now everything's up and running ;)
