### ISSUE TITLE
ember-concurrency 0.9 has issues - allow 0.8.x as dependency as well?

### ISSUE THREAD

**Issue by mydea** [cibernox/ember-power-select#1219]
We are experiencing various issues with updating to ember-concurrency 0.9. Basically, everything breaks, and I'm not quite sure why - see also https://github.com/machty/ember-concurrency/issues/285.

Since this addon depends on 0.9.0, this kind of forces us to update or add manual resolutions to prevent multiple versions.

What do you think about relaxing the dependency version, to `"ember-concurrency": "~0.8.27 || ~0.9.0"`?

**Comment by cibernox** [comment]
That sounds like a good idea. The only reason why I updated is to support
some very new version of Ember, but I you're in an older one I don't care
what version of ember-concurrency your app uses.

Go ahead, I'll merge it.
