### ISSUE TITLE
"power-select-multiple requires a searchField" thrown incorrectly

### ISSUE THREAD

**Issue by lolmaus** [cibernox/ember-power-select#1223]
Steps to reproduce:

1. Create a power select with multiple enabled and without a search field.
2. Pass a list of options with a disabled element, make the disabled element pre-selected.
3. Click the trigger so that it expands and receives focus.
4. Press <kbd>Backspace</kbd> on the keyboard.

Expected behavior: nothing happens, the selected item remains, no error message appears. Users tend to press random keys at times, it should *not* crash the app.

Actual behavior:

* An error is thrown: *Assertion Failed: `{{power-select-multiple}}` requires a `searchField` when the options are not strings to remove options using backspace*.
* The item disappears! <img src="https://user-images.githubusercontent.com/200884/56975249-0f18a900-6b79-11e9-88a8-991811923085.png" alt="wtf" width="40">
* The `onchange` action is NOT called, preventing me from intercepting the removal of the selected element.

**Comment by cibernox** [comment]
@lolmaus that is expected (the assertion being thrown, the rest is possibly a consequence of everything blowing up). Deleting an element transforms it into text, and for that it needs the `searchField`.

Arguably, in this case, since the selected items are disabled we should early exit without deleting (that is assuming that disabled elements cannot be selected, which I think it's resonable but it didn't occur to me until now, I thought of those element as elements you can't select, not unselect).

**Comment by lolmaus** [comment]
> it didn't occur to me until now, I thought of those element as elements you can't select, not unselect

Yeah, we have a case of undeletable (enforced) elements. An owner has a list of allowed pet names. A user can't remove a pet name from an owner if that name is assigned to a pet.

Regardless, how can blowing up be expected? That's kinda ridiculous.

If my power select configuration is invalid, it should blow up eagerly on init. I want to know about invalid configuration during development and not after deploying to production, from a client.

If `searchField` is not provided, why can't it simply ignore the <kbd>Backspace</kbd> and not flip out? I have not activated the search field, the user is not supposed to type anything.

**Comment by cibernox** [comment]
@lolmaus if you can put together a PR with a failing test I think I can fix it on thursday (tomorrow it's a holiday here)

**Comment by lolmaus** [comment]
Ok, I've learned that passing `@searchEnabled={{false}}` resolves the issue for me.

**Comment by lolmaus** [comment]
Maybe `searchEnabled` should be off by default?

That would prevent the default configuration from spitting errors and removing unremovable items.
