### ISSUE TITLE
[Documentaion] 'onChange' did not render the component. Update it to 'onchange' to make it work

### ISSUE THREAD

**Issue by prabakaranfresh** [cibernox/ember-power-select#1241]
When I tried to replicate the same as in the documentation, the component did not render. As I went through few trial and errors, I found the dropdown rendering after I changed the **`onChange`** to **`onchange`** (_case sensitive_).

If I am not wrong, Can you please update the same in the documents?

**Comment by cibernox** [comment]
What version of the addon are you using and what version of the docs are you checking? Seems that you are looking for using V2 but reading the docs for V3

**Comment by prabakaranfresh** [comment]
Oops! I see that now. But when I entered power-select docs, it got me to the V3 version and in the installation section, it was mentioned to `ember install ember-power-select` which installed version 2.3.4.

Anyway, thank you for your response.
