### ISSUE TITLE
PowerSelectMultiple shows two search inputs when searchEnabled=true 

### ISSUE THREAD

**Issue by XuluWarrior** [cibernox/ember-power-select#1249]
In the example in the website (https://ember-power-select.com/docs/multiple-selection/) when typing a search, both the search inputs defined in `power-select-multiple/trigger.hbs` and `power-select/before-optinon.hbs` are displayed. 

```
<PowerSelectMultiple
  @searchEnabled={{true}}
  @options={{names}}
  @selected={{name}}
  @placeholder="Select some names..."
  @onChange={{action (mut name)}} as |name|>
  {{name}}
</PowerSelectMultiple>
```

![image](https://user-images.githubusercontent.com/7773288/61535359-002fed00-aa2a-11e9-9ae2-e1e62ceee29e.png)

(The CSS is also a bit off, masking some of the search text.  But that's a different issue)

**Comment by cibernox** [comment]
Good catch!

**Comment by XuluWarrior** [comment]
Thank you very much for your prompt response.
Our tests now pass again 👍
