### ISSUE TITLE
AngleBracket Syntax - what am I missing?

### ISSUE THREAD

**Issue by fran-worley** [cibernox/ember-power-select#1257]
This is either a bug or the docs need updating as I'm getting the following error:

Error: Assertion Failed: <PowerSelect> requires an `@onChange` function

for the following component:

```ruby
<PowerSelect
   @options={{this.options}}
  @selected={{this.model.radius}}
  @renderInPlace="true"
  @onChange={{action (mut this.model.radius)}}
  @searchEnabled="false"
as |option|>
  {{option}} mile
</PowerSelect>
```
The onKeydown example here https://ember-power-select.com/docs/action-handling seems to indicate that the `action` and `mut` helper still works.

As you can see, I've got an onChange function set for my power select so I'm not sure why I'm getting the error I'm seeing - any ideas?

**Comment by cibernox** [comment]
Are you in the latest version of this addon? Also, are you in ember 3.11?

**Comment by fran-worley** [comment]
I am indeed:

"ember-cli": "~3.11.0",
"ember-source": "~3.11.1",
"ember-power-select": "^3.0.1"

**Comment by cibernox** [comment]
Something else must be going on because action and mut do work. In fact the docs are just an ember app and that you see in the template is what is actually being run.

**Comment by cibernox** [comment]
Can you check with `npm/yarn list ember-power-select` if that is effectively the version being installed? Can you reproduce this on a blank ember app?

**Comment by fran-worley** [comment]
/Projects/my-ember-app
└── ember-power-select@3.0.2

**Comment by cibernox** [comment]
@fran-worley can you then reproduce it consistently in a new ember app? If so, can you share a repo with that blank ember app so I can figure out what is going on?

Also, I've noted that you are passing `@renderInPlace="true"` and `@searchEnabled="false"`. In angle bracket syntax if you want to pass a boolean you have to pass `={{true}}` or `={{false}}`, otherwise you're passing the strings "true" and "false". And since 3.0 `searchEnabled` is false by default, so no need to pass it.

Not that it's related with your problem, but I realized just now.

**Comment by fran-worley** [comment]
@cibernox I'll try and get something up for you today. I spotted my error with the "true" after I posted but didn't want to trigger lots of unnecessary emails/ edit notices given that it wouldn't have any impact on my issue. Didn't spot the searchEnabled change so will update that - thanks!

**Comment by fran-worley** [comment]
@cibernox so I'm not entirely sure what was going on here as I definitely restarted the app server about a dozen times but having brought this up on a new laptop it's working perfectly with my example above so I think we can safely close this! Thanks for you input so far and taking the time to update this wonderful addon.

**Comment by cibernox** [comment]
glad it's fixed!
