### ISSUE TITLE
Onchange action assertion fails

### ISSUE THREAD

**Issue by szsoppa** [cibernox/ember-power-select#126]
I followed example from official documentation page with a simple names array. I've declared simple foo action with coffeescript:
````
foo: ->
  console.log('foo')
````
and assign it with emblem in template like this: 
````
power-select options=names onchange="foo" as |name|
    li = name
````
I've tried also to set it this way:
````
power-select options=names onchange=(action "foo") as |name|
    li = name
````
In both examples I get:
`Assertion Failed: {{ember-power-select}} requires an onchange function` I thought it might be an issue with emblem but hbs gave me same result. Important thing to add is the fact that action is set properly because using it with a button and click action work fine.

**Comment by cibernox** [comment]
It's because you need ember 1.13.9 or newer to use this addon.

**Comment by cibernox** [comment]
For the record, the correct usage is the second one, with `onchange=(action "foo")`.

Let me know if that fixes it.

**Comment by szsoppa** [comment]
Thank you for response, now it works fine ;)
