### ISSUE TITLE
Setting calculatePosition when extending Power Select 3.x

### ISSUE THREAD

**Issue by mayatron** [cibernox/ember-power-select#1262]
Hi,

I'm trying to extend Power Select 3.0.3 to globally override the `calculatePosition` function. This worked for me in 2.x but I haven't been able to do it since the 3.x upgrade. Any ideas?

```
import PowerSelect from 'ember-power-select/components/power-select';

export default PowerSelect.extend({
  onClose() {
    console.log('This is called, for example.');
  },

  calculatePosition() {
    console.log('This is never called.');
  },
});
```

Cheers, thanks!

**Comment by cibernox** [comment]
This should be fixed in 3.0.4
