### ISSUE TITLE
Error "Assertion Failed" with Ember 3.8 (& 3.9)

### ISSUE THREAD

**Issue by boesi** [cibernox/ember-power-select#1265]
I created a new ember project, only add ember-power-select and just implement the first example from the [documentation](https://ember-power-select.com/docs/how-to-use-it).

With Ember 3.10 and above it works fine. But with Ember 3.8 and 3.9 I get the following error:
```
Uncaught Error: Assertion Failed: computed expects a function or an object as last argument.
    at assert (index.js:163)
    at new ComputedProperty (metal.js:2757)
    at computed (metal.js:3220)
    at Module.callback (power-select.js:52)
    at Module.exports (loader.js:106)
    at Module._reify (loader.js:143)
    at Module.reify (loader.js:130)
    at Module.exports (loader.js:104)
    at requireModule (loader.js:27)
    at Class._extractDefaultExport (index.js:426)
```
Ember 3.8 is a LTS release and I can't find any hint, that Ember 3.10 is needed. So is that on purpose?

This happens with Ember Power Select 3.0.0 and above. Version 2.3.5 is fine with Ember 3.8 and 3.12, I only need to change `@onChange` to `@onchange`.

**Comment by fran-worley** [comment]
@boesi version 3 only supports ember 3.11 and above - see the change log entry - https://github.com/cibernox/ember-power-select/blob/master/CHANGELOG.md#300-beta1 

You'll need to downgrade your version of ember-power-select to continue to use it with older versions of ember.

**Comment by cibernox** [comment]
@boesi that's indeed true. Try updating you version of Ember.
