### ISSUE TITLE
Assertion Failed: computed expects a function or an object as last argument.

### ISSUE THREAD

**Issue by fitra90** [cibernox/ember-power-select#1268]
I'm installing power select on my current project, but resulting error "Assertion failed". I just copy the sample code and just didn't works.

**Comment by basicBrogrammer** [comment]
Did you figure out the problem? I'm running into the same issue.

**Comment by fitra90** [comment]
I end up change to ember-power-select-blockless, and works just like what I want
https://github.com/cibernox/ember-power-select-blockless

**Comment by corrspt** [comment]
@basicBrogrammer You might need to update your EmberJS version, I think this is a duplicate of https://github.com/cibernox/ember-power-select/issues/1265
