### ISSUE TITLE
Assertion thrown after updating to Ember 3.14

### ISSUE THREAD

**Issue by Windvis** [cibernox/ember-power-select#1294]
# Version info
Ember: 3.14
Ember Power Select version: 3.0.4
Ember Basic Dropdown version: 2.0.10

# Problem description
After updating our app to Ember 3.14 (coming from 3.12 LTS) we started seeing the following console error:

```
Error: Assertion Failed: You're trying to attach the content of a dropdown to an node with ID ember-basic-dropdown-wormhole, but there is no node with that ID in the document. This can happen when your Ember app is not in control of the index.html page. Check https://ember-power-select.com/docs/troubleshooting for more information
```

Someone in the discord experienced [the same problem](https://discordapp.com/channels/480462759797063690/486202731766349824/638823119120760875). Moving `{{content-for "body-footer"}}` above the script tags _does_ fix the problem, but that doesn't seem like an ideal solution to me.

Any idea what could be causing this? And why it only started happening after updating?

**Comment by Jaesaces** [comment]
I get the same problem in Ember CLI 3.13.1, also using ember-power-select version 3.0.4.

I noticed that the issue occurs when trying directly loading the page containing a power select, but does not occur if you start on a different page in the same application then navigate to it.

**Comment by victornamuso** [comment]
I'm seeing the same as @Jaesaces

**Comment by cibernox** [comment]
I believe that this has been fixed in the latest version, can you check?
