### ISSUE TITLE
ember-power-select + octane + fastboot => unable to render dropdown

### ISSUE THREAD

**Issue by lifeart** [cibernox/ember-power-select#1298]
given:

![image](https://user-images.githubusercontent.com/1360552/69655239-31c75d80-1087-11ea-8ef5-d9392b857169.png)

with `http://localhost:4200/?fastboot=false query param I get different error

![image](https://user-images.githubusercontent.com/1360552/69655300-515e8600-1087-11ea-8e3d-218c5c583251.png)

```
ember-power-select ^3.0.4
ember-cli ~3.15.0-beta.1
ember-cli-fastboot ^2.2.1
```

```
process.env.EXPERIMENTAL_RENDER_MODE_SERIALIZE = true;
```

Reproduction repo:
https://github.com/lifeart/-power-select-octane-fastboot

**Comment by cibernox** [comment]
@lifeart if you update to 3.0.5 it should be fixed. Thanks for reporting!

**Comment by lifeart** [comment]
@cibernox after updating to ` 3.0.5` I see this:

![image](https://user-images.githubusercontent.com/1360552/69781110-34789e80-11be-11ea-8898-a93217322ca5.png)

**Comment by cibernox** [comment]
@lifeart In the repo you  linked it seems to for for me after updating to 3.0.5. 
I'm running the server with `EXPERIMENTAL_RENDER_MODE_SERIALIZE=1 ember serve`

**Comment by lifeart** [comment]
@cibernox yes, in reproduction repo this flag enabled in ember-cli settings - https://github.com/lifeart/-power-select-octane-fastboot/blob/master/.ember-cli.js#L1
