### ISSUE TITLE
Allow system-wide configuration via config/environment.js

### ISSUE THREAD

**Issue by cibernox** [cibernox/ember-power-select#13]
At the moment if you want to opt out to some default you need to explicitly pass an option on every component invocation. There is no way of, by example, disabling the search to for all selects in one place.

Basic plan:

```js
ENV['ember-power-select'] = {
  searchEnabled: false,
  loadingMessage: 'Loading results...'
}

// This options will get merged in the class extension, becoming the new defaults.
```

**Comment by miguelcobain** [comment]
@cibernox The standard way to do this would be to leverage the power (no pun intended) of ember-cli-resolver like:

```javascript
//app/components/ember-power-select
import EmberPowerSelectComponent from 'ember-power-select/components/ember-power-select';

export default EmberPowerSelectComponent.extend({
  searchEnabled: false,
  loadingMessage: 'Loading results...'
});
```
You can also import your config and use values from configuration here.
So, I'm not so sure about the relevance of this.

**Comment by cibernox** [comment]
So this can just be fixed with a note on the docs or the cookbook.
