### ISSUE TITLE
onChange on modifier

### ISSUE THREAD

**Issue by jrock2004** [cibernox/ember-power-select#1319]
I have setup a new octane app and trying to use the on modifier with the onChange property. I am ok when I do not have to pass in additional properties, but as soon as I do I cannot get the new value that was selected. What am I doing wrong?

```html
<PowerSelect
  @options={{this.times}}
  @selected={{@hour.fromTime}}
  @onChange={{fn this.updateFromTime @hour}}
  as |time|>
  {{time}}
</PowerSelect>
```

So in my action I can see the hour property but how do I see the new option that I selected?

**Comment by conormag** [comment]
I believe its curried on as the next value

```
updateFromTime(hour, value /*, powerselect, mouseevent */) {
  // value should contain your selection
}
```

**Comment by jrock2004** [comment]
This worked. Thank you
