### ISSUE TITLE
dropdown appears in wrong location on demo pages

### ISSUE THREAD

**Issue by jgelens** [cibernox/ember-power-select#132]
Using Firefox on OS X: ![screen shot](https://cloud.githubusercontent.com/assets/2479/11213783/26342136-8d3e-11e5-86bb-1e5133f832d5.png)
It seems to work fine using Safari.

**Comment by cibernox** [comment]
I don't see the same thing but certainly this example looks broken. The dropdown should be `width: 100%` and shouldn't be rounded.

I'll check it.

**Comment by jgelens** [comment]
I can reproduce this on multiple computers, it happens on all pages with multiple select dropdowns. The first dropdown on the page always works correctly.

**Comment by corrspt** [comment]
I tried the examples on the site using Firefox on OSX v.37 (and after update v42) and it happens to me as well on both versions, **but not on all examples**. 

It seems to be the positioning calculation somehow. If I try to open an example that's on the top of the page or near the top, the problem does not occur. However if I scroll down to an example in the bottom of the page (or middle of the page), the problem appears.

**Comment by jgelens** [comment]
If I set position to 'fixed' on the element, then it works. So it's probably a minor CSS issue.

**Comment by cibernox** [comment]
Glad I decided to do betas in 0.6.0 after a break-all-the-things internal refactor.

Fixed in 0.6.0-beta.2, and deployed. Should be fine now
