### ISSUE TITLE
[Ember 3.17.0-beta.2] Failed to execute 'removeChild' on 'Node'

### ISSUE THREAD

**Issue by jelhan** [cibernox/ember-power-select#1326]
Ember Power Select is affected by this bug: https://github.com/emberjs/ember.js/issues/18696 It's causing some of the tests to fail for `ember-beta` scenario. Most of them are failing with #1325. Opening this issue to keep track and direct people in the right direction if facing that error.

**Comment by cibernox** [comment]
Should be fixed now
