### ISSUE TITLE
`ember-concurrency-decorators` broken in Legacy Edge

### ISSUE THREAD

**Issue by patrickberkeley** [cibernox/ember-power-select#1332]
We're using v4.0.0-beta.6 of `ember-power-select` which uses `ember-concurrency-decorators` here: https://github.com/cibernox/ember-power-select/blob/3e0acb7b9b38e0ec47bda07a383cfbfe7e3cfa63/addon/components/power-select.ts#L542

That library breaks Legacy Edge: https://github.com/machty/ember-concurrency-decorators/issues/65, and therefore `ember-power-select` breaks in Legacy Edge.

**Comment by cibernox** [comment]
Is this something I can help with? If machty/ember-concurrency-decorators releases a fix I'm happy to update the dependency.

**Comment by patrickberkeley** [comment]
Closing until ember-concurrency-decorators releases a fix. Hopefully someone else will find this issue to be informative.
