### ISSUE TITLE
[v3.0.6] Autocloses if content overlays trigger

### ISSUE THREAD

**Issue by mehulkar** [cibernox/ember-power-select#1334]
I'm trying to achieve a UI where the dropdown opens above the trigger. I do this by applying a `transform: translateY()` onto the content element.

```hbs
<PowerSelect
  @options={{this.options}}
  @selected={{this.selectedOption}}
  @onChange={{this.setSelection}} as |opt|>
  {{opt}}
</PowerSelect>
```

```scss
.ember-power-select-dropdown.ember-basic-dropdown-content {
  transform: translateY(-32px);
}
```

When I click on the trigger, the dropdown closes as soon as it's opened.

## Investigation

What's happening is that when I click on the trigger, when the content is on top of the trigger, the click event is dispatched by the `body` element (I'm not sure why?). That means that the callback decides to close the dropdown, since it's [not a click on the trigger][1]. If the content is *not* on top of the trigger, the `click` event is dispatched by the trigger element, and it effectively ignores the event.

## Possible solutions

1. If I pass the `rootEventType` to `mouseup` to EBD, I get the behavior I want. The semantics between click and mouseup are different, but I believe it's correct behavior for my usecase. **However EPS does not expose this to the end user**, so it would need to be added as public API and [passed into EBD here][2].
2. Another solution is to figure out *why* the `click` event is being dispatched on `body`. I'm guessing it's because the `mousedown` is on the trigger and `mouseup` is on the content, so the closest ancestor is the `body`? I looked into the `stopPropagation` API as a possible solution for this, but I am not sure it's the right solution.

Here's the UI I'm trying to get:

![bugreport](https://user-images.githubusercontent.com/490968/74890311-84d44800-5338-11ea-97e9-5dca492f8cf7.gif)

One issue I notice with changing `rootEventType` to `mouseup` though is that if I don't move my mouse at all and click again, it doesn't go away. I haven't figured out what the issue is there.

[1]: https://github.com/cibernox/ember-basic-dropdown/blob/v2.0.13/addon/components/basic-dropdown-content.js#L123-L136
[2]: https://github.com/cibernox/ember-power-select/blob/v3.0.6/addon/templates/components/power-select.hbs#L2-L15

**Comment by mayatron** [comment]
Seeing the same issue here.

Possibly related? https://github.com/cibernox/ember-basic-dropdown/issues/508

**Comment by mayatron** [comment]
I can reproduce this issue on EPS `4.0.0-beta.6`.

This issue is visible on the EPS page if you add the following style to place the dropdown content above the trigger...

```
.ember-basic-dropdown-content {
  top: -40px !important;
}
```

![power select 2020-02-21 16_04_26](https://user-images.githubusercontent.com/1009725/75081435-060c1600-54c4-11ea-88bc-c134431dd823.gif)

I haven't been able to isolate the exact cause of this yet, but the `findOptionAndPerform` function (which subsequently selects an option and closes the menu) is being triggered here in the failure case, but otherwise typically not until an item is selected.

https://github.com/cibernox/ember-power-select/blob/master/addon/components/power-select/options.ts#L57

**Comment by mehulkar** [comment]
I believe this is the same root cause as #1263 (overlapping content and trigger), so I'm going to close this.
