### ISSUE TITLE
Somehow my power select search input has spellcheck="true"

### ISSUE THREAD

**Issue by krainboltgreene** [cibernox/ember-power-select#1336]
While there are many reasons why this would happen (like `{{input spellcheck="true"}}` amusingly enough) that isn't the case for this component.

Any thoughts?

**Comment by krainboltgreene** [comment]
So we managed to solve, this, it seems to be because while you're using the HTML `<input>`, as so as you involve `{{on}}` or `{{did-insert}}` it considers the rest of the call to be the component form: `<Input>` or `{{input}}`. Amusingly, the other properties are also failing.

**Comment by cibernox** [comment]
wait, that doesn't make sense. If that is the case, it would be a horrendous bug in Ember.js itself.

**Comment by krainboltgreene** [comment]
@cibernox I got some bad news: https://ember-twiddle.com/14100e6dfaabb6bab22427e11c957004?openFiles=templates.application%5C.hbs%2C

**Comment by uconnjosh** [comment]
fix for until Ember fixes the underlying problem!

https://github.com/cibernox/ember-power-select/pull/1337

**Comment by cibernox** [comment]
This is fixed in 4.0

Closing
