### ISSUE TITLE
v4-beta ember-power-select-is-selected helper not working properly with ember-data collections

### ISSUE THREAD

**Issue by tobiaszwalczak** [cibernox/ember-power-select#1341]
Since upgrading to EPS `4.0.0-beta.6` (to resolve the issue https://github.com/cibernox/ember-power-select/issues/1338), I experience problems with the `ember-power-select-is-selected` helper when passing an ember-data collection/relation to the `@selected` attribute.

I investigated the issue and in this version, the `ember-power-select-is-selected` helper receives the `@selected` attribute not as plain array anymore, like in the previous version `3.0.6`.

To resolve the problem I would transform the `@selected` attribute with `toPlainArray` also when it is assigned from the arguments:

https://github.com/cibernox/ember-power-select/blob/master/addon/components/power-select.ts#L200

Like it is already handled for `@options`:

https://github.com/cibernox/ember-power-select/blob/master/addon/components/power-select.ts#L186

**Comment by cibernox** [comment]
This can be closed now
