### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'appendChild' of null with ember octane

### ISSUE THREAD

**Issue by davideferre** [cibernox/ember-power-select#1343]
I'm trying to use ember-power-select with the last version of ember (3.17) and I got this error when I try to click on the select:
`Uncaught (in promise) TypeError: Cannot read property 'appendChild' of null`

I'm trying the first example of the docs:

```
<PowerSelect @options={{this.names}} @onChange={{this.foo}} as |name|>
        {{name}}
    </PowerSelect>
```
and in my component-class I've declared `names` as `@tracked names=['foo','bar']` and foo as an `@action`.
What I'm doing wrong?

**Comment by cibernox** [comment]
I believe this is fixed in 4.0.0, can you check?

**Comment by davideferre** [comment]
I confirm, in 4.0.0 this issue is fixed, thank you!

**Comment by quaertym** [comment]
I still see this issue in ember 3.23.0.

**Comment by cibernox** [comment]
@quaertym can you create a reproduction repo? Also, can you confirm that you are using 4.0.0? Perhaps your dependency in `ember-power-select-typeahead` is making you use an older version, check the package-lock.json to be sure.
