### ISSUE TITLE
AfterOptionsComponent is missing PublicAPI

### ISSUE THREAD

**Issue by huberts** [cibernox/ember-power-select#1352]
In commit 593ea1365cb560d3e619f94ee875f093a2677c67 the `select `parameter was cut off in `AfterOptionsComponent`:
[ember-power-select.hbs](https://github.com/cibernox/ember-power-select/blob/master/addon/templates/components/power-select.hbs#L118)
I assume it is a bug?

**Comment by huberts** [comment]
I do not know the drill - should I close the issue? :)

**Comment by cibernox** [comment]
Yeah, this can be closed. Thanks!
