### ISSUE TITLE
Breaking with embroider: `cannot identify a component in rule snippet: "{{power-select/before-options}}"`

### ISSUE THREAD

**Issue by scottmessinger** [cibernox/ember-power-select#1368]
Hi! Great addon. Thanks so much for creating it! 

I haven't seen reports of this (or have just failed at googling) so I'm wondering if I'm doing something wrong. Here's what's happening:

After adding embroider per the directions:
```sh
// Add dependencies:
yarn add --dev @embroider/core @embroider/compat @embroider/webpack
```

```diff
// Edit ember-cli-build.js:

-return app.toTree();
+const { Webpack } = require('@embroider/webpack');
+return require('@embroider/compat').compatBuild(app, Webpack);
```

I fire up my ember and get:

```
Build Error (WaitForTrees)

cannot identify a component in rule snippet: "{{power-select/before-options}}"
```

Info:
- Node 10.15.3
- Ember 3.18.1
- Power-select 3.0.4 and 4.0.0-beta.6 (same behavior)

Let me know if there's any other info I can provide or anything else I can do to help diagnose this!

**Comment by cibernox** [comment]
I have to investigate, I believe embroider no longer allows to dynamically resolve components by name.

**Comment by scottmessinger** [comment]
@cibernox Thanks for looking into this! I didn't enable the static components setting, and my understanding is it should just work. Only when static component is set to true can components not be dynamically resolved. I could be totally off here, though.
