### ISSUE TITLE
Update ember-concurrency-decorators dependency to version ^2.0.0

### ISSUE THREAD

**Issue by andreyfel** [cibernox/ember-power-select#1375]
It was recently released and supports TypeScript now, so, the apps using TS and e-c will want to migrate to it.
If the app is using ember-power-select there will be a dependency conflict.

I think it will require a major version bump for ember-power-select.

Another option is to specify "^1.0.0 || ^2.0.0" as a dependency.

@cibernox what option do you prefer?

**Comment by andreyfel** [comment]
Oh, I see there is an attempt to do the upgrade #1373

**Comment by andreyfel** [comment]
Created another PR to do that #1377

**Comment by andreyfel** [comment]
@cibernox could you please cut a new release since #1377 is merged?

**Comment by cibernox** [comment]
@andreyfel done! 🎉

**Comment by andreyfel** [comment]
Awesome! Thanks!
