### ISSUE TITLE
Power Select doesn't go very well with bulma

### ISSUE THREAD

**Issue by rafaelcn** [cibernox/ember-power-select#1383]
Is there any way to implement it? I'm not proficient enough in CSS to do this implementation, althought with guidance I could try to do it myself.

**Comment by cibernox** [comment]
I afraid I know nothing about bulma. But if the current CSS styles doesn't play well with any CSS framework, you can disable them altogether you can disable them completely in your app's `ember-cli-build.js`:

```js
var app = new EmberApp(defaults, {
  'ember-power-select': {
    theme: false
  }
});
```

**Comment by rafaelcn** [comment]
Ok, thank you.
