### ISSUE TITLE
Assertion Failed: {{power-select}} requires an `onchange` function

### ISSUE THREAD

**Issue by FrancoisLetourneau** [cibernox/ember-power-select#1385]
I just updated ember to 3.20.0. 

I got this error 

`Assertion Failed: {{power-select}} requires an `onchange` function`

Power-select was working fine prior to updating ember. 

Just to make sure, I've updated ember-power-select to latest (4.0.3). 

Still getting this error anywhere that I am using a power-select. There is always a onchange given to the component. 

Here's the line that is throwing the error, from power-select.js

`line 114 (true && !(this.get('onchange') && typeof this.get('onchange') === 'function') && Ember.assert('{{power-select}} requires an `onchange` function', this.get('onchange') && typeof this.get('onchange') === 'function'));`

Anyone has an idea what is wrong?

**Comment by cibernox** [comment]
Are you sure you're running the EPS 4.0.3? The line you pasted seems from an old version, because in the error message should have been `<PowerSelect> requires an `@onChange` function`.

Perhaps you have some other addon that is locked to an old version of EPS that that's what you're getting

**Comment by FrancoisLetourneau** [comment]
Thanks cibernox.

This is exactly what was happening. I found what was wrong.

Our app had ember-power-select-with-create module installed, and this module was using ember-power-select version 2.x.x. 

I've forced the update of ember-select-with-create to latest, which use ember-power-select v4.0.0, and now everything works!

Thanks you very much!

**Comment by cibernox** [comment]
👍

**Comment by FrancoisLetourneau** [comment]
Sorry cibernox if I may ask another question.

I am now getting this error `TypeError: _powerSelect.default.extend is not a function`

We made an extension of power-select which is called `power-select-extend.js`

In that file there is 

`import EmberPowerSelect from './power-select';`

`export default EmberPowerSelect.extend({` <-- Seems like this line is causing the bug. 

I'm calling it like so 

`                    <PowerSelectExtend
                      @triggerClass="ui dropdown search selection no-bottom-margin filter-trigger"
                      @selected={{this.user}}
                      @allowClear={{true}}
                      @onChange={{this.filterByUser}}
                    as |user|
                    >
                      {{user.firstName}} {{user.lastName}} ({{user.username}})
                    </PowerSelectExtend>`

I can't find in the doc how to update the code to make it work with the latest version. Any idea?

**Comment by cibernox** [comment]
@FrancoisLetourneau that's because in the newest version EPS uses native javascript classes. You can use 
```js
import EmberPowerSelect from './power-select';


class SomeClass extends EmberPowerSelect {
   // ...
}
```
