### ISSUE TITLE
Apple Pencil tap does not work

### ISSUE THREAD

**Issue by kr3ved** [cibernox/ember-power-select#1387]
First of all, thanks a lot for such a useful addon!

I'm reporting it here, but it's relevant for `ember-basic-dropdown` as well.
Here is the GIF illustrating the problem:

![apple_pencil_issue](https://user-images.githubusercontent.com/1285996/90515235-029fd180-e16b-11ea-8c5b-9a04949f1532.gif)

A single tap using a finger triggers two events: `touchstart` and `touchend`.
A single tap using an apple pencil also triggers `touchmove` event because of pencil being very precise — it's just a few pixels of touch "distance", but current logic aborts an action if `touchmove` event was triggered at all.

Here is the list of all code occurrences that I've found:
- [ember-power-select/addon/components/power-select/options](https://github.com/cibernox/ember-power-select/blob/c36d826efd9bef2c732f6d1b6733af5bc76cef00/addon/components/power-select/options.ts#L77-L80)
- [ember-basic-dropdown/addon/components/basic-dropdown-trigger](https://github.com/cibernox/ember-basic-dropdown/blob/ad81ef4dc161943bdc05ac3048b209f30ee19a4b/addon/components/basic-dropdown-trigger.ts#L101-L103)
- [ember-basic-dropdown/addon/components/basic-dropdown-content](https://github.com/cibernox/ember-basic-dropdown/blob/ad81ef4dc161943bdc05ac3048b209f30ee19a4b/addon/components/basic-dropdown-content.ts#L107-L110)

**Comment by cibernox** [comment]
Hey, thanks for reporting! I'm not sure how to fix it. Perhaps check how much it has move and if it's a very small amount (a couple pixels) still consider the "click" valid.

I will investigate it.
