### ISSUE TITLE
JS Heap grows with selected PromiseProxy

### ISSUE THREAD

**Issue by flexyford** [cibernox/ember-power-select#1391]
Hello and thanks for the great addon.

We are exercising this [block of code that observes PromiseProxies](https://github.com/cibernox/ember-power-select/blob/fb688e44c166e42e58d6c89de02ede553464e38a/addon/components/power-select.ts#L335-L341) and noticed that `PowerSelect` Component instance accumulates in the JS Heap when the initial `selected` value is a `PromiseProxy`. 

I believe that in Chrome, these Component instances are not torn down until a Major Garbage Collection occurs in the browser (Chrome calls this "Major GC" in their Performance dev tools flame chart).

**Dummy App Reproduction Steps**

I've modified the "Playground" portion of the app to show the Component accumulation when the initial `selected` value is a PromiseProxy. The "Playground" renders one PowerSelect component.

```hbs
{{!-- dummy/app/templates/playground.hbs--}}
<h1>Playground</h1>
<PowerSelect @selected={{this.selected}} @onChange={{fn (mut this.selected)}} as |name|>{{name}}</PowerSelect>
```

```js
// dummy/app/controllers/playground.js
import ObjectProxy from '@ember/object/proxy';
import PromiseProxyMixin from '@ember/object/promise-proxy-mixin';
let ObjectPromiseProxy = ObjectProxy.extend(PromiseProxyMixin);

export default class extends Controller {
  init() {
    super.init(...arguments);

    const proxy = ObjectPromiseProxy.create({ promise: resolve('I am a PromiseProxy Object') });
    this.set('selected', proxy);
  }
}
```

The initial state of the JS Heap contains**1** PowerSelect instance, but the final state contains **6** instances (because we visited a page containing the PowerSelect with `selected` PromiseProxy a total of five times). Although the component is destroyed, it still remains in the JS Heap. 

_Visiting a page containing  a `PowerSelect` where `selected` value is a PromiseProxy (visited 5 times in the gif)_
![Screen Recording 2020-09-04 at 09 58 AM](https://user-images.githubusercontent.com/8826403/92253643-60cff280-ee95-11ea-86c1-d95319e0ba85.gif)

**Comment by flexyford** [comment]
i believe to resolve this issue, we will need to remove the last remaining observer from the component

```ts
// addon/components/power-select.ts
export default class PowerSelect extends Component<PowerSelectArgs> {
  //...
  willDestroy() {
    if (this._lastSelectedPromise) {
      this._lastSelectedPromise = undefined;
      removeObserver(this._lastSelectedPromise, 'content', this, this._selectedObserverCallback);
    }
    super.willDestroy.apply(this, arguments);
  }
}
```

I will open up a PR shortly with this change

**Comment by cibernox** [comment]
That's some serious javascript VM archeology 👏 👏 👏 

Bring it on, I'll should have time today to review stuff.

**Comment by flexyford** [comment]
I'm seeing the same JS Heaph growth due to [eventListeners of PowerSelect/Options](https://github.com/cibernox/ember-power-select/blob/fb688e44c166e42e58d6c89de02ede553464e38a/addon/components/power-select/options.ts#L57-L72) not being removed. 

I'll open a separate Issue/PR for that as well, hopefully today
