### ISSUE TITLE
Js Heap contains extra PowerSelect instance when default Options Component rendered

### ISSUE THREAD

**Issue by flexyford** [cibernox/ember-power-select#1393]
We are exercising this `PowerSelect/Options` Component and noticed that the [eventListeners of PowerSelect/Options](https://github.com/cibernox/ember-power-select/blob/fb688e44c166e42e58d6c89de02ede553464e38a/addon/components/power-select/options.ts#L57-L72) are not never removed. This causes an extra instance of the `PowerSelect` Component to remain in the JS Heap until the `PowerSelect/Options` Component is re-rendered. 

**Dummy App Reproduction Steps**

I've modified the "Playground" portion of the app to show the Component accumulation when the Options dropdown is rendered. The "Playground" renders one PowerSelect component.

```hbs
{{!-- dummy/app/templates/playground.hbs--}}
<h1>Playground</h1>
<PowerSelect @options={{this.cities}} @selected={{this.selected}} @onChange={{fn (mut this.selected)}} as |name|>{{name}}</PowerSelect>
```

The initial state of the JS Heap contains **1** PowerSelect instance, but the final state contains **2** instances. Although the component is destroyed, it still remains in the JS Heap. This is not the same linear component instance JS Heap growth we saw in #1391 but is a memory leak nonetheless that we can patch up. The remaining instance is removed when the Options dropdown is re-rendered. 

_Visiting a page containing a `PowerSelect`_ 
    **Snapshots explained:**
  - Snapshot 1: Visit PowerSelect Playground and open `Options` dropdown
    - **1** PowerSelect instance exists
  - Snapshot 2: Visit Addons Page
    - **2** PowerSelect instances exist (instance from Snapshot 1 remains)
  - Snapshot 3: Visit PowerSelect Playground
    - **2** PowerSelect instances exist (instance from Snapshot 1 remains)
  - Snapshot 4: Open `Options` dropdown (re-rendered)
    - **1** PowerSelect instances exist (instance from Snapshot 1 removed)

  ![Screen Recording 2020-09-08 at 11 28 AM](https://user-images.githubusercontent.com/8826403/92503298-ad356e00-f1c6-11ea-96ca-5c3f8318dd49.gif)

**Comment by flexyford** [comment]
@cibernox I wanted to make sure to document the issue as discussed in https://github.com/cibernox/ember-power-select/pull/1392#issuecomment-688330878 

PR is coming soon. I've got some TypeScript learning to do, but hopefully, you can lead me in the right direction when the PR is open.

**Comment by cibernox** [comment]
I'll try, I'm not that big of an expert in typescript myself, but I get by.
