### ISSUE TITLE
Multiselect enter-key results in multidimensional arrays being selected

### ISSUE THREAD

**Issue by Brian11f** [cibernox/ember-power-select#1400]
When using `power-select-multiple` and setting `closeOnSelect` to `false`, multidimensional arrays are created when making a selection with the enter-key and selecting the same selected value more than once.
![power-select](https://user-images.githubusercontent.com/16297587/94609411-97f6b100-0253-11eb-9a48-afcc1377f2e3.gif)

**Comment by ozywuli** [comment]
i'm also experiencing this issue. has anyone found a workaround?

**Comment by ozywuli** [comment]
i ran into the same issue. is a fix in the works?

**Comment by kiwiupover** [comment]
@Brian11f does #1447 fix your issue here?

**Comment by Brian11f** [comment]
Yes, that resoled the issue. Thanks!
