### ISSUE TITLE
I can't seem to prevent closure of the menu on a select

### ISSUE THREAD

**Issue by arthur5005** [cibernox/ember-power-select#1401]
I see that there's a way to prevent closure in onClose by returning false or preventing the default on the event object, but unfortunately it doesn't seem as if the event object actually get's passed in from the `_choose` method, which I believe is a bug, but I'm not sure.

So it's impossible to tell the dropdown to only prevent close on choose.

![Screen Shot 2020-09-29 at 11 05 26 PM](https://user-images.githubusercontent.com/697846/94648863-4cbabd80-02a8-11eb-987c-fbdde80bf50e.png)

**Comment by cibernox** [comment]
There is a `@closeOnSelect={{false}}` option you can use for that. Does that work for you?

**Comment by arthur5005** [comment]
I don't know how I missed that in the API reference, my apologies! 

It still feels though as the intention was to have access to the event object in the close handler... regardless you're welcome to close this if you don't see a problem with that.
