### ISSUE TITLE
Codemod for onchange and onopen

### ISSUE THREAD

**Issue by mfeckie** [cibernox/ember-power-select#1402]
Would you be interested in a PR to add a migration tool to the README?

I've built https://github.com/mfeckie/powerselect-codemod to handle the deprecation of `onchange` for `onChange` and `onopen` for `onOpen`.

Might be helpful for folks who are moving from 2.x up to more recent versions

**Comment by rwwagner90** [comment]
Probably wouldn't hurt to include it in the docs somewhere, although it has been awhile now.

**Comment by mfeckie** [comment]
Probably doesn't work anymore, haven't looked at it in a long time. I'll close the issue
