### ISSUE TITLE
Silent failure: PowerSelect component does not render?

### ISSUE THREAD

**Issue by allthesignals** [cibernox/ember-power-select#1404]
I'm trying to update this component because the change from `onchange` to `onChange` is causing many failures in some of our addons.

Here's the code:

```
      <PowerSelect @options={{array 1 2 3 4}} @onChange={{action 'setBorocode'}} as |name|>
        {{name}}
      </PowerSelect>
```

Nothing happens now, nothing appears, and there's no error. Nothing is in the DOM. 

Here are my changes: https://github.com/NYCPlanning/labs-ember-search/commit/d4d8eb87a6d8087dafb3d81446d65d1066cee0ad

Is there a reason the component would just silently not render?

**Comment by cibernox** [comment]
All seems good in your example. I copy-pasted your snipped in this app and it rendered just fine.

I'd suggest to check if you have two incompatible versions of Ember Power Select or Ember Basic Dropdown in your package-lock.json or yarn.lock (perhaps one being required by another addon you use). That's the only thing that comes to mind that could result in a silent failure.

**Comment by robert9g** [comment]
This happened to me too.
Node: v12.19.0
Ember: v3.11

After I updated Ember to version 3.22 it worked without any issues.

**Comment by allthesignals** [comment]
> All seems good in your example. I copy-pasted your snipped in this app and it rendered just fine.
> 
> I'd suggest to check if you have two incompatible versions of Ember Power Select or Ember Basic Dropdown in your package-lock.json or yarn.lock (perhaps one being required by another addon you use). That's the only thing that comes to mind that could result in a silent failure.

Thanks, resolving those conflicts helped a lot. Going to close for now. @robert9g I suggest looking at this: https://github.com/salsify/ember-cli-dependency-lint
