### ISSUE TITLE
Updating an array proxy through results

### ISSUE THREAD

**Issue by snewcomer** [cibernox/ember-power-select#142]
Hi!  I'm looking to pass in an array proxy to `options` (that is populated at some point later from an xhr) and traced down the problem to breaking the cache on `results.[]` instead of just `results`.  Making this change works in production. Wrote a quick test but haven't got it to work yet; guessing I can't get that array proxy to update after its passed in for some reason.  Is your intended use to have the options be always wrapped in a promise (as your other tests show) or do you want to support something like this?  (noticed you mentioned in another post that if one wanted the loading message, all options must be wrapped in a promise)

    //line 41 in power-select/base.js
    resultsLength: computed('results.[]', function() {
      return countOptions(this.get('results'));
    }),

    test('xxxx wat', function(assert) {
      let done = assert.async();

      let numbers_0 = Ember.A([]);
      this.numbersArrayProxy = Ember.ArrayProxy.extend({
          content: Ember.computed('source.[]', function() {
              return this.get('source');
          })
      }).create({
          source: numbers_0 
      });

      Ember.run.later(function() { 
          numbers_0.pushObjects(numbers);
      }, 100);

      this.render(hbs`
        {{#power-select options=this.numbersArrayProxy onchange=(action (mut foo)) as |option|}}
          {{option}}
        {{/power-select}}
      `);

      Ember.run(() => this.$('.ember-power-select-trigger').click());

      assert.equal($('.ember-power-select-option').text().trim(), 'Loading options...', 'The loading message appears while the promise is pending');
      setTimeout(function() {
        assert.ok(!/Loading options/.test($('.ember-power-select-option').text()), 'The loading message is gone');
        assert.equal($('.ember-power-select-option').length, 20, 'The results appear when the array proxy is populated');
        done();
      }, 150);
    });

**Comment by toranb** [comment]
@miguelcobain @cibernox @snewcomer care if I take this on over the weekend?

**Comment by snewcomer** [comment]
@toranb yep go ahead!  I'll wait for your PR.

**Comment by cibernox** [comment]
@toranb Please, be my guest. Although I foreseen that it won't be a very simple change.

I guess that you'll need to define `results` as a computed property that depends on the options and the searchText. Perhaps a PromiseArrayProxy?

**Comment by toranb** [comment]
@cibernox dude it wasn't bad at all :)

https://github.com/cibernox/ember-power-select/pull/143

**Comment by toranb** [comment]
@snewcomer you can close this issue out - thanks for the help !!!
