### ISSUE TITLE
Override trigger template in v4

### ISSUE THREAD

**Issue by Bouke** [cibernox/ember-power-select#1422]
First of all, thank you for the great effort spent on this addon.

In EPS v3 I was able to override the trigger template by having a template file `templates/power-select/trigger.hbs`. Now with v4 the addon switched to co-located templates, so the template is now at `components/power-select/trigger.hbs`. If I introduce a file at that location, Ember throws the following error:

> Uncaught (in promise) TypeError: can't redefine non-configurable property "default"

My guess is that having a file named `components/power-select/trigger.hbs`, I'm not actually overriding a template, but introducing a new component (shadowing the addon). How would I go about replacing the actual trigger template with v4?

**Comment by oakho** [comment]
We're having the exact same issue while upgrading our app to Octane and didn't manage to find a solution either.

An "easy" way I can think of would be to create a component wrapping power select's one and set a custom trigger component but, in our case, that would involve lots of effort while we still having lots of other concerns migrating to Octane.

Any guidance on how to handle this case would be appreciated ! And, of course, thanks for this awesome addon, we are relying a lot on it in our app.

**Comment by Bouke** [comment]
Cross-post from [discuss.emberjs.com](https://discuss.emberjs.com/t/how-to-override-addons-template/18442/9):

So I suppose the answer to my question is answered here: [Build-time transformations](https://emberjs.github.io/rfcs/0481-component-templates-co-location.html#build-time-transformations):

> One caveat here is that each component JavaScript file should export a value that is unique to that file. For example, this should be **avoided** :
> 
> ```
> // app/components/foo-bar.js
> 
> import MyParentComponent from "./my-parent";
> 
> // BAD: don't do this!
> export default MyParentComponent;
> ```
> 
> This is problematic because `setComponentTemplate` will be called on `MyParentComponent` directly, affecting the parent component and all of its descendants. This can be avoided by subclassing, even when no customization is required:
> 
> ```
> // app/components/foo-bar.js
> 
> import MyParentComponent from "./my-parent";
> 
> // GOOD: do this instead!
> export default class extends MyParentComponent {}
> ```

With that in mind, I've changed my code to read like this:

```js
import Trigger from 'ember-power-select/components/power-select/trigger';
export default class extends Trigger { }
```

And now my custom template is being used!

As a separate issue I cannot seem to find the magical incantation to get TypeScript to allow the import. TypeScript insists on adding `/addon/`, which fails run time. This might be due to the following caveat listed in ember-cli-typescript:

> * Similarly, apps must use `.js` to override addon defaults in `app` , since the different file extension means apps no long consistently "win" over addon versions (a limitation of how Babel + app merging interact).

**Comment by oakho** [comment]
Wow, thanks for sharing, I'll have a look next week to try your solution.

**Comment by cibernox** [comment]
Thanks! I wasn't aware of this limitation myself, I haven't had to subclass a built in component in a while.

**Comment by oakho** [comment]
@Bouke this worked like a charm, thanks again for sharing !

**Comment by cibernox** [comment]
Good to hear there's a solution. Closing.

**Comment by abel-n** [comment]
I am trying to override options component in an addon that is using pod structure. I have the following files:
```
addon
  components
    form-elements
      select-multiple
        options
          component.js
          template.hbs
app
  components
    form-elements
      select-multiple
        options
          component.js
          template.js
```

The component import / export looks like this:
```js
import BaseComponent from 'ember-power-select/components/power-select/options';

export default class FormElementsSelectMultipleOptionsComponent extends BaseComponent { }
```
As far as I can tell this is the format that was suggested in the [comment before](https://github.com/cibernox/ember-power-select/issues/1422#issuecomment-761117755)

I couldn't figure out what would be the correct export in `app` folder so that the template in `template.hbs` gets rendered. It always renders the default template. Any suggestions?

**Comment by abel-n** [comment]
I also tried to mimic the component structure of EPS, unfortunately it did not change anything.
```
addon
  components
    power-select
      options.js
      options.hbs
app
  components
    power-select
      options.js
```
I'll fork the repository as a workaround but it would be preferable to maintain one component than to maintain a whole repository.

**Comment by bmaehr** [comment]
> 
> With that in mind, I've changed my code to read like this:
> 
> ```js
> import Trigger from 'ember-power-select/components/power-select/trigger';
> export default class extends Trigger { }
> ```
> 
> And now my custom template is being used!
> 
> As a separate issue I cannot seem to find the magical incantation to get TypeScript to allow the import. TypeScript insists on adding `/addon/`, which fails run time. This might be due to the following caveat listed in ember-cli-typescript:
> 
> > * Similarly, apps must use `.js` to override addon defaults in `app` , since the different file extension means apps no long consistently "win" over addon versions (a limitation of how Babel + app merging interact).

Could you please explain more precisely (names of the files, what you did else) because I'm also not able to get it working...
