### ISSUE TITLE
Types not correctly created in published package

### ISSUE THREAD

**Issue by mydea** [cibernox/ember-power-select#1425]
I was wondering why there are no types to be imported even though this is a TS project, and after some digging I found that apparently the types are not correctly created (?) by the `prepublishOnly` step in package.json.

I do not know how the release process for this addon (& ember-basic-dropdown) is, but I guess something is not working as expected there. 

This is the same as https://github.com/cibernox/ember-basic-dropdown/issues/542

**Comment by rwwagner90** [comment]
@mydea can you elaborate? The TS files seem to exist in node_modules.

**Comment by mydea** [comment]
This issue is more than a year old, I think it is resolved in the meanwhile :smile:

**Comment by rwwagner90** [comment]
@mydea we actually need this to fix types https://github.com/cibernox/ember-power-select/pull/1526
