### ISSUE TITLE
Performance issues?

### ISSUE THREAD

**Issue by justinzelinsky** [cibernox/ember-power-select#1435]
Hi! Great component -- I was wondering if there was any upper limit when it came to the number of options being rendered in the select? I'm noticing that it's taking ~9 seconds to render 5000 options when using version `2.3.5`. 

Business requirements aside, do you know about when the number of options starts to affect performance? Or do you think this is an issue with my app that is outside of the scope of power select?

Cheers!

**Comment by justinzelinsky** [comment]
Ah -- I found your repo with the use of the vertical collection component. That works well!

**Comment by charlesfries** [comment]
https://github.com/cibernox/ember-power-select-collection
