### ISSUE TITLE
Examples in the docs are not working

### ISSUE THREAD

**Issue by chbonser** [cibernox/ember-power-select#1437]
The `Result` tabs in the docs are not rendering anything!

<img width="790" alt="Screen Shot 2021-03-19 at 7 58 57 AM" src="https://user-images.githubusercontent.com/1022582/111784096-f6a6fa00-8888-11eb-9cb2-83db795c1df5.png">

**Comment by cibernox** [comment]
FIxed in #1438 

Thanks for reporting it!
