### ISSUE TITLE
ember-power-select not rendering the list

### ISSUE THREAD

**Issue by Lazarevsky** [cibernox/ember-power-select#144]
Hi all,

Ember version: 1.13.10
Ember-cli: 1.13.13
"ember-power-select": "0.6.0-beta.4" (came with 0.5.something but also did not work)

in the application.hbs I have the following code:
{{#power-select options=names onchange=(action "foo") as |name|}}
  {{name}}
{{/power-select}}

and in the application controller i have this:
  names: ['Stefan', 'Miguel', 'Tomster', 'Pluto'],

I am printing {{names}} in the template to verify that they indeed exist and they do.

This is the generated HTML for the selectbox:

<div id="ember565" class="ember-power-select ember-view ember-basic-dropdown">
<div class="ember-basic-dropdown-trigger ember-power-select-trigger" tabindex="0">
  <span class="ember-power-select-status-icon"></span>
</div>
</div>

Please assist as I would really love to use your addon!

Thanks so much!

**Comment by cibernox** [comment]
Everything looks correct, so I guess that it's some kind of problem with the wormhole destination div.

Have you checked if you have a div in the root of your body like this? `<div id="ember-basic-dropdown-wormhole"></div>`.

If not,we can investigate a bit more

**Comment by Lazarevsky** [comment]
Wow!

Thanks for the speedy response, I greatly appreciate it!

Yes I do indeed have that div in the root of my html.

Weird I don't see the HTML generated by the addon in my previous post. So basically it's generated a div with the following classes "ember-power-select ember-view ember-basic-dropdown" and then within it there's another div with the following classes "ember-basic-dropdown-trigger ember-power-select-trigger" and iwthin that there's a span "ember-power-select-status-icon".. The lsit does not seem to have been bound to the select :/

**Comment by Lazarevsky** [comment]
Also, I did not have an app.scss file in my app the the plugin generated one for me, although I am not sure I am usign sass to begin with.. could that be it? I know for sure that I've not manually installed it (SASS)

**Comment by cibernox** [comment]
The list is only rendered when the component is opened, and it's not rendered there but in the wormhole div (because it has to be in the root of the body and absolutely positioned).

Can you check if when you open the select the list is rendered inside the wormhole div? If so, problably is a css issue.

**Comment by Lazarevsky** [comment]
Umm.. what select? I see no select on my page :) I guess I did not make myself clear.. besides the list name that I'm pritning {{names}} there's nothing on the UI..

**Comment by cibernox** [comment]
The list of options not rendering inside the component is expected. It is rendered inside the `<div id="ember-basic-dropdown-wormhole"></div>` in the root of the body (only when you click the component)

**Comment by Lazarevsky** [comment]
Ok I understand that, it is mentioned in the docs. My problem is that NOTHING is rendered.. your addon added a <select> element in my html which is empty.. I can't clikc anything cuz there's nothing there..

**Comment by cibernox** [comment]
Ok, I understand now. The select is empty and the div collapses. I guess that it is a problem with the css being imported. I think that ember-power-select *thinks* that you're using sass when you're not.

Do you have `ember-cli-sass` listed in your package.json?

**Comment by Lazarevsky** [comment]
That was it! :) thanks soooo so much for your help and for the speedy response! Maybe you should add in the docs that this addon assumes there's sass installed :)

Cheers!

**Comment by cibernox** [comment]
I have some notes here: http://www.ember-power-select.com/docs/styles

The problem is not that the component always asumes that you're using sass. It works without sass just fine. The problem is that the component assumes that if you have ember-cli-sass among your addons is because you're using it :laughing: 

Let me know anything else fails.

**Comment by Lazarevsky** [comment]
oh one other thing I've noticed is that there's not "prompt" option or am I missing something? That'd be mighty useful to have so I dont have to manually create new objects and add them tot he list which would simulate that.. thanks again, you guys rock!

**Comment by cibernox** [comment]
There is, but it's called "placeholder". I should change it to propt perhaps, since it's more idiomatic.
