### ISSUE TITLE
Regression: selecting an option with [Enter] triggers form submission

### ISSUE THREAD

**Issue by EvgenyOrekhov** [cibernox/ember-power-select#1440]
I have `<PowerSelectMultiple>` inside `<form>`. Version 3.0.6 worked fine, but after upgrading to 4.1.3, it is no longer possible to select options via pressing <kbd>Enter</kbd>, it submits the form instead.

**Comment by EvgenyOrekhov** [comment]
Actually, the previous version might have been 2.3.5. I honestly can't tell, our dependencies are a mess.

**Comment by AndreJoaquim** [comment]
@EvgenyOrekhov I believe this was fixed by https://github.com/cibernox/ember-power-select/pull/1452

**Comment by EvgenyOrekhov** [comment]
It works in 4.1.6, thank you!
