### ISSUE TITLE
Embroider: Unsafe dynamic component

### ISSUE THREAD

**Issue by gilest** [cibernox/ember-power-select#1441]
When running with the embroider build and `staticComponents: true`.

Believe this is due to dynamic use of the `component` helper.

See [Addon Author Guide](https://github.com/embroider-build/embroider/blob/master/ADDON-AUTHOR-GUIDE.md#support-level-optimized-embroider-safe) specifically the `staticComponents` section and the [Replacing the Component Helper
](https://github.com/embroider-build/embroider/blob/master/REPLACING-COMPONENT-HELPER.md) document.

**Comment by mehulkar** [comment]
Tried running embroider-optimized test scenario in an addon and got:

```
Unsafe dynamic component: @groupComponent in $TMPDIR/embroider/b4c8ac/node_modules/ember-power-select/components/power-select/options.hbs
```

**Comment by mehulkar** [comment]
nope

**Comment by rwwagner90** [comment]
This should be fixed now I think. Our embroider tests are passing. If not, please reopen!
