### ISSUE TITLE
ember-power-select 3.x Minimum ember version

### ISSUE THREAD

**Issue by justinzelinsky** [cibernox/ember-power-select#1444]
Hi there,

According to the docs, I should be able to upgrade to version `3.x` since I am currently on Ember 3.12. However, I've run into an issue where _none_ of my `<PowerSelect />` components are rendering and I have no errors with which to figure it out.

I spent a lot of time digging into the code and I found something odd -- `ember-basic-dropdown` is a dependency of `ember-power-select` and when I install `ember-power-select` on the 3 major version branch, it installs a version of `ember-basic-dropdown` that is `2.x`. However, according to the docs for `ember-basic-dropdown`, the `2.x` versions require Ember `3.13`. 

Does this mean that the `3.x` versions of `ember-power-select` actually require Ember `3.13`?

I do not know what else would cause literally every one of my components to render nothing...

**Comment by chasegiunta** [comment]
I'm running into the same thing. I'm sure you're correct, the min version in the docs needs to change to 3.13.

**Comment by rwwagner90** [comment]
This is probably the case, yes. Assuming it is and closing for now.
