### ISSUE TITLE
Prevent submit event from firing when enter is pressed on search input

### ISSUE THREAD

**Issue by betocantu93** [cibernox/ember-power-select#1446]
# Problem
If you have a `<PowerSelectMultiple />` with searchEnabled inside a `<form>` and press <kbd> Enter </kbd> while searching or choosing with keyboard, the submit event gets triggered on the `<form>` causing an unexpected UX (submitting the form...)

After a long debugging session I noticed something that is not entirely a bug from ember-power-select but how browsers handle form submit events: submit events get triggered on the `<form>` element and can't be stopped from being executed when any button with type submit gets pressed or <kbd> Enter </kbd> is pressed while on any of the form's inputs , i.e. stopPropagation on <kbd> Enter </kbd> doesn't work at all.

Having
```hbs
<form {{on "submit" this.onSubmit}}>
 <PowerSelectMultiple
    @options={{array "1" "2" "3"}}
    @selected={{this.selected}}
    @onChange={{this.onChange}}
    @searchEnabled={{true}}
  as |option|>
    {{option}}
 </PowerSelectMultiple>
  <button type="submit">Submit</button>
</form>
```

I have two possible solutions in mind:
1. One way to solve this and probably the most a11y friendly, is to wrap this search input inside its own `<form>` and so prevent the submit event to be triggered on the parent form.
2. Use the `form` attribute to fake the browser that this input is meant to submit the fake form with id "fake-form-power-select-form"
```hbs 
<input form="fake-form-power-select-form" />
```

What do you think?

Something like this

```hbs
 <form
          class="euiComboBox__input"
          style="font-size: 14px; display: inline-block;"
          {{on "submit" (prevent-default)}}
        >
          <input
            class="ember-power-select-trigger-multiple-input euiComboBox__input"
            autocomplete="off"
            autocorrect="off"
            autocapitalize="off"
            spellcheck={{false}}
            id="ember-power-select-trigger-multiple-input-{{@select.uniqueId}}"
            value={{@select.searchText}}
            aria-controls={{@listboxId}}
            style={{this.triggerMultipleInputStyle}}
            placeholder={{this.maybePlaceholder}}
            disabled={{@select.disabled}}
            tabindex={{@tabindex}}
            {{on "focus" @onFocus}}
            {{on "blur" @onBlur}}
            {{on "input" this.handleInput}}
            {{on "keydown" this.handleKeydown}}
            {{did-insert this.storeInputStyles}}
          />
  </form>

```

**Comment by oakho** [comment]
We are encountering the exact same issue after we upgraded ember-power-select. 

I had no idea but there's a bunch of our users that were relying on the keyboard features (ie, selecting with enter key) which reported us that this is kind of broken now.

I successfully worked around this with your form wrapping solution (thanks) but that would indeed be great if there was a built-in solution get this behavior back.

Cheers!

**Comment by cibernox** [comment]
I'd sweat this worked before. Maybe we had a regression on this?
I wonder if we can just call preventDefault on the event with no consequences.

**Comment by cibernox** [comment]
I opened a PR using the second option (adding `form="non-existent-form"`). I like that better because it's zero-javascript and i'm not sure nested forms are legal.

**Comment by betocantu93** [comment]
Great! I went the nested form approach, honestly because it made "sense" but, I'll update it!

**Comment by cibernox** [comment]
I should be releasing a patch version at some point today
