### ISSUE TITLE
Ember power select last version use old  ember modifier package version

### ISSUE THREAD

**Issue by usamahamed** [cibernox/ember-power-select#1466]
I currently face warnings due to the ember modifier version I use, currently, according to this issue https://github.com/emberjs/ember-render-modifiers/issues/32 These warnings were fixed on the last version of ember modifier but I still got the same warnings because the last ember power select version uses the ember modifier v1.0.2

![image](https://user-images.githubusercontent.com/23267284/137458979-e51af9c1-144d-4b76-a1d2-58f685340480.png)

**Comment by SergeAstapov** [comment]
@usamahamed please re-check, this should be fixed now as https://github.com/cibernox/ember-basic-dropdown/pull/632 has landed and released in v3.0.21
