### ISSUE TITLE
disable specific select items

### ISSUE THREAD

**Issue by jamesdixon** [cibernox/ember-power-select#147]
Hi @cibernox - first off, amazing addon! Really enjoying it.

I wanted to see if it's possible to disable specific select items? My use case is this: I have a list of Staff that can be assigned to an appointment. In some cases, a Staff member is not available, but instead of not showing that particular Staff member, we'd like to show them in the list, but disable the selection of the option.

Thanks!

**Comment by jamesdixon** [comment]
Well, it looks like your addon follows the same conventions as Select 2 and will disable items automatically that have a property called `disabled` :) No changes needed. Is this documented? If not, it might be worth adding! 

Thanks!
James

**Comment by cibernox** [comment]
Yes, that is supported, but I wasn't aware that ember-select2 did that too, so the fact of being compatible is a pure coincidence.

Some related code in the tests: 
https://github.com/cibernox/ember-power-select/blob/master/tests/integration/components/power-select-test.js#L50-L58

https://github.com/cibernox/ember-power-select/blob/master/tests/integration/components/power-select-test.js#L1561-L1605

I definitively need to document that, probably here: https://github.com/cibernox/ember-power-select/blob/master/tests/dummy/app/templates/docs/the-list.hbs

**Comment by jamesdixon** [comment]
It's actually a feature from the actual Select 2 library (https://select2.github.io/examples.html#disabled-results). But yeah, crazy coincidence! Made my life much easier :+1: 

Thanks @cibernox!
