### ISSUE TITLE
"The Search" docs page has examples which affect each other

### ISSUE THREAD

**Issue by AddisonG** [cibernox/ember-power-select#1473]
Two of the search fields are linked together on this doc page, and so when one changes, so does the other. This doesn't happen with any other fields.
https://ember-power-select.com/docs/the-search/

The two examples that affect each other are the **"Customize the search field"** and the **"Prevent autofocus"** examples

Example video.
https://user-images.githubusercontent.com/5109532/141202372-fd55c670-6634-404f-bada-5981c1d373b3.mp4

Replicated issue on latest Firefox and Chrome.

**Comment by mkszepp** [comment]
Closing, as this was fixed in last time
