### ISSUE TITLE
select's content doen't update immediately, requires 2 clicks

### ISSUE THREAD

**Issue by Lazarevsky** [cibernox/ember-power-select#148]
So the page loads and I only have 1 dropdown populated with products (lightweight version - i'll explain). When the user selects a product from the dropdown, I get the subsystems for that product and populate a new dropdown which appears right next to the first one.

I click the subsystems dropdown for the first time and it's empty. I close down the selectbox and click it again and it's showing the right data! I thought that this had to do with waiting period or something like that but no.. it doesn't matter how many seconds/minutes pass between selecting a product and clicking the subsystems menu for the first time, on first click it ALWAYS shows empty option list and then on subsequent clicks in shows the right data.

Is this a known bug?

Thanks!

**Comment by cibernox** [comment]
Are you using 0.6.0-beta.4?

**Comment by Lazarevsky** [comment]
I am indeed

**Comment by cibernox** [comment]
In that case is new. Can you come up with a reproducible example? Perhaps a small ember-cli-app with only 2 selects and a similar logic.

**Comment by amageed** [comment]
Just weighing in here... I haven't had this issue since version 0.6.4, and given that the other issue was closed I think this has been resolved.

**Comment by Lazarevsky** [comment]
You are absolutely right amageed - the issue was not coming from ember-power-select but from another part of my code.

Closing the issue
