### ISSUE TITLE
Release using EBD 4?

### ISSUE THREAD

**Issue by lougreenwood** [cibernox/ember-power-select#1489]
I'm getting some dependency lint configs since EBD 4 was released? Is a release of power select due which includes this dependency  upgrade? 🤞 

Thanks!

**Comment by cibernox** [comment]
I need to make it compatible with both versions. There's nothing preventing it from working with 3 o 4.

**Comment by cibernox** [comment]
Released 5.0.1 that allows both v3.1+ and v4 of ember-basic-dropdown. v4.0 was mainly bumped because it drops IE11 support.

**Comment by lougreenwood** [comment]
Beautiful, thank you @cibernox so much for handling this (and doing it so quickly 🎉)
