### ISSUE TITLE
Persistent Deprecation Warning on Ember 3.28

### ISSUE THREAD

**Issue by sdellisImpinj** [cibernox/ember-power-select#1497]
After upgrading to Ember 3.28, I start to see this whenever I build the app:

DEPRECATION: registerPlugin is deprecated, please pass plugins directly via compileand/orprecompile. [deprecation id: template-compiler.registerPlugin]

This appears to be due to ember-maybe-in-element (which is a dependency of ember-basic-dropdown) not updating their version of ember-cli-htmlbars:
DockYard/ember-maybe-in-element#47

Since ember-maybe-in-element hasn't been touched since May, 2021 I filed an issue with ember-basic-dropdown to hopefully get it fixed on their end (by not using ember-maybe-in-element, which only provides a small convenience):
https://github.com/cibernox/ember-basic-dropdown/issues/640

My hope with filing this issue here is to track this and hopefully get ember-power-select updated with a hypothetical future version of ember-basic-dropdown so that it won't block me folks from migrating to Ember 4.0 (since this deprecation warning will turn into a proper error at that point).

**Comment by villander** [comment]
I have an issue with the Ember 3.28 #1498 complaining about duplication of `ember-cli-htmlbars`

**Comment by raido** [comment]
For me deduplication of packages solved it - https://github.com/DockYard/ember-maybe-in-element/issues/47#issuecomment-1039088546

**Comment by cibernox** [comment]
What's the fix for this? Update `ember-cli-htmlbars`? If so, to what version?

**Comment by sdellisImpinj** [comment]
Updating to the latest version of ember-power-select and running radio's deduplication suggestion resolved this for me.
