### ISSUE TITLE
Import ember-power-select styles doesn't work on Addons/Engines

### ISSUE THREAD

**Issue by villander** [cibernox/ember-power-select#1507]
I have an addon that uses SASS and I'm trying to use the import described in that guide: https://ember-power-select.com/docs/installation

`@import "ember-power-select` doesn't work on addons and engines inside the monorepo, only works in the ember app. 

Is there a hack on #1421 accessing `node_modules` but I assume it's not what we want here, right? 

cc:// @cibernox

**Comment by cibernox** [comment]
TBH I haven't used engines in ... 3 years? Maybe more. 
If the addon is a direct dependency of the engine, `@import "ember-power-select` doesn't work? 
I'm not sure what changes would be required.

**Comment by BryanCrotaz** [comment]
any news on this? Is there a workaround?

**Comment by cibernox** [comment]
The styles very rarely change, if ever. A workaround could be to copy the relevant files from https://github.com/cibernox/ember-power-select/tree/master/app/styles into your app/engine.
