### ISSUE TITLE
Tag mode -- ability to type a value not from the options list

### ISSUE THREAD

**Issue by lolmaus** [cibernox/ember-power-select#151]
Hi!

I want users to select a value from the dropdown, but they should also be able to type a new value not available in the dropdown list.

Currently I have to use two fields: a text input and a dropdown. It would be awesome if ember-power-select allowed doing that without the extra text input.

**Comment by cibernox** [comment]
Pull request #150 covers this use case. Will be merged today.

**Comment by cibernox** [comment]
Closed via #150
