### ISSUE TITLE
Issue using Ember Data for options with ember-power-select v5.0.4 

### ISSUE THREAD

**Issue by danieledraganti** [cibernox/ember-power-select#1516]
Similar to #1482.
I have the following component, using `ember-bootstrap-power-select` (which basically renders a `power-select` component with the relative args, no magic here):
```
      <form.element
        @controlType="power-select"
        @property="parentId"
        @label={{t "customers.fields.parentId"}}
        @options={{this.resellers}} as |el|>
        <el.control
          @placeholder={{t "customers.fields.parentId"}} as |option|>
          {{option.name}}
        </el.control>
      </form.element>
```
And in the relative controller:
```js
  get resellers() {
    return this.store.query('customer', {type: 'reseller'});
  }
```

I get a similar error as in the mentioned issue, which is, the component shows "Loading data..." even when the promise has been resolved already, and the add-on keeps triggering REST requests to the backend.
Seeing that it could be due to the `@ember/render-modifiers` add-on, I forced the latest version (2.0.4) in the `package.json`, but I still get the same error.
Does anyone else still get this? Is there any other workaround?

**Comment by cibernox** [comment]
I really don't have any advice or idea of what can be the reason for that without a mire detailed reproduction, which doesn't seem easy to provide with so many addons working together.
