### ISSUE TITLE
Option for moving the arrow icon to the other side

### ISSUE THREAD

**Issue by alechirsch** [cibernox/ember-power-select#1518]
I looked through the docs and could not find anything that woudl allow me to move the arrow icon from the right side to the left side. Does an option like this exist, or is this a new feature?

**Comment by cibernox** [comment]
There is no option because that is more easily done with pure css.  Making the trigger a flexbox container and reversing the flow to right-to-left is how I'd probably do it. `Float: left` is another option. There are several ways.


I hope it helps.
