### ISSUE TITLE
async doc page doesn't work

### ISSUE THREAD

**Issue by Kallin** [cibernox/ember-power-select#152]
The search here is generating js errors:
http://www.ember-power-select.com/docs/asynchronous-search

![screen shot 2015-11-27 at 10 17 06 am](https://cloud.githubusercontent.com/assets/158169/11444055/4b111478-94f0-11e5-99a4-769c095ef8a6.png)

**Comment by cibernox** [comment]
Oops, that's because I enabled ember-cli-mirage in production by mistake. Thanks for reporting. Will fix this evening.
