### ISSUE TITLE
Documentation missing for Bootstrap and Material themes

### ISSUE THREAD

**Issue by EstesE** [cibernox/ember-power-select#1520]
The links on [https://ember-power-select.com/docs/styles](https://ember-power-select.com/docs/styles) to the Bootstrap and Material theme documentation are not working (404).

**Comment by cibernox** [comment]
thanks! I'll take a look

**Comment by craigteegarden** [comment]
I have the same issue with all direct links on the project site. It seems like a Netlify redirect config might need to be adjusted to work with single page apps that use pushSate:

https://answers.netlify.com/t/deploying-single-page-applications/14695

**Comment by mkszepp** [comment]
Closing, as we have refacored the netlify script and it works now
