### ISSUE TITLE
Upgrade to the latest version of basic-dropdown

### ISSUE THREAD

**Issue by azhiv** [cibernox/ember-power-select#1521]
Are there any plans on migrating to the latest version of `ember-basic-dropdown` which is currently `6.0.1`?  `basic-dropdown` has migrated to the latest version of `ember-modifier`, so did we in our project. But as of now, since you are referencing `ember-basic-dropdown 4.0.2` it's impossible for us to move forward with the upgrade.

**Comment by cah-briangantzler** [comment]
I cant remember if NPM provides for this, but if you are using yarn try adding a resolutions block. Below is the one from my app. We had to do this for the `@embroider` packages to solve the same problem. If you add ember-basic-dropdown here, it should resolve the one being used by ember-power-select to the version you specify

An other example would be `ember-cli-mirage` is currently pointing to `0.1.43` of `miragejs` and this resolution gets me to update my version to `0.1.45` and then the resolution ups the `ember-cli-mirage` version to the same.  
```
  "resolutions": {
    "miragejs": "~0.1.45",
    "@embroider/macros": "^1.7.0",
    "@embroider/util": "^1.7.0",
    "ember-cli-babel": "^7.26.1",
    "@fortawesome/fontawesome-svg-core": "1.2.35"
  }
```

**Comment by edflips** [comment]
Resolving to `"ember-basic-dropdown": "6.0.1"` in our `package.json` does fix our issue and allows us to move forwards; although I'd like to see `power-select` updated so we don't have to do this.

**Comment by mansona** [comment]
Hey folks 👋 I opened a PR on this today https://github.com/cibernox/ember-power-select/pull/1524

It's mostly to start the discussion because it has some changes to the aria implementation that I don't understand 🤔
