### ISSUE TITLE
Failed to execute 'observe' on 'MutationObserver'

### ISSUE THREAD

**Issue by koryteg** [cibernox/ember-power-select#154]
getting this error:
`Uncaught NotFoundError: Failed to execute 'observe' on 'MutationObserver': The provided node was null. basic-dropdown.js:200`

 ``` handlebars
{{#power-select
  placeholder="pick some tags"
  options=tags
  selected=campaign_email.tags
  onchange=(action (mut campaign_email.tags))
  multiple=true
  as |tag|}}
  {{tag}}
{{/power-select}}
```

`tags` is an array of strings and `campaign_email.tags` is a property on a ED model

any idea what this could be?

**Comment by cibernox** [comment]
Code looks ok. Which version are you using?

The error is in [this line](https://github.com/cibernox/ember-basic-dropdown/blob/master/addon/components/basic-dropdown.js#L139), but I don't know why would `.ember-basic-dropdown-content` be null. 

More info. Version of the addon? Is this componen getting rendered properly in other situations?

**Comment by koryteg** [comment]
on version 0.5.2

**Comment by cibernox** [comment]
Try first to update and see if that helps. If not we'll dig deeper

**Comment by koryteg** [comment]
updated to `0.6.0-beta.6` no difference. `ember-basic-dropdown` is version `0.6.3`. that was released 3 days ago. ill try `0.6.2`.

**Comment by koryteg** [comment]
adding `renderInPlace=true` fixed it. not sure what you want to do with that. close if you want to but might be a bug still.

**Comment by cibernox** [comment]
I suspect that it has to do with the ember-wormhole. 

Is the div `<div id="ember-basic-dropdown-wormhole"></div>` properly appended to the DOM? 
Have you installed ember-basic-dropdown and ember-power-select separately? And ember-wormhole?

Many people is using the addon without any problem so I imagine that it has to be something in your specific installation, but I'd need more info to be sure.

If you could reproduce the problem creating an empty app with the same package.json and a minimal reproducible example I'd love to investigate it further.

**Comment by cibernox** [comment]
This is probably related to #145, so I'm closing it.
