### ISSUE TITLE
incompatible with ember-style-modifier

### ISSUE THREAD

**Issue by jeffstagedoor** [cibernox/ember-power-select#1554]
Somehow ember-power-select and ember-power-calendar will not work anymore once ember-style-modifier is installed.
I'm sorry that can't give more investigative information or hints on why.

**Comment by cibernox** [comment]
Ember-basic-dropdown, which the other addons use, depends on   `"ember-style-modifier": "^0.8.0",`. Probably that version should be updated.

**Comment by cibernox** [comment]
I just release a minor update of ember-basic-dropdown, 6.0.2. 

Reinstalling your dependencies should fix the problem. At least I believe it will.
