### ISSUE TITLE
beforeOptionsComponent args are overridden

### ISSUE THREAD

**Issue by mswedgar** [cibernox/ember-power-select#1561]
![企业微信截图_16729987125788](https://user-images.githubusercontent.com/6195824/210976202-fab58567-35df-4add-aa52-48f8711b499d.png)

EmberPowerSelect will override my own beforeOptionsComponent's arguments, please consider avoiding this

**Comment by mkszepp** [comment]
Sry but i havend understand the exact problem.

We pass on all custom components / default component always the same paramenters

If you have custom parts you need to pass it with extra paramenter
