### ISSUE TITLE
onChange not fired when selected value is updated programmaticaly

### ISSUE THREAD

**Issue by andr31** [cibernox/ember-power-select#1574]
Having an usage like this
```
          <PowerSelect
            class="search-select"
            @allowClear={{false}}
            @searchEnabled={{true}}
            @searchField="name"
            @triggerClass="project-branch-breadcrumb-selector"
            @dropdownClass="project-branches-option-list"
            @selected={{this.selectedBranch}}
            @options={{this.model.branches}}
            @onChange={{this.onBranchChange}}
            as |branch|
          >
            <FaIcon class="margin-left-tiny" @icon="code-branch" @fixedWidth={{true}} @prefix="fal" @size="sm" />
            {{branch.name}}
            {{if branch.isDefault (t "app.portfolio.portfolio-item.branches.default.title")}}
          </PowerSelect>
```
onChange is fired correctly if switching between values in the dropdown.
The problem: onChanged does not fire at all if the `@selected` attribute is updated by a getter or a button action for example instead of manually selecting a different option. The selected value shows up correctly in the component but onChange event is not being triggered.

Any thoughts is this expected behavior?

**Comment by mkszepp** [comment]
Sry for delayed response...

This behavior is correctly, because the seleced value will be changed in your passed onChange function.

If you change the value outside of eps, you can call the same onChange function or you need to outsource codeparts in an other function which you can call pn both actions
