### ISSUE TITLE
Null as a legit value

### ISSUE THREAD

**Issue by lolmaus** [cibernox/ember-power-select#158]
Hi, thank you for the awesome addon.

I'm trying to manage relationships with `ember-power-select`. Everything is fine, except that I'm unable to remove a relationship.

I tried providing a `null` value like this:

```js
[null, ...this.get('parent.children').toArray()]
```

But `{{power-select}}` ignores `null`. The dropdown only has records and no blank value.

To work around that, I had to use ids instead of records and wordy actions instead of `(action (mut parent.children))`.

**Comment by cibernox** [comment]
I think I'm missing something. You mean that one of the records in a hasMany relationship is `null`?
Is that even possible?

Also:
- Version of the addon
- Version of Ember
- Version of ember-data

**Comment by lolmaus** [comment]
I'm talking about a `belongsTo` relationship and it can be `null`.

This `[null, ...this.get('parent.children').toArray()]` is an array of options I'm trying to pass to `{{power-select}}`.

* ember-power-select: 0.5.2
* ember: 1.13.11 or 2.2.0
* ember-data: 1.13.11 or 2.2.0

**Comment by cibernox** [comment]
Ok, understood. So want to mix two relationships into a single array, and one of them is null.

So the problem is that you want null to be a valid value. I'm not aware of having disallowed that explicitly, but perhaps there is some kind of null check. In any case seems like an odd requirement. What will you show when the option in null?

`[null, ...this.get('parent.children').toArray()].map(x => ({ content: x }))` can work for now?

**Comment by lolmaus** [comment]
> What will you show when the option in null?

A blank line. That's a typical way of letting user select nothing.

**Comment by lolmaus** [comment]
> `[null, ...this.get('parent.children').toArray()].map(x => ({ content: x }))` can work for now?

Won't this make it impossible to use the `mut` helper to update the relationship without coding a wordy action?

**Comment by cibernox** [comment]
yes, you'd need to code an action yourself. 

If you want to allow the user to select nothing there is an `allowClear` option that might give you the same functionality (select nothing). I don't know if usability-wise it's better or worse than having a blank option.

**Comment by lolmaus** [comment]
> If you want to allow the user to select nothing there is an `allowClear` option

Oh, cool! Why is it not documented?

What does it set the value to?

**Comment by corrspt** [comment]
It's [documented](http://www.ember-power-select.com/docs/the-trigger), but it doesn't work on `multiple=true`

**Comment by lolmaus** [comment]
> It's documented,

Awesome, thank you! I wish the docs had an explicit list of options, though.


> but it doesn't work on `multiple=true`

`multiple=true` is already capable of a blank array! :D


PS Can you please tell me, what does `allowClear` set the value to when the empty option is selected?

**Comment by cibernox** [comment]
I'd say that it sets the value to null: https://github.com/cibernox/ember-power-select/blob/master/tests/integration/components/power-select-test.js#L1259-L1280

**Comment by cibernox** [comment]
If this covers your use case I'll close that issue. 

But I'm curious about why null is not a valid value. It's not something I planned on purpose.

**Comment by lolmaus** [comment]
Yeah, it does cover my use case! Thank you.
