### ISSUE TITLE
Breaking change, needs major.

### ISSUE THREAD

**Issue by betocantu93** [cibernox/ember-power-select#1590]
Hello, we bumped ember-power-select to 7.1.0 in our addon, ember-eui but it seems that version added a new component 

`power-select-multiple/input` caused our tests to fail, because we used this.handleInput which was previously inside `power-select-multiple/tigger` backing class and now was refactored to the `input`. 

I think it's a way better api to have another slot there (`input`) but I also was surprised it wasn't released as a major with breaking changes, my suggestion would be to just re-release it as a major to respect semver and also somehow mark 7.1.0 as deprecated or anything that points that it was a major instead or a minor

Also, please let me know if you need any help with this or any further maintenance, happy to help

**Comment by mkszepp** [comment]
@betocantu93 sry for this incident... unfortunately, we cannot undo / deprecated the latests v7.x versions. We will take better care in the future for that.

As i have seen there was already fixed in `ember-eui` and there is possible to resolve in own app, we can close the issue
