### ISSUE TITLE
Whole repo published to npm

### ISSUE THREAD

**Issue by NullVoxPopuli** [cibernox/ember-power-select#1605]
should probably only publish what's needed.

https://www.npmjs.com/package/ember-power-select?activeTab=code

![image](https://github.com/cibernox/ember-power-select/assets/199018/787107a0-ee09-4099-9ecb-0db9c2bdaca5)

**Comment by mkszepp** [comment]
@NullVoxPopuli addon is now a V2 addon and we publish only necessary code parts
https://www.npmjs.com/package/ember-power-select/v/8.0.0-beta.0?activeTab=code

![grafik](https://github.com/cibernox/ember-power-select/assets/19845290/023a3853-6788-4ec9-b0b0-441172449220)
