### ISSUE TITLE
Change to importable CSS

### ISSUE THREAD

**Issue by NullVoxPopuli** [cibernox/ember-power-select#1607]
few reasons:
- some folks may want their own CSS
- some folks don't want preprocessors (less, scss, which are forced right now)
- allows folks to opt in to which css customizations they want.

potential examples:

```js
// app.js
import 'ember-power-select/styles';
import 'ember-power-select/theme/material'; // or whatever
```

**Comment by mkszepp** [comment]
@NullVoxPopuli `ember-basic-dropdown` and `ember-power-select` are now V2 addon (both were released now as beta v8.0.0-beta.0). The migration to v2 addon has bring also some braking changes see https://github.com/cibernox/ember-power-select/pull/1619 & https://github.com/cibernox/ember-basic-dropdown/pull/728

The css is now not anymore auto-imported. It must be manually done like you have described.

CSS import example is present in documentation:
- https://ember-power-select.com/docs/installation
- https://ember-power-select.com/cookbook/bootstrap-theme
- https://ember-power-select.com/cookbook/material-theme

**Comment by johanrd** [comment]
I also stumbled upon the change in v2 when importing css in vanilla css contexts. FWIW, I found it possible to import the css directly into /assets/styles.css like this:

```css
@import 'ember-power-select/vendor/ember-power-select.css';
```

(It may be a matter of personal taste, but I find it cleaner to import css directly in css, and not via js.).

**Comment by NullVoxPopuli** [comment]
Importing in css is fine, but more confusing to recommend, because in order to get the css to be part of your module graph, you need css imported into js.
That is, it's not clear if importing in to css is from special css that already participates in the module graph, or if from the legacy style system, which is always global, and can't participate in route based (or any kind of) splitting ever

**Comment by mkszepp** [comment]
There are a lot of options to import the css in the app... but i think we should add only one way in documencation (which is already), because i think that is the recommended way.
Since the file is public everyone can add it like he want. We can block that only by creating a "-private" folder, but if somebody want to import from "-private" he has always the possibility.

Option 1 (recommended):
```js
// app.js or other js file
import 'ember-power-select/styles';
```

Option 2:
```css
/* assets/styles.css */
@import 'ember-power-select/vendor/ember-power-select.css';
```

Option 3:
```js
// ember-cli-build.js
app.import('node_modules/ember-power-select/vendor/ember-power-select.css');
```

**Comment by NullVoxPopuli** [comment]
Option 3 should be banned from historical records 😅 

Option 2 in fine for tiny apps.

But only importing in js, or css-that-participates-in-the-module-graph, can you canditionally get the power-select css upon an `await import(..)` component/route/whatever.

> but i think we should add only one way

This would be ideal, but (un)fortunately we don't have only one way. 
Hopefully soon tho!

**Comment by mkszepp** [comment]
okay thank you!
I have removed option 3 in my comment 😅...

If i have understand corretly, we should add option 2 also in docs with example from a component and describe, that there is also possible to use in route and controllers... right?

**Comment by NullVoxPopuli** [comment]
> If i have understand correctly, we should add option 2 also in docs with example from a route and describe, that there is also possible to use in component and controllers... right?

yeah, exactly.

> The blueprint adds always this lines in app.js like in your initial comment

yeah, it's the lazy documentation way.


And _depending on your app's build config_, you can use 
```css
@import 'ember-power-select/styles`
```
_and_ have it participate in the module graph.

It's a weird balance between trying to document what's possible, and trying not to cover all cases possible.
I _like_ to lean towards over-documenting this sort of stuff, because build behavior is super opaque to folks unfamiliar with how crazy JS build tooling is.

**Comment by mkszepp** [comment]
@NullVoxPopuli @johanrd i have added the option in docs... would you like to review before we merge it?

**Comment by johanrd** [comment]
oh, great. Looks good to me. 

I learnt something new regarding the module-graph benefits of importing through js, thanks! Regarding the benefits – if i understand it correctly – importing directly to `app.js`, won't give any module loading benefits, right? – you would rather need to `import 'ember-power-select/styles';` in all the actual components / controllers / routes that are using ember-power-select.

**Comment by NullVoxPopuli** [comment]
Correct

**Comment by mkszepp** [comment]
Great! Many thanks for imputs... PR is merged and so i think, that we can also close this issue
