### ISSUE TITLE
Issue with default selected state for an object

### ISSUE THREAD

**Issue by gregjopa** [cibernox/ember-power-select#162]
I just switched from using select2 to this addon and it's awesome! Everything has worked great except for the default "selected" state. I'm not sure if this is a bug or if I'm doing something wrong on my end. Here is the code I'm working with:

Template:
```handlebars
{{#power-select
  options=repos
  selected=selectedRepo
  onchange=(action (mut selectedRepo))
  placeholder="Select repo"
  searchField="name"
  as |repo|}}
  {{repo.name}}
{{/power-select}}
```

Controller data:
```js
repos: Ember.A([
  { name: 'ember', id: 'emberjs/ember.js' },
  { name: 'angular', id: 'angular/angular' },
  { name: 'backbone', id: 'jashkenas/backbone' },
  { name: 'knockout', id: 'knockout/knockout' }
]),

selectedRepo: { name: 'ember', id: 'emberjs/ember.js' }
```

There seems to be an issue with the equality statement for the selected value: https://github.com/cibernox/ember-power-select/blob/master/addon/helpers/ember-power-select-option-classes.js#L11. If you manually select a different item from the dropdown list the selected state successfully works. It just doesn't work for the default selected state.

You can see a demo of this issue here: http://gregjopa.me/ember-reporting-dashboard/#/details.
Demo code: https://github.com/gregjopa/ember-reporting-dashboard

Versions:
Ember: 1.13.11
ember-power-select: 0.5.2

**Comment by cibernox** [comment]
The reason is that this component compares objects by equality.

Remember that `{ foo: 'bar; } === { foo: 'bar' }` and `{ foo: 'bar; } == { foo: 'bar' }` are both false. They are not **the same object**.

Try
```js
repos: Ember.A([
  { name: 'ember', id: 'emberjs/ember.js' },
  { name: 'angular', id: 'angular/angular' },
  { name: 'backbone', id: 'jashkenas/backbone' },
  { name: 'knockout', id: 'knockout/knockout' }
]),

selectedRepo: Ember.computed.oneWay('repos.firstObject')
```

and close this issue if this works for you.

**Comment by gregjopa** [comment]
Thanks, that worked! The object comparison tripped me up. I think I get it now. The object comparison for determining "selected" is done by reference, not by value. So if its a reference to the same object it returns true.

 Ex:
```js
var repo1 = { id: 'ember' };
var repo2 = repo1;
var repo3 = { id: 'ember' };

repo1 === repo2  // returns true
repo1 === repo3  // returns false
```

**Comment by cibernox** [comment]
For the record, the reason for that is just simplicity. This addon compares using `===` (although in this case `==` would give the same result).

Comparing objects by content is tricky because the comparison has to iterate over all the keys comparing, and in case the key contains another object it needs to compare recursively that object too.

Since it's generally easy to fix in user-land I decided to not be that smart.

**Comment by gregjopa** [comment]
That seems reasonable to me. Ember doesn't seem to have a helper function for comparing objects and adding lodash for this would be a large dependency (https://lodash.com/docs#isEqual). I like the fact that this library is lightweight with few dependencies. So I agree with your design decision. If other devs get tripped up by this issue then we could always add a note about it in the troubleshooting section of the docs.

**Comment by devop911** [comment]
@cibernox 
What is the best way to handle this, I adore, that you like to keep your API as simple as possible, but 
we need to write very much code, it could be easily removed, if you had an component argument like:
equalPropertyKey = id.

Atm we need to do this trick:

```
 selectedGroups: computed('model.user.groups.edges.[]', function () {
    return this.model.groups.edges.reduce((result, group) => {
        if (this.model.user.groups.edges.mapBy('node.id').includes(group.node.id)) {
          result.push(group)
        }
        return result;
      },
      []);
  }),
```

What is the best practice for this issue?

**Comment by cibernox** [comment]
@devop911 since elements are compared with `Ember.isEqual`, that method checks if objects have an `isEqual` method implemented. Usually I do this:

```js
selectOptions: computed('model.user.groups.edges.[]', function() {
  return this.get('model.user.groups.edges').map(g => { group: g, isEqual: (g1, g2) => g1.id === g2.id }
```

**Comment by cibernox** [comment]
@devop911 that said, I think I don't oppose to your idea anymore, as long with the same option can take both a property name or a function to be invoked with the option.

Property name:
```hbs
<PowerSelect @options={{opts}} @selected={{thing}} @onChange={{action (mut thing)

 @isEqual="id" as |opt|>
  {{opt}}
</PowerSelect}}
```

Function:
```hbs
<PowerSelect @options={{opts}} @selected={{thing}} @onChange={{action (mut thing)

 @isEqual={{this.compareOptions}} as |opt|>
  {{opt}}
</PowerSelect}}
```
```js
compareFunctions(o1, o2) {
  return o1.id === o2.id; // The compare function could be arbitrarily complex this way.
}
```

**Comment by devop911** [comment]
This is a loveley Idea! 
Would love to see it in next version
