### ISSUE TITLE
V2 addon error: ember-power-select is trying to import from #embroider_compat but that is not one of its explicit dependencies

### ISSUE THREAD

**Issue by johanrd** [cibernox/ember-power-select#1622]
Hi. Great work on the port to V2 addon!

Stumbled upon a couple of errors with `v8.0.0-beta.0`
```
Build Error (PackagerRunner) in ../../.pnpm/ember-power-select@8.0.0-beta.0_@ember+test-helpers@3.2.1_@glint+environment-ember-loose@1.2._bnfzrf5wx5clqt7xmhrz5t7dbi/node_modules/ember-power-select/dist/components/power-select.js

Module not found: Error: ember-power-select is trying to import from #embroider_compat but that is not one of its explicit dependencies
```

```
"ember-cli": "^5.4.1",
"ember-auto-import": "^2.7.1",
"ember-source": "5.5.0",
"@embroider/compat": "3.4.3",
"@embroider/core": "3.4.3",
"@embroider/router": "2.1.6",
"@embroider/webpack": "3.2.1",
"ember-power-select": "8.0.0-beta.0",
```

**Comment by mkszepp** [comment]
Hi @johanrd,

can you try to add ember-basic-dropdown as dependency `"ember-basic-dropdown": "8.0.0-beta.0",` and check if it works after that...

i have discoverd that the blueprint was not exported correctly and so also this dependency was not added.

**Comment by johanrd** [comment]
@mkszepp thanks, yes, I can verify that adding `ember-basic-dropdown@8.0.0-beta.1` to package.json fixes this error.

**Comment by mkszepp** [comment]
@johanrd great! i have extended the documentation (manual installation), that ember-basic-dropdown is necessary & blueprint should be fixed with next version
