### ISSUE TITLE
V2 addon error: Module not found: Error: Can't resolve 'ember-power-select/test-support'

### ISSUE THREAD

**Issue by johanrd** [cibernox/ember-power-select#1623]
Hi. Great work on the port to V2 addon!

Stumbled upon a couple of errors with `v8.0.0-beta.0`
```
"ember-cli": "^5.4.1",
"ember-auto-import": "^2.7.1",
"ember-source": "5.5.0",
"@embroider/compat": "3.4.3",
"@embroider/core": "3.4.3",
"@embroider/router": "2.1.6",
"@embroider/webpack": "3.2.1",
"ember-power-select": "8.0.0-beta.0",
```

WIth ember-cli `ember-serve`:

```
import { selectChoose } from 'ember-power-select/test-support'
```

VS Code seems to import it correctly, yet embroider seems to struggle:

```
Build Error (PackagerRunner) in tests/acceptance/example-test.ts

Module not found: Error: Can't resolve 'ember-power-select/test-support' in 'app/node_modules/.pnpm/ember-power-select@8.0.0-beta.0_@ember+test-helpers@3.2.1_@glint+environment-ember-loose@1.2._bnfzrf5wx5clqt7xmhrz5t7dbi/node_modules'
```

Looking at the [docs](https://ember-power-select.com/docs/test-helpers), the correct import is 

```
import { selectChoose } from 'ember-power-select/test-support'
```

Yet, looking in [`test-app`](https://github.com/cibernox/ember-power-select/blob/master/test-app/tests/acceptance/helpers-test.js#L9) it seems like the expected import is from 

```
import { selectChoose } from 'ember-power-select/test-support/helpers';
```

not sure why vs code gets it but embroider does not.

**Comment by mkszepp** [comment]
thanks for reporting... it looks like there was some outdated/deprecated code part in the test-app

correct way is `import { selectChoose } from "ember-power-select/test-support`.

I have fixed the export in V2 addon and updated the tests

**Comment by mkszepp** [comment]
It should be fixed in `v8.0.0-beta.1`

**Comment by cah-brian-gantzler** [comment]
Should this be listed in the migration docs? There are other helpers that were moved which some (clickTrigger) for example were left in `/helpers'. Had to go through one by one til I got all my tests to pass.

**Comment by mkszepp** [comment]
@cah-brian-gantzler you can use the `clickTrigger` like before, its no braking change... Can you tell me more about your issue?

Here our example in test-app:
https://github.com/cibernox/ember-power-select/blob/549acda816f9ed66589980ba04be951b5237e45a/test-app/tests/integration/helpers-test.js#L6-L10

Braking is possible `selectChoose` from `/helpers`, but this was already deprecated in v1, but deprecated code was never removed
https://github.com/cibernox/ember-power-select/blob/f54704662c59583f9ae97fdf312b023c8c080cc5/addon-test-support/helpers.js#L113-L123
