### ISSUE TITLE
Unable to highlight a specific object option

### ISSUE THREAD

**Issue by rogeraraujo90** [cibernox/ember-power-select#1629]
When we use object options, we are unable to highlight a specific option. The first one is always the current when the dropdown is opened.

I did a fast investigation and looks like we should be using `isEqual` [here](https://github.com/cibernox/ember-power-select/blob/master/ember-power-select/src/utils/group-utils.ts#L43), and [here](https://github.com/cibernox/ember-power-select/blob/master/ember-power-select/src/utils/group-utils.ts#L67)

Looks like a fast fix!

**Comment by mkszepp** [comment]
Hi @rogeraraujo90 thanks for reporting...

Can you provide an example in which case it dosn't match? So we can add a test and fix it.

**Comment by rogeraraujo90** [comment]
Hi @mkszepp, I have group options like that:

```js
class TimePickerOption {
  constructor(group, value) {
    this.group = group;
    this.value = value;
  }

  isEqual(other) {
    return this.group === other?.group && this.value === other?.value;
  }
}

const options = [{
  groupName: "period",
    options: [
      new TimePickerOption("Period", "AM" ),
      new TimePickerOption("Period", "PM" ),
    ]
}]
```
Given these options, if I try to highlight the option with the value "PM", the `isEqual` method is not called. Internally, we do the `entry === option`, which will always return `false`. If replacing by `isEqual(entry, option)`, this would work.

I was trying to highlight the option by doing:

```js
eps.actions.highlight(new TimePickerOption(PERIOD_GROUP, period));
```

Let me know if you need more info!

**Comment by rogeraraujo90** [comment]
Hey, just noticed that, due to a similar cause, the `aria-current` is not properly defined as "true". We need a logic similar what we have for `aria-selected` [here](https://github.com/cibernox/ember-power-select/blob/master/ember-power-select/src/components/power-select/options.hbs#L31).

**Comment by rogeraraujo90** [comment]
Let me know if I can help with the fix! I'm using EPS in a new feature in my project :)

**Comment by mkszepp** [comment]
@rogeraraujo90 you want you can add a PR for your requests

**Comment by rogeraraujo90** [comment]
> @rogeraraujo90 if you want you can add a PR for your requests

I just opened the PR!
