### ISSUE TITLE
v0.6.1 doesn't actually use getOwner polyfill

### ISSUE THREAD

**Issue by mike183** [cibernox/ember-power-select#163]
The change log seems to suggest that v0.6.1 should include a bug fix to avoid deprecation warnings in Ember 2.3 using the getOwner polyfill. I assume this was supposed to include the [PR](https://github.com/cibernox/ember-basic-dropdown/pull/22) that @toranb submitted to ember-basic-dropdown.

It appears that this isn't the case due to the lastest release of ember-basic-dropdown not including the bug fix, as a result deprecations are still being thrown in Ember 2.3.

**Comment by cibernox** [comment]
Bad release. Will fix in a moment.

**Comment by cibernox** [comment]
Published to NPM

**Comment by mike183** [comment]
Awesome, deprecations have gone!
