### ISSUE TITLE
Rendering Issue With Ember 2.2.0

### ISSUE THREAD

**Issue by flynnawtc** [cibernox/ember-power-select#166]
Hi
I have been testing ember-power-select (0.6.2) with Ember 2.2.0 and am seeing a rendering bug in both Firefox and Chrome as follows:
  - create two ember-power-select selection boxes
  - click on one to open the  dropdown list (it is rendered correctly)
  - immediately click on the second to open its dropdown list. The first dropdown list disappears as it should but the new one is rendered full width across the top of the page instead of below the trigger.
*Note: The second dropdown list is rendered correctly when using Ember 2.1.0.*

The difference in the rendering is because the ember-basic-dropdown-content div in the wormhole has no styles attached but it should have 'width', 'top' and 'left' values. 

**Simple Sample:**
Create app using ember init
add app/templates/application.hbs
```html
<h2 id="title">Welcome to Ember</h2>

{{outlet}}

<table style='width:80%'>
    <tr>
	<td style='width:50%'>
	    {{#power-select selected=item options=items renderInPlace=false onchange=(action "chooseItem") as |item|}}
		{{item.caption}}
	    {{/power-select}}
	</td>
	<td style='width:50%'>
	    {{#power-select selected=item2 options=items renderInPlace=false onchange=(action "chooseItem2") as |item|}}
		{{item.caption}}
	    {{/power-select}}
	</td>
    </tr>
</table>
```
add app/controllers/application.js
```javascript
import Ember from 'ember';

export default Ember.Controller.extend({
  items: [
	    {caption : 'Item1'},
	    {caption : 'Item2'},
	    {caption : 'Item3'},
	    {caption : 'Item4'}
	],
  item: null,
  item2: null,

  actions: {
    chooseItem(item) {
      this.set('item', item);
    },
    chooseItem2(item2) {
      this.set('item2', item2);
    }
  }
});
```
Any suggestions to make this work with Ember 2.2.0 would be gratefully received.

Thanks for all the work

Adrian

**Comment by cibernox** [comment]
Hey, thanks for reporting! 

I was able to reproduce it, I'll dig into that tomorrow.

**Comment by cibernox** [comment]
For the record, I've found the problem and I know how to fix it, but I want to try to add a test to prevent regressions.

**Comment by flynnawtc** [comment]
Thanks for the quick response. Appreciate the help.
