### ISSUE TITLE
Option to open search and set focus to it when component gets focus. 

### ISSUE THREAD

**Issue by sweco-semtne** [cibernox/ember-power-select#172]
When entering the component from another form field the focus is set but it is not possible to immediately start typing and perform search. 
In a conversation with cibernox a proposed solution is to give the user an onfocus property to bind an action to. The action receives (select, event) and by calling select.actions.open() the search input can be automatically opened onfocus.

**Comment by cibernox** [comment]
Rough design of the feature.

```hbs
{{#power-select options=a selected=foo onchange=(action (mut foo) onfocus=(action "selectFocused") as |opt|}}
  {{opt}}
{{/power-select}}
```

and in the context

```js
actions: {
  selectFocused(select, evt) {
    select.actions.open();
  }
}
```

The reason why I favor this over another property like `openOnFocus=true` is that it gives more freedom to the users to do whatever they feel like, like by example show a tooltip, clear the errors, prefetch results, ect...)
