### ISSUE TITLE
Typing when ember-power-select is active should trigger search

### ISSUE THREAD

**Issue by luketheobscure** [cibernox/ember-power-select#178]
Use Case: As an advanced user, I like to fill out forms using only my keyboard. Using ember-power-select requires an additional keypress (the down arrow) to activate search.

Suggested resolution: Typing anything when ember-power-select is active (i.e., after I have hit "tab" to highlight it) should automatically start the search.

**Comment by cibernox** [comment]
This is already possible with the onfocus action. There is an example in the action-handling section of the docs.
