### ISSUE TITLE
being able to search on select when onfocus

### ISSUE THREAD

**Issue by jcope2013** [cibernox/ember-power-select#179]
so when using the onfocus action, I want to interact with and search on the select but at the moment it isn't exposed, is there a way we can add it to the dropdown actions by merging it in with the existing dropdown actions here https://github.com/cibernox/ember-power-select/blob/master/addon/components/power-select/single.js#L47

we would have access to the base search action as it is extending

https://github.com/cibernox/ember-power-select/blob/master/addon/components/power-select/base.js

example:

```
handleFocus(select, e) {
     select.actions.search("test");
}
```

**Comment by cibernox** [comment]
That makes total sense. I was planning to do that

**Comment by cibernox** [comment]
This should be possible in master since #181
