### ISSUE TITLE
onfocus not being triggered

### ISSUE THREAD

**Issue by luketheobscure** [cibernox/ember-power-select#180]
The onfocus event is not being triggered. I've made an example app here:

https://github.com/luketheobscure/power-select-bug

This is just a generated ember app, and [this](https://github.com/luketheobscure/power-select-bug/commit/305a94cd47826fc86daa650258e5666800b6dfe0) is the commit where I set up ember-power-select.

**Comment by jcope2013** [comment]
ember-power-select in your package.json must be 0.7.0-beta.1

**Comment by cibernox** [comment]
Indeed, that feature was added in 0.7.0.
