### ISSUE TITLE
infinity scrolling, paging

### ISSUE THREAD

**Issue by acerov** [cibernox/ember-power-select#182]
Hi,
discovered this control yesterday and I like it.
I will try to explain what I would like to achieve through example.
You have 1 million items on server, using asynchronous search you hit server with search "term" that qualifies 1000 items but server pages response in chunks of 25 and as you scroll down the power-select it gets page by page in infinite scrolling mode.
I don't know is it possible already or qualify these as feature request.

**Comment by cibernox** [comment]
It is not a built in functionality but you can replace parts of the component with your own. 

The list of options with a component can be replaced entirely with something different, including a component with infinite scroll, but is up to you to implement it. 

If you do so and want to open source it, open a PR to add it to the addons section of the docs
