### ISSUE TITLE
TypeError Cannot read properties of null (reading 'length') on `this.searchText.length > 0`

### ISSUE THREAD

**Issue by johanrd** [cibernox/ember-power-select#1854]
Hi. In sentry I have some reports on `Cannot read properties of null (reading 'length')` on `this.searchText.length > 0` on [get results()](https://github.com/cibernox/ember-power-select/blob/913c85ec82d5c6aeb80a7a3b9d9c21ca9613e900/ember-power-select/src/components/power-select.ts#L293-L297)

Not sure if I am stretching the usage here, but anyways, I think ember-power-select should be resilient towards this.

Two fixes I can think of:

1) Optional chaining on all consumers of this.searchText.length (i.e. `this.searchText?.length`)

```diff
  get results(): any[] {
-    if (this.searchText.length > 0) {
+    if (this.searchText?.length > 0) {
      if (this.args.search) {
        return toPlainArray(this._searchResult || this.options);
```

2) Nullish coalescing on all assignments to this.searchText to ensure it is not null or undefined?

```diff
 @action
  _search(term: string): void {
    if (this.searchText === term) return;
-    this.searchText = term;
+    this.searchText = term ?? '';
    if (!this.args.search) {
      this.lastSearchedText = term;
      this._resetHighlighted();
    }
  }
  ```

**Comment by mkszepp** [comment]
I'm not sure if this is really an issue of EPS, because from type we allow only string for `searchTerm`.
This means that when the app is not passing a string, its an incorrect using, which should be fixed inside app.

In the typed world you issue will never appear, but in JS its always everything possible.

**Comment by johanrd** [comment]
ok, thanks. FYI: I am in a fully typed world (all .gts) and do not get any glint errors in my component usage. Still this issue appears in sentry.

**Comment by mkszepp** [comment]
Hmm... can you share the example like you are using? Because with TS it should bring an error

**Comment by mkszepp** [comment]
Closing in favor of no aditional feedback

**Comment by johanrd** [comment]
@mkszepp Ok, I was finally able to create a reproduction: https://github.com/johanrd/ember-power-select-reproduction-of-issue-1854

This happens if:
1) the matcherFunction returns more results than searching by `searchField` alone.
2) You select an option from the list where the option[searchField] is `null`
3) Then do a backspace. 

<img width="651" alt="Screenshot 2024-12-18 at 17 58 49" src="https://github.com/user-attachments/assets/f9e318a9-96da-4109-bf4e-5be62f780f60" />

**Comment by mkszepp** [comment]
oh... okay that make sense... thank for reporting and PR
