### ISSUE TITLE
The property 'opened' doesn't seem to do anything

### ISSUE THREAD

**Issue by Lazarevsky** [cibernox/ember-power-select#187]
{{isOpened}} // prints true
      {{#power-select searchField="name" placeholder="Please select" options=models opened=true selected=selected onchange=(action "selectionChanged") as |model|}}
        {{hoverable-list-item-edit model=model}}
      {{/power-select}}

IS this a known issue? Thanks

**Comment by cibernox** [comment]
Are you in 0.7.0?

**Comment by Lazarevsky** [comment]
opened was introduced in 0.7.0 - I was on 0.6.0-beta4.
