### ISSUE TITLE
Clear button doesn't seems work on the doc

### ISSUE THREAD

**Issue by ngouy** [cibernox/ember-power-select#189]
So if i get it, there is no multiple=true option, but if i click on the clear button, nothing is cleared and the list appear on the click and disappear just after release the click. 
Is it a bug or i misunderstood ? ...

**Comment by cibernox** [comment]
It is a bug, indeed. Because now the component opens with mousedown instead of click.

I'll fix it before 0.7.0 stable

**Comment by ngouy** [comment]
ty
