### ISSUE TITLE
Up and down keys on Power Selects with search

### ISSUE THREAD

**Issue by snewcomer** [cibernox/ember-power-select#193]
On your website examples, navigating the list brought back from a remote search works with the up and down keys.  However, in my own project, I can't seem to get this functionality.  Below is the template for the power select.  Looking through the code, it looks like you handle enter and backspace, so is navigating through the list of options using the up and down keys provided by default?  Really the only difference I see b/w your examples and mine is that mine uses Ember objects.  Any thoughts?

```
{{#power-select
  selected=ticket.wat
  options=options
  class="t-ticket-wat-select"
  search=(action "update_filter")
  onchange=(action "selected")
  placeholder="Please select an wat"
  as |assignee|
}}
  {{wat.name}}
{{/power-select}}

```

**Comment by cibernox** [comment]
Yes, it is provided by default. Version?

**Comment by snewcomer** [comment]
Touche`.  0.6.2 to the latest works!
