### ISSUE TITLE
Acceptance Testing Search

### ISSUE THREAD

**Issue by snewcomer** [cibernox/ember-power-select#199]
Using the async search example on the power select website gives me an `apply of undefined` error with acceptance tests.  I would guess in a non-testing environment, that approach would work just fine.  For an acceptance test, this is what I had to do to get it to work based on your test code (repository just returns an ArrayProxy fyi)  (https://github.com/cibernox/ember-power-select/blob/master/tests/integration/components/power-select/custom-search-test.js#L70)

```
            return new Ember.RSVP.Promise((resolve, reject) => {
                Ember.run.later(() => {
                    if (Ember.isBlank(search)) { return resolve([]); }
                    resolve(repository.find(search));
                }, 300);
            });

```

**Comment by cibernox** [comment]
I'm not sure of what are you reporting, I need more info.
I have acceptances tests that involve asycnhronous searches and they work ok, so I need a more concrete example.

Also, as usual, ensure you're on the latest version.

**Comment by snewcomer** [comment]
I guess I was just saying that this specific snippet below from the power select website was not acceptance test friendly

```
export default Ember.Controller.extend({
      actions: {
        searchRepo(term) {
          if (Ember.isBlank(term)) { return []; }
          const url = `//api.github.com/search/repositories?q=${term}`;
          return ajax({ url }).then(json => json.items);
        }
      }
    });
```

But I now see in your helpers-testing dummy app that your tests are using the searchAsync action (similar to what worked for me above).

https://github.com/cibernox/ember-power-select/blob/master/tests/dummy/app/controllers/helpers-testing.js

**Comment by cibernox** [comment]
I don't see any reason why this snipped wouldn't be acceptance friendly. What are you using as `ajax`? jQuery ajax? `ic-ajax`? `ember-ajax`?
