### ISSUE TITLE
Select item on tab

### ISSUE THREAD

**Issue by kevinansfield** [cibernox/ember-power-select#20]
With system select boxes and other plugins it's almost always possible to select items by pressing the <kbd>tab</kbd> key.

As well as selecting the currently highlighted option, the default behaviour of moving focus to the next input should be kept unless it's a multi-select in which case the item should be selected and focus kept.

**Comment by cibernox** [comment]
I did it on purpose because I was copying Select2.js and it doesn't selects the highlighted element on tab.
See: https://select2.github.io/examples.html

However I also questioned that design decision while I was developing it. I just considered easier to start the project as a 1:1 copy.

I'll have a look to other libraries like selectize.js and dropkick.js (and the native select) to see what is the general opinion about the subject and perhaps diverge from select2 on this.

**Comment by miguelcobain** [comment]
I've seen selectize.js considered as an UX holy grail.

**Comment by kevinansfield** [comment]
@miguelcobain agreed, that's why we ended up using it over the other options - it matched our UX expectations pretty much exactly.

**Comment by cibernox** [comment]
@miguelcobain @kevinansfield Actually selectize.js DOES NOT select the highlighted option when you press TAB.
It transitions to the next element in the form, but it doesn't select the element.

**Comment by kevinansfield** [comment]
Ah, just realised it's an option in selectize that we've made the default as it was just confusing without, especially in multi-select/token mode.

**Comment by cibernox** [comment]
I'll consider it. 

I want to keep the number of configuration options to a minimum, but perhaps this makes the cut.

Another option would be to have an `onkeypress` action that is called with some info (among that info the highlighted element) and the user decides what to do.

Example:
```hbs
{{#ember-power-select options=options selected=selected onkeydown=(action "handleKeydown") as |city|}}
  {{city}}
{{/ember-power-select}}
```
```js
actions: {
  handleKeydown(state, e) {
    if (e.keyCode === 9) {
       this.set('selected', state.highlighted);
    }
  }
}
```

Seems too verbose tho. I guess that a `selectOnTab` option makes sense. Just need to figure out how that would work in multiple mode.

**Comment by sandstrom** [comment]
Perhaps it varies between OSs, but on OS X (Chrome and Safari) the native select won't do anything on <kbd>tab</kbd>. It will select on <kbd>space</kbd> and <kbd>return</kbd>.

**Comment by cibernox** [comment]
I never realized that the `space` tab also selects the highlighted element. 

In any case, in master branch is already possible to use the `onkeydown` to customize this at will, although that part of the component is not properly documented in the docs page, every action receives as the penultimate argument an object that I like to call the `publicAPI` of the select.

That object has this shape:

```ts
{
  isOpen: <boolean>,
  highlighted: <any>, // the highlighted element
  actions: {
    open: <function>,
    close: <function>,
    search: <function>,
    highlight: <function>,
    select: <function>
  }
}
```

so for someone, make the component select on tab is as simple as:

```js
onKeyDownHandler(select, e) {
  if (e && e.keyCode === 9) {
    select.actions.select(select.highlighted, e);
    select.close(e); // You might want to close the select because the `select` actions *only* selects the value, and nothing else.
  }
}
```

**Comment by BartVanBeurden** [comment]
@cibernox I'm having some problems combining this solution with asynchronous search as described in http://www.ember-power-select.com/docs/custom-search-action.
Specifically, I have following problems:

- blur seems to cancel the timeout, and the search never happens
- on tab, the close action should happen immediately while the select action should be deferred until after the search finishes loading the items

**Comment by cibernox** [comment]
@BartVanBeurden I think that this is expected. If the search has not finished how do you expect to select one item that is there yet by pressing tab? Even if you "schedule" the close until the search is finished, how do you know that you are selecting the right option if your search didn't finish?
