### ISSUE TITLE
selected property too difficult to make work practically

### ISSUE THREAD

**Issue by robneville73** [cibernox/ember-power-select#204]
Either that or I'm just not smart enough....this can't be a unique pattern I've got.

Say I have a route that returns a list of orders and a separate list of someOtherModel. The order model contains a someothermodel_id field. That is to say, some other model is a lookup value (not a relationship to order per se).

For each order, I want to display a power-select on the page with values populated from the someOtherModel array whose value should effectively be bound to each order's someothermodel_id field.

{{#each model.order as |order|}}
...
   {{#power-select
          options=model.someOtherModels
          selected=order.someothermodel_id <== ????????
          onchange=(action "setFromSite" order)
          as |someOtherModel|}}
              {{someOtherModel.someothermodel_id}}
   {{/power-select}}
...
{{/each}}

What the heck am I supposed to put in selected to make this work? Each someOtherModel is going to be a model (i.e. a POJO and not a list of straight id strings). So I can't do what I have there or it'll never be true that: someOtherModels[i] === order.someothermodel_id. 

It feels like there's a piece missing here to allow me to do this. I get that you're trying to keep it simple, but without something like an option to specify a callback function that allows me to specify the comparator function that should be used for the purpose of determining the selected value, I don't see how to get this done.

**Comment by robneville73** [comment]
For that matter I can't even get a simpler idea to work for the same reason.

So, my order model has two other fields that need drop-downs for them. One of them is delivery type. There's only two options:
```
deliveryTypes: [
    {id: 'D', text: 'Delivery', description: 'Delivery', locked: false},
    {id: 'P', text: 'Pick-Up', description: 'Pick-Up', locked: false}
  ],
```
Template looks like this:
```
        {{#power-select
            options=order.deliveryTypes
            selected=order.selectedDeliveryType
            onchange=(action "setDeliveryType" order)
            as |deliveryType|}}
              {{deliveryType.text}}
          {{/power-select}}
```

Then on the order model I've put this:
```
selectedDeliveryType: function() {
    for (var i=0; i < this.deliveryTypes.length; i++) {
      if (this.deliveryTypes[i].id === this.get('deliverytype')) {
        return this.deliveryTypes[i];
      }
    }
  }.property('deliverytype'),
```

THAT works fine. If I programmatically set deliverytype on order, it updates the drop-down correctly. However, I've got another one that's a little different.

On the model, I've got a relationship property like so:
`zones: DS.hasMany('zone', {async: false}),`

And a similar setup on the template:
```
{{#power-select
         options=order.zones
         selected=order.selectedZone
         onchange=(action "setZone" order)
         as |zone|}}
           {{zone.description}}
{{/power-select}}
```

And a similar calculated property on the model:
```
selectedZone: function() {
    this.get('zones').forEach(function(zone, index) {
      if (zone.get('zoneid') === this.get('shipzoneid')) {
        return this.get('zones').objectAt(index);
      }
    }, this);
  }.property('shipzoneid'),
```

That does NOT work as expected. Clearly I need to be able to do this models in the store and not just hard-coded arrays. I'm sure there's some clever way to get this all to work but it seems confusing (at least right now it does). Maybe explaining how I'm being dumb will help the next person though?

Thanks.

**Comment by cibernox** [comment]
The `selected` property must receive the option that is currently selected. Not the id, the _real_ option.

Assuming that `options` is `[{id: 1, name: 'John'}, {id: 2, name: 'Jane'}]`, and the the id of the selected is `2`, then `selected` has to be  the second element of that array (`{id: 2, name: 'Jane'}`).

**Comment by cibernox** [comment]
Regarding the second question (I'm not sure that I fully understand it), this computed property should work:
```js

selectedZone: function() {
    return this.get('zones').findBy('zoneid', this.get('shipzoneid'));
  }.property('shipzoneid'),
```

**Comment by robneville73** [comment]
Yeah I understood the first bit...my confusion was in how to reference the matching option when that option lived in DS.store as opposed to a static array.

So you're saying I have to issue another find inside the computed property so that it references the same object in DS.store as was used to populate options? (which I guess should already be cached)?

**Comment by cibernox** [comment]
However you find more practical. 
You can query the store with the id (will be cached), you can iterate over the records in the list of options to find the one with the given id, or you can create a computed property that mangles the data structure to give you something nicer to iterate. Not really related with the component itself.

The decision of using the object itself instead of `labelPath` and `idPath` like the old `{{view "select"}}` component is intentional, and more often than not results in a nicer experience. In your case since you have the id and not the record you have to add something (a computed property by exaple) to find the record, but it's very straightforward.

**Comment by robneville73** [comment]
" you can iterate over the records in the list of options to find the one with the given id" if I understand you, that's what I'm saying wasn't working for me. It's quite possible I was doing something wrong though.
```
selectedZone: function() {
    this.get('zones').forEach(function(zone, index) {
      if (zone.get('zoneid') === this.get('shipzoneid')) {
        return this.get('zones').objectAt(index);
      }
    }, this);
  }.property('shipzoneid'),
```
in that case, the zones collection was the source of options for power-select while 'shipzoneid' was the key property being compared to it.
```
model.shipzoneid <-- DS.attr('string')
model.zones <--        DS.hasMany('zone')
```
if I programmatically set model.shipzoneid, the calculated property as shown would find the appropriate zone and return that value but it would not cause the power-select to select that option.

In the end I just used this approach http://balinterdi.com/2015/08/29/how-to-do-a-select-dropdown-in-ember-20.html and have been able to make it work in several scenarios just fine. But I know I'll have situations where a type-ahead search-y thing will be nice to have so I'd still like to know what I'm doing wrong. 

I'm sure it is straightforward but I'm apparently having a tough time wrapping my head around it. Sorry for being dense :)

**Comment by cibernox** [comment]
> if I programmatically set model.shipzoneid, the calculated property as shown would find the appropriate zone and return that value but it would not cause the power-select to select that option.

I will. If you return the proper zone it will work. But that example you pasted will return `undefined`. That return is returning from the callback of the forEach, not from the computed property.

Use the example I pasted 2 comments ago.

**Comment by cibernox** [comment]
Closing, reopen if still a problem.
