### ISSUE TITLE
trigger an action after onchange (set to (mut value)) like onfocusout

### ISSUE THREAD

**Issue by ngouy** [cibernox/ember-power-select#211]
My problem is that i have to use the same action myCustomAction on many power-select components after a selection was made.
The second fact is that i'm obliged to use the onChange action like this:
onchange=(action (mut myValue))
because all values cant be set with a generic function, so a good way to do this is with mut helper... And so i cant set onchange to customAction

Am i missing something, or did it the wrong way ? 
Or can we imagine an action triggered like the onfocus action -> onfocusout action ?

Sorry my english

**Comment by cibernox** [comment]
Sorry, but I need more information. I haven't understood the problem you want to solve.

**Comment by ngouy** [comment]
My template have many power-select for many user attributes eg user.job, user.country, user.favourite_color ...
When the user use one of them and select a new value for one of these attrs, i want to update and save the new value (with user.save() ) he selects eg user's job among a job list.

It's not a good choice to directly use a function with observer on user.job because it's not only triggered when the user pick a new one. (but after loading too, etc ..)

But i cant use a generic custom action to send to 'onchange' option like :

{{#power-select
    options=model.job_activity_sectors
    searchField="name"
    selected=model.user.job_activity_sector
    onchange=(action 'customAction')
    as |job|
}} [...] {{/power-select}}

because it only send the <selected value> to my customAction, and i cant send as params which user's attribute i want to update, and so i have to make one customAction by attr.
I cant use neither :

{{#power-select
    options=model.job_activity_sectors searchField="name"
    selected=model.user.job_activity_sector
    onchange=(action (mut user.job))
    as |job|
}} [...] {{/power-select}}
because it just update the user.attr without saving it.

An action triggered when we focus out the component seems me a good way to combine (mut attr) helper and a custom action after this kinda 'auto-update'

**Comment by cibernox** [comment]
Pass the name of the attribute as the first argument to the option and do the save.

```hbs
{{#power-select
    options=model.job_activity_sectors
    searchField="name"
    selected=model.user.job_activity_sector
    onchange=(action 'customAction' 'job_activity_sector')
    as |job|
}} [...] {{/power-select}}
```

```js
actions: {
  customAction(propertyName, selection) {
    this.set('model.user.' + propertyName, selection);
    this.get('model.user').save();
  }
}
```

**Comment by ngouy** [comment]
Gosh ... i tried using it this way :
```handlebars
{{#power-select
    options=model.job_activity_sectors
    searchField="name"
    selected=model.user.job_activity_sector
    onchange=(action 'customAction' 'job_activity_sector'  selected)
    as |job|
}} [...] {{/power-select}}
````
thoughting i had to explicitly give the new selected value in my customAction params...

Thanks a lot. seems logic

**Comment by cibernox** [comment]
Arguments to pass when you create the closure action are "curried" over the ones the action receives when it's invoked, meaning that you pass 2 arguments to the action, and ember-power-select invokes this action with another 2 arguments, the function till be called with 4 arguments in total. 
Your arguments go first and the usual arguments provided by ember-power-select go next. 

Check Ember's docs about this topic: https://guides.emberjs.com/v2.2.0/templates/actions/#toc_modifying-the-action-s-first-parameter

Closing, since this is seems solved.

**Comment by ngouy** [comment]
Ok tanks. Good to know. Sorry for bothering you

**Comment by cibernox** [comment]
Don't worry, I'm here to help.
