### ISSUE TITLE
power-select.js:125 Uncaught TypeError: this.get(...) is not a function

### ISSUE THREAD

**Issue by msalahz** [cibernox/ember-power-select#221]
Hi!, I'm a new user for ember-power-select and I'm trying to replace ember-select2 with it. I notice the following error during the migration `Uncaught TypeError: this.get(...) is not a function` in the following line [/compoants/power-select.js:105](https://github.com/cibernox/ember-power-select/blob/master/addon/components/power-select.js#L105) after debugging I found `this.get('search')` value is `Class {__ember1451491411427: null, __ember_meta__: Meta}` and it's expected to be null

my implementation
```
{{#power-select 
     placeholder="Select Link Name" 
     allowClear=true selected=linkName
     options=model.linksNamesOptions 
     onchange=(action (mut linkName)) as |item|}}
    {{item}}
 {{/power-select}}
``` 
 as a temporary fix I added `search=null` to the component element

I think it's better to validate this using Ember.typeOf() by applying the following change on line 104 :
 `} else if (Ember.typeOf(this.get('search')) === "function") {`

```
ember.js: v2.2.0
ember-power-select: v0.8.0-beta.1
$ ember -v 
version: 2.2.0-beta.2
node: 0.12.7
npm: 2.14.10
os: darwin x64
```

Will be glad to create a PR for this.

**Comment by cibernox** [comment]
Hey, I've been away on holidays so I'm a bit behind in the issue list.

I tried to replicate it but I couldn't. What is does `model.linksNamesOptions` contain? A collection of strings? A collection of records?

Given you snippet I don't see any way why `search` would not be nil. You are not passing it.

**Comment by msalahz** [comment]
It's a collection of strings.
the problem is in power-select.js line [29](https://github.com/cibernox/ember-power-select/blob/master/addon/components/power-select.js#L29), I see `fallbackIfUndefined(null)` result is `{__ember1451491411427: null, __ember_meta__: Meta}` instead of nil

**Comment by cibernox** [comment]
`foobar: fallbackIfUndefined(null)` is a computed property, but doing `this.get('foobar')` should return null.

I haven't seen this happening. Can you come up with a reproducible example? A brand new ember app with just one controller and one template with a select on it would help me chase it.

**Comment by cibernox** [comment]
Closing this.

I'll reopen if you can provide some reproducible example
