### ISSUE TITLE
selectedComponent needs support for placeholder, allow clear

### ISSUE THREAD

**Issue by cah-briangantzler** [cibernox/ember-power-select#222]
The default selectedComponent property contains all the information for placeholder and allow clear. If I provide my own selectedComponent I have to reproduce all that as I did below 

```
{{#power-select/selected selected=selected placeholder=placeholder as | selected |}}
    {{selected.fullName}}
{{/power-select/selected}}
```

When all I really needed was to provide {{selected.fullName}}. Would be nice if the selectedComponent was just used in place of the yield when supplied, or create a new property selectedItemComponent that is used in place of the yield, we would be able to just override the desired functionality without having to reproduce things like placeholder.

If either of those are desirable could see about producing a PR.

**Comment by cibernox** [comment]
I might see the value. Having to replicate the logic of parts you don't want to change is not hard (just a matter of coping the original component), but it's a bit tedious.

What API would you suggest?

**Comment by cah-briangantzler** [comment]
I did kind of suggest one. Allow for another component "selectedItemComponent" that, if supplied, replaces the yield in the current selectedComponent. This would allow overriding the entire selectedComponent or just the "meat" of the component.

While the copying and pasting does work, if you improve your component, and add features to the selected component, I then have to recopying or make changes to also support that feature. Would really like to avoid if possible.

**Comment by cibernox** [comment]
I totally see the value on this. I reckon that 80% of the time the user only want to customize the item itself, not the entire trigger. 

This also made me realize that `selectedComponent` is slightly misleading as a name, since is basically everything in the trigger, so I've renamed it to `triggerComponent`.

This will make this `selectedItemComponent` less confusing.

Do you want to implement it youself? Both for single & multiple mode.

**Comment by cah-briangantzler** [comment]
Since you renamed selectedComponent to triggerComponent, selectedComponent is now available if you wanted to use that name, although I think selectedItemComponent is more expressive.  I am currently at a conference this week, but can look into at night or next week.

**Comment by cibernox** [comment]
I also prefer `selectedItemComponent`, but the names being more different also makes them easier to remember.

I'd like you to implement it. The best kind of PR are the ones that solve a pain point of your own.

No rush, the component is not moving anywhere. Enjoy the conference.

**Comment by cah-briangantzler** [comment]
You provide a triggerComponent, and they user can override. This means there is a div around the selectedComponent.

For the selectedItemComponent I can either......

1) do and IF and yield or display component (this means if they provide a component they will get the normal component wrapper, and if they do not they will not get that div as its only a yield, current behaviour) 

2) provide a selectedItemComponent, use it (meaning they will get a div where they didnt before) and if they override it use that instead.

Option 2 is more consistent with how trigger and options are handled, but the user will see a new div in the layout, possibly breaking. However that div can now be uniquely identified for better testing, before it was part of the trigger spans.

Also not real good at CSS so will attempt to work with your SASS variables but may need some help

Which would you prefer?

**Comment by cibernox** [comment]
I actually think that option 1 is backwards compatible and only if the user specifies a component, is up to them to also style things accordingly. I don't think that an extra div/span would break any style. 
Besides, components can be tagless if the user specifies `tagName: ""`. Another minor advantage is that yield is more performant than instantiating a new component with all it's lifecycle hooks.

Another open question is where this component includes or not markup other than the bare minimum yield. Specially in multiple mode I see 2 options.


Option 1: The component replaces only the yield
```hbs
{{#each selected as |opt|}}
  <span class="ember-power-select-multiple-option">
    {{#unless disabled}}
      <span aria-label="remove element" class="ember-power-select-multiple-remove-btn" onmousedown={{action "removeOption" opt}}>&times;</span>
    {{/unless}}
    {{#if selectedItemComponent}}
      {{component selectedItemComponent option=opt}}
    {{else}}
      {{yield opt searchText}}
    {{/if}}
  </span>
{{/each}}
```
vs

Option 2: The component replaces all the markup related with the selected item, including the surrouding span, and the cross to remove it.
```hbs
{{#each selected as |opt|}}
  {{#if selectedItemComponent}}
    {{component selectedItemComponent option=opt disabled=disabled removeOption=(action "removeOption")}}
  {{else}}
    <span class="ember-power-select-multiple-option">
      {{#unless disabled}}
        <span aria-label="remove element" class="ember-power-select-multiple-remove-btn" onmousedown={{action "removeOption" opt}}>&times;</span>
      {{/unless}}
      {{yield opt searchText}}
    </span>
  {{/if}}
{{/each}}
```

I'd advocate for the 1st option. Is the simplest solution, and probably if someone wants to modify things more aggressively it's ok to force them to customize the entire trigger.

**Comment by cah-briangantzler** [comment]
I had just learned about the tagname:"" recently. Is that an actually forward support thing, and was it always there? or did it come about recently. Cause I could have used that a year or more ago.

agree on all accounts.

Will implement as above. Will look at tests, but thinking the changes are pretty much going to be just in the HBS so tests will be minimal.

**Comment by cah-briangantzler** [comment]
You pass searchText into the yield, shouldn't it be passed into the component as well? Not sure what you would do with it, but noticed you pass it into options as well.

**Comment by cibernox** [comment]
I only pass it for consistency. Since the block is reused for both the trigger and the option in the list, and for the options in the light might be useful to have the text for things like highlight text by example. 

I never came up with an use case for the searchText in the trigger, but it doesn't harm to have it.

**Comment by cah-briangantzler** [comment]
I may not have marked the PR correctly (Dont know what may have been needed) but should this be closed as a result of the pull request?
