### ISSUE TITLE
Alternative to creating entire component for a simple template

### ISSUE THREAD

**Issue by cah-briangantzler** [cibernox/ember-power-select#223]
Hate having to create an entire component just for the template {{selected.fullName}}.
As a suggestion, changing the yield to include a section param would allow for the following (only relevant parts included)

{{#power-select as | section, option, term |}}
    {{#if (eq section "option") }}
         {{option.fullNameWithMrn}}
    {{else if (eq section  "selected") }}
         {{option.fullName}}
    {{/if}}
{{/power-select}}

since your already using truth helpers. Would allow for the before and after option as well. While the yield to inverse is nice, ember failed when you cant pass params meaning you cant do something like "No options match {{term}}", the above approach could also replace inverse as well.

Placing section first makes the most sense although last would make it more backward compatible, although currently you are passing term as a second yield param, but the docs dont really show it so not sure how many people are using it. 

Could also change the yield to yield a hash, allowing for the name option when its a list option template, and selected when its the selected template. Would also leave room for adding more params in the future without breaking backward compatibility. 

I know it isn't very backward compatible, but its a suggestion. If the dev needs a the power of a component, they still have that option by placing {{my-comp}} in the if.

**Comment by cibernox** [comment]
Wouldn't your suggestion in #222 solve the same issue? I thought about passing the "section" to the block but I was reluctact because if means that you will perform on extra `if` + `eq` invocation for each element of the list.

Besides, I've also been holding that because there is some RFCs for allowing multiple blocks in components without this hack, although I haven't heard of any progress on that.

**Comment by cah-briangantzler** [comment]
The suggestion in #222 would solve the selectedComponent problem yes. But this suggestion could also solve it for beforeOptions, afterOptions,  "inverse" yield (which doesnt allow for yielded parms) and any other component.

I saw this suggested someone else and yes it does seem a hack until they give us some form of multiple blocks. I don't know if this is the right way to go or not. Just wanted to put it out there as a talking point as it does seem to work for the most past for what is trying to be accomplished.
