### ISSUE TITLE
Support for minimum characters and debounce

### ISSUE THREAD

**Issue by cah-briangantzler** [cibernox/ember-power-select#224]
I know the cookbook shows how to do debounce, but looking at the code, its a lot of boiler plate to reproduce with only minimal changes. When search is supplied, sometimes a minimum characters are needed to guarantee a smaller set before even attempting the async search. 

If the current "search" action were replaced with the below (and use fallbackIfUndefined, was private so I couldn't), and the additional methods. both of these options should be supported. (example just extends power-select, but would be nice if it was included)(Hmmm, looks like debounceSearch could have been _debounceSearch)

```
import Ember from 'ember';
import powerSelect from 'ember-power-select/components/power-select';

let {
    isPresent,
    run
    } = Ember;

export default powerSelect.extend({
    minChar: 3,
    keyDelayMS: 750,

    actions: {
        search(dropdown, term /*, e */) {
            let doSearch = true;
            let minChar = this.get('minChar');
            if (isPresent(minChar) && isPresent(term) && term.length < minChar) {
                doSearch = false;
            }
            if (doSearch) {
                let keyDelayMS = this.get('keyDelayMS');
                if (isPresent(keyDelayMS) && keyDelayMS > 0) {
                    this.debounceSearch(dropdown, term, keyDelayMS);
                }
                 else {
                    this._doSearch(dropdown, term);
                }
            }
        }
    },
    debounceSearch(dropdown, term, delayMS) {
        run.debounce(this, this._performSearch, dropdown, term, delayMS);
    },
    _performSearch(dropdown, term) {
        this._doSearch(dropdown, term);
    }
});

```

 Could put together a PR if you wish, thought I would get approval first in case this was something you didn't want to support.

**Comment by cibernox** [comment]
I also considered this and I was sitting on the fence. 

In principle I want to encourage people to create and release their own custom versions of this component with custom behaviour. By example, this can be achieved with this approach in ember 2.3+

```hbs
{{power-select beforeOptions=(component "debouncedSearchBox" minChars=3 delay=750) onchange...}}
```

And you might also want to wrap this for convenience in another component
The contextual components feature in ember 2.3 enables new set of composition patterns I want to explore before deciding if this goes into the core or not.

**Comment by cah-briangantzler** [comment]
I must have misunderstood beforeOptions. I thought that was a component to allow some customization before the list (under the search), I didn't realize that was actually replacing the search box. I would assume that component would have to support certain actions to communicate the search. I looked through the docs and didn't see any information on how beforeOptions actually works. I think I just saw it mentioned in change notes and made an assumption of what it was, which turned out to be incorrect

I do like the syntax above through. Pretty cool.

**Comment by cibernox** [comment]
Just a bit. `beforeOptionsComponent` is indeed the component that goes before the list of options, which in this case contains only the search box.

I'm not rejecting the idea, but I'd like to wait for ember 2.3 and see if this can be accomplish in a composable way instead of adding another couple configuration options.

I'm picky about what I include in the core because before you realize the component has 30 options to tweak and more functionality to mantain that I feel confortable with.

Nothing is written in the store, this is totally reasonable, I just want to wait for composable component and explore them before.

**Comment by cah-briangantzler** [comment]
Totally agree. Im fine with what I would have to do until 2.3 (well more importantly, I am able to upgrade to 2.3)

Thanks for considering
