### ISSUE TITLE
Implement Material Design Styling

### ISSUE THREAD

**Issue by brendanoh** [cibernox/ember-power-select#226]
Really great select component.

I was wondering if anyone has styled this for a Material Design implementation.

Currently I am using material-design-lite (via ember-material-lite) which does not have a select component.

I was hoping someone had done something similar in terms of styling as ember-paper or ember-materialize.

Thanks in advance

**Comment by cibernox** [comment]
I'm not aware of any, but @miguelcobain created ember-paper and probably can provide some light on how complicated it would be.

**Comment by brendanoh** [comment]
@cibernox that would be great. 

Hopefully @miguelcobain has had this question before :-)

**Comment by miguelcobain** [comment]
@brendanoh Never seen power-select and Material design together, sorry.
Ember paper has a select component (not based on power-select).

Your best bet would be to reuse some existing styles and customize power-select to comply with the needed markup. (And then OSS it. :+1:)

**Comment by cibernox** [comment]
I don't have time now to try to implement alternative styles for this component, but certainly Material Design and Bootstrap are in the top of the list.

If anyone want to step forward on implementing themes, ping me in slack and I'll help.

**Comment by cibernox** [comment]
This has been implemented already as a light skin and if someone wants a more complete solution they can use ember-paper.
