### ISSUE TITLE
Create different component for multiple mode

### ISSUE THREAD

**Issue by cibernox** [cibernox/ember-power-select#23]
If it wasn't for the special cases for handling multiple mode the code would be much easier to follow, and there is still a few use cases of the multiple mode that are not implemented (create new "tags" with free text is a complicated one)

Perhaps split the multiple mode into a different component extends or composes the basic one make sense. It would also make the templates simpler (and theoretically more performant too).

Idea:
```hbs
{{#ember-power-select-multiple options=options selected=selected as |option|}}
  {{option}}
{{/ember-power-select-multiple}}
```

The rest of the API remains the same (but configuration options that only concern to multiple mode don't pollute the regular select).

**Comment by miguelcobain** [comment]
I think having the same component for multiple and single mode may be preferable.
More in line with html selects, easier to https://github.com/cibernox/ember-power-select/issues/13#issuecomment-145689616, (maybe others).

Can't we separate that logic in a different way?
Inheritance? Base class with single and multiple mixins?
I'm still not very familiar with the code, that's why I'm just throwing possibilities.

**Comment by cibernox** [comment]
The issue is that the normal select and the multiple select have slightly different behaviours and rules, and that forces the code to have several "if isMultiple do this else do that", and the same in templates.

I also prefer to keep it more inlined with the select tag, but at least internally some kind of separation of concerns would make the code easier to follow).

Another solution that comes to my mind is having a `{{ember-power-select-simple}}` and `{{ember-power-select-multiple}}` that are private "ish" and `{{ember-power-select}}` is a component with `tagName: ""` that just renders internally the appropriate one.

**Comment by miguelcobain** [comment]
> The issue is that the normal select and the multiple select have slightly different behaviours and rules, and that forces the code to have several "if isMultiple do this else do that", and the same in templates.

I remember dealing with this as well. Irritating. :-1: 

A "proxy" `ember-power-select` would be awesome.
