### ISSUE TITLE
Allow position over trigger as well as above and below on basic dropdowns

### ISSUE THREAD

**Issue by harlio** [cibernox/ember-power-select#240]
Instead of only allowing the dropdown component to render above or below the trigger, would be nice to have an option to let it render directly over the trigger. This would make it feel more inline with the native experience of a select list.

**Comment by miguelcobain** [comment]
ember-basic-dropdown would have to support that.

I'm confused. I think native select dropdowns render below the trigger. 
Ah, except on MS Edge, I think.

**Comment by northborn** [comment]
And Chrome, and Safari, and it's how Material Design specs out Select/Menu elements, so it would go a long way in being able to theme Power Select as a paper element. If MS Edge does as well then I think that leaves Firefox as the outlier.

**Comment by cibernox** [comment]
I actually agree. I tend to prefer the option list to be below or above, but have it over the trigger is an acceptable request. 

I'm not sure however about how this should work when combined with search. If the searchbox is in the trigger it will be hidden by the dropdown box, and if the input is inside the floating box, I think that it will look weird, specially if after filtering there is no results or just a few.

Can you point me to some UI examples to check how other libraries implemented this?

**Comment by northborn** [comment]
On simple dropdowns (without search or multiselect), I tend to prefer the Material Design method, which probably feels the closest to a native dropdown experience. Notice how the selected option in the menu itself usually appears directly over the trigger.

https://material.angularjs.org/latest/demo/select
http://miguelcobain.github.io/ember-paper/#/paper-select

This probably wouldn't be too hard to implement just through overriding the default styles, except that the option menu loads on mousedown of the trigger, so clicking on the trigger also registers a click on the option directly over the trigger as well and immediately closes the menu.

**Comment by cibernox** [comment]
Good point too. If we want to implement a mode where the options will be over the trigger I need to add some login.

I still think that mouseup is the right event to listen, because it's how real selects work. Perhaps a viable solution is to register the X and Y position of the mousedown and ignore the mouse up if the the positions is the same (perhaps with a small +/- 5px difference)

**Comment by cibernox** [comment]
@northborn In #243 i've taken care of the logic preventing the selection of the element on mouseup if the mouse is in the same position where the mousedown that opened the dropdown happened.
I've tested this making the component be on top of the trigger with some naive CSS and seems to work.

I've not tacked positioning the floating box centered, but not you're free to experiment using `transform: translateY(-50%);`. I don't know if it worth doing something on the javascript side or that line of css covers your use case.
