### ISSUE TITLE
Disable loadingMessage after first results

### ISSUE THREAD

**Issue by dustinfarris** [cibernox/ember-power-select#244]
I would like to be able to disable the loadingMessage after the first batch of results are returned from the async search.  I think the UI experience would be smoother.

**Comment by cibernox** [comment]
I see two ways of doing that:

1. Providing your own `optionsComponent` that is basically a copy of the default one with that bit customized.
2. On the app side, in the search action, set `loadingMessage` to null after the first async request finishes.
