### ISSUE TITLE
onchange error again (ember 2.3.0)

### ISSUE THREAD

**Issue by shaunc** [cibernox/ember-power-select#247]
Using ember 2.3.0 I am getting 

    Uncaught Error: Assertion Failed: {{power-select}} requires an `onchange` function

with

    {{#power-select 
       options=players selected=player onchange=(action "setPlayer")
        as |player|}}
      {{player}}
    {{/power-select}}

I see this was reported in #60 and was fixed then by upgrading. It seems to have reoccurred.

**Comment by cibernox** [comment]
I'd be surprised if this has nothing to do with the upgrade to ember 2.3. Neither this addon nor ember  changed anything on action handling, and this addon is tested agains all versions of ember between 1.13 and 2.5-canary.

Can you provide a reproducible example?

**Comment by cibernox** [comment]
Doing spring cleaning of issues.

If you can provide a reproducible example I'll reopen this.

**Comment by jhonandres21** [comment]
Yes, actually I'm trying now, in ember 2.3.0 and the error occurs just as @shaunc describes.
I will be really thankful if you know how to fix it.

**Comment by cibernox** [comment]
I never was able to receive reproduce it. I suspect that it is an error in ember itself, because I can't see why onchange would be something other than a function. 

Can you create an example?

**Comment by jhonandres21** [comment]
Of course,

I will try one last thing and I will let you know if I confirmed this issue. 
If true where can I upload the example?

**Comment by cibernox** [comment]
An dummy app in github that I can pull would be perfect.

**Comment by jhonandres21** [comment]
No, my mistake.
I had been thinking all this time that I have installed the 2.1.0 ember version.
All I did to solve this was upgrade my installation.

Thank you for your time.

**Comment by shaunc** [comment]
(btw -- I also can't reproduce ... for now "closed" seems the right answer :))
