### ISSUE TITLE
can't trigger a async search onOpen

### ISSUE THREAD

**Issue by rnt363** [cibernox/ember-power-select#252]
I'm trying to cause the search action to be invoked when the dropdown is opened. Basically, I want to populate the dropdown with options before the user has to type anything. Here's my javascript:

        actions: {
    onSelectOpen: function(select, e) {
      console.log('open');
      console.log(select);
      select.actions.search('');
    },
    
    onChange: function(choice) {
      this.set('testSelected', choice);
    },

    search: function(query) {
      return ['hi', 'bye'];
}

and my hbs:

{{#power-select-multiple
	   onopen=(action "onSelectOpen")
	   search=(action "search")
	   selected=rule.value
	   renderInPlace=true
	   disabled=disableValueEdit
	   onchange=(action "onChange") as |name|}}
	  {{name}}
	{{/power-select-multiple}}

when i click on the component, onSelectOpen is triggered, but 'search' is not.
I'm probably just missing something, but I'd appreciate some guidance.

**Comment by cibernox** [comment]
Version of the component in use?
I think that the reason is that passing search to the empty string is an special case and doesn't fire the search. If you search for "foobar" does it work?

**Comment by rnt363** [comment]
wow, thanks for the speedy reply! I'm using version 0.8.0

Unfortunately, no. I tried that as well, and still verified that the 'search' action was not being called

**Comment by cibernox** [comment]
You were right, this was broken. Fixed in 0.8.2, and added a regression tests.

Thanks for reporting!

**Comment by rnt363** [comment]
awesome thanks!

**Comment by rnt363** [comment]
Sorry to bring this up again, but is it intentional that calling search on an empty string do nothing? And if so, is there a good way for me to call search with a dummy phrase (foobar like you suggested) and not have foobar show up in the inbox on the UI?

**Comment by cibernox** [comment]
It is intentional. The idea is that clearing the search return the component to its initial state. That is, to the original set of results.

If you have some results that you want to show even before the user types, you can both pass options **and** a search function.

```hsb
{{#power-select options=defaultOptions selected=selected onchange=(action (mut selected)) search=(action "search") as |opt|}}
  {{opt}}
{{/power-select}}
```

If for some reason you don't have those initial results right away or you want to avoid fetching them until the user opens the component because it involves a request, you can use the `onopen` function to populate the options:

```hbs
{{#power-select options=initiallyEmpty selected=selected onchange=(action (mut selected)) search=(action "search") onopen=(action "initializeOptions") as |opt|}}
  {{opt}}
{{/power-select}}
```
```js
actions: {
  initializeOptions() {
    if (this.get('initiallyEmpty.length' === 0) {
      this.set('initiallyEmpty', this.store.findAll('user'));
    }  
  }
}
```

**Comment by okachynskyy** [comment]
@cibernox, how to trigger loading state of select-dropdown component for manual fetching initial data? E.g. publicAPI.loading will not be set to true on manual fetching and user can't see a loadingMessage for initial search.
