### ISSUE TITLE
onchange triggered when no results found and user hits return key

### ISSUE THREAD

**Issue by Kilowhisky** [cibernox/ember-power-select#257]
Not entirely sure if this is something i should be validating or a bug. 

With the multi-select if the user types in something that doesn't match any of the selections and then hits the return key the `onchange` handler is fired with an array of size 1 and an index value of `undefined`.

**Comment by cibernox** [comment]
Nope, that is a legitimate bug that slipped through the test suite. 

You never have enough tests :disappointed:
