### ISSUE TITLE
power-select-multiple gives `Cannot read property 'getState' of undefined`

### ISSUE THREAD

**Issue by rinti** [cibernox/ember-power-select#260]
Hi!

I'm not sure if I'm doing something wrong, or if it's actually the addons fault. I'm guessing it's me :)

Basically I use the component like this:
```handlebars
{{#power-select-multiple matcher=userMatcher options=users selected=usersInitial keydown=(action "handleKeydown") onchange=(action (mut user)) as |user|}}
  {{user.fullName}} 
{{/power-select-multiple}}
```

```javascript
  users: Ember.computed(function() {
    return this.store.findAll('user');
  }),
  userMatcher: function(options, st) {
    return options.get('fullName').toLowerCase().indexOf(st.toLowerCase()) > -1;
  },
  usersInitial: Ember.computed('model.users', function() {
    return this.get('model.users');
  }),
```

It's semi-working, the component renders, and it selects the correct items, and the dropdown shows all users.
However whenever I try selecting something in the dropdown (or type anything) I get `Cannot read property 'getState' of undefined`

**Comment by cibernox** [comment]
I'll start mentioning that it's `onkeydown`, not `keydown`, although I don't think it's related.

Also `onchange=(action (mut user))` is going to mutate the user, but that will have no effect on the selected value because `usersInitial` doesn't change. You want to do `onchange=(action (mut usersInitial))`.

Third, the matcher function is invoked once per option, so it should be `userMarcher(option, searchTerm)`. Probably this is only a typo, because you seem to treat `options` as a single object, not a collection.

If you could provide a longer stack trace as long as the version of the addon you're using what'd be helpful.

**Comment by rinti** [comment]
Thank you, changing to `mut usersInitial` i can now add/remove items from the select.

Yes `options` was a typo, thanks!

I'm using the version you released an hour ago (0.8.3) together with ember 2.3.0 and ember-data 2.3.3.

I think I found the problem though:

`console.log(this.store.findAll('user').mapBy('username'));` gives me an empty array
```javascript
    this.store.findAll('user').then(function(user) {
      console.log(user.mapBy('username'));
    });
```

Gives me the expected output.

So I believe this is ember data-related and not power-select-related.

Stacktrace:
```
Uncaught TypeError: Cannot read property 'getState' of undefined_nodeIsView @ VM31223:4196
_shouldShowNode @ VM31223:4164(anonymous function) @ VM31223:4123
_appendNodeChildren @ VM31223:4122
(anonymous function) @ VM31223:4128
_appendNodeChildren @ VM31223:4122
(anonymous function) @ VM31223:4128
_appendNodeChildren @ VM31223:4122
(anonymous function) @ VM31223:4128
_appendNodeChildren @ VM31223:4122
(anonymous function) @ VM31223:4128
_appendNodeChildren @ VM31223:4122
(anonymous function) @ VM31223:4128
_appendNodeChildren @ VM31223:4122
(anonymous function) @ VM31223:4128
_appendNodeChildren @ VM31223:4122
(anonymous function) @ VM31223:4128
_appendNodeChildren @ VM31223:4122
(anonymous function) @ VM31223:4128
_appendNodeChildren @ VM31223:4122
(anonymous function) @ VM31223:4128
_appendNodeChildren @ VM31223:4122
viewTree @ VM31223:3764
(anonymous function) @ VM31223:3720
fn @ ember.debug.js:890
Queue.invoke @ ember.debug.js:327
Queue.flush @ ember.debug.js:391
DeferredActionQueues.flush @ ember.debug.js:192
Backburner.end @ ember.debug.js:570
Backburner.run @ ember.debug.js:692
Backburner._runExpiredTimers @ ember.debug.js:1081
Backburner._boundRunExpiredTimers @ ember.debug.js:536
```

**Comment by rinti** [comment]
Well, apparently I'm a dumbass :) It appears it has nothing to do with the select. If I remove it the error is still there.

Sorry for making this issue! Thanks for clarifying the `mut userInitial` though!

**Comment by bugant** [comment]
I have the same issue. As soon as I type something in the search box the error appears.

The collection I use for `options` is an Ember.Array of POJOs. Note that If I leave my console closed and thus not having the Ember Inspector enabled, no error occurs.

**Comment by rinti** [comment]
Yes, I think this is an ember inspector bug, and not power select related. I still get the error in an app I'm not using.
