### ISSUE TITLE
Styling the remove button with multiple select

### ISSUE THREAD

**Issue by drewclauson** [cibernox/ember-power-select#267]
Great component and very easy to restyle, thanks for all your efforts!

I'm coming from Select2 boxes which have integrated styling in the HTML template that we are using, but it knows nothing about ember-power-select.  So, I created my own styling to match (see below), I think it's looking pretty good.

![image](https://cloud.githubusercontent.com/assets/10655807/12647384/e6d97a5c-c5a2-11e5-8576-8296fa437109.png)

I'd like to get the remove button to the right hand side of the selected options to keep the user experience the same.  I looked at [the code for the template](https://github.com/cibernox/ember-power-select/blob/master/addon/templates/components/power-select-multiple/trigger.hbs#L4) and noticed that it is pretty well forced to the beginning and I can't think of any CSS hacks to move it.  I'm up for contributing some sort of option to be able to set which side to put it on, but I'm still pretty new to Ember.  To accomplish this, would it be best to put the remove button into a partial and then do something like this?  Thanks for your help and input.

_remove-button.hbs
```
    {{#unless disabled}}
      <span aria-label="remove element" class="ember-power-select-multiple-remove-btn" onmousedown={{action select.actions.select (ember-power-select-build-selection opt selected multiple=true)}}>&times;</span>
    {{/unless}}
```

```
{{#each selected as |opt|}}
  <span class="ember-power-select-multiple-option">
    {{#unless removeButtonRight}}
      {{partial "remove-button"}}
    {{/if}}
    {{#if selectedItemComponent}}
      {{component selectedItemComponent selected=opt lastSearchedText=lastSearchedText}}
    {{else}}
      {{yield opt lastSearchedText}}
    {{/if}}
    {{#if removeButtonRight}}
      {{partial "remove-button"}}
    {{/if}}
  </span>
{{/each}}


```

**Comment by cibernox** [comment]
Making the button a `float: right` wouldn't work?

**Comment by drewclauson** [comment]
@cibernox Wow, today is that day where the simplest answer is staring you right in the face and you totally miss it.

Where's the delete button for an issue?  :expressionless:
