### ISSUE TITLE
Hardcoded em Units in Default .scss

### ISSUE THREAD

**Issue by CAH-MaggieRoss** [cibernox/ember-power-select#268]
There are two places in ember-power-select.scss (lines 22 and 158) where the height of an element is being defined or calculated and you've hardcoded an em unit after the variables. I'd like to request that these be removed as I'm not using em units for styling, the em isn't consistently placed after the line-height variable, and it's breaking the height calculations on those two classes--since my line-height is in vmax units, this is resulting in: 
`-height: ##vmaxem;`

Which somehow is breaking the positioning, probably because it's also breaking the scrolling for long lists. While I can override these, going back to letting me pick my own units by default would be far more my preference.

**Comment by cibernox** [comment]
It should probably use `rem` units. Design is not my main strength. 
If you can put together a PR i'd be happy to merge it.
