### ISSUE TITLE
No placeholder in ember-select-multiple

### ISSUE THREAD

**Issue by Crabar** [cibernox/ember-power-select#273]
Hi! I'm using v0.8.6 and trying to set search placeholder with property "searchPlaceholder" as mentioned at [docs](http://www.ember-power-select.com/docs/the-search). It works fine for single select but doesn't work for multiple.

**Comment by cibernox** [comment]
In the multiple select since the search input is inside the trigger you should use just `placeholder`.

Now that you mention, it's true is a bit inconsistent. Any idea how to make it more intuitive? Or just improving the docs would suffice?

**Comment by cibernox** [comment]
I leave this open because just the fact that you had to ask is a symptom that something is not intuitive.

**Comment by Crabar** [comment]
I don't see a reason to use different names for this property. In my opinion, the best is just to use "placeholder" for both components. If it impossible, then will be greate to add appropriate example to docs.

**Comment by cibernox** [comment]
Actually there is a reason.

When the search box is not inside the trigger (per example in the single select) the `placeholder` is the text that goes inside the trigger (similar to a prompt) while the `searchPlaceholder` is the one that goes inside the search box in the dropdown.

They can be different. But I agree that naming is a bit unclear.

Suggestion?

**Comment by Crabar** [comment]
Oh, now I understand where is the problem. In this case I think it will be reasonable to add more examples to docs with `placeholder` and `searchPlaceholder` and to emphasize difference between them.

And I can't find better names =\.

**Comment by cibernox** [comment]
I'm actually thinking about renaming `placeholder` to `prompt`. 
That is also more correct and would leave `searchPlaceholder` as the only placeholder.

Do you think that it would make the difference between both clearer?

**Comment by Crabar** [comment]
For me these terms have same meaning. So previous variant with `searchPlaceholder` is better I'm think.

**Comment by cah-briangantzler** [comment]
changing placeHolder to prompt would be a breaking change and I think placeholder is pretty consistent. That is the name I would look for when searching the docs for something like this. I actually just came across searchPlaceholder a few days ago and thought, cool, you can set that. But didn't think of its effects on multiple-select. 

I would vote for keeping it exactly as it is and just updating the docs to say what you said above. Since the search for a multi is part of the trigger, the searchPlace holder is not applicable. I am assuming that beforeOptions is also the same, a single select only component.

**Comment by patricklx** [comment]
what if search is disabled and I want a placeholder?
Does not seam to be supported...

**Comment by cibernox** [comment]
@patricklx that is a very good point, at the moment that basically prevents you from having a placeholder. I haven't considered that. 

I'm going to close this issue and open a new one for implementing that.
