### ISSUE TITLE
Add example that includes lastSearchedText ie 'as |name term|'

### ISSUE THREAD

**Issue by eddiesholl** [cibernox/ember-power-select#276]
After quite a bit of hacking around and digging through the components, I discovered that both the current option AND the current search term are yielded. This took me ages to discover, and made it way cleaner and easier to solve a non trivial search scenario.

Including this in at least one of the awesome examples on the site might help people stumble on this more easily. Right now every single example makes use of just the yielded item. I guess part of it was my lack of awareness of yielding multiple items, so I didn't think to look there.

I had originally tried to achieve this by catching it using a customer searcher, but this doesn't get called when the search box goes back to blank.

**Comment by cibernox** [comment]
The reason why it wasn't documented it that is wasn't until 0.8.6 (5 days ago) until I was satisfied with the behaviour and performance of the yielded results.

I added one example on the search section.
