### ISSUE TITLE
Add blockeless form

### ISSUE THREAD

**Issue by cibernox** [cibernox/ember-power-select#28]
Not completely sold because it doesn't add any value other tab being more concise for very simple use cases, but still worth considering

**Comment by miguelcobain** [comment]
I've done a poor job trying to convince you. :smiley: 

- IMO a block that `{{yield`s inside a loop is more difficult to grasp than a blockless form, so newcomers might jump in more easily
- More concise for simple cases:
```hbs
{{ember-power-select options=names labelPath="name"}}
{{!-- or even --}}
{{ember-power-select options=names}}
{{!-- if names is a string array --}}
```
vs
```hbs
{{#ember-power-select options=names as |name|}}
  {{name}}
{{/ember-power-select}}
```
- "Simple cases" are frequent (talking from my experience, YMMV)
- ember-cli-selectize users (and possible others) will "feel at home"

- near zero overhead to have this feature

**Comment by cibernox** [comment]
Ok, I'm sold.I just didn't considered valuable but since as you said has near 0 overhead there is no point in holding this back.

The only requirements for a PR including this are:

- Given that you are giving the name of the attribute used for each option of the list, makes sense to automatically default the `searchField` to that very same attribute. This is actually one improvement over the block syntax, since with blocks you need more information to be able to filter. People using the block syntax still need to specify which field they use to filter.
- Update the docs, probably both the "How to use it" and the "The search" sections.

The open question is that if we can think in a better name than `labelPath`. Nothing against it, just my "question everything" policy.

**Comment by miguelcobain** [comment]
> This is actually one improvement over the block syntax, since with blocks you need more information to be able to filter. People using the block syntax still need to specify which field they use to filter.

Indeed, didn't think of that.

> The open question is that if we can think in a better name than labelPath. Nothing against it, just my "question everything" policy.

Some alternatives:
Ember.Select: `optionLabelPath`
ember-cli-selectize: `optionLabelPath`
ember-select-2: `optionLabelPath`
:stuck_out_tongue_winking_eye: 

Well, if we just specify `label` that really looks like a fixed `label`. This is indeed a path, so something allusive to it should be present.
Another option could be `labelKey` or `optionLabelKey`.

**Comment by cibernox** [comment]
Nah, `optionLabelPath` it is. Is good to preserve familiarity. 
As long as we don't implement `optionValuePath` we can be friends.

**Comment by karellm** [comment]
@cibernox Sorry to bring that back but I don't think it warrants a new issue. Why are you against `optionValuePath`? In our app, there are a lot of simple select like that:

```
export default Ember.Controller.extend({
  cities: [
    {value: 'bar', label: 'Barcelona'}, 
    {value: 'lon', label: 'London'}
  ],
  destination: 'lon'
});

{{#power-select
  selected=destination
  options=cities
  onchange=(action (mut destination))
  as |name|
}}
  {{name}}
{{/power-select}}
```

It would be nice to do:

```
{{power-select
  selected=destination
  options=cities
  optionLabelPath="label"
  optionValuePath="value"
  onchange=(action (mut destination))
}}
```

Is there a reason I can't?

**Comment by miguelcobain** [comment]
There is this addon: https://github.com/cibernox/ember-power-select-blockless
but it is probably outdated.

**Comment by cibernox** [comment]
@karellm the reason is that blocks >>>> attributes.

Everything that can be expressed by attributes can be expressed with a block, but not the other way around, so this components takes the most flexible choice, and leaves to other addons to implement the blockless version, like the one @miguelcobain mentioned.

Yes, it is outdated, but is just a matter of updating the dependencies.

**Comment by miguelcobain** [comment]
> Everything that can be expressed by attributes can be expressed with a block, but not the other way around

While agree with you that blocks >>> attributes in many ways, I think there are certain things that blocks can't easily express that attributes can. E.g expressing "do this when the selection changes".

@cibernox I think you need to update templates as well to accommodate new versions of power-select. There isn't a way to proxy all attributes to a child component that I know of. :(
Would be very helpful for addons.

I still think my arguments are valid at https://github.com/cibernox/ember-power-select/issues/28#issuecomment-147977397, but I don't have a big problem with that. :+1:

**Comment by cibernox** [comment]
@miguelcobain It might be one once the splat syntax arrives to htmlbars. There was an RFC for that.
