### ISSUE TITLE
when providing options as objects, those selected are not highlighted

### ISSUE THREAD

**Issue by rnt363** [cibernox/ember-power-select#281]
Not sure if this is a bug really, I just need some help. 
My options look like this:
{id: 1, text: 'some-text'}

I have tried giving the same format to the 'selected' property, and the pills do show up as I would expect, but when I toggle the dropdown these options are not highlighted.

Any suggestions? I'm using the latest version btw.

**Comment by cibernox** [comment]
In the bullet list in the bottom of this section you will find why: http://www.ember-power-select.com/docs/how-to-use-it

**Comment by rnt363** [comment]
so does that mean that there is no way around this?

**Comment by rnt363** [comment]
Perhaps it would make sense to use the searchField property to compare selected elements to the options list?

Otherwise, the user can click and add an already selected option in multi-select, causing the pill to appear twice.

**Comment by cibernox** [comment]
I don't consider it an issue, is absolutely intentional.

The `selected` attribute **has to be one of the options in order to be highlighted**.
Not a similar object or an option with some attribute equal, but **the same object**.
