### ISSUE TITLE
ember-power-select.com CSS issue

### ISSUE THREAD

**Issue by varoot** [cibernox/ember-power-select#282]
In code sample box, when the code line is too long, it puts the scrollbar on the whole page instead of just that box. (For example, http://www.ember-power-select.com/docs/the-trigger, second box, Template)

This is broken on Firefox and Chrome (48+). (Chrome recently just changed the way it renders FlexBox) To fix this, just add `min-width: 0` for `.doc-page`.

**Comment by cibernox** [comment]
Good catch, fixed.

Thanks
