### ISSUE TITLE
Explicitly reference "this" in matcher function

### ISSUE THREAD

**Issue by danidr** [cibernox/ember-power-select#283]
Hey there,
I have upgraded to the latest ember-power-select version, and I am facing a problem regarding the _this_ keyword.
In the previous version (unfortunately, I can't remember the number), I set up the custom _matcher_ function like this:
```
countriesMatcher: function(country, term) {
		if (!this.get('i18n')) {
			this.set('i18n', Ember.inject.service('i18n'));
		}
		return term === '' || country.toUpperCase().indexOf(term.toUpperCase()) > -1 ||
stripDiacritics(this.get('i18n').t('countries.' + country)).toUpperCase().indexOf(stripDiacritics(term).toUpperCase()) > -1;
    }
```
I was basically injecting the i18n service directly in whatever the _this_ keyword was referring to, thinking it was the actual ember-power-select component, or anyway, an Ember object. With the latest version, it throws a "this.get is undefined", because apparently, the _this_ object is not defined in the scope of the function called.
I know that my code is just a hack, but at least it was working before.
To avoid situations like these, wouldn't it be better to change the scope of the matcher function to be the ember-power-select component, so that every service injected in the initializer can be called directly in the matcher as well?
Let me know what you think.

**Comment by cibernox** [comment]
Thanks for reporting, I wasn't aware that behaviour changed, mostly because I wasn't even aware of that being possible.

I'd argue that allowing people to manipulate the component using the matches as you were doing is actually a dangerous practice, and probably one that might incur in some performance penalty in some engines.

Instead of injecting the i18n in the component, I'd suggest to pass as matches a function bound to your controller/component, and that will have access to whatever service you want.

```js
init() {
  this._super(...arguments);
  this.countriesMatcher = this.countriesMatches.bind(this);
},
countriesMatcher(country, term) {
  // your code can not do `this.get('i18n')`
}
```

That should work, and doesn't mangles the select component.

**Comment by danidr** [comment]
Thanks for the quick answer,
Yes, I realize it would be very dangerous to use it as common practice; but it was the only way I could come up with. Your solution is interesting, I'll test it, thank you.
I was only suggesting changing the scope in ember-power-select code because it would probably allow for more flexibility if the matcher function needed any service injection.
Keep up the good job! :)

**Comment by cibernox** [comment]
Is the opposite approach, but I'd say that is more idiomatic (and less dangerous and probably more performant) to make your matcher have the context you want than to inject services into the select in runtime.

**Comment by danidr** [comment]
Gotcha, didn't think about the performance issue. Yes, it'd probably be much of an overhead.
