### ISSUE TITLE
Unable to load www.ember-power-select.com

### ISSUE THREAD

**Issue by jaswilli** [cibernox/ember-power-select#298]
It appears to have run afoul of SRI for its javascript assets.  I've tried Chrome (48.0.2564.103), Firefox (44.0.1) and Safari (9.0.3).

![screen shot 2016-02-08 at 5 08 19 pm](https://cloud.githubusercontent.com/assets/214142/12902377/96b0982a-ce86-11e5-89ce-b8e2001d8dc8.png)

**Comment by cibernox** [comment]
Yeah, I messed with the deployment. Fixed now.
