### ISSUE TITLE
mutate selected

### ISSUE THREAD

**Issue by miguelcobain** [cibernox/ember-power-select#30]
Currently we don't mutate the `selected` property.
I understand that this is to conform with Ember's "data down actions up", and it makes total sense.

But one thing that I found is that this may not apply to every case, even in React land, were this concept somewhat originated. `{{mut` properties will be around and people may want to use them.

This issue has been raised before at ember-cli-selectize.
Please read the follwing comment and the respective links: https://github.com/miguelcobain/ember-cli-selectize/pull/66#issuecomment-100853217

> Think about a long form with many selects. It would very cumbersome to write an action to each select instance. I think it would be a step backwards.

Do closure actions solve this?

Still, I have an app which is **heavily** form based. Has a very complex data model and has dozens of selects. It would still be cumbersome to have even one action per controller.

My suggestion is that we should mutate `selected` property **only if** `onchange` action wasn't specified.

**Comment by cibernox** [comment]
As discused in slack I prefer to stick the the "everything is strictly immutable" policy. Sometimes is a bit more verbose but is easier to understand and more performant.

Besides, using the `mut` helper is not that much typing: `onchange=(action (mut myValue))` is all that takes to simulate 2 way bindings.

**Comment by miguelcobain** [comment]
I wasn't aware that the mut helper could do this stuff.

That's the way to go!
