### ISSUE TITLE
Error in `_runloopAwareRepositionDropdown`

### ISSUE THREAD

**Issue by brandonparsons** [cibernox/ember-power-select#304]
I'm seeing some errors when opening `ember-power-select` select boxes, and I think it is only happening on windows.

It's a long story, but I can't really get un-minified output using a windows computer, so I'm hoping the attached information might mean something to you!

![capture](https://cloud.githubusercontent.com/assets/1277162/12933412/24e9fbfe-cf45-11e5-8d87-88423bc26305.PNG)

The error is occurring on this line:

`this.get("matchTriggerWidth") && (r.style.width = s + "px");`

**Comment by cibernox** [comment]
Weird, I never heard of a javascript bug that depends on the OS.

What version of the addon are you using? Have you tried with the latest master?

**Comment by brandonparsons** [comment]
@cibernox Turns out it doesn't depend on the OS.  It's not exactly important why ( :D ), but it was a misunderstanding.

I'm still getting the error though, on all browsers.  It specifically happens when I try to drop down the select box, and for some reason the select options get pushed to the bottom of the screen.

I'm opening the select box in a modal... Does that have anything to do with it?

![screenshot 2016-02-09 19 24 26](https://cloud.githubusercontent.com/assets/1277162/12937146/d29e958a-cf62-11e5-9c57-6fe1375fa093.png)

**Comment by brandonparsons** [comment]
Sorry, didn't answer your question. I'm using `0.8.2`, will try the latest master version.

**Comment by brandonparsons** [comment]
Using the latest master, I don't get the error, but the select box is still being pushed to the bottom of the page (as per the image above).

**Comment by cibernox** [comment]
Having the select inside a dropdown should have any problem (except perhaps a z-index issue that would be trivial to fix).

Everything that has to do with the position of the component is actually handled by another component, ember-basic-dropdown. My only guess at the moment is that you have an old version of that one, perhaps because of being locked by lockfile?

**Comment by brandonparsons** [comment]
I was playing around with this a bunch, and fixed it by using `renderInPlace=true` from another one of your message threads.

I don't 100% understand why, but it is working now :)

**Comment by cibernox** [comment]
I think this is fixed in master, so I'm closing it.
