### ISSUE TITLE
Add class for missing search option

### ISSUE THREAD

**Issue by RuslanZavacky** [cibernox/ember-power-select#305]
When you do search and receive "No results found" its currently impossible to give a different styling for:

`ember-power-select-options`
`ember-power-select-option`

I'd propose to add 2 more classes based on search results

`ember-power-select-options--no-results`
`ember-power-select-option--no-results`

That way it will be possible to style not found separately.

@cibernox thoughts? :)

**Comment by cibernox** [comment]
@RuslanZavacky Mmm, if you want custom styles have you considered using the inverse block?

```
{{#power-select ... as |opt|}}
  {{opt}}
{{else}}
  <div class="my-custom-div">
    <span class="icon-cross red">Nooope<span>
  </div>
{{/power-select}}
```

**Comment by cibernox** [comment]
Even if you do that, it might still make sense to add some special class. It's basically free and people might find it useful.
