### ISSUE TITLE
[ux] multiple doesn't clear user input on select

### ISSUE THREAD

**Issue by knownasilya** [cibernox/ember-power-select#314]
Currently when using multiple select, if you enter some search text and select your item, the search text stays and you have to erase to search for another item. This is very unintuitive, and a poor UX. I think that should be how it works by default, at least most people would expect it to work that way.

Is there a way to clear it myself, after making a selection?

**Comment by cibernox** [comment]
That bug was fixed a couple weeks ago. What version are you using?

**Comment by knownasilya** [comment]
0.7.2, guess i can upgrade :+1:

**Comment by cibernox** [comment]
I recommend to update to the 0.9.0 cycle. It's beta but pretty stable already. Beware that there is a couple breaking changes (all is noted in the changelog)

**Comment by knownasilya** [comment]
Ah, didn't realize I was using power-select-sortable. It has the same bug.
