### ISSUE TITLE
Autofocus

### ISSUE THREAD

**Issue by bakerac4** [cibernox/ember-power-select#318]
I am trying to implement an autofocus attribute feature, so when it renders and I add an autofocus attribute, my power select will automatically be open and have the cursor ready to go

Here is my power select
```
{{#power-select renderInPlace=true selected=productSelected
                                    search=(action "searchForProducts") allowClear=true
                                    placeholder="Search for Product" onchange=(action (mut productSelected))
                                    onfocus=(action "selectFocused") class="product-select"
                                    autofocus="autofocus"
                                    as |item|}}
                        {{item.name}}
                    {{/power-select}}
```
 I was playing around with this, but I can't quite figure out how to force the power select to open. Do you know of a solution that would work?

```
import Ember from 'ember';
import EmberPowerSelect from 'ember-power-select/components/power-select';
export function initialize(/* application */) {
    EmberPowerSelect.reopen({
        didInsertElement: function() {
            this._super(...arguments);
            Ember.run.next(() => {}
                if (this.get('autofocus')) {
                    

                }
            });
        }
    });
}

export default {
  name: 'power-select',
  initialize
};
```

**Comment by cibernox** [comment]
Reopening the component to add a `didInsertElement` can work. Inside that you can focus the trigger by it's id:
```js
didInsertElement() {
  this._super(...arguments);
  document.getElementById(this.get('triggerId')).focus();
}
```

About the automatically open the component on focus, there is one example in the docs:  http://www.ember-power-select.com/docs/action-handling

**Comment by cibernox** [comment]
Alternatively, you can build your own wrapper around EPS, that does the autofocus and auto-open stuff:

```
{{#power-select-with-autofocus ...attributes as |abc|}}
  ....
{{/power-select-with-autofocus}}
```

Basically your component has to render a EPS and forward ALL attributes to it, expect the ones you want to customize, like the `onfocus` action by example. This is how the multiple select is build, actually: https://github.com/cibernox/ember-power-select/blob/master/addon/templates/components/power-select-multiple.hbs

That way you can be sure that you don't access any private API.

**Comment by bakerac4** [comment]
I tried to add what you said in didInsertElement and I see this.get('triggerId') is undefined. 

I am on "ember-power-select": "0.7.0", not sure if that could have something to do with it?

**Comment by cibernox** [comment]
Yes, you have to update to have it. 

The wrapper component doesn't require you to update, and strictly speaking the triggerId is not public API, so I think that is probably a safer solution.

**Comment by cibernox** [comment]
@bakerac4 did you solve it?

**Comment by bakerac4** [comment]
I'll close for now since this got put on hold for a bit. If I have trouble with the wrapper component I'll re-open. Thanks!

**Comment by perlun** [comment]
@cibernox This has been disturbing me for a while, and today I found this issue.

Would it make sense if we added this to the public API? Being able to automatically give focus to "the most important form field" in a form is IMHO good practice, and will improve the user experience greatly for certain (app-like) web pages & web apps.

**Comment by lougreenwood** [comment]
I agree with @perlun - I've just started using EPS today and I expected an `autofocus` attribute to be available, much like the standard Ember input helpers.

https://guides.emberjs.com/v3.1.0/templates/input-helpers/

**Comment by cibernox** [comment]
@lougreenwood The problem is that autofocus is an html attributes that only works on native inputs, textareas and selects. EPS is not a real select and AFAIK it's impossible to replicate it reliably. Focusing the select on `didInsertElement` is the closest we can get, but in reality it is more complex than that, that's why I am reluctant to implement it that way.
