### ISSUE TITLE
Using the search term inside the block : Second parameter 'term' is found as blank object in the helper

### ISSUE THREAD

**Issue by abuSayedMohammad** [cibernox/ember-power-select#325]
**My code in template.js (shortened):**
{{#power-select
options=names
selected=selection
onchange=(action (mut selection))
as |name term|
}}
  {{highlight-text name term}}
{{/power-select}}

**JavaScript(shortened):**
names: ['Stefan', 'Miguel', 'Tomster', 'Pluto'],
selection: null,

**Helper Method(shortened):**
export function highlightText(text, termToHighlight) {
  console.log('text->'+text);
  console.log('termToHighlight->'+termToHighlight);
  return String.htmlSafe(text.replace(new RegExp(termToHighlight, 'i'), '$&')); // Warning. This is not XSS safe!
}

_I am getting 'termToHighlight' parameter  as blank object And searched text is merged with the search string in 'text' parameter of the helper._

Could anybody guide me?

**Comment by cibernox** [comment]
First thing first: are you in the latest version?

**Comment by abuSayedMohammad** [comment]
"ember": "~2.3.1",
"ember-power-select": "0.8.6",

**Comment by urbany** [comment]
Try this:

*app/helpers/highlight-text.js*
```JavaScript
import Ember from 'ember';

export function highlightText([text, termToHighlight]/*, hash*/) {
  return Ember.String.htmlSafe(text.replace(new RegExp(termToHighlight, 'i'), '<b>$&</b>'));
}

export default Ember.Helper.helper(highlightText);
```

**Comment by abuSayedMohammad** [comment]
Hello Urbany,
The problem is , it is getting blank object in variable termToHighlight.
When I search by I, following is the console output..
**text = ["22000 - Patrick Autocare Head Office", "I"], termToHighlight = Object {}.**
As you can see, 'I' is merged with text variable and termToHighlight variable is blank object..

**Comment by urbany** [comment]
Yes, if you check my snippet you'll notice I'm doing:
```javascript
export function highlightText([text, termToHighlight]) {
```
instead of your:
```javascript
export function highlightText(text, termToHighlight) {
```

(Notice the squared brackets)
More info here: https://babeljs.io/docs/learn-es2015/#destructuring

**Comment by abuSayedMohammad** [comment]
My mistake... It's working .. I did not know this destructuring thing.. Thank you very much for enlightening me..I am trying to understand how this destructuring thing works.. Thanks
