### ISSUE TITLE
Multiple selection hijacks shift+tab events

### ISSUE THREAD

**Issue by johanrd** [cibernox/ember-power-select#328]
Steps to reproduce:
1) Get to focus on a multiple selection by pressing the tab key (http://www.ember-power-select.com/docs/multiple-selection)
2) Press shift+tab and experience that the focus is not moved to the previously focused element, but that the focus stays in infinite loop on the multiple selection. 

Probably because the multiple selection inserts two input fields in the DOM?

**Comment by cibernox** [comment]
Good catch. Tagged as bug.

I think I know the reason.

**Comment by cibernox** [comment]
I'll try to allocate some time this weekend for this.

**Comment by mupkoo** [comment]
Workaround is passing `tabindex=-1` for the `power-select-multiple`

```htmlbars
{{#power-select-multiple
    tabindex=-1
    ....
```

I might create a PR later.

**Comment by vigneshwaran-kannan** [comment]
Hi,

Is there any update regarding the above PR for SHIFT + TAB not working
