### ISSUE TITLE
Multiple selection bug in IE: dropdown doesn't close when selecting option

### ISSUE THREAD

**Issue by supersabillon** [cibernox/ember-power-select#330]
Dropdown list box won't close if only 1 option is selected.

Steps to reproduce:
Using this as an example: http://www.ember-power-select.com/docs/multiple-selection
1. Choose Stefan, the dropdown should immediately close. It stays open on IE11.
2. If you do choose a second option for example, Pluto. The dropdown does close. The bug only occurs when nothing is currently selected.

(Also, the site http://www.ember-power-select.com/ doesn't work properly on IE.)

**Comment by cibernox** [comment]
I'll try to reproduce it in a VM tomorrow. Thanks for the heads up.

**Comment by gregjopa** [comment]
I work with @supersabillon. Please let us know how we can help troubleshoot this IE issue. We tested the `ember-basic-dropdown` demo in IE 11 and it seems to work fine. So I'm thinking the problem is with `ember-power-select`.

Have you considered adding debug logging to `ember-power-select`? It would be helpful if there was a debug log level we could turn on to troubleshoot issues like these. Perhaps [Ember.Logger](https://github.com/emberjs/ember.js/blob/master/packages/ember-metal/lib/logger.js) can be used and the debug statements could be stripped out from production builds using this method: https://github.com/ember-cli/ember-cli/issues/3200.

**Comment by ktrhn** [comment]
For me the dropdown also does not close with single selections. Does that work for you?

**Comment by gregjopa** [comment]
@ktrhn No, this bug only occurs for me with multi-selects. The single select works fine.

@cibernox We just tested out ember-power-select v0.9.1 and it fixes this issue in IE 11. The only small issue with 0.9.1 is the placeholder values no longer show up in IE. 

I think this issue can be closed.

**Comment by cibernox** [comment]
Yeah, there is a bug in IE in which when a input has a placeholder it keeps regaining the focus all the time. The nasty bugfix I did was to disable placeholders in IE.

I need to find a workaround.

**Comment by gregjopa** [comment]
Sounds like a tricky bug. Maybe this IE bug is the cause: https://connect.microsoft.com/IE/feedback/details/810538/ie-11-fires-input-event-on-focus. This bug report says the "input" event is triggered every time the input gets focus.

**Comment by f3anaro** [comment]
@cibernox I am experiencing this bug with Embe.js v3.1 and ember-power-select v2.0.3:

If you open the doc [page for multiselection](https://ember-power-select.com/docs/multiple-selection/) with IE11, the dropdown immediately opens up.

I found that if you set the `maybePlaceholder` property to `null` instead using a computed property, it fixes the problem.

```js
// addon/components/power-select-multiple/trigger.js

// ...
let maybePlaceholder;

if (isIE) {
  maybePlaceholder = null;
} else {
  maybePlaceholder = computed('placeholder', 'select.selected.length', function() {
    if (isIE) {
      return null;
    }

    let select = this.get('select');
    return (!select.selected || get(select.selected, 'length') === 0) ? (this.get('placeholder') || '') : '';
  });
}

export default Component.extend({
  // ...
  maybePlaceholder,
  // ..
});
```

Should I open a new issue for that or can this issue be reopened?
