### ISSUE TITLE
power-select-multiple selected items in RTL layout are not aligned correctly

### ISSUE THREAD

**Issue by behnoodk** [cibernox/ember-power-select#331]
`power-select` renders correctly when `dir=rtl` is set. the only thing that has not been included in the default CSS is the alignment of the selected items (span tags) and input element in `power-select-multiple`. this can be resolved by adding these two classes.

```
.ember-power-select[dir=rtl] .ember-power-select-trigger .ember-power-select-multiple-option,
.ember-power-select[dir=rtl] .ember-power-select-trigger .ember-power-select-trigger-multiple-input{
  float: initial;
}
```

right now the default, for both `ltr `and `rtl `is `float:left`.
let me know what do you think, I can make a pull request.

**Comment by cibernox** [comment]
I'm not using any rtl language at the moment, so I'm not surprised I missed stuff.

That PR sounds good :shipit:
