### ISSUE TITLE
before-options handleKeyDown can be simplified

### ISSUE THREAD

**Issue by cah-briangantzler** [cibernox/ember-power-select#335]
Suggestion: If would appear that the before-options handleKeyDown action could be as follows:

```
    handleKeydown(e) {
      const select = this.get('select');
      //if (e.keyCode === 13) {
      //  const onkeydown = this.get('onkeydown');
      //  if (onkeydown) { onkeydown(select, e); }
      //  if (e.defaultPrevented) { return; }
      //  select.actions.choose(this.get('highlighted'), e);
      //} else {
        select.actions.handleKeydown(e);
      //}
    }
```

and would yield the same result, simplifying the code. (Commented code left if to see the difference, of course you would remove the commented code)

One test fails, because it appears to actually get a select object that isn't quite the same, but wouldnt make a difference. There is a property highlighted that is different.(Should be the same) Wondering though why the select object is different. (Place a breakpoint on [line 67 of public-actions-test](https://github.com/cibernox/ember-power-select/blob/master/tests%2Fintegration%2Fcomponents%2Fpower-select%2Fpublic-actions-test.js#L68)). Also wondering why the property highlighted isnt being used but instead doing a this.get('highlighted') (Shouldnt they be the same based on [line 37 of the template power-select.hbs](https://github.com/cibernox/ember-power-select/blob/master/addon%2Ftemplates%2Fcomponents%2Fpower-select.hbs#L37))

**Comment by cibernox** [comment]
will check today.

**Comment by cibernox** [comment]
I obviously didn't check it 3 days ago. Hard to find time. Lets try this weekend.

**Comment by cah-briangantzler** [comment]
I believe this is still applicable if you haven't had time to check yet.

**Comment by cibernox** [comment]
Unsure if this still applies, so I'm going to close it for now.
