### ISSUE TITLE
Opt out of rendering for empty state

### ISSUE THREAD

**Issue by bttf** [cibernox/ember-power-select#337]
I'm facing a use case where we don't want to present any options or message when the user enters a search with no results. 

Setting `noMatchesMessage` does remove the message but leaves a thin grey line visible for the collapsed div that contains it. Utilizing `{{else}}` does the same.

Wondering if we can add an option to completely opt out of rendering for an empty set.

**Comment by cibernox** [comment]
That is actually not hard to do. You just need to close the component if the search has no results.

You can do that from the outside of the component using the `search` action, that receives the component's API as 2nd argument.

It can also be done from the trigger component. [ember-power-select-typeahead](https://github.com/cibernox/ember-power-select-typeahead) does that when there is no results.

**Comment by bttf** [comment]
Ok - thanks for the help!
