### ISSUE TITLE
power-select-multiple with create?

### ISSUE THREAD

**Issue by karellm** [cibernox/ember-power-select#339]
Hi,

I can't seem to figure out how to use the multiple addon with create functionality. It looks like I can either use `power-select-multiple` or `poser-select-with-create`. Am I missing something? Thanks!

**Comment by cibernox** [comment]
You're the second person that asks the same, so I will just create an example in cookbook. 

The tl;dr; would be to use the `onkeydown` action to detect when the user presses enter, create a new option on the fly, add it to the list of options and select it.

**Comment by karellm** [comment]
My bad, I searched the doc and issues without success. An example would be great!

**Comment by cibernox** [comment]
Don't worry, the other person asked in slack. There was nothing to be found here.

**Comment by cibernox** [comment]
@karellm I've create an example in the cookbook. This example requires some code in the very latest version. http://www.ember-power-select.com/cookbook/create-custom-options

This should explain how to take advantage of the `onkeypress` action to create custom behaviours.
