### ISSUE TITLE
ember-wormhole failed to render into '#ember-basic-dropdown-wormhole'

### ISSUE THREAD

**Issue by haldiggs** [cibernox/ember-power-select#340]
new user here... the select seems to be functioning as expected but I see an error
`Uncaught Error: ember-wormhole failed to render 
into '#ember-basic-dropdown-wormhole' because the element is not in the DOM`

thats pops up every time I use the control. While I was looking for a decent add-on its possible I removed something I shouldn't have... but if this is something anyone knows about I'd love an assist.

**Comment by cibernox** [comment]
This div should be automatically added by the addon to the root of your body. If it's not there... are you rendering your app the body or in a special location? 

This div is appended in the `{{content-for "body-footer"}}` if your `index.html`.

**Comment by haldiggs** [comment]
ahhh, sorry my app is wrapped in an MVC app. I have to manually copy the setup from the ember-app into my NVC views as needed. Pain in the neck but since the only way to use Ember is with the CLI it just is what it is. Thanks for the response.

**Comment by cibernox** [comment]
You're welcome. Closing this then.

**Comment by haldiggs** [comment]
quick follow-up, my mvc app is acting as a shell for more than one ember-app. The #ember-basic-dropdown-wormhole div seesm to react differently depending on where I place it. For instance, if its at the true footer of the body then the dropdown action seems to move the content to the top of the page. Sometimes its a few inches below the actual dropdown itself. I didn't see any specific rules concerning this placement. Could you point me to anything? I guess I can leave you alone now :-)

**Comment by charneykaye** [comment]
Hey team, just adding that I found this thread when in fact I had accidentally introduced *un unclosed `<div>`*  to my app/index.html - and the only noticeable side effect was the failure-to-render of the footer content.
