### ISSUE TITLE
Hide selected elements

### ISSUE THREAD

**Issue by karellm** [cibernox/ember-power-select#346]
I was wondering how I could hide selected elements from the dropdown. I find it extremely noisy to keep them in there. Obviously I could use the css class `ember-power-select-option--selected` but it is less than ideal.

Is the expectation for me to update the `options` list to remove the selected items? Or is there an options I'm missing?

Thanks!

**Comment by cibernox** [comment]
Exactly. You can remove them from the list once selected (and add them back
if unselected). It's up to you.
