### ISSUE TITLE
IE11: Multiple select with no items cannot be unselected

### ISSUE THREAD

**Issue by lwblackledge** [cibernox/ember-power-select#357]
We are using ember-power-select, which works well when there are items in the initial array of options.
However, in IE11 if this initial array is empty then once you open the dropdown it cannot be closed.

I tried to trace this and saw that `handleClose` was firing correctly and setting the search text to ''.
Afterwards it was calling `handleOpen` for no known reason (which did not happen in Chrome).

I could not see why `handleOpen` would be called by IE11 twice, unless there is some strange event bubbling happening?

**Comment by cibernox** [comment]
I fixed it like 3h ago. Install the latest version and report back if it worked.

**Comment by lwblackledge** [comment]
Hah! Thanks, I'll try that tomorrow morning.

**Comment by lwblackledge** [comment]
Yeah, the latest update fixed it, along with switching the power-select-multiple. Thanks!

**Comment by cibernox** [comment]
Closing then
