### ISSUE TITLE
selectChoose onopen action that is async

### ISSUE THREAD

**Issue by snewcomer** [cibernox/ember-power-select#360]
https://github.com/snewcomer/ember-power-select/commit/0bc580a77032aae8929133e00fd46a789e248be5

Here is a commit with a failing test to have the selectChoose helper work with an onopen action that is async. 

I would have thought this line would wait for async operations...Am I missing something here? 

https://github.com/cibernox/ember-power-select/blob/master/test-support/helpers/ember-power-select.js#L60

**Comment by cibernox** [comment]
I think the component at the moment opens and does the selection synchronously. Making the component wait for an async operation fired when it is opened **before** selecting the option is easy, just a matter of adding an `andThen` around [this line](https://github.com/cibernox/ember-power-select/blob/master/test-support/helpers/ember-power-select.js#L60).

I'm not sure if that should be the default behaviour tho. I guess that it can be annoying to teste this if you are precisely using this action to load the options on demand when the component is opened.

**Comment by snewcomer** [comment]
Yeah you are right.  Probably shouldn't be the default behavior.  

Interesting.  I thought the `click` helper within the registered async helper would check for outstanding async requests.  If it doesn't then that is probably why `andThen` didn't work either.  Ember run later helped out the test though.  Still a bit confused (I'm probably missing something), but not a big deal at the moment!!

**Comment by cibernox** [comment]
I just though on another scenario where waiting for promises to resolve after opening the dropdown can be also desired: Animations.

So perhaps that `andThen` should be there, and if you want to test something where you interact with the component before some async action is still in progress, that is probably more exceptional.

I'd take a PR with your failing test and the fix (for both single and multiple selects) if you fancy doing it.
