### ISSUE TITLE
internal search action may no longer be called

### ISSUE THREAD

**Issue by cah-briangantzler** [cibernox/ember-power-select#364]
Although you give an example of debounce, this is in the parent (controller/component) and would have to be rewritten every where you want a debounce.

I have extended the component to add min char and debounce by overriding the internal search action. This was awesome because the search action called nothing but _doSearch and was a great override point.

In version 0.9.0 you have streamlined things to where I believe the internal search action is no longer being called. I believe this is also the case of highLight and select. The choose action is still preserved. You can see this in the [publicAPI](https://github.com/cibernox/ember-power-select/blob/master/addon/components/power-select.js#L144). Could we not remove those actions but instead bring them back by having the publicAPI call them similiar to choose.

**Comment by cah-briangantzler** [comment]
Looking at the code, this issue it still applicable to the 10-beta.2

**Comment by cibernox** [comment]
This is not public API but it's true that is more idiomatic. I'll check it today, finally.

**Comment by cah-briangantzler** [comment]
Looked at this code, think this does what I wanted it to do. Thanks.
Looking forward to a release that includes it to try it out.

**Comment by cibernox** [comment]
I think I already did one release yesterday including this.

**Comment by cah-briangantzler** [comment]
Sorry, yes you did do a tag. I am use to looking for actual releases (they show up big on the releases page), and missed the collapsed tags at the top. Sorry
