### ISSUE TITLE
ember-basic-dropdown-wormhole not added when built for test environment

### ISSUE THREAD

**Issue by bakerac4** [cibernox/ember-power-select#371]
Im seeing an odd issue, when I do a build for development or production 
`<div id="ember-basic-dropdown-wormhole"></div>`
is added to my index.html.

But when I do a test build, nothing is added.

**Comment by cibernox** [comment]
@bakerac4 That is intended. The qunit container (that small window) is used as the destination of the placeholder. Is that causing you any trouble?

**Comment by cibernox** [comment]
Closing this. Let me know if this decision cause your any issue.
