### ISSUE TITLE
Custom Option-Elements broken

### ISSUE THREAD

**Issue by Haidy777** [cibernox/ember-power-select#389]
Since v0.10.0-beta.0 options with custom elements are broken.

Example:
```handlebars
{{#power-select options=someList selected=selectedItem onchange=(action 'someAction') as |item|}}
  <div class="special-class">
    <i class={{item.icon}}></i>
    {{item.text}}
  </div>
{{/power-select}}
```

If you click on the 'i'-Tag in the list, nothing happens.
After some investigation i found out, why it doesn't work:

[addon/components/power-select/options Line 19](https://github.com/cibernox/ember-power-select/blob/74202ee25bc189883edca130b75c76eb2eec9410/addon/components/power-select/options.js#L19)
```javascript
this.element.addEventListener('mouseup', e => {
  if (e.target.dataset.optionIndex) { // the clicked element 'i' doesn't have a data-option-index property
    this.get('select.actions.choose')(this._optionFromIndex(e.target.dataset.optionIndex), e);
  }
});
```

The clicked 'i' doesn't have a 'data-option-index'-Property, so the if gets passed by and nothing happens.

That could be solved with the little help of jquery:
```javascript
this.element.addEventListener('mouseup', e => {
  const optionIndex = Ember.$(e.target).closest('li').data('option-index').toString();
  if(!isEmpty(optionIndex)){
    this.get('select.actions.choose')(this._optionFromIndex(optionIndex), e);
  }
});
```

Maybe there is also another solution?

**Comment by cibernox** [comment]
You're totally right. This shouldn't assume that the click happens in the `<li>`. It can happen in any element inside. Your suggestion is exactly the right solution.

Can you do that PR and add a test case to avoid any future regressions?

**Comment by Haidy777** [comment]
Sure, I will open a PR.
Might there be another place where this error would occur?

**Comment by cibernox** [comment]
I don't think so, this is the only place in the addon where I decided to go with event delegation instead of attach events directly to save a bit of performance due to reduce the number of event listeners.

**Comment by Haidy777** [comment]
Just pushed one commit to github. Looks like there is something broken with the package.json?
See https://travis-ci.org/Haidy777/ember-power-select/builds/117483023

**Comment by cibernox** [comment]
@Haidy777 Can you try again, I've changed the package.json to use https instead of git.

**Comment by Haidy777** [comment]
@cibernox Thanks, that worked ;)
