### ISSUE TITLE
ability to keep dropdown open when in multiple mode

### ISSUE THREAD

**Issue by miguelcobain** [cibernox/ember-power-select#39]
A handy feature in multiple selection would be to keep the dropdown open when selecting stuff.

Example: https://brianreavis.github.io/selectize.js/ (Under "E-mail contacts")

**Comment by cibernox** [comment]
Yeah, I had that in mind too. It can also be paired with pressing ctrl/cmd to do so, or even caps to select a range.

**Comment by cibernox** [comment]
I think that the `closeOnSelect` option already handles this.
