### ISSUE TITLE
Add integration test helpers documentation to website

### ISSUE THREAD

**Issue by blimmer** [cibernox/ember-power-select#391]
The acceptance test helpers are well documented, but the integration test helpers aren't exposed on the website.

**Comment by snewcomer** [comment]
@cibernox I can take a wack at this if you want.  Basically two sections - Acceptance Test Helpers and Integration Test Helpers.  See a few typos on the helpers page as well I can fix.

**Comment by cibernox** [comment]
@snewcomer Absolutely.

I never intended to make those integration helpers public API, just the acceptance ones (which BTW, are tested so I can be sure I don't break them). 

But I guess that once they are added, there is no harm in telling people that they exist. Just add a small disclaimer that they are unlikely to change, but there is a very small chance that they do.
