### ISSUE TITLE
Show number of items selected(count) instead of actual items. 

### ISSUE THREAD

**Issue by murli2308** [cibernox/ember-power-select#392]
![1_selected](https://cloud.githubusercontent.com/assets/851034/13943144/2a7c85e0-f020-11e5-99cc-2d33e7c4275c.png)

only 1 item selected which fits inside width

![2_selected_oveflowing_width](https://cloud.githubusercontent.com/assets/851034/13943145/2a8004ae-f020-11e5-9eda-3a6889c854fe.png)

when 2 items are selected it changed to count mode.

I came across a situation where I wanted to show the count like "3 items selected" instead of actual items. If the selected items are overflowing width it should not come down. It should switch to count mode.

**Comment by cibernox** [comment]
You should be able to do this with a custom `triggerComponent` pretty easily.
Pass `{{power-selec-multiplet blah blah triggerComponent="my-custom-trigger"}}` and roll your own solution.

**Comment by murli2308** [comment]
is it possible to provide a simple example ?

**Comment by cibernox** [comment]
```hbs
{{!-- components/my-custom-trigger.hbs --}}
{{#if (gt selected.length 1)}}
  {{selected.length}} items selected
{{else}}
  {{selected.firstObject}}
{{/if}}
<span class="ember-power-select-status-icon"></span>
```

```js
// components/my-custom-trigger.js
import Ember from 'ember';
export default Ember.Component.extend({})
```

**Comment by terryroe** [comment]
This replaces the trigger with a non-functioning div and no input field.  Are there more complete instructions for how to override the triggerComponent somewhere?

**Comment by cibernox** [comment]
@terryroe The code I pasted was a trigger for the single select, which is already pretty much a non-functional empty div.

I need to add that to the docs, but I've been delaying it waiting for the API to be stable, which is 9X% done.

The tl;dr; of extending components until there is a better guide.

- Customize the most fine-grained component that can give you the desired behaviour. The [Architecture](http://www.ember-power-select.com/docs/architecture) section of the docs has a diagram enumerating all the pieces of the dropdown that can be customized with your own component.
- If you want to create a very small modification over the default behaviour of, say, the trigger, you are probably better creating a component that extends from `ember-power-select/components/power-select/trigger.js` or `ember-power-select/components/power-select-multiple/trigger`, copy the original template and customize the thing you want.
- If what you want to build is different enough from the default behaviour, you might want just create a component that doesn't inherit from anything in particular and do your vodoo, taking into account a couple things:
    * A lot of behaviour is handled by the trigger, so if you don't handle an event in your component and you let it bubble, chances the default behaviour will happen (by example open/close on click/enter/tap)
    * If you want to do something custom by example when the user hits enter instead of the default behaviour, prevent bubbling with `e.stopPropagation()`. If you want to do both your custom thing and the default, let it bubble.
    * The component uses mousedown/up, not click. There is a reason for this.
    * The component uses mostly native events, not jquery ones, so you probably don't want to use jquery's event delegation.
    * This video can come up handy: https://vimeo.com/154419491

**Comment by cibernox** [comment]
I'm closing this for now since it is doable with custom components.

I have to write a guide on how to extend EPS. I'll try to do that the next weekend.
