### ISSUE TITLE
Select all/none option should be provided for power-select-mulitple

### ISSUE THREAD

**Issue by murli2308** [cibernox/ember-power-select#393]
Is it possible to implement select all/none ?

**Comment by cibernox** [comment]
Passing custom components you can do pretty much anything.

**Comment by cibernox** [comment]
Closing this, since it is something doable with custom components. I need to allocate some time to create a "How to extend EPS" guide to make this easier.

**Comment by adambedford** [comment]
How would one go about doing this? I figure it involves `beforeOptionsComponent` with buttons for "Select All" and "Clear", but what would be the best way to set all options as selected/not selected?
