### ISSUE TITLE
Use default select2 CSS classes

### ISSUE THREAD

**Issue by ludalex** [cibernox/ember-power-select#398]
Awesome project first of all. 
I was wondering, since I'm using a UI kit that provides nice custom CSS select2 classes, if it's possible to implement the feature or there's already an option to use the default select2 classes instead of the "ember-power-select*" ones so that one can use all the custom select2 themes available out there overriding the default classes.
Thanks in advance.

**Comment by cibernox** [comment]
That is not really easy to do, if possible at all.
Although the base styles are inspired by select2, the actual markup is different, so not all classes could be translated. Some part actually are styles based in aria-* roles to improve the accessibility, not based on classes. And most likely an incomplete solution wouldn't work.

That said, specially if you are using sass, there is a few variables you can use to adapt the component to your theme.

Useful links: 
http://www.ember-power-select.com/docs/styles
https://github.com/cibernox/ember-power-select/blob/master/app/styles/ember-power-select/variables.scss

I hope this helps.

**Comment by ludalex** [comment]
Okay, thanks anyway for the detailed answer.
