### ISSUE TITLE
Selected wait for Promise

### ISSUE THREAD

**Issue by jrock2004** [cibernox/ember-power-select#404]
Great plugin but I am having an issue that I cannot figure how to solve. I have a dropdown that is returning a promise so when the page loads, the selected option is not getting set because the promise has not been fulfilled yet

// Route
```
  model(params) {
    return this.store.findRecord('employee', params.employee_id);
  },

  setupController(controller, model) {
    this._super(controller, model);

    controller.set('setAction', 'saveEmployee');
    controller.set('providerList', this.store.findAll('provider'));
  },

  renderTemplate() {
    this.render('admin/employeeform');
  },

  actions: {
    saveEmployee(saveEmployee) {

      saveEmployee.save().then(() => this.transitionTo('admin.employees'));
    }
  }
```

// Template

```
    {{#power-select
      selected=model.provider.content
      options=providerList
      onchange=(action (mut model.provider))
      as |provider|}}
        {{provider.name}}
      {{/power-select}}
```

// Model

```
export default DS.Model.extend({
  name: DS.attr('string'),
  phone: DS.attr('string'),
  email: DS.attr('string'),
  notes: DS.attr('string'),
  provider: DS.belongsTo('provider')
});
```

When the page loads and I click the dropdown, I can see the options. What is not working is on page load, the provider is not being selected. Thoughts?

**Comment by cah-briangantzler** [comment]
Is there a reason .content is on the end of `selected=model.provider.content`? on change is only mutating `model.provider`

**Comment by jrock2004** [comment]
I can remove.content and the same things still happen

**Comment by cah-briangantzler** [comment]
What version of ember are you using? If you are using 2 or greater the default access for belongsTo is async, meaning, what you are getting back is a PromiseObject, whose content will be the provider once its resolved. Power select is checking that the object selected is in the list of providers, it is not, another object (PromiseObject) is the selected, which points to the provider.

**Comment by jrock2004** [comment]
So I need to resolve my promise first? I'm using Ember 2.4

**Comment by cah-briangantzler** [comment]
Ok, LOL, thats why you had content on the end. Yes, the model.provider will have to resolve first, then assign model.provider.content to the selector.

Now that being said, I would have thought that when the promise resolved, model.provider.content would have caused the power-select to have been re-rendered.

whats going on with this? `controller.set('setAction', 'saveEmployee');` Could that have something to do with it?

**Comment by cibernox** [comment]
I think I guarded for the options being a promise but I never guarded for the select element to being one. 

Seems a very reasonable request. 

I'll mark this as a bug.

**Comment by cah-briangantzler** [comment]
I have been thinking about this, since he is passing in model.provider.content shouldnt it re-render when content is resolved without you having to do anything? Is is possible that there are records in the cache and the find all is resolving them (not as a promise), then doing a background load, and when that load is finished the array size is changing. But you [check accordingly](https://github.com/cibernox/ember-power-select/blob/v0.10.0-beta.6/addon%2Fcomponents%2Fpower-select.js#L99). This really should be working as is unless there is more we don't know.

**Comment by miguelcobain** [comment]
When this gets implemented, we should have ember-data tests for this as well.
e.g `selected=model.someAsyncBelongsToRelationship`

**Comment by jrock2004** [comment]
Thanks, let me know what you need from me to help solve this

**Comment by cibernox** [comment]
Actually, just a PR with a failing test would be perfect.

**Comment by jrock2004** [comment]
PR?

**Comment by cibernox** [comment]
Pull request

**Comment by cibernox** [comment]
I think I've fixed this in just now. Check the latest beta and let me know.
