### ISSUE TITLE
ember-power-select-multiple: onkeydown called twice for non-character keys

### ISSUE THREAD

**Issue by aquamme** [cibernox/ember-power-select#405]
Tested with ember-power-select versions 0.9.0, 0.9.2, 0.10.0-beta.6, using Ember 1.13.10. Keys a-z and space are not effected, but all others (numbers, special characters, control keys, etc) cause the onkeydown action to be called twice.

**Comment by cibernox** [comment]
@aquamme in testing only or also with real interaction?

**Comment by aquamme** [comment]
@cibernox with real interaction.

**Comment by cibernox** [comment]
Oops, that's bad. I'll tag this as a bug and tackle it after emberconf. Can you provide a failing test?

**Comment by aquamme** [comment]
I wrote a test, but the darn thing wouldn't fail. I also couldn't reproduce the issue using the dummy/doc app from this repository. So far it looks like something specific to my app. I'll keep working on narrowing down the cause and let you know what I find out.

**Comment by cibernox** [comment]
Have you customized the component containing the searchbox?

On reason why I might see this happening is that is, if the searchbox is inside the trigger and you don't call `stopPropagation()`, that might happen. If that is not the case, I can think in any other reason any the `onkeypress` would be called twice.

**Comment by aquamme** [comment]
`stopPropagation` did the trick -- I don't have a clear understanding of why it does though. It might be worth adding something to the docs about that.

Thank you for your help and for the slick components. I can tell they were made with love :smile:

**Comment by cibernox** [comment]
For completeness, the reason why you need to stop propagation is because the trigger listen for key events (enter by example, to open & close the component). 
So if you handle a keydown in you custom component and you don't want it to be bubble and be handled twice it has to be stopped.

Writing a guide about how to extend components is on my todo list, but probably after v1.
