### ISSUE TITLE
When hovering over a disabled list-item there is a console error.

### ISSUE THREAD

**Issue by gertjanwytynck** [cibernox/ember-power-select#407]
`Error: options.js:32 Uncaught TypeError: Cannot read property 'dataset' of undefined`

This is also on the demo page: http://www.ember-power-select.com/docs/the-list (bottom)

Any tips for a solution?

**Comment by Haidy777** [comment]
Looks like that error is produced by this line: https://github.com/cibernox/ember-power-select/blob/master/addon/components/power-select/options.js#L24 .

I think a slightly altered if should fix it.

**Comment by cibernox** [comment]
Thanks for reporting, this seems fixed now.
