### ISSUE TITLE
Custom Option-Elements touch-events broken

### ISSUE THREAD

**Issue by Haidy777** [cibernox/ember-power-select#408]
Since v0.10.0-beta.0 options with custom elements seem to be broken on touchy devices.

Might be a similar problem we had in #389? I couldn't find the problem yet, mabye someone else already did?

**Comment by cibernox** [comment]
Labelled as bug, I'll check it after emberconf. Can you provide a failing test to help fixing it and prevent future regressions?

**Comment by Haidy777** [comment]
Sure, I will try to add one tomorrow.

**Comment by Haidy777** [comment]
Sorry I didn't reply any earlier. I've been pretty busy the last days.
Unfortunately I can't make the test running. Seems like they are not that easy to run on a windows environment?

**Comment by cibernox** [comment]
@Haidy777 I never tried. The node ecosystem is not very windows-friendly in general, so this doesn't surprise me at all. 
What is failing? Phantomjs maybe?

Most people using node (and therefore using ember-cli) tend to use a linux VM (even if it's without UI). That is the only idea I can give you given that I never used ember-cli with windows.

**Comment by Haidy777** [comment]
Sorry that it's been awhile since my last comment. I could track down the lines which are causing this problem.
As you can see in [addon/components/power-select/options.js](https://github.com/cibernox/ember-power-select/blob/master/addon/components/power-select/options.js#L43) it is the same kind of problem as in #389.

The touched element is not the one with the `options-index`. I've already got a solution, currently working on some tests. PR to come.
