### ISSUE TITLE
DEPRECATION: Usage of `Ember.merge` is deprecated, use `Ember.assign` instead. [deprecation id: ember-metal.merge]

### ISSUE THREAD

**Issue by urbany** [cibernox/ember-power-select#410]
Hi, this line seems to be using a method deprecated in Ember@2.5.0-beta.3
https://github.com/cibernox/ember-power-select/blob/445a5230291099ba1977f824712f26367f76d946/addon/components/power-select.js#L158

**Comment by miguelcobain** [comment]
@urbany there is already an open PR for that problem: https://github.com/cibernox/ember-power-select/pull/406
