### ISSUE TITLE
JSHint error - possible typo

### ISSUE THREAD

**Issue by pgengler** [cibernox/ember-power-select#412]
[Line 58 of `addons/components/power-select/options.js`](https://github.com/cibernox/ember-power-select/blob/master/addon/components/power-select/options.js#L58) triggers a JSHint error when I run the tests locally (no idea why it isn't being caught by the CI build).

The error is:
```
modules/ember-power-select/components/power-select/options.js should pass jshint.
modules/ember-power-select/components/power-select/options.js: line 60, col 9, 'option' was used before it was declared, which is illegal for 'let' variables.
```

I'm not 100% sure but it seems like maybe the use of `option` (singular) on this line was a typo and `options` (plural) was intended.

**Comment by cibernox** [comment]
@pgengler Totally. I've just fixed it, but the fact that the tests passed with this typo concerns me :confused:
