### ISSUE TITLE
Selected option doesn't transfer to blue-highlight?

### ISSUE THREAD

**Issue by toobulkeh** [cibernox/ember-power-select#415]
Great library! Just switched over to it from xselect as xselect has no support for promises.

It took me a while to figure things out, but so far so good!

The first visual problem I have is when the selected option doesn't match the highlighted blue in the dropdown.

In this example we have a Model "Account" that has a list of users and a single owner:
`account.js`
```javascript
export default DS.Model.extend({
  owner: DS.belongsTo('user', {async: true}),
  users: DS.hasMany('user', {async: true}),
  ....
```
then a component that is a form consuming ember-power-select
`account-form.hbs`
```hbs
<div class="form-group">
  <label>Account Owner</label>
  {{#power-select
    dropdownClass='in-modal-dropdown'
    options=account.users
    selected=account.owner
    searchEnabled=false
    onchange=(action 'chooseOwner')
    as |user|}}
    {{user.fullName}}
  {{/power-select}}
</div>
```

I'm not exactly sure why this happens, but this is how it renders on first click:
![screen shot 2016-03-30 at 4 35 36 pm](https://cloud.githubusercontent.com/assets/1342064/14156829/6356e3ca-f696-11e5-84e2-9f9cb2058e85.png)

Some ideas that I think it's related to are:

1. It's in a modal. I only change the z-index though...
2. Both the options and selected are promises and there's [this currently open issue](https://github.com/cibernox/ember-power-select/issues/404), aptly numbered 404 :smiley_cat: 
2. I'm still not very skilled at finding when promises are resolved, so maybe account is still a promise as well?

Now that I think about it, I am using a custom action, because the mut shortcut didn't work... because #404... so is this yet another side effect that would be solved by the selected promise being resolved?

**Comment by cibernox** [comment]
Yeah, this issue is most likely related. I'll get #404 fixed a few days after emberconf (i'm travelling at the moment). I have to make the `selected` property promise-aware as the `options` property.

**Comment by cibernox** [comment]
@toobulkeh I think that I've fixed this. Try the beta.7 and let me know if that is not the case.

I'm optimistically closing this

**Comment by toobulkeh** [comment]
yup, that was it! Thanks for the fast work!
