### ISSUE TITLE
Click doesn't register if a component is used for the contents of the list item?

### ISSUE THREAD

**Issue by barelyknown** [cibernox/ember-power-select#416]
If I use a component for the contents of a list item...

```
{{#power-select ... as |customer|}}
  {{customer-name customer=customer}}
{{/power-select}}
```

...then a click on the component (`customer-name`) does not bubble to the `power-select` component.

I looked in the documentation for the idiomatic way to handle this, but I couldn't figure it out. Is there one?

**Comment by cibernox** [comment]
@barelyknown Can you try the latest beta (or the master branch). I think this has already been fixed.

Also, in case you are having issues in testing, this component uses native events, not jquery events, so you need to fire native events. Also, the options of the list are selected with mouseup, not click (intentionally)

**Comment by barelyknown** [comment]
I just used the master branch and it's fixed. I would have checked that earlier but I didn't see an issue in GitHub - sorry!
