### ISSUE TITLE
Horizontal position with matchTriggerWidth=false

### ISSUE THREAD

**Issue by Pasikonik** [cibernox/ember-power-select#421]
It's possible to set horizontal position when trigger is narrower than dropdown content?
![Image](http://i.prntscr.com/39a8bd4693e444e7b98daf0547920fb4.png)

I would like to align dropdown by right side of trigger.

**Comment by cibernox** [comment]
Mmm... apparently it's not, I must have forgotten to forward that property. 

I'm in holidays, but if you fancy a PR I should have enough time to press a merge button :grin: 

Check this lines:

Basic dropdown:
https://github.com/cibernox/ember-basic-dropdown/blob/master/addon/components/basic-dropdown.js#L20

Power select:
https://github.com/cibernox/ember-power-select/blob/master/addon/templates/components/power-select.hbs#L8

**Comment by Pasikonik** [comment]
#423 done :)
