### ISSUE TITLE
When both `options` and `selected` are async and `selected` arrives first, `selected` does not work

### ISSUE THREAD

**Issue by batjaa** [cibernox/ember-power-select#430]
Few lines of codes are equal to thousands of words :)

```js
test('The `selected` option and `options` can be both async but `selected` but `options` arriving later does not clear selection', function(assert) {
  let done = assert.async();
  assert.expect(6);
  server.logging = true;

  let users = server.createList('user', 10);
  let mainUser = server.create('user', { friendIds: users.map(u => u.id), bestieId: users[3].id });

  Ember.run(() => {
    this.store.findRecord('user', mainUser.id).then(record => {
      this.mainUser = record;
      this.friends = new Ember.RSVP.Promise((resolve) => {
        setTimeout(() => resolve(mainUser.friends), 50);
      });
      this.bestie = new Ember.RSVP.Promise((resolve) => {
        setTimeout(() => resolve(mainUser.bestie), 10);
      });
      this.render(hbs`
        {{#power-select options=friends selected=bestie searchField="name" onchange=(action (mut foo)) renderInPlace=true as |option|}}
          {{option.name}}
        {{/power-select}}
      `);

      clickTrigger();

      assert.equal($('.ember-power-select-option[aria-selected="true"]').length, 0, 'no element is selected');
      assert.equal(this.$('.ember-power-select-trigger').text().trim(), '', 'Nothing is selected yet');

      setTimeout(function() {
        assert.equal(this.$('.ember-power-select-trigger').text().trim(), 'User 3', 'The trigger has the proper content');

        setTimeout(function() {
          assert.equal($('.ember-power-select-option[aria-current="true"]').text().trim(), 'User 3', 'The 4th element is highlighted');
          assert.equal($('.ember-power-select-option[aria-selected="true"]').text().trim(), 'User 3', 'The 4th element is highlighted');
          assert.equal(this.$('.ember-power-select-trigger').text().trim(), 'User 3', 'The trigger has the proper content');
          done();
        }, 100);
      }, 10)


    });
  });
});
```
^ test fails.

When options arrive later `indexOfOption()` does a hard equal check on `selected` and `entry`. Not sure if that's the issue. Thoughts?

**Comment by cibernox** [comment]
Good catch. 
I'll try to fix it using this failing test case.

**Comment by cibernox** [comment]
The test you provided failed, everything seemed to be fine, so I created a simplified version without involving mirage and ember-data, and it seems to work.

https://github.com/cibernox/ember-power-select/pull/432

**Comment by batjaa** [comment]
Yes. I'm trying to think of an easy way to replicate it but couldn't and that's how that test was written.

I think the problem I'm having is, again the scenario is the same. Both `selected` and `options` are async and `selected` comes first. But I see that once `options` gets resolved `selected` being set to `null`.

This might be some underlaying ember-data thing, where a new collection arrives it will re-set any model that is in  that collection. But I don't know.

**Comment by cibernox** [comment]
It might be be that. In those examples in the PR, using just plain promises with strings it does work as expected, so the order in which the promises are resolved don't seem to matter.

**Comment by batjaa** [comment]
I'm gonna look a little bit more into ember-data and will update if I find something. Thanks for the help.

**Comment by cibernox** [comment]
I'm going to close this in the meanwhile. Reopen it if after your research you find this is actually a problem in EPS.
