### ISSUE TITLE
Test helpers are broken

### ISSUE THREAD

**Issue by foxnewsnetwork** [cibernox/ember-power-select#431]
### What?
On version `0.10.0-beta.8` , using the test helpers `selectChoose` and `selectSearch` are both broken. The both result in some form of the following error message
```shell
TypeError: Cannot read property '1' of null
    at .<anonymous> (http://localhost:4200/assets/tests.js:1169:123)
    at http://localhost:4200/assets/vendor.js:55393:19
    at isolate (http://localhost:4200/assets/vendor.js:55594:13)
    at http://localhost:4200/assets/vendor.js:55578:14
    at tryCatch (http://localhost:4200/assets/vendor.js:68023:14)
    at Object.invokeCallback (http://localhost:4200/assets/vendor.js:68038:15)
    at http://localhost:4200/assets/vendor.js:70164:25
    at http://localhost:4200/assets/vendor.js:46562:7
    at Queue.invoke (http://localhost:4200/assets/vendor.js:14814:16)
    at Object.Queue.flush (http://localhost:4200/assets/vendor.js:14878:11)
```

### Details
Digging into the codebase here:

https://github.com/cibernox/ember-power-select/blob/master/test-support/helpers/ember-power-select.js#L74

```javascript
find(cssPath).find('.ember-power-select-trigger').attr('id').match(/ember-power-select-trigger-ember(\d+)/)[1]
```
I note that the helper attempts to find a class like `ember-power-select-trigger-ember23423`, but is unsuccessful.

Digging into my own use case with the browser console (screenshot here):
![screenshot-console](https://cloud.githubusercontent.com/assets/1010423/14272285/905a211a-fab6-11e5-9579-7ac31548ec23.png)

I note that, in my use case, my power-select-trigger class is actually:

```html
<div id="ember-power-select-trigger-em-input-ember2189" ...>
```
In particular, it also features the `-em-input-` string which completely messes up the test helpers

### My Suggested Solution
Consider changing the id match regex from `/ember-power-select-trigger-ember(\d+)/` to `/ember-power-select-trigger.*ember(\d+)/`

This way, we can be more robust with how power select goes about fudging with its id names.

Please let me know if you want me to pr

**Comment by cibernox** [comment]
Test helpers are themselves tested to validate they don't break between versions. Can you create a failing test case for this? 
I'm surprised a regression wasn't caught by them.
