### ISSUE TITLE
Add ability to auto select first value

### ISSUE THREAD

**Issue by jcbvm** [cibernox/ember-power-select#434]
It would be nice if there is an option to automaticly select the first value on init (when options are loaded) when selected is undefined or not a promise.

Currently this can be done by setting the selected value somewhere in the route, controller etc which gets annoying when having to repeat several times.

(I'm willing to create a PR if needed)

**Comment by cibernox** [comment]
I'm curious about how this plays in an scenario without double bindings like this component.

```hbs
{{#power-select options=options selected=selected onchange=(action (mut selected)) as |opt|}}
  {{opt}}
{{/power-select}}
```

If this feature gets added to the component (which BTW I think that it would fit better as another addon with a wrapper component), what would happen? The `onchange` action is automatically fired when the component is first rendered? Will also be called if the options change (or resolve if they are a promise)?

Just to see all the corners of the subject.

It feels a bit weird to me to fire the `onchange` action without user interaction, and I certainly want to avoid double bindings.

**Comment by jcbvm** [comment]
That's something I also struggled with. As you mentioned, double binding should be avoided, so the only option is to indeed fire the onchange action. But this may lead to a little messy state, because the selected property doesn't have to get changed when the onchange is fired (that's up to the user).

I don't think firing the onchange is weird though, if the option is enabled by the user to do so.

**Comment by cibernox** [comment]
If you want to explore this as a separate component, I think that you should create an addon (`{{power-select-autochoose}}`?) that is just a wrapper component over `{{power-select}}` and has this behaviour.

I try to keep the core component as slim as possible and make it easy to extend or compose so people can create their own flavours and publish them in NPM. 

www.ember-power-select.com/addons has some examples of this approach if you want to explore it.

**Comment by jcbvm** [comment]
Thanks, will take a look at it

**Comment by cibernox** [comment]
@jcbvm I'm closing this for my mental sanity (keep the issues counter low). Let me know if you find any problem creating that wrapper component.
