### ISSUE TITLE
Selected bound to query param

### ISSUE THREAD

**Issue by Aaronfischer** [cibernox/ember-power-select#438]
I have a few routes that need to use a URL query param (?profile_id=X) to return the model on the route, so it looks like the same model is preserved across routes.

I have the power-select that is returning a promise from a relationship (`profile`). I am then binding the query param `profile_id` as the power-select `selected`.

```js
// controller

// query param
profile_id: null,

profileContent: Ember.computed(function() {
    return this.store.findAll('profile');
}),

setProfile: Ember.observer('profile_id', function() {
    if (this.get('profile_id')) {
        this.get('profileContent').then(function(profiles) {
            this.set('model', profiles.findBy('id', this.get('profile_id')));
        }.bind(this));
    }
}),
```

```js
// route
setupController(controller, model) {
    this._super(controller, model);

    // Ensure model is set on transition
    // If profile_id does not exist set it to the firstObject
    controller.get('profileContent').then(function(profiles) {
        if (!controller.get('profile_id')) {
            controller.setProperties({
                profile_id: profiles.get('firstObject.id'),
                model: profiles.get('firstObject')
            });
        } else {
            controller.set('model', profiles.findBy('id', controller.get('profile_id')));
        }
    });
},
```

```hbs
<!-- templates -->

{{#power-select
    options=billingProfileContent
    selected=(find-by billingProfileContent 'id' billing_profile_id)
    searchField="label"
    searchEnabled=false
    placeholder="Select the company"
    class="ship-to"
    onchange=(action (mut billing_profile_id) value="id")
    as |profile|}}
        {{profile.name}}
{{/power-select}}
```

The problem is, when the page loads and a query-param is in the URL, `selected` is not set on the dropdown. However, after an option is selected, the query-param is updated and everything stays in sync. Its just not working on an initial refresh. Any thoughts?

**Comment by Aaronfischer** [comment]
Note:
I'm using `"ember-power-select": "0.10.0-beta.8",` and Ember 2.4. Not sure if this issue may be related to #404 or not?

**Comment by cibernox** [comment]
I tried to grasp what is going on but it's hard. Many moving parts at once.

The template snippet seems reasonable, that is how I'd do it. 
My guess is that this is not EPS-related, but something with `(find-by billingProfileContent 'id' billing_profile_id)` not updating property when one of those promises promise/observer thing resolves.

The logic of EPS when it comes to the selected is particularly simple. I just check if it's a promise, and if it's not (and that `find-by` helper I don't think it will return a promise) it's just forwarded to the trigger, where it is displayed. 

I'd be surprised if EPS has something to do with this.

**Comment by Aaronfischer** [comment]
@cibernox Yup, I think you were exactly right, it was an issue with the `find-by` helper, I needed to resolve the `billingProfileContent` promise as the `find-by` helper was not able to wait for a promise.
