### ISSUE TITLE
Removing the ul in ember-power-select-multiple

### ISSUE THREAD

**Issue by karellm** [cibernox/ember-power-select#440]
Hi,

I noticed that selected options are wrapped in a `ul.ember-power-select-multiple-options`. This causes the input where we type to be pushed on a new line when selected options don't fit on a single line:

![](https://s3.amazonaws.com/f.cl.ly/items/2W1f1L1c2L1i3T2r3G3T/Image%202016-04-07%20at%201.12.05%20PM.png?v=93f8d866)

As reference, here is how selectize does it:

![](https://s3.amazonaws.com/f.cl.ly/items/3d0z0U1d2G343p2f1R3n/Image%202016-04-07%20at%201.11.05%20PM.png?v=7947784d)

Is there a reason for that? Are you open to a PR?

**Comment by karellm** [comment]
@cibernox This is blocking us in our application, can you tell me whether I should spend time on a PR or hack the solution locally?

**Comment by cibernox** [comment]
I think I can move the input inside the `<ul>`. I don't know how bad it is from an accesibility point of view, but probably some `role=*` can fix it. Will be fixed today

**Comment by cibernox** [comment]
This should be fixed now in the master branch.

**Comment by karellm** [comment]
Thanks that did the trick!
