### ISSUE TITLE
When grouping options currently async is not supported

### ISSUE THREAD

**Issue by batjaa** [cibernox/ember-power-select#441]
```js
this.groupedNumbers = [
    {
      groupName: "Smalls",
      options: new Ember.RSVP.Promise((resolve) => {
          setTimeout(() => resolve(numbers), 10);
        })
    },
    {
      groupName: "Mediums",
      options: new Ember.RSVP.Promise((resolve) => {
        setTimeout(() => resolve(numbers), 50);
      })
    }
  ];
  this.render(hbs`
    {{#power-select options=groupedNumbers onchange=(action (mut foo)) as |option|}}
      {{option}}
    {{/power-select}}
  `);
```
this seem not work.

Was this a design decision to wrap all grouped options to be resolved together. Or is this an edge case?

I could think of some weird behaviors like showing multiple `Loading...` messages under groups.

**Comment by cibernox** [comment]
I guess this *could* be handled, but seems pretty edge to me. I wouldn't know what to display in this case. Multiple loadings? Ugh.

I'd rather leave to the user to create a promise that resolves once all the internal groups are resolved. Do you agree?

**Comment by batjaa** [comment]
Agree, for the simplicity I would just wrap all promises.
Handling promises feels like opens too many possibilities.

**Comment by cibernox** [comment]
Closing then :+1:
