### ISSUE TITLE
Disable and enable power select dropdown

### ISSUE THREAD

**Issue by adhithyaraja** [cibernox/ember-power-select#444]
Hi,

I went through the docs power-select and did few samples using it , I couldn't find the option to enable or disable a drop-down, when onChange of another drop-down. If this option is available, how to achieve it.

Thanks.

**Comment by cibernox** [comment]
The documentation has an extensive API reference here: http://www.ember-power-select.com/docs/api-reference

The property is name (unsurprisingly :grin:) `disabled=true/false`
