### ISSUE TITLE
Issue with ember-power-select.scss inside of an addon. 

### ISSUE THREAD

**Issue by onlymejosh** [cibernox/ember-power-select#448]
We're including ember-power-select inside of an internal addon and hit an issue where `ember-power-select.scss` cannot be found. 

I initially added this:
```
sassOptions.includePaths.push(
 +      this.pathForNodeDependency('node_modules/ember-power-select/app/styles'),
```

However this didn't solve the issue as there is also a dependency on `ember-basic-dropdown`.

So we need to do this.. which is a little nasty:

```
sassOptions.includePaths.push(
  ...
  this.pathForNodeDependency('node_modules/ember-power-select/node_modules/ember-basic-dropdown/app/styles')
```

Could you include the sassDependency of `ember-basic-dropdown`? Happy to do a PR if you're OK with it.

**Comment by cibernox** [comment]
From the `included` hook in the index.js of that addon, do you have a line like this? `this._super.included.apply(this, arguments);` It might have nothing to do, but just in case.

Also, you might need to do this in your addon to allow the addon to insert the placeholder automatically in the root of the body.

```js
  contentFor: function(type, config) {
    var emberPowerSelect = this.addons.filter(function(addon) {
      return addon.name === 'ember-power-select';
    })[0]
    return emberBasicDropdown.contentFor(type, config);
  }
```

About your addon, I'd just expect you to define inside your addon's `/app/styles/my-addon.scss` to do:

```scss
@import 'ember-power-select';
```

and it should work. No need to define any sass include paths.
Having 3 levels of addons is something new to me, so maybe I need to apply some pattern I'm not aware of.

**Comment by alechirsch** [comment]
+1 here, can not seem to figure out how to include the sass inside of an internal addon.
