### ISSUE TITLE
[ux] multiple doesn't clear user input on select with closeOnSelect=true

### ISSUE THREAD

**Issue by felixkiss** [cibernox/ember-power-select#450]
The same problem described in #314 still exists if you set `closeOnSelect=false`.

Failing integration test:

```js
test('it resets searchText after creating a new item', function(assert) {
  this.set('countries', [{name: 'Canada'}]);
  this.set('selectedCountry', null);

  this.render(hbs`
    {{#power-select-multiple
        options=countries
        selected=selectedCountry
        onchange=(action (mut selectedCountry))
        closeOnSelect=false as |country|
    }}
      {{country.name}}
    {{/power-select-multiple}}
  `);

  clickTrigger();
  Ember.run(() => typeInSearch('Foo Bar'));
  nativeMouseUp('.ember-power-select-option:eq(0)');

  Ember.run(() => assert.equal(
    this.$('.ember-power-select-trigger-multiple-input').val(),
    '',
    'search field should be cleared'
  ));
});
```

Additionally, `closeOnSelect` is not in the [API reference](http://www.ember-power-select.com/docs/api-reference) and should be added.

**Comment by cibernox** [comment]
@felixkiss Actually the search is not cleared when an element is selected, but when the component it's closed, so it's expected to me that when `closeOnSelect` is false, the search is not cleared.

I think that clear the search when the component is closed is more expected than doing that when a value is selected. 
Specially in multiple selects is likely that a user wants to perform a search and then select several results. Closing after the first one is selected would make that use case more awkward. 

I think that you can handle that more easily in the `onchange` action doing:

```js
actions: {
  didSelect(value, select) {
    this.set('selected', value);
    select.actions.search(''); // search an empty string.
  }
}
```

Makes sense?

**Comment by felixkiss** [comment]
Sure. I just wanted to let you know that this is also the case in EPS, because at cibernox/ember-power-select-with-create#11 it did sound like you thought it was a regression related to ember-power-select-with-create.

**Comment by cibernox** [comment]
@felixkiss I'd say that when I answered thre I didn't notice the `closeOnSelect=false`.
