### ISSUE TITLE
Fastboot collision when running tests

### ISSUE THREAD

**Issue by davidlormor** [cibernox/ember-power-select#453]
Just forked the repo and ran the tests. Get the following error:
```
Build failed.
File: modules/ember-data/adapter.js
The Broccoli Plugin: [Babel] failed with:
ReferenceError: The plugin "babel-plugin-feature-flags" collides with another of the same name at PluginManager.validate (/Users/davidlormor/Development/GitHub/ember-power-select/node_modules/babel-core/lib/transformation/file/plugin-manager.js:159:13)
```
Seems like this is related to:
- https://github.com/emberjs/data/pull/4328
- https://github.com/emberjs/data/issues/4322

Sounds like the addition of fastboot may be causing the issue in Ember Data - running against canary seems to solve the issue.

**Comment by cibernox** [comment]
Closes by #454
