### ISSUE TITLE
Position:fixed and scrolling

### ISSUE THREAD

**Issue by basz** [cibernox/ember-power-select#456]
Hi,

I have a dropdown on a fixed element (header). Whenever the dropdown opens and one scrolls the body there a visual problem. The opened dropdown scroll with the page and seems to be updated by a scroll event after a small delay.

On iOS no redraw is performed (no scroll events?)

Is this a know issue? Or am I making a mistake somehow?

**Comment by cibernox** [comment]
No, that's no mistake. The position is calculated with every scroll event but it never matches perfectly the scroll speed (although in the latest betas I've improved the responsiveness and the delay is smaller).

I wasn't aware of this not working in iOS.

For dropdowns inside fixed headers I recommend you try to add `renderInPlace=true`. That way the dropdown will inside the fixed header and no repositions need to happen.

Let me know if this helps.

**Comment by basz** [comment]
yes that (`renderInPlace=true`) helps very much! thank you
