### ISSUE TITLE
best practice - date-picker select has no options data

### ISSUE THREAD

**Issue by BryanCrotaz** [cibernox/ember-power-select#459]
When using power-select as a date-picker, the options component doesn't need any input
However because the options data is empty, it doesn't display the options component.

What's best practice here?

**Comment by BryanCrotaz** [comment]
how about if `options===undefined` and there is an `optionsComponent` then it is used in preference to the `else` block?

**Comment by BryanCrotaz** [comment]
Then a date picker would be as simple as:
```
{{#power-select
  selected=startDate
  optionsComponent='power-select-date-options' 
  beforeOptionsComponent=null
  allowClear=true 
  placeholder="Start from today"
  onchange=(action (mut startDate)) 
  as |date|}}
    Start from {{moment-format date 'ddd Do MMM YYYY'}}
{{/power-select}}
```
```
// power-select-date-options.hbs
{{eui-calendar on-select=(action select.actions.choose)}}
```

**Comment by cibernox** [comment]
Closing during issue triage.
