### ISSUE TITLE
Allow noMatchesMessage to be an action

### ISSUE THREAD

**Issue by karellm** [cibernox/ember-power-select#460]
With Selectize, if you have a multiple select supporting adding new element, you get a message that looks like: 

![](https://s3.amazonaws.com/f.cl.ly/items/3y1L0h3O2s293E13133t/Image%202016-04-19%20at%206.35.25%20PM.png?v=0af0b192)

Are you interested in providing a way to do that with power-select?

**Comment by cibernox** [comment]
Not in the core, but check https://github.com/cibernox/ember-power-select-with-create

**Comment by karellm** [comment]
@cibernox Would you mind making `noMatchesMessage` html safe? If I put html in it, it doesn't render. (I can't reproduce the bold effect above).

**Comment by cibernox** [comment]
If you pass a safeString I think it should work already.

**Comment by karellm** [comment]
One of these day when I shouldn't be coding. Thanks for the great support as usual!
