### ISSUE TITLE
Support for custom attributes

### ISSUE THREAD

**Issue by mangatinanda** [cibernox/ember-power-select#463]
In our application we are using `data-test-id` attribute to select the elements in tests instead of css class names. We have reopened the Ember.Component class and added `attributeBindings: ['data-test-id']` so that the attribute can be applied to all components. It is not working for power-select component.

We tried extending power-select and adding `attributeBindings: ['data-test-id']`, but still not working.

Any suggestions?

**Comment by ultimatemonty** [comment]
@mangatinanda did you ever find a solution for this? we have a similar need

**Comment by cibernox** [comment]
In 0.10.10 you can use the same `Reopen` trick you have to do to bind `data-*` to `Ember.LinkComponent`, but that won't work in 1.0.0 (which you shouldn't use yet, it is broken).

I'm on holidays but I should document how do that once I'm back. For the time being, a dummy class is the simplest thing to do.

**Comment by ultimatemonty** [comment]
thanks @cibernox will give that a whirl! enjoy your holidays!

**Comment by yuriyk** [comment]
@cibernox does `Reopen` allow now to add custom `data-` attributes?

**Comment by cibernox** [comment]
probably, yes. You probably want to reopen or reextend the trigger component tho.

**Comment by yuriyk** [comment]
yes, `Reopen` allows to add custom attributes:
```
import EPSM from "ember-power-select/components/power-select-multiple";
EPSM.reopen({
    attributeBindings: ["dataAutomate:data-automate"]
});
```
thank you, @cibernox
