### ISSUE TITLE
Freezes page if power select is first input in a liquid-fire modal

### ISSUE THREAD

**Issue by mukk85** [cibernox/ember-power-select#469]
It seems to be in an infinite loop in the focus function. I have worked around it by adding an input in a hidden div before it. I also ran into a case where I could not get the search field focused when inside the modal, but do not have a way to reliably reproduce.

**Comment by cibernox** [comment]
Are you in the latest version? Browser?

**Comment by mukk85** [comment]
Chrome, 0.10.0-beta.13

**Comment by cibernox** [comment]
There is a 2 versions but I don't think that anything changed there lately. That is hard to track without an example. Does it happen in the single or multiple select?

**Comment by mukk85** [comment]
Single, but I have not tried multiple.

**Comment by davidgovea** [comment]
Experiencing the same problem - it's a weird one! Thanks for the workaround @mukk85 

Chrome `Version 50.0.2661.102 (64-bit)` - Linux

```
DEBUG: Ember      : 1.13.13  
DEBUG: Ember Data : 1.13.16  
DEBUG: jQuery     : 2.2.3
```

```
    "ember-power-select": "0.9.2",
    "liquid-fire": "^0.23.0",
```
I'll throw together an example soon too

**Comment by cibernox** [comment]
@davidgovea First try the latest version. I suspect that whatever the problem is, it probably was solved a while ago because nobody else complained.

**Comment by boydkr** [comment]
I just opened an issue with `liquid-fire` that seems possibly related.  Liquid Fire modals will steal focus from anything that is outside of the modal:
https://github.com/ember-animation/liquid-fire/issues/460

**Comment by cibernox** [comment]
I see. In the meanwhile then, you can use `renderInPlace=true` to make sure the dropdown is rendered inside the modal.

**Comment by mukk85** [comment]
setting renderInPlace=true has fixed my issues. Is there a reason that is not the default behaviour?

**Comment by cibernox** [comment]
@mukk85 Yes, because render the dropdown in the root of the body is a much safer default because it's not constrained by overflow rules.

**Comment by mukk85** [comment]
Makes sense. Thanks for the fix!
