### ISSUE TITLE
searchField and matcher incompatibility

### ISSUE THREAD

**Issue by karellm** [cibernox/ember-power-select#473]
Hey,

I have a `power-select-multiple` of people of the form `{name, email}`. If I don't set the `searchField` and hit backspace, I get `Assertion Failed: `{{power-select-multiple}}` requires a 'searchField' when the options are not strings to remove options using backspace`. But when I set `searchField="email"`, then the matcher mis-behaves:

```js
recipientsSearchMatcher(user, term) {
  // I expect user to be the object {name, email}, but it is only the email
}
```

I run `0.10.1`.

Is that an expected behaviour or am I missing something? I would personally that the backspace doesn't throw an exception, it is fine to remove the item altogether without entering edit mode. If that's not an option, I would expect the matcher to still get the object and not just the email.

**Comment by cibernox** [comment]
No, seems like a bug. I will be on holidays until the 4th, but I'll check it later.

**Comment by cibernox** [comment]
If you can find a fix yourself, I should be able to merge from the phone :D
