### ISSUE TITLE
Long option name with "allowClear=true" overlaps the clear button

### ISSUE THREAD

**Issue by 12hys** [cibernox/ember-power-select#475]
Like the title says.

Screenshot:
![screen shot 2016-04-28 at 11 59 06 am](https://cloud.githubusercontent.com/assets/4165861/14892442/c30988f0-0d38-11e6-9bd4-3452f71d42c7.png)

When allowing the selected option to be cleared, the eliding needs to happen before the clear button. On version 0.10.0-beta.12.

Edit: Updated to 0.10.2 and it's still an issue.

**Comment by mschwenk** [comment]
Hey @12hys, 
you could easily change this within your CSS file. For example: 
`.ember-power-select-trigger {
  padding-right: 50px; //or any other value that would fit your needs.
}`

**Comment by cibernox** [comment]
That said, maybe the trigger should have a modifier class `--allow-clear` when that option is truthy and have a bigger padding by default.

I'll flag this issue as a bug.
