### ISSUE TITLE
Autopopulate CSP headers to mark images secure?

### ISSUE THREAD

**Issue by cibernox** [cibernox/ember-power-select#48]
An alternative would be a triangle with css.

**Comment by miguelcobain** [comment]
That is how bootstrap does it.

A sex, 16/10/2015, 10:05, Miguel Camba <notifications@github.com> escreveu:

**Comment by cibernox** [comment]
I guess that is simpler. But I did it with svg just to try one technique. Also at the moment the triangle is a background image while I want to make it a `::after` pseudo element to be able to animate it.

**Comment by sandstrom** [comment]
A proposed change to ember-cli will make CSP-handling in Ember addons easier:
https://github.com/ember-cli/rfcs/pull/22

**Comment by cibernox** [comment]
Actually I'd say that this is not an issue anymore. EPS used to have inlined SVG in the stylesheets for the triangle, but not it's just done with borders. 

There is nothing to customize in the consuming app.
