### ISSUE TITLE
em-based width calculation is not reliable

### ISSUE THREAD

**Issue by karellm** [cibernox/ember-power-select#483]
It looks like the width of the `.ember-power-select-trigger-multiple-input` input is calculated from the length of its value. This is not reliable as you can see here:

![](https://s3.amazonaws.com/f.cl.ly/items/0n0k0K2b0N0A3Y313Z3K/Screen%20Recording%202016-05-04%20at%2010.09%20AM.gif?v=9ba79dd4)

In the recording, narrow letter work ok, while wide letters cause the input to be too small. Is there a reason why every letter adds `.5em` to the width? With webfonts, there is no correlation between a letter width and ems that I know of.

**Comment by cibernox** [comment]
@karellm I know that it's not reliable, but is the closest aproximation I could find to make this work in browsers without flexbox support.
If the text is a _real word_ chances are that long and short letters are going to be evenly distributes and this will work most of the time. 
I thought about using the classical trick of using an offscreen canvas to measure the width of the text, but seemed overkill. Any other idea?

**Comment by karellm** [comment]
What I can say is that it doesn't work for our use case. We type emails in and everyone in our team hit that issue. I wouldn't rely on the expectation the distribution will even out.

Flexbox was my first thought. Is there a reason you don't want to use it? If you don't want flexbox, offscreen calculation is the only solution I can think of. I wouldn't consider it overkill though, the UX is pretty bad right now with the letters jumping.

**Comment by cibernox** [comment]
I'll try if I can do JS feature detection to know if the browser supports flexbox, and if it does, don't do any width calculation at all. Flexbox just will take care of the rest.

**Comment by karellm** [comment]
@cibernox Let me know if you want help on this. It is quite important for our application. Thanks!

**Comment by cibernox** [comment]
Can you check the PR #499 

After some experimentation, seems to be the only option that works back to IE9

**Comment by cibernox** [comment]
@karellm I've closed #499 in favour of #502, which I think it will be a simpler solution.

Check it out. I still have to check why tests are failing, but seems to work like a charm.

**Comment by karellm** [comment]
@cibernox For some reason, I updated to `0.10.6` and the `selected` isn't picked up anymore, so the input is alway `100%` and goes on a [new line](https://s3.amazonaws.com/f.cl.ly/items/0j3S381a2u0G2N1q370M/Image%202016-05-13%20at%2010.43.01%20AM.png?v=e9271557). When I refresh (so selected has a length), the calculation isn't happening, it is stuck on `25px`.

Did you successfully test the change?

**Comment by cibernox** [comment]
I deployed it (http://www.ember-power-select.com/docs/multiple-selection) and seems to work

**Comment by cibernox** [comment]
@karellm I think I know why it it failed. Install 0.10.7

**Comment by karellm** [comment]
I confirm that the dependency is now loaded and the fix working. Thanks for the prompt and awesome support, as always 👍
