### ISSUE TITLE
power select dropdown isn't working inside each element

### ISSUE THREAD

**Issue by adhithyaraja** [cibernox/ember-power-select#485]
``  {{#each listofObject as |object|}}
{{#power-select options=object.ListValues selected=selectedListValues
                   placeholder="Select a Type..." searchEnabled=false 
                   onchange=(action (mut selectedListValues)) as |name| }}
                       {{name}}
    {{/power-select}}
    {{/each}}
``

options appearing as No results found. Am I missing something?

**Comment by cibernox** [comment]
EPS works inside `{{each}}`, so I'm pretty sure there is a typo or something dummy going on with your code. Maybe `object.ListValues` should be `object.listValues`?

**Comment by cibernox** [comment]
I'm closing this. Let me know if you have a reproducible example.
