### ISSUE TITLE
Can't select/close dropdown on IE9

### ISSUE THREAD

**Issue by cemarte** [cibernox/ember-power-select#486]
Hi,

I'm testing ember-power-select on IE9 and had some issues when trying to pick a value from the dropdown. Here are the steps I took trying to solve the problem so far:
First step is adding [html5-dataset.js](https://gist.github.com/brettz9/4093766) shim to ember app, which doesn't require changes to ember-power-select / basic-dropdown code.
Second step is disabling animation on basic-dropdown addon, which has a 'animationEnabled' attr that is not exposed by ember-power-select. This requires changing [power-select.hbs](https://github.com/cibernox/ember-power-select/blob/master/addon/templates/components/power-select-multiple.hbs) && [power-select-multiple.hbs](https://github.com/cibernox/ember-power-select/blob/master/addon/templates/components/power-select.hbs).

 Is it possible to expose this attribute on ember-power-select? Is there any other side effect I'm not aware of? 

Thanks

**Comment by cibernox** [comment]
@cemarte Hi. Yeah, some people reported issues with IE9 but I never gathered the time and will to investigate them, so this is much appreciated.

About the animations, animations should just be disabled in IE9, so that should be a PR to ember-basic-dropdown and won't need any work here.

About the dataset, I wasn't aware that doesn't work in IE9, but I think we can use jQuery for that (`$el.data('whatever')`) and avoid adding a polyfill.

**Comment by cemarte** [comment]
Thanks @cibernox. Correct if I'm wrong but I think basic-dropdown already has a animationEnabled flag. So to make it available on ember-power-select we just need to add a "animationEnabled=animationEnabled" in power-select.hbs. I tried it and it seems to do the trick. About dataset polyfill I agree with you. Thanks again.

**Comment by cibernox** [comment]
@cemarte Yes, ember-basic-dropdown has that flag enabled by default. What I mean is that it should be disabled if the browser doesn't support animations. Some sort of feature detection should be done in the addon to enable or disable it.

**Comment by cemarte** [comment]
That's what I was thinking, thank you. There's an [open pull request](https://github.com/cibernox/ember-basic-dropdown/pull/82) for basic-dropdown related to the same problem. Probably he found a better way to solve the issue, I tested it and it works. Is it good to merge?

I'll close this one then...

Thanks!

**Comment by cemarte** [comment]
Closing in favor of [PR 82](https://github.com/cibernox/ember-basic-dropdown/pull/82)
