### ISSUE TITLE
Adding to the list for single select and selecting the new item.

### ISSUE THREAD

**Issue by angelosarto** [cibernox/ember-power-select#487]
Following the [cookbook](http://www.ember-power-select.com/cookbook/create-custom-options) it was easy to see how the tag creator works.

However, if I change the code to #power-select (without multiple) I can't seem to make it work.
I changed the line 
`select.actions.choose(select.searchText);` to `select.actions.select(select.searchText);`
which I think is right for single select.  

The new item is added to the array, selected is set correctly, but the render component shows blank.

Is there a different action I should be calling, or is there a refresh or something that is needed?

**Comment by cibernox** [comment]
Check if https://github.com/cibernox/ember-power-select-with-create does what you want, and if not you can still check how it works and copy it.

**Comment by angelosarto** [comment]
I'll give that a try thanks
