### ISSUE TITLE
Dropdown not scrolling to selected option

### ISSUE THREAD

**Issue by jcbvm** [cibernox/ember-power-select#488]
I've upgraded from 0.9.1 to 0.10.3 and noticed that the selected option is not getting scrolled into the view anymore. I see that it is scrolling to the right position if I close the dropdown.

**Comment by cibernox** [comment]
Yes, I can reproduce it. I'm not sure how/when that happen. It is hard to add tests for scroll position, but I'll try.

**Comment by jcbvm** [comment]
from what I can see it's introduced in 0.10.0, version 0.9.2 is the latest where it's still working

**Comment by cibernox** [comment]
I think I have it. Hold on tight.

**Comment by cibernox** [comment]
@jcbvm This should be fixed in master, along with another long-standing bug related with scrolling that I never had the time to tacked until now.

**Comment by jcbvm** [comment]
Awesome, thanks for you help :+1:
