### ISSUE TITLE
Ember 2.0: Uncaught TypeError: _this2.matcher is not a function

### ISSUE THREAD

**Issue by srsgores** [cibernox/ember-power-select#49]
I get this when I click on the dropdown, when passing in data with Ember Data 2.0:

> Uncaught TypeError: _this2.matcher is not a functionmatcher @ base.js:139filterOptions @ group-utils.js:96refreshResults @ base.js:142onOpen @ base.js:71closureAction @ ember.debug.js:21946open @ ember-basic-dropdown.js:91toggle @ ember-basic-dropdown.js:78toggle @ ember-basic-dropdown.js:58closureAction @ ember.debug.js:21946

**Comment by srsgores** [comment]
I found the fix:

```
if (this.get('searchField')) {
      matcher = (option, text) => this.get("matcher")(get(option, this.get('searchField')), text);
    } else {
      matcher = (option, text) => this.get("matcher")(option, text);
    }
```

Notice I use ``get``, short for ``this.get()``, instead of trying to access the method directly from the class.

Want a PR?

**Comment by cibernox** [comment]
Hey, good catch. I think this one slipped in a recent refactor. Please go ahead with the PR.

I'm worry tests didn't catch that one.

**Comment by cibernox** [comment]
@srsgores Can you install the addon from master and check if it's fixed?

**Comment by cibernox** [comment]
@srsgores Can you confirm this is not an issue anymore?

**Comment by cibernox** [comment]
I'm closing this assuming that it's because you're on an version of Ember older that 1.13.9.

Let me know if it's not the case.
