### ISSUE TITLE
Options Component with button and Label

### ISSUE THREAD

**Issue by prasathsarath** [cibernox/ember-power-select#491]
I have optionsComponent set for a power select dropdown, where in that I have,

`<ul>
  {{#each options as |option index|}}
<li>
<label  {{action 'optionChosen'}}>{{option.name}}</label>
<button {{action 'triggerSomeAction'}}></button>
</li>
</ul>`

So, now If i click on the button(which is inside the option), that particular action is working, but when I click on the label, the default dropdown selection is not working

Also in the documentation, I could not find anything related to this.

Please help me with this

**Comment by cibernox** [comment]
@prasathsarath If you want the default behaviour to work, you need to do more work.

Typically the simplest thing to do if you want to create a custom `optionsComponent` is
0. Consider of you can achieve the same behaviour in a less involved way, like using the block you pass to EPS. If not, take the following steps.
1. Import the default component, and make your component extend from it.
2. Take inspiration from the default markup here: https://github.com/cibernox/ember-power-select/blob/master/addon/templates/components/power-select/options.hbs 
All those properties have a function. Particularly the one that makes click on options work is the `data-option-index="{{groupIndex}}{{index}}"` bit.

**Comment by prasathsarath** [comment]
Thanks @cibernox that really helped
