### ISSUE TITLE
Tests no longer pass in the browser

### ISSUE THREAD

**Issue by yethon** [cibernox/ember-power-select#492]
I wanted to revisit this PR [https://github.com/cibernox/ember-power-select/pull/472](https://github.com/cibernox/ember-power-select/pull/472) but noticed that some tests are no longer passing in the browser (chrome, safari and firefox).  I first noticed this on Friday and initially thought it must be due to some discrepancy in my fork, but I just confirmed it happens in the current repo.

I assume this is supposed to open the select so that it displays its options? [https://github.com/cibernox/ember-power-select/blob/master/test-support/helpers/ember-power-select.js#L64](https://github.com/cibernox/ember-power-select/blob/master/test-support/helpers/ember-power-select.js#L64)

![screen shot 2016-05-09 at 11 42 53 am](https://cloud.githubusercontent.com/assets/10037587/15119690/20cd5430-15e0-11e6-9df3-beee03a7f748.png)

Naturally, Phantom misleads you by being cool with it. 😃 
![screen shot 2016-05-09 at 12 21 09 pm](https://cloud.githubusercontent.com/assets/10037587/15119896/1272d2e2-15e1-11e6-86bc-bf6218e3fd49.png)

**Comment by cibernox** [comment]
Tests might fail in the browser because if the window is not focused, the focus event is not fired, that that affects a few tests. Afaik, this is not solvable, but if you run those failing tests one by one and take care of having the window focused during the process, they should pass.
