### ISSUE TITLE
Animation class not applied when `renderInPlace=true`

### ISSUE THREAD

**Issue by ludalex** [cibernox/ember-power-select#497]
Self explanatory.

**Comment by cibernox** [comment]
Is this still a bug?

**Comment by ludalex** [comment]
With which version of `ember-power-select`/`ember-basic-dropdown` am I supposed to test?

**Comment by cibernox** [comment]
The version of ember-basic-dropdown is automatic, so just install the latest 1.0.0-beta.X

**Comment by ludalex** [comment]
I confirm this is fixed.
