### ISSUE TITLE
Add option to debounce asynchronous searches

### ISSUE THREAD

**Issue by cibernox** [cibernox/ember-power-select#5]
Although in general i'm agains incrementing the API surface of the component, I think this is a reasonable addition.

It's possible to debounce searches by the user, but what would involve a double nested promise, while in the component side is trivial to implement.

Something on the line of `debounceSearch=200` (time in milliseconds)

**Comment by corrspt** [comment]
Hey @cibernox , how would I be able to use a debounce myself?

I've tried this a controller:

```javascript
searchForItem(term) {
    console.log(term);
    return this.store.findAll('welding-position');
  },

  actions: {
    searchTerm(term) {
      return Ember.run.debounce(this, 'searchForItem', { 'term': term }, 200);
    }
  }
```

The query is executed, but I don't see any results on the search results.
This is my template
```handlebars
{{#power-select search=(action 'searchTerm') selected=value onchange=(action (mut value))   multiple=true as |option|}}
    {{option.visualLabel}}
{{/power-select}}
```

**Comment by nightire** [comment]
@corrspt I think because `Ember.run.debounce` returns an array contains the timer info for use of cancelling, not the promise returned by debounced method call.

**Comment by corrspt** [comment]
@nightire Yeah, you're right about that, thanks for pitching in. Do you have an idea on how to use the debounce and return a promise that returns the colection the addon wants? I'd be happy to make a PR with an example to the documentation, but I don't know how to achieve this :)

**Comment by cibernox** [comment]
I've just added an [entry in the cookbook](http://www.ember-power-select.com/cookbook/debounce-searches) showing how to do this on the user's end, which only takes a couple extra lines of code.

I hope that helps understand promises + debounce.

**Comment by corrspt** [comment]
@cibernox Thank you :+1: :tophat:
