### ISSUE TITLE
Should run before SRI Integrity Generation

### ISSUE THREAD

**Issue by zacstewart** [cibernox/ember-power-select#503]
Similar to this issue: https://github.com/miguelcobain/ember-paper/issues/224

If this addon generates its assets after ember-cli-sri has run, the integrity hash is wrong and causes this error:

Failed to find a valid digest in the 'integrity' attribute for resource

**Comment by cibernox** [comment]
@zacstewart Mm.. and how is that order configured? On that subject, the addon is using the default blueprint that ember-cli uses for all addons.

**Comment by miguelcobain** [comment]
@cibernox the order is configured using a package.json property. See referenced PR in that issue (https://github.com/miguelcobain/ember-paper/pull/337).

**Comment by zacstewart** [comment]
It looks like you just declare the it comes before `ember-cli-sri`: https://github.com/miguelcobain/ember-paper/pull/337/files
