### ISSUE TITLE
`removeMultipleOption` test helper does not use `wait` helper

### ISSUE THREAD

**Issue by mupkoo** [cibernox/ember-power-select#507]
Not sure if this is intentional or not, (if it is, I am sorry for the issue) but the `removeMultipleOption` test helper does not trigger the `wait` helper.

The following example is not working, without triggering the `wait` helper manually.
Changing the tags is making an async request to reload a list of items.

```javascript
removeMultipleOption('[data-autoid="search-select"]', 'master');

// Its not working without this line
wait(); 

andThen(() => {
  expect('.ember-power-select-multiple-option').to.have.size(0);

  // Fails here
  expect('[data-autoid="item"]').to.have.size(3); 
});
```

Let me know if this is intentional and I can open a pull request.
Thank you

**Comment by cibernox** [comment]
No, it's not intentional. I would have thought that the `andThen` should be enough, but ¯\_(ツ)_/¯

Go ahead.
