### ISSUE TITLE
[a11y] Outstanding issues

### ISSUE THREAD

**Issue by cibernox** [cibernox/ember-power-select#509]
Taking the opportunity that the Global Accessibility Awareness Day provides, I'll document some outstanding issues that need some love in this component to work totally as expected.
### Make TAB (and SHIFT+TAB) work as expected when the searchbox is rendered in the root of the app

The default behaviour for the component in single-mode is to display a searchbox inside the content of the dropdown. See picture below.

<img width="362" alt="screen shot 0028-05-18 at 16 22 54" src="https://cloud.githubusercontent.com/assets/265339/15364625/0cdf6846-1d15-11e6-88df-37969d1322f3.png">

While this is very convenient and an approach that many other select-like components take, it carries some basic a11y challenge when the content is rendered in the root of the body, which is the default since its the safest choice to to not be constrained by overflow rules.

The problem is that input is focused, TAB and SHIFT+TAB don't work follow the natural order anymore.
Ideally, they the focus should jump to the first focusable element there is before or after _the trigger_ of the component. This problem doesn't exist if the search is disabled because the focus stays in the trigger.

I did some research and apparently there is no programatic way to instruct the browser to do this. I guess that some hand-rolled javascript will be needed.

**Disclaimer: This will be tricky to implement, so I'll be happy to pair on this if the codebase is a bit overwhelming**
### Multiple select. The buttons (crosses) to remove the selected items can't be focused and interacted with keyboard.

I also couldn't find a way to achieve this in a way that doesn't get in the middle of the user. I consider this less prioritary because at the end you can achieve the same result with backspace or by clicking/hit-enter on the option in the list that you want to "unselect", but might worth exploring it.

<img width="359" alt="screen shot 0028-05-18 at 16 34 18" src="https://cloud.githubusercontent.com/assets/265339/15364982/6bc22cc6-1d16-11e6-8422-151cde6f965b.png">
### General A11y audit of both multiple and single element.

Ditto.

**Comment by mupkoo** [comment]
Not sure if this should be part of this, but `power-select-multiple` bubbles the `enter` key event, unlike `power-select`, which does not. 

So if have the component inside a form and you have a "onsubmit" action, selecting a item in the dropdown via the enter key, will submit the form.

```htmlbars
<form {{ action "submit" on="submit" }}>
  {{#power-select-multiple...}}
  {{/power-select-multiple}}
  <buttont type="submit">Submit</button>
</form>
```

**Comment by cibernox** [comment]
I think that both should bubble it (unless the user himself stops the propagation). Can you provide a failing test?

**Comment by amirshakya2010** [comment]
I am facing the same issue. Can anyone give me solution for this :(

**Comment by cibernox** [comment]
Closing this in favour or more recent issues
