### ISSUE TITLE
Returning false within onclose doesn't prevent the component from closing

### ISSUE THREAD

**Issue by jeaxelrod** [cibernox/ember-power-select#511]
I'm using "0.10.0-beta.8"

**Comment by cibernox** [comment]
It should. Can you provide a reproducible example? There is even a test for ensuring this behaviour: https://github.com/cibernox/ember-power-select/blob/master/tests/integration/components/power-select/public-actions-test.js#L435-L464

**Comment by jeaxelrod** [comment]
hmmm I'll try. It seems to be working in the docs too. Not in the codebase I'm working on tho :(

**Comment by cibernox** [comment]
If you have shrinkwrap, check that it's not preventing ember-basic-dropdown to update. The latest version of is 0.11.7

**Comment by cibernox** [comment]
@jeaxelrod Can you confirm that this is working? I'll close this for now.

**Comment by jeaxelrod** [comment]
idk when i can revisit this :/. but when im working on this ill confirm and try to re-create if relevant.
