### ISSUE TITLE
Integrating smoke and mirrors

### ISSUE THREAD

**Issue by IAmJulianAcosta** [cibernox/ember-power-select#515]
Hi! I'm working in a project that probably will render thousand of elements in power-select and I want to know if is a possibility to integrate [smoke and mirrors](https://github.com/runspired/smoke-and-mirrors) vertical collection, to render only the visible elements.

**Comment by cibernox** [comment]
Yes, you can. I actually did a spike with ember-collection already: https://github.com/cibernox/ember-power-select-collection/ in one hour to check that is was possible.
@ghedamat at some point improved it but he hasn't had time to publish it.

If you do it and want to publish it, let me know it so I can list it here: http://www.ember-power-select.com/addons

**Comment by ghedamat** [comment]
@cibernox I'm sorry for the delay on this one, I'll try to find some time this week to PR your repo, but I'm not sure if the solution is worth sharing as I have to hack around https://github.com/emberjs/ember-collection/issues/115
