### ISSUE TITLE
Introduction to ember-power-select on The Ember Show at Global Ember Meetup

### ISSUE THREAD

**Issue by taras** [cibernox/ember-power-select#516]
Would you someone familiar with this library be interested in giving a lightning talk about this addon on The Ember Show? We're recording the next episode on June 11th followed by July 2nd. 

An introduction to <addon> talk is about 15 minutes long and covers the following:
- Why was this addon created?
- When should it be used?
- How does one get started?
- What should the person be aware of?

You can see some of the previously recorded introduction talks on [Global Ember Meetup Videos](https://www.embermeetup.com/videos?category=addon-introductions) page.

Would you be able to give this talk?

**Comment by cibernox** [comment]
Yes, I can prepare it, but the 11th of June I'll be on holidays, hopefully in a place with no computers whatsoever. I could do it in July I think.

**Comment by taras** [comment]
Do you want to double check if you can do July and let me know?

**Comment by cibernox** [comment]
If it's a 15 minutes talk, I'm sure I can do it.

**Comment by taras** [comment]
@cibernox yep, 15 minutes similar to the format that I described above.

**Comment by taras** [comment]
@cibernox we're going to move July 2nd event to July 9th because of Holidays in US. Does July 9th work for you?

**Comment by cibernox** [comment]
Yes, I don't have anything planed for that date.

2016-06-02 15:51 GMT+01:00 Taras Mankovski <notifications@github.com>:

**Comment by taras** [comment]
Great. Thank you 👍

**Comment by cibernox** [comment]
Talk given, issue closed
