### ISSUE TITLE
Trigger dropdown from js

### ISSUE THREAD

**Issue by Blackening999** [cibernox/ember-power-select#517]
Hello.

Great component, however, quite rigid.
How can I trigger dropdown from js?
I have custom placeholder with z-index > than trigger and I want to trigger dropdown openning by invoking the action. I haven't found any native thing like "dropdownOpened" which might simplify many things.

This isn't working btw:
```js
  triggerDropdown() {
      run(this, function() {
        this.$('.ember-basic-dropdown-trigger').mousedown();
      });
    },
```

**Comment by Blackening999** [comment]
pointer-events: none;
fixes the thing :)

**Comment by cibernox** [comment]
Yes, that is a simper solution. For the record, the problem with your code above is that you are using jQuery. jQuery event's are very bad citizens and do not trigger native event handlers (those added with `element.addEventListener('mousedown', fn)`.

The native event works.
```js
 triggerDropdown() {
      run(this, function() {
        $('.ember-basic-dropdown-trigger').get(0).dispatchEvent(new MouseEvent('mousedown')); 
      });
    },
```

**Comment by gabrielgrant** [comment]
@cibernox is this still the recommended way to trigger the opening of a power-select from an external ember event (eg clicking a button)?
