### ISSUE TITLE
Modifying search text in onKeyDown handler

### ISSUE THREAD

**Issue by Ramblurr** [cibernox/ember-power-select#525]
I'm writing an addition to ember-power-select (-with-create) that parses the search text and performs on the fly comma delimiting. When the user types "Foobar," it will automatically select or create "Foobar".

To achieve this I need to be able to reset the value of the input. The public API doesn't expose a way to change `searchText`. And using jquery to set the `val()` on the input directly is overriden by the call to `updateInput()`.

**Comment by cibernox** [comment]
Have you tried to use the `search` action with an empty string. IIRC that would clear the searchbox.

**Comment by Ramblurr** [comment]
That indeed works, I should have thought of that thanks.
