### ISSUE TITLE
Can't focus on search input in modal

### ISSUE THREAD

**Issue by boydkr** [cibernox/ember-power-select#526]
I'm using Liquid Fire modals in my app, and I tried adding a `power-select` inside the modal.

The search input box is not focusable inside the modal. I opened an issue in Liquid Fire, but I thought maybe someone here would have an idea of how to resolve the issue:

https://github.com/ember-animation/liquid-fire/issues/460

**Comment by cibernox** [comment]
@boydkr If liquid fire is being smart pants about stealing the focus of everything outside the modal, I guess that the solution you can use is to pass `renderInPlace=true` to the component so it is rendered inside the modal.

**Comment by boydkr** [comment]
Thanks, I'll give that a shot

**Comment by boydkr** [comment]
`renderInPlace=true` works well enough for now, Thanks!

**Comment by cluis13915** [comment]
Thanks @cibernox ! It worked for ember-boostrap's modal to.
