### ISSUE TITLE
Keep last-searched results as options

### ISSUE THREAD

**Issue by boydkr** [cibernox/ember-power-select#527]
I'm using the `search` function override, and it would be nice if the last results from the search appears in the dropdown list the next time the component was opened.

**Comment by cibernox** [comment]
You can do that too. The component can receive both `options` and a `search` action. The options is the initial set of results that is displayed when no search term is present. 

If your search action, besides of returning the a new set of results also updates the initial options, the last search results will be the initial results the next time the component is opened.

```js
actions: {
  performSearch(name) {
    return this.store.query('users', { name }).then(users => this.set('options', users));
  }
}
```

All this information is in the docs: http://www.ember-power-select.com/docs/custom-search-action
