### ISSUE TITLE
Set placeholder text in trigger

### ISSUE THREAD

**Issue by boydkr** [cibernox/ember-power-select#528]
The placeholder text for search is fine once the component is open, but I would like to put placeholder text in the closed component so the dropdown/search is more discoverable.

Is this already possible?  Is that a feature that could be added?

I would only want it to display if there was no default selected option.

**Comment by cibernox** [comment]
In the [API reference](http://www.ember-power-select.com/docs/api-reference) you have a list of all the options. I believe that you are using `searchPlaceholder` when you want to use `placeholder.`

**Comment by boydkr** [comment]
Aha, thanks
