### ISSUE TITLE
status icon gets rendered outside the drop-down box

### ISSUE THREAD

**Issue by holandes22** [cibernox/ember-power-select#539]
Hi,

The status icon of the drop-down box gets is placed outside the box. This happens with the 0.11.0-beta.0 and 1.0.0-alpha.0 versions in chrome/chromium/FF (tested only on Linux). 
To reproduce I simple created a new ember app and used the  first example from the docs. See the screenshots below.

![closed](https://cloud.githubusercontent.com/assets/510233/15884440/23148566-2d59-11e6-9450-4245f551920b.png)
![open](https://cloud.githubusercontent.com/assets/510233/15884439/23141874-2d59-11e6-99cd-27629176f176.png)

BTW, it also happens in the docs website:

![site](https://cloud.githubusercontent.com/assets/510233/15884438/23132f68-2d59-11e6-8e17-3a6c04dbf367.png)

**Comment by cibernox** [comment]
Thanks, good catch. I forgot a `position: relative` during the refactor. Fixed in master

**Comment by holandes22** [comment]
Awesome, tried to fiddle with the CSS myself but got nowhere.

Thank you for the quick response!
