### ISSUE TITLE
Missing `class` option {{power-select}}

### ISSUE THREAD

**Issue by zhujy8833** [cibernox/ember-power-select#541]
I noticed in in `1.0.0-alpha.1` version, even though I passed `class` option to `{{power-select}}` component, the class name is not added to the `.ember-basic-dropdown` container. 

I seems the option was there in 0.10.10: https://github.com/cibernox/ember-power-select/blob/v0.10.10/addon/templates/components/power-select.hbs#L7.

Is there a reason that option was removed? Or is there something else I need to add?

Thanks

**Comment by cibernox** [comment]
Yes, there is no class in `.ember-basic-dropdown` because there is no `.ember-basic-dropdown`. The component is not simper and doesn't require any wrapper, the trigger is right there.
Check the changelog: https://github.com/cibernox/ember-power-select/blob/master/CHANGELOG.md

**Comment by zhujy8833** [comment]
@cibernox Thanks for the explanation :-) I understand it makes the component simpler but it seems broke some styles in my project after upgrading to the alpha version since before we customize the "wrapper" by adding a class to it, and there are some styles around that specific class.

**Comment by 3-john-4** [comment]
It seems like the removal of the `class` option is now causing the [acceptance test helper](http://www.ember-power-select.com/docs/test-helpers) `selectChoose(cssPath, optionText)` to fail. I'm not sure what my `cssPath` should be since class can no longer be specified on the component. I'm only seeing this will single select, not multi-select since class can still be specified on multi-select.

**Comment by 3-john-4** [comment]
I had to wrap my `power-select` in a div with an id, and then use that id as my `cssPath` in the `select-choose("#someId", "optionText")` to get it to work.
```
      <div id="someId">
        {{#power-select
          ...
        {{/power-select}}
      </div>
```

**Comment by davewasmer** [comment]
@cibernox is the lack of ability to add a class to the top-level element here considered a `wontfix`? If not, would you be willing to reopen the issue?

**Comment by cibernox** [comment]
@davewasmer You can. Use `triggerClass="my-class"` and/or `dropdownClass="my-other-class"`

**Comment by davewasmer** [comment]
@cibernox - ah, my mistake. I was looking under the "Styles" section on the site. Would you be open to a PR to mention them there?

**Comment by cibernox** [comment]
All the options are listed in http://www.ember-power-select.com/docs/api-reference

I don't really think that the styles section is the best for this since that section is only about css/sass, while customizing class names is more related with templates.

**Comment by lukemelia** [comment]
FWIW, I looked in the Styles section for this before finding this issue.

**Comment by cibernox** [comment]
I guess that I should put at least a link from one section to another given that more people got confused.
