### ISSUE TITLE
Dropdown css broken in alpha

### ISSUE THREAD

**Issue by bitsoflogic** [cibernox/ember-power-select#544]
Hey, just a heads up that I did an `ember install ember-power-select` and npm picked up the 1.0 alpha in a new/clean Ember 2.5.0 project.  When clicking on the select dropdown, the dropdown would appear attached to the coords: 0,0 rather than the bottom of the select.  

Changing it back to v0.10.10 it works fine.

**Comment by sarus** [comment]
I'm having the same issue.  The dropdown list is not being positioned when using `1.0.0-alpha.1`

The list always appears at the top left of the screen.

Works fine for me on `v0.10.10`

**Comment by cibernox** [comment]
Yes, alpha broke a few days ago. I'll investigate when I'm back from my holidays. Use 0.10 for now

**Comment by cibernox** [comment]
@bitsoflogic @sarus I've released a new alpha that should be more polished now. Check it!

**Comment by sarus** [comment]
Awesome!  Thanks for your hard work on such an incredible component.
