### ISSUE TITLE
Cannot Access hasMany-Belongs To  Object  in #each loop

### ISSUE THREAD

**Issue by talhaobject90** [cibernox/ember-power-select#545]
I had a scenario where i use ember-cli-selectize for creating new orders for an inventory managment system.  As you can see in the screen shot , when i click "add new item" a new orderitem will be created to the "orders" records (where order has many orderitems) . And every orderitem Belongs to a product.  I needed to integrate ajax search with ember-power-select to search for products. (which is tough with ember-cli-selectize). But the problem is i couldn't set the selected product to the element in the loop. 

![orders](https://cloud.githubusercontent.com/assets/7547924/16002525/bd9101da-3175-11e6-9afd-7873d4926146.png)

The models have a relationship like this
```
//models/order.js.js
orderitems: DS.hasMany('orderitem' ,{embedded: 'always', async:true}),
```

```
//models/orderitems.js
 order: DS.belongsTo('order' ,{async:true}),
product: DS.belongsTo('product' ,{async:true}),
```
```
//models/product.js
itemcode: DS.attr('string'),
productname: DS.attr('string'),
```

```

// in Template
// This is the loop for orderitems 
    {{#each orderitems  as |orderitem|}}

// Currently i Use ember ember-selectize and the below code works , the selection parameter //automatically sets the selected product with the orderitem in the loop

    {{ember-selectize
                content=products
                optionValuePath="content.id"
                optionLabelPath="content.productname"
                selection=orderitem.product
                placeholder="Select a Product"
              }}


// my attempt was like this.
// Here the list is getting populated, but cannot set the product to orderitem

     {{#power-select
       search=(action "searchProduct")
       selected=selected
       onchange=(action "selectOrderitem" orderitem.id)
       as |repo|
     }}
     {{repo.attributes.productname}}
     {{/power-select}}

          {{/each}}


// in controller file
actions:{



// the ajax search function .It's working good
    searchProduct(term) {
              if (Ember.isBlank(term)) { return []; }
              const url = `/products?direction=asc&page=1&productname=${term}`;
              return this.get('ajax').request(url).then(json=>json.data);
            },

// attempt to manually trigger on change , 
    selectOrderitem( orderitemid , product){
       console.log(product);
// Console-Output: Object {id: "4", type: "products", relationships: Object, __ember1465812627710: "ember1116", __ember_meta__: Meta}


      console.log(orderitemid);
// Console-Output: 71

      var orderitem = this.store.findRecord('orderitem',orderitemid);
     orderitem.set('product', product);

// Console.-Output: 
ember.debug.js:16628 Uncaught Error: Assertion Failed: Cannot delegate set('product', [object Object]) to the 'content' property of object proxy <(subclass of Ember.ObjectProxy):ember1118>: its 'content' is undefined.

  },

// it create New Orderitem like this. I assign every Orderitem to order 1 and at last i correct the ordernumber properly
    addNewOrderItem:function(){
       var controller = this;
      var orderitem = controller.store.createRecord('orderitem', {
        quantity :1,
        total :'',
        poitemstatus :'',
        product :controller.get('products').get('firstObject'),
        order : controller.get('orders').get('firstObject'),
      });

      orderitem.save().then(function(){
        controller.get('orderitems').pushObject(orderitem);
      })
      });
    },

}
```

I dont know the way i am doing this is correct . May be there could be some easy solutions , Could any one help? Please comment if my question is not clear(and sorry for the infant code. i am a newbie to ember).

Thanks in advance

**Comment by snewcomer** [comment]
So `Cannot delegate set('product',` is saying that the object returned from `findRecord` is undefined.  

Here is the docs for `findRecord` which says it returns a promise.  http://emberjs.com/api/data/classes/DS.Store.html#method_findRecord

1.  From this, it seems you need to attach `.then` (just like your `orderitem.save()` below) on the end and call `set` in the callback.

2.  Then to visually see it, make sure the `{{repo.attributes.productname}}` is actually the property that should visually show after selection.  For example if `person` is a model, then `{{person.fullname}}` is what will show after selected.

No worries on being a newbie.  We all are :).  What I try to do when I think about submitting an issue is make sure my `issue` is potentially related to bugs/improvements to the project you are using and any other question that I suspect is something I caused will usually be put that on the ember slack channel. Ppl are REALLY helpful there.  http://emberjs.com/community/

Let us know if this solves your issue and remember close out the issue if it does!

**Comment by cibernox** [comment]
@snewcomer thanks for respond so many issues while I'm on holidays!
I'll keep 🚣 🏄 ☀️

**Comment by talhaobject90** [comment]
Sorry , this is not helping , can you give me any working examples of async-search with hasMany loop.
Give me some working codes , i think i can pick from there, I am closing this issue. Trying other plugins too.

Thanks

**Comment by talhaobject90** [comment]
A similar thread aroused in the [discussion platform](http://discuss.emberjs.com/t/ember-power-select-how-to-set-a-preselected-value-in-ember-power-select-custom-search-action/10853). 
I am reopening this as this could benefit some more people.

The best help could be some working examples, 

Thanks

**Comment by rinoldsimon** [comment]
The problem is in search action. Because it is returning regular json objects, and when assigning them with the (mut) action, it wont really change the reference, it will just rename existing object. So i tried querying the data using "store.query" method.

**Comment by talhaobject90** [comment]
Thanks brother ! It worked great

    {{#power-select
      search=(action "searchProduct")
      selected=orderitem.product.productname
      onchange=(action "selectOrderitem" orderitem)
      as |repo|
    }}
      {{repo.attributes.productname}}
    {{/power-select}}
  selectOrderitem( orderitem , selected){
    return this.store.findRecord('product', selected.id).then(function(product){
      orderitem.set('product',product);
    });
  },
  searchProduct(term) {
            if (Ember.isBlank(term)) { return []; }
            // return this.get('store').query('product', {productname: term});

            const url = `/products?direction=asc&page=1&productname=${term}`;
            return this.get('ajax').request(url).then(json=>json.data);
          },
