### ISSUE TITLE
Use with Stylus

### ISSUE THREAD

**Issue by danilovaz** [cibernox/ember-power-select#546]
How can I use this addon if I don't use SASS but use Stylus?

**Comment by snewcomer** [comment]
Sorry for my ignorance, but are you referring to customizing the power select or just simply using it?

I am sure you saw this page, but just wanted to put it out there just in case - 
http://www.ember-power-select.com/docs/styles

FYI I have never used Stylus.  If you are just trying to customize power selects, is it possible to try and find where these variables (https://github.com/cibernox/ember-power-select/blob/master/app/styles/ember-power-select/variables.scss) are used and target those class names by overriding them w/ Stylus?

**Comment by cibernox** [comment]
If you don't use Sass, EPS will just include de default styles precompiled to regular css. You don't have to do anything. With that you can't take advantage of Sass variables (obviously) but you can override the default styles just like you'd do if you include an externar css file.

Someone mentioned before interest to compile from Sass to Less and Sylus so everybody can take advatage of the variables, but so far nobody did any work on that.
