### ISSUE TITLE
using with ember validations

### ISSUE THREAD

**Issue by haldiggs** [cibernox/ember-power-select#547]
has anyone wired this drop down to respond to the ember validations library?
https://github.com/dockyard/ember-validations

**Comment by snewcomer** [comment]
@haldiggs I believe Ember-Power-Select is independent of any validation library.  Might just have to get a bit crafty with how you implement it.  I've used it w/ Ember-cp-validations and Ember-simple-validations.

If you put together an example, ppl would definitely be willing to help; esp on the Ember Slack channel.
http://emberjs.com/community/
