### ISSUE TITLE
Close dropdown event handler

### ISSUE THREAD

**Issue by supersabillon** [cibernox/ember-power-select#548]
Hello, thanks for this great addon. I'm using a custom options component were I have some form elements and a submit button. I would like to have a cancel button that closes the dropdown. Is there an event handler I could use?

**Comment by cibernox** [comment]
I'm on holidays, but on Monday I'll come up with an example. The cancel button is inside or outside the component?

**Comment by supersabillon** [comment]
thank you! It's inside the component.

**Comment by cibernox** [comment]
Try `<button onclick={{select.actions.close}}>Close</button>`

**Comment by cibernox** [comment]
@supersabillon did you try that? Every subcomponent of EPS has an object named `select` that is the public API of the component. That object contains actions you can use to control the component.

**Comment by supersabillon** [comment]
Hey @cibernox, yes just tried it and it worked! thanks!
