### ISSUE TITLE
Use the selected item when an external "search" button is pressed

### ISSUE THREAD

**Issue by terryroe** [cibernox/ember-power-select#549]
We have designed the EPS component to have a Search button alongside it.  We would like the selected item in the dropdown to be used when this external Search button is selected.  However, clicking on this external Search button causes a blur event, and then the dropdown closes and the entered text is cleared.  Is there a way to fire a search using an external button like this?  I can't seem to find a combination that works.

**Comment by terryroe** [comment]
Bump.

(We have a deadline and we need to make a decision whether the above will be possible or not.  Please respond soon, if you can.)

**Comment by cibernox** [comment]
Hi @terryroe. I've been in holidays until yesterday. I'll check this evening.

**Comment by terryroe** [comment]
Thanks Miguel.

**Comment by cibernox** [comment]
@terryroe Is the button in a sub-component or totally outside the component?

You can an any point prevent the component from closing implementing an `onclose=(action "foo")`  action that returns `false`. If it returns false, the component will remain open.

```js
actions: {
  foo(select, e) {
    if (e.target === theButton) {
      return false;
    }
  }
}
```

Then, that button can do whatever you need. If the button is outside the select, there is in the master branch a way of controlling the component from the outside.

```hbs
{{#power-select ... registerAPI=(action (mut selectRemoteController)) as |opt|}}
  {{opt}}
{{/power-select}}
```

Then, having a reference to the public API of the component, you can use it to control the component from the outside.

**Comment by terryroe** [comment]
Miguel,

We have a handler for `onclose` as you suggest.  I tried adding `return false;` as the only line in the handler and it doesn't prevent the list from closing.  Here's the code:
```
  onclose=(action 'handleClose')
...
    handleClose () {
      return false;
    },
```
I'd expect the dropdown to never close with this code, but it still always closes.

**Comment by cibernox** [comment]
It should remain open, unless you are on a very old version of the component.

**Comment by terryroe** [comment]
"ember-power-select": "0.10.0-beta.9",

**Comment by cibernox** [comment]
I can't recall when I added that, but I do have a test for that: https://github.com/cibernox/ember-power-select/blob/949ee42437a4996b36186b1004c694d1832da33a/tests/integration/components/power-select/public-actions-test.js#L336

**Comment by cibernox** [comment]
You probably want to update to 0.10.11 at least (or 1.0.0-alpha.2 if you feel more adventurous)

**Comment by terryroe** [comment]
Ah!  You're right!  (I swear I tested version 0.10.11, but I must have made a stupid mistake while testing it.)  Thank you so much for your help, Miguel!

**Comment by terryroe** [comment]
I was able to implement our solution after upgrading.  Thanks again for your help Miguel.
