### ISSUE TITLE
select objects in multiselect with search can be selected again

### ISSUE THREAD

**Issue by patricklx** [cibernox/ember-power-select#551]
When using ember-multi-select with search, an option that is already selected can be selected again.
Probably because the validation just compares the object, but on a new search the object is different.
My current workaround(?) is to check if the selected object exists in the search results and overwrite them with the selected ones. This becomes more complicated if initial options and initial values are added.
Is there another way to solve this? 
Would be good to have some examples of this use cases in the documentation:
- how to multiselect 
 - with objects 
 - initial values 
 - search 
 - options

and the objects for `options/inital values/search` come from different places e.g server

**Comment by cibernox** [comment]
Yes, it's because the object is the same. I was reluctant to add more API, but since this is not the first time someone ask something related with this, I might worth to add some sort of config option that determines how to compare objects. By default it would default to a simple equality check (`===`) but can be configured to compare some key (an ID by example).

**Comment by bambery** [comment]
My usecase was slightly more complicated, in that I didn't want already selected options appearing in the dropdown once they were selected, so my dropdown options is a computed property that subtracts selected items from the total list of dropdown items with Ember.Enumerable.filter. I suspect it's not terribly efficient, so if anyone else has other solutions to this problem, I'd be interested to see them.

**Comment by cibernox** [comment]
I feel inclined to think that this can be solved in user-land easily enough to not be on the core functionality.

By example, using `ember-composable-helpers`, it's actually very nice and expressive.

```hbs
{{#power-select-multiple 
  options=(without selectedOpts allOpts) 
  selected=selectedOpts 
  onchange=(action (mut selectedOpts)) as |opt|}}
  {{opt}}
{{/power-select-multiple}}
```

Having such simple ways of composing EPS with helpers, I'd rather not implement this in the component.

**Comment by cibernox** [comment]
I think I'm closing this. Extra documentation would be welcomed tho.
