### ISSUE TITLE
Alpha2: onkeydown doesn't seem to trigger on [a-z] keypresses

### ISSUE THREAD

**Issue by sarus** [cibernox/ember-power-select#555]
Tried out the latest alpha (`v1.0.0-alpha.2`) and noticed that `onkeydown` does not trigger when pressing any of the letter keys.  It does trigger when pressing `enter`, directional arrow keys and anything on the number pad.

Is this is an expected change of behavior?

**Comment by cibernox** [comment]
No, it's not expected. It is a bug.
