### ISSUE TITLE
Prevent mouse click from propagating when using checkbox inside selected option and search results

### ISSUE THREAD

**Issue by sarus** [cibernox/ember-power-select#562]
I wanted to add a checkbox to options and search results.  Something like this:

```
{{#power-select-multiple
  search=(action "searchChannels")
  selected=selectedChannels
  renderInPlace=true
  searchField="channelName"
  loadingMessage=channelLoadingMessage
  placeholder="Select Channels"
  onchange=(action (mut selectedChannels))
  as |channel term|
}}
<input type="checkbox" {{action 'subscribeToWriteChannel' channel bubbles=false}}>
<span class="channel-marker">#</span>{{channel.channelName}}
{{/power-select-multiple}}
```
![image](https://cloud.githubusercontent.com/assets/306319/16281073/9715e878-3890-11e6-9412-d8ddfa0c495b.png)

But clicking on the checkbox always triggers a click on the option itself which either causes it to chosen or causes the dropdown to appear.  I can't seem to prevent propagation of the mouse click if the user only clicks on the checkbox.

Any ideas on how this could be done or if it's even possible?

**Comment by cibernox** [comment]
Yes, I sounds doable. Probably the problem is that the options are selected on click, as you might first imagine, but on `mouseup` (if you wonder, that's not a whim, that is how real selects work, so I copied it).

If you want to prevent a selection, you need to prevent the propagation of the mouseup event.

```hbs
<input type="checkbox" onchange={{action 'subscribeToWriteChannel' channel}} onmouseup={{action "stopPropagation"}}>
```

(your need to implement the `stopPropagation` action)

**Comment by sarus** [comment]
Awesome!

```
<input type="checkbox" onchange={{action 'subscribeToWriteChannel' channel}}
       onmouseup={{action "stopPropagation"}}
       onmousedown={{action "stopPropagation"}}>
```

Added `stopPropagation` to `onmousedown` to prevent the dropdown from opening if you click on an option that has been selected already.  

Thanks!

**Comment by cibernox** [comment]
🎉
