### ISSUE TITLE
verticalPosition="above" is not applied if renderInPlace="true" is also set

### ISSUE THREAD

**Issue by yuriyk** [cibernox/ember-power-select#563]
Currently,  `renderInPlace="true"` option disables `verticalPosition="above"` option, and dropdown is still placed below the trigger.
Which workaround or fix would be the best so that I could have options list placed above trigger and rendered in place at the same time?

**Comment by cibernox** [comment]
I am aware of that limitation, but its not high in my priority list (just because there is other stuff to be tackled before). 

There is no workaround possible right now, other than not rendering in place. Why do you want to render there?

**Comment by yuriyk** [comment]
For writing tests exclusively. Having a list as a child element makes it possible for me to right unit tests: by referring to select wrapper I can than find amongst child elements a selected option.

**Comment by cibernox** [comment]
Given that only one select can be opened at the same time, you can just target the options without referencing any parent.

If it's for acceptance tests I'd advice your to use the `selectChoose` and `selectSearch` helpers provided by the addon.

I'll close this now since I am aware of the limitation, but I don't expect to tackle that one until 1.0 is finished.

**Comment by yuriyk** [comment]
Thank you! Issue resolved.

**Comment by vamsikaja** [comment]
@cibernox @yuriyk Is `verticalPosition=above` is not applied when `renderInPlace="true"` issue is fixed ? I had a power-select with renderInPlace="true" and is at the bottom of the page and when I clicked, I'm not able to see entire drop-down-content, So I wanted to use `verticalPosition=above` and Its is not positioning as I needed

**Comment by cibernox** [comment]
Not yet. Can you not render the content in place?

**Comment by vamsikaja** [comment]
No @cibernox, As it is positioned relative to root when we scroll it is fixed there only without moving along with the trigger
