### ISSUE TITLE
Rendering different template for selected options versus search list

### ISSUE THREAD

**Issue by sarus** [cibernox/ember-power-select#564]
Is it possible to render different things for the dropdown list versus when something is selected in a `power-select-multiple`?  In other words,  I'd like to change the display for items that are in the autocomplete search list versus items that have been selected and are in the options and it requires more than just CSS changes.  Right now it seems like both locations render the same thing.

For example, is there some built in way to accomplish something like this:

```
    {{#power-select-multiple
      options=names
      selected=name
      placeholder="Select some names..."
      onchange=(action (mut name))
      as |name|
    }}
      {{#if isSearchMode}}
             <input type="checkbox">
       {{/if}}
       {{name}}
    {{/power-select-multiple}}

**Comment by cibernox** [comment]
Use the `selectedItemComponent`. Check also http://www.ember-power-select.com/docs/architecture explaining the sub-components that you can use.
