### ISSUE TITLE
Helper not found

### ISSUE THREAD

**Issue by confuser** [cibernox/ember-power-select#565]
Using v1.0.0-alpha.5, with Ember 2.5.1

```
$ ember install ember-power-select
Installed packages for tooling via npm.
installing ember-power-select
  create app/styles/app.scss
Installed addon package.
```

However, getting the following error when attempting to use it `Error: Assertion Failed: A helper named 'power-select' could not be found`. I'm fairly new to ember, so not quite sure what I'm doing wrong. Hoping someone can point me in the right direction. Following the debounce search recipe example.

emblem template
```emblem
power-select search=(action 'search') selected=selected onchange=(action (mut selected)) as |player|
  li = player.name

```

controller (debounce search recipe)
```js
import Ember from 'ember'

const { run, isBlank, inject } = Ember

export default Ember.Controller.extend(
{ ajax: inject.service()
, actions:
  { search(term) {
        return new Ember.RSVP.Promise((resolve, reject) => {
          run.debounce(this, this._performSearch, term, resolve, reject, 600)
        })
      }
    }
  , _performSearch(term, resolve, reject) {
      if (isBlank(term)) return resolve([])

      this.get('ajax')
        .request(`http://localhost:58885/search/player?name=${term}&limit=10`)
        .then(json => resolve(json.results), reject)
    }
})
```

**Comment by cibernox** [comment]
My only guess is that there was a problem during installation. No other thing makes any sense. Is `ember-power-select` listed in the package.json?

**Comment by confuser** [comment]
It is indeed. It's also within node_modules as expected.

**Comment by cibernox** [comment]
Discarded that, it must be a problem with emblem. I've never used it now I know anyone using it.

**Comment by cibernox** [comment]
Can you try using it in plain handlebars and see if it works?

**Comment by confuser** [comment]
I've just generated a new project. Works as expected with handlebars. It does appear to be an issue with emblem.

**Comment by confuser** [comment]
For anyone else that comes across this issue. Updating to emblem 0.8.1 fixed this.
