### ISSUE TITLE
Drop down renders strangely - ember-wormhole failed to render into '#ember-basic-dropdown-wormhole' because the element is not in the DOM

### ISSUE THREAD

**Issue by jaredgalanis** [cibernox/ember-power-select#566]
I get this error message in the browser JS console when I try to use the example code for multiple select. The drop down appears, but separated from the select input and in a seemingly random part of the DOM.

`ember-wormhole failed to render into '#ember-basic-dropdown-wormhole' because the element is not in the DOM`

**Comment by cibernox** [comment]
Check the "Nothing is rendered when I click the select" in http://www.ember-power-select.com/docs/troubleshooting

Are you doing something custom with the `index.html` of your app or rendering it in a container other than the body?

**Comment by jaredgalanis** [comment]
Thanks @cibernox. Not sure I understand a connection to that section of the troubleshooting guide. I am using Thoughtbot's ember-cli-rails gem to share assets between a rails and ember project and the ember project is being inject into the rails layout, so I'm not sure that the ember index.html ember file is being rendered. That said, the ember app is being injected into the body of the rails layout.

**Comment by jaredgalanis** [comment]
@cibernox, I went through the troubleshooting guide and I now see what you were referring to. I manually added <div id="ember-basic-dropdown-wormhole"></div> to the application.hbs file and things are working as expected now. Thanks very much!!!

**Comment by cibernox** [comment]
@jaredgalanis Glad to hear. Were you doing something custom with the index.html or is `ember-cli-rails` the one that by default behaves differently? If so, it might worth edit the troubleshooting section to highlight that ember-cli-rails doesn't run the `content-for` hook and the user must add the destination div manually.

**Comment by jaredgalanis** [comment]
@cibernox, ember-cli-rails has two ways of mounting an ember app into a rails app. The option that I'm using (which is technically discouraged by the authors of ember-cli-rails) bypasses index.html and injects the ember app into the body of the rails layout. Not sure if you want to have the troubleshooting section to reflect this or not given that it is a discouraged practice.
