### ISSUE TITLE
Cannot read property 'actions' of undefined

### ISSUE THREAD

**Issue by Drujik** [cibernox/ember-power-select#579]
I'm new in Ember.
Everything works good in UI, but I can see this error in console.
That's what I did:
metric-bar-chart-frame.hbs (component): 
`{{#power-select selected=metricName
              options=metrices onchange=(action (mut metricName)) as |metric|}}
                    {{metric.name}}
              {{/power-select}}`

metric-bar-chart-frame.js (component):
`metricNameChanged: Ember.observer('metricName', function(){
    this.sendAction('chooseMetric', this.get('metricName'));
  })`

overview.hbs (template)
`{{pi-overview/metric-bar-chart-frame
          chooseMetric="chooseCurrentMetricName1"
          metrices=metrices}}`

overview.js (controller):
`actions:{
    chooseCurrentMetricName1(val){
      this.set('currentMetricName1', val);
    }
  }`

What I wanted to do is, onSelect to change some property in controller (to get some data from server), and when I select another value, I do get the expected result but I can see this error in console
'Cannot read property 'actions' of undefined'
![capture](https://cloud.githubusercontent.com/assets/3778760/16609464/0cade532-435d-11e6-9049-2aaf33692792.PNG)

Please advise

**Comment by Argun** [comment]
Encountered same error, how to resolve it?

**Comment by cibernox** [comment]
I don't know why the public API would be undefined. Can any of you provide a reproduction?

**Comment by xamoom-pali** [comment]
I could help explaining what happens in my case. This is how I use the component:
```
          {{#if restrictedUsersToChooseFrom}}
                {{#power-select
                options=restrictedUsersToChooseFrom
                searchEnabled=false allowClear=false
                onchange=(action 'assignUser') as |user|}}
                  {{user.username}}
                {{/power-select}}
          {{else}}
            No more users to choose from.
          {{/if}}
```

Action `assignUser()` action ads selected user to the array which `restrictedUsersToChooseFrom` depends on.
`restrictedUsersToChooseFrom` gets empty after all users have been assigned. The component is destroyed. This is the point where the error occurs.

**Comment by fogisland** [comment]
Got the same error too, however the functionality of the select is still fine.

**Comment by gpluta** [comment]
I had this same error while using 1.0.0-beta.4 version. After upgrading to beta.23 the error is gone. Perhaps this issue could be closed?

**Comment by cibernox** [comment]
Probably yes. Closing
