### ISSUE TITLE
Improve blueprint to append to existing app.scss

### ISSUE THREAD

**Issue by cibernox** [cibernox/ember-power-select#58]
At the moment the blueprint attempts to add an `app.scss` unconditionally, regardless of if the project uses sass or not.

A better solution would be to only do so if the user is a sass user (by detecting the presence of ember-cli-sass) and **append** a couple lines to the existing `app.scss` (or create it if not present).

**Comment by miguelcobain** [comment]
Similarly, once #57 is completed, we should detect presence of ember-cli-less and add an `app.less` with an import statement.
