### ISSUE TITLE
`Shift + Tab` is broken on Multi-Select

### ISSUE THREAD

**Issue by iheanyi** [cibernox/ember-power-select#580]
Whenever you try to `Shift + Tab` out of a multi-select, it gets stuck. Upon further inspection, it's because the `trigger` has a tabindex of `0` when it should be a tabindex of `-1`.

https://github.com/cibernox/ember-basic-dropdown/blob/master/addon/components/basic-dropdown/trigger.js#L23 - I've narrowed down the issue to this call to Basic Dropdown with no `tabindex` value set. What ends up happening is that it defaults to zero.

**Comment by cibernox** [comment]
I think that this has been fixed, can you confirm

**Comment by iheanyi** [comment]
Tested it on the site, it worked properly. Thanks for fixing!
