### ISSUE TITLE
.ember-basic-dropdown-content does not get positioned properly when ember is embedded app

### ISSUE THREAD

**Issue by curtisgr** [cibernox/ember-power-select#581]
It appears the position of the dropdown is relative to the window, but if you embedded ember into a page and bind to an element other than `<body>`, this seems to cause an issue where the dropdown is offset the same distance that the element you are binding to is offset from the window.

In other words, my ember app is binding to a div that appears on the page like 500px from the top and 50px from the left of the window and so when you click an ember power select element, the dropdown is 500px below that element and 50px left of where it should be.

**Comment by cibernox** [comment]
Can I get a minimum dummy as an example? It seems doable to "correct" the the positioning of the dropdown. I can tackle it next week the earliest.

All the positioning vodoo happens in https://github.com/cibernox/ember-basic-dropdown/ so I'm closing this issue to keep the tracker clean. If you can create an example, open an issue in the other repo.
