### ISSUE TITLE
Question: How can I select from drop down OR enter text manually 

### ISSUE THREAD

**Issue by danielspaniel** [cibernox/ember-power-select#583]
I am trying to figure out how to have a power select drop down with an input box available for freestyle text ( in case you don't see anything in the drop down you like ) 

Has anyone ever tried that? And made it work?

**Comment by corrspt** [comment]
Never tried, but if I had to try, I would probably start by using the `afterOptionsComponent` reference in the [API](http://www.ember-power-select.com/docs/api-reference) and create a component with the input.

Best of luck

**Comment by danielspaniel** [comment]
Hmm .. that was actually a good suggestion, though I went with the caveman approach. 

```hbs
    <input class="ro-number" value={{case.roNumber}} onchange={{action setRoNumber value="target.value"}}/>
    {{#power-select
      options=roNumbers
      selected=case.roNumber
      onchange=(action setRoNumber)
      as |roNumber|
    }}
      {{roNumber}}
    {{/power-select}}
```

Where I absolutely position the input of mine over the usual power select faux input trigger component.
