### ISSUE TITLE
afterOptionsComponent bug

### ISSUE THREAD

**Issue by shawjak3** [cibernox/ember-power-select#586]
I am having an issue with the `afterOptionsComponent` option on EPS. Here is my component, 

`{{#power-select
            placeholder="None"
            selected=deal.proposedCarrier
            options=deal.agency.carriers
            onchange=(action (mut deal.proposedCarrier))
            afterOptionsComponent=(component
              'before-options-button'
              isSingle=true
              text='Add Carrier'
              action=(action 'addCarrier' false))
          as |carrier|}}
            {{carrier.name}}
          {{/power-select}}`

It was previously using the `beforeOptionsComponent` option but the client wants this component to come after the list so I switched it to `afterOptionsComponent`. Anyway the bug I'm seeing in the console is this,

`Uncaught TypeError: Cannot read property 'on' of undefined`
`DEPRECATION: A property of <insurance@view:-outlet::ember478> was modified inside the didInsertElement hook. You should never change properties on components, services or models during didInsertElement because it causes significant performance degradation.`

It is complaining about this bit of code, `didInsertElement: function didInsertElement() {
      this._super.apply(this, arguments);
      this.focusInput();
      this.get('eventSender').on('focus', this, this.focusInput);
    },`

Any help would be appreciated, I may be missing something obvious as your has been very stable so far.

**Comment by cibernox** [comment]
The code you mention doesn't exist anymore, si I'd suggest you to try the latest version (1.0.0-beta.0) and see if it works.

There is a small number of breaking changes if you come from 0.10, mainly that the component is doesn't have an `.ember-power-select` wrapper around the trigger unless it's rendered in place, and the public API received by sub-components is now concentrated in one object.

Reopen this if the error is still present in 1.0.0

**Comment by shawjak3** [comment]
Thanks, upgrading solved the issue. And the heads up about the wrapper helps a lot.
