### ISSUE TITLE
Custom animation when tag is removed from multi-select

### ISSUE THREAD

**Issue by terryroe** [cibernox/ember-power-select#587]
We would like to fade out a tag when its close button is selected.  I can't seem to find a way to hook into the event lifecycle when a tag is removed.  I need to know which tag is being removed so I can apply the animation to it.  Is this possible to be notified when a particular tag is being removed?

Thanks, TR

**Comment by cibernox** [comment]
I see two ways of accomplishing this.

What I think it's simpler and enough for this use case, is to provide a `selectedItemComponent`. In multiple selects, this components is each one of the "pills" inside the trigger. Then, inside the `willDestroyElement` hook, you can animate the pill by creating a "clone", fade it out, and then remove it.

The second option would be to create your own custom `triggerComponent`. That gives you even more control, but seems overkill for this.

**Comment by terryroe** [comment]
Miguel,  We already have a custom `triggerComponent` and I was trying to figure out a way to accomplish the task using it.  Did you have some thoughts on how I might do it with this custom component?  I tried a few things and wasn't able find a way.  Do you think it would be the same type of thing where I'd have to create a clone element to use for the animation?  Thanks.

**Comment by cibernox** [comment]
Animate things entering is easy, but animate things fading out requires the clone trick. If you already have a custom trigger component and you have liquid-fire installed in your app, I don't think that it would be hard to use `{{#liquid-if}}` to fade-out the pills. Liquid fire already takes care of the "cleate a clone and fade it out" for you.

**Comment by terryroe** [comment]
Miguel, We aren't using liquid-fire and probably won't be adding it this close to release.  Is this the element I need to clone and fade out? 
```
    <li class="ember-power-select-multiple-option">
```
I'm 99% sure it is, but was just hoping you could quickly confirm so I'm not headed in the wrong direction.

**Comment by cibernox** [comment]
In that case I suggest you the approach in my first response: Render one component per selection in your custom trigger:

```hbs
{{#each select.selected as |opt idx|}}
  {{my-custom-pill class="ember-power-select-multiple-option" option=(readonly opt) select=(readonly select)}}
{{/each}}
```

Inside that component, use the `willDestroyElement` hook to create a clone, append it to the DOM, and then animate it out, and when the animation finishes, remove it completely.

```js
willDestroyElement() {
  this._super(...arguments);
  let list = this.element.parentNode;
  let clone = this.element.cloneNode(true);
  clone.style.transition = "opacity 0.3s"
  clone.style.opacity = 0;
  list.insertBefore(clone, this.element);
  Ember.run.later(function() {
    list.removeChild(clone);
  }, 300);
}
```

This was coded from memory, but something similar should work

**Comment by terryroe** [comment]
Thank you very much Miguel.  I'll give it a try.
