### ISSUE TITLE
Cannot read property 'dispatchEvent' of undefined in integration testing

### ISSUE THREAD

**Issue by kasunvp** [cibernox/ember-power-select#588]
This is due to this logic in ember-basic-dropdown here: https://github.com/cibernox/ember-basic-dropdown/blob/master/test-support/helpers/ember-basic-dropdown.js#L45 or here https://github.com/cibernox/ember-power-select/blob/fdea3c7bb78ea549d66a6ab593311afd72126f11/addon/components/power-select.js#L145

if you use `clickTrigger` in an integration test with the trigger '.my-trigger', the selector ember-basic-dropdown will look for is '.my-trigger .ember-power-select-trigger', but in the DOM both classes exist in the same element.

**Comment by kasunvp** [comment]
Or is it that we need to use the component class name as the `scope` for `clickTrigger`? Looks like it works that way.

**Comment by kasunvp** [comment]
Looks like it works fine if you use the selector class as the scope in clickTrigger. 
So closing this.

**Comment by Sinled** [comment]
@cibernox 
Have the same error in integration tests when specifying default options for `searchEnabled`
```js
export default EmberPowerSelect.extend({
  searchEnabled: false,
});
```
any ideas why this happening?

**Comment by cibernox** [comment]
@Sinled can you track it? The helper is trying to find the trigger and dispatch an event on it but it can't find it. Perhaps the selector is wrong?

**Comment by Sinled** [comment]
@cibernox it seems disabling search in `power-select` affects `power-select-multiple`, but only in one of my integration tests, 
if `searchEnabled: false` 
`power-select-multiple` renders without input `ember-power-select-trigger-multiple-input`
and `typeText` helper can not find corresponding helper

**Comment by AlekzZz** [comment]
I don't use `power-select-multiple` yet i get this error.

**Comment by cibernox** [comment]
@AlekzZz This basically means that the helper cannot find the trigger. Very recently (a few days ago) I've improved the test helpers to work when the given selector belongs to the trigger itself. Make sure you have the last version of ember-power-select and ember-basic-dropdown (0.22.4)

**Comment by AlekzZz** [comment]
@cibernox oh man, i just realized the problem... and it is my fault, I added `searchEnabled: false` by default but my tests were still doing `typeInSearch` in some cases... my bad sorry.
