### ISSUE TITLE
Multiple select placeholder when search is disabled

### ISSUE THREAD

**Issue by cibernox** [cibernox/ember-power-select#589]
At the moment, setting `searchEnabled=false` on multiple selects removes the input, and therefore also removes the placeholder.

The component should be capable of having a placeholder when the search is disabled.

Approaches:

1. Keep the search input when the component is disabled, but make it disabled. Seems the easiest approach. Not sure if it might have some problem with the sizing on the input.
2. Place some sort of span instead of the search input when the search is disabled and nothing is selected. Maybe it's a bit easy to style, although placeholders are not the number 1 feature people want to customize.

**Comment by cibernox** [comment]
@patricklx if you want to take a stab on this, be my guest.

**Comment by patricklx** [comment]
hi, okay. Working on it

**Comment by cibernox** [comment]
I still not sure of what is the best approach, so try and see how the first one works, and if it is problematic (styles or something) then try the second.

**Comment by Pasikonik** [comment]
any progress in this area?

**Comment by patricklx** [comment]
Hi, ah sorry...
I tried out both and the problem with the disabled input is that it's quite visible (gray background) and the "disabled" cursor shows when hovering.
Of course all can be changed with CSS, but just might go ahead with a span... which also needs a bit of styling.. but just to set the color.
