### ISSUE TITLE
Customize noMatchesMessage as separate component?

### ISSUE THREAD

**Issue by shijistar** [cibernox/ember-power-select#592]
From the documentation, I find it's allowed to customize a complex layout of `noMatchesMessage`, but it's pretty good if it's configurable via `noMatchesMessageComponent` or something else. With that I can create a standalone component and make it easy reusing everywhere, unless right now I have to copy&paste the `html` codes everywhere. 
The same thing to `loadingMessage` and `searchMessage` I think.

**Comment by cibernox** [comment]
I've considered that, but since there is no default behaviour that this component should implement for those, I thought that if someone wants to reuse the no-matches message they would do:

```hbs
{{#power-select ... as ||}}
  {{opt}}
{{else}}
  {{no-matches-component}}
{{/power-select}}
```

That gives you the same reusability, right?

**Comment by shijistar** [comment]
Yes, this exactly what I want. Thank you very much!

I'd prefer to use power select a little easier in my project. Some behaviors are quite similar in most scenarios since they are in a same project, targeting to same customer and business. I extended the class and provided some default values for some properties, and what's more you can see I also provided a default `onchange` handler to automatically set `value` property. Violate Ember's Data Down Actions Up (DDAU) philosophy, right? But it's really easy to use, and in most cases I just use it in a such simple way. ;-)

```js
import Ember from 'ember';
import PowerSelect from 'ember-power-select/components/power-select';
import observer from 'ember-metal/observer';

export default {
    name: 'init-power-select',
    initialize: function(app) {
        PowerSelect.reopen({
            valueField: "id",
            searchField: "name",
            value: null,
            loadingMessage: Locales.components.powerSelect.loadingMessage,
            noMatchesMessage: Locales.components.powerSelect.noMatchesMessage,
            searchMessage: Locales.components.powerSelect.searchMessage,
            searchPlaceholder: Locales.components.powerSelect.searchPlaceholder,
            init() {
                let self = this;
                self.set("onchange", function(selectedItem, publicAPI) {
                    self.set("selected", selectedItem);
                });

                let { selected, value, valueField } = this.getProperties("selected", "value", "valueField");
                if (selected && value === null) {
                    this.set("value", Ember.get(selected, valueField));
                } else if (value !== null && !selected) {
                    let options = this.get("options");
                    if (options) {
                        let selectedItem = options.find((item, index) => {
                            /* jshint eqeqeq:false */
                            return (Ember.get(item, valueField) == value);
                        });
                        if (selectedItem) {
                            this.set("selected", selectedItem);
                        }
                    }
                }

                this._super(...arguments);
            },
            _onSelected: observer("selected", function() {
                let { selected, valueField } = this.getProperties("selected", "valueField");
                this.set("value", Ember.get(selected, valueField));
            }),
        });
    }
};
```

**Comment by cibernox** [comment]
In this case, my advice is to compose the component instead of reopening it. Mostly because I the SemVersion I try to follow offers guarantees over the public API but not about the internals, so this kind of approach might break at any moment.

My approach would be to create a component named `my-select` that internally does:

```hbs
{{#if (hasBlock "inverse")}}
  {{#power-select options=options selected=selected onchange=(action "onChange") ...otherOptions as |opt select|}}
    {{yield opt select}}
  {{else}}
    {{yield to="inverse"}}
  {{/power-select}}
{{else}}
  {{#power-select options=options selected=selected onchange=(action "onChange") ...otherOptions as |opt select|}}
    {{yield opt select}}
  {{/power-select}}
{{/if}}
```

The `onChange` option can automatically do the thing you are achieving with this reopening but without using private API. You can also set default values even for the inverse block.

I use this approach myself in the multiple-select (https://github.com/cibernox/ember-power-select/blob/master/addon/templates/components/power-select-multiple.hbs) to avoid using private-apis and dogfood the component.
