### ISSUE TITLE
onchange with mut and undefined value don't work

### ISSUE THREAD

**Issue by kaermorchen** [cibernox/ember-power-select#597]
Hello.

I have below code:
```
{{#power-select
  options=statuses
  selected=(find-by statuses 'id' status)
  onchange=(action (mut status) value="id")
  searchField="name"
  disabled=(not statuses.length)
  placeholder="Select status"
  allowClear=true
  as |status|}}
    {{status.name}}
{{/power-select}}
```

When I push clear button, I catch error: `Uncaught Error: Assertion Failed: Cannot call get with 'id' on an undefined object.`

How right update this code to work without error?

I have ember-power-select version v0.10.0-beta.13.

**Comment by cibernox** [comment]
I'm afraid that `(action ... value="id")` doesn't support to extract values from null/undefined. So probably in this case you need to implement an action that is a bit smarter yourself:

```hbs
{{#power-select
  options=statuses
  selected=(find-by statuses 'id' status)
  onchange=(action "updateStatus")
  searchField="name"
  disabled=(not statuses.length)
  placeholder="Select status"
  allowClear=true
  as |status|}}
    {{status.name}}
{{/power-select}}
```

```js
actions: {
  updateStatus(status) {
    this.set('status', status && get(status, 'id');
  }
}
```

**Comment by cibernox** [comment]
Either way, this not specific to EPS, so I'm closing this issue 😃
