### ISSUE TITLE
[DOC] Proofread documentation

### ISSUE THREAD

**Issue by cibernox** [cibernox/ember-power-select#6]
- [ ] Overview
- [ ] Installation
- [ ] How to use it
- [ ] Action handling
- [ ] Groups
- [ ] Multiple selection
- [ ] The trigger
- [ ] The list
- [ ] The search
- [ ] Styles
- [ ] Asynchronous search

**Comment by corrspt** [comment]
Where's the documentation located? I've started reading through the docs (with the intent of trying it out). And I found a few typos in the documentation, I think I can contribute with a little help in this department, but I can't seem to find the files for the documentation.

**Comment by miguelcobain** [comment]
@corrspt The docs are the dummy app in the tests folder in this repo.
It's a regular ember app.

**Comment by corrspt** [comment]
Thanks @miguelcobain !

**Comment by corrspt** [comment]
I've made a PR (#105). Where I reviewed (to the best of my abilities, I'm not a native speaker) most of the documentation and examples.

**Comment by cibernox** [comment]
After that PR this can be considered closed. It can always be better, but at least someone has reviewed it cover to cover.
