### ISSUE TITLE
Extending ember-power-select with an autosuggester input behaviour?

### ISSUE THREAD

**Issue by monovertex** [cibernox/ember-power-select#600]
This is more of a question, really.

I want to create an input field that provides suggestions in an ember-power-select dropdown based on what you're writing, and you can either select one of the options provided and it will autofill it in the field, or just leave whatever you wrote in the field.

Basically, it would be like the multiple selection power select, but without the multiple aspect and preferably without the tag styling.

I don't have enough experience with this plugin yet, so I'm wondering if this idea would be compatible with the plugin in the first place. If yes, any tips or directions I should head into to achieve this?

Thanks!

**Comment by cibernox** [comment]
There is a package that you might be interested in that does that: https://github.com/cibernox/ember-power-select-typeahead

However it's not up to date and doesn't work with 1.0.0 or ember-power-select.

I'm working *right now* on making the public API of the component immutable (https://github.com/cibernox/ember-basic-dropdown/pull/120) so this kind of patterns are easier to implement, and after that I'll fix the typeahead repo.

For the record, the main problem with this component I found is the dual nature of select/text-input. For selects, if your options are an array of users, the expected value when you select one is one item of that collection. However, if you just type a string and focus some other component, the value you care about is a string, not a user (what you do with that string is not the business of the component). 

I haven't found a single way of handing this duality that makes everybody happy, so I've decided to do nothing and keep the input events and the change event separated and let the user decide which one to use. If you go ahead and decide to implement this yourself, I lean towards having a select that requires the user to use both the `oninput` and `onchange` actions.

```hbs
{{#power-select 
  options=users 
  selected=selectedUser 
  triggerComponent="customized-trigger-with-only-an-input"
  beforeOptionsComponent=null
  oninput=(action (mut username)) 
  onchange=(action "selectUser") as |usr|}}
  {{usr.name}}
{{/power-select}}
```

```js
actions: {
  selectUser(user) {
    this.setProperties({ selectedUser: user, username: null });
  }
}
```

**Comment by monovertex** [comment]
Thanks you for the input.

After discussing with my team, we will probably extend ember-power-select to 1. place the input over the trigger button, in the dropdown, so the user doesn't see those as separate (it's an UI improvement required in our application) and 2. always select an instance, not a meaningless string. 

We will achieve no. 2 by providing the user with a "Create" control, so when the user writes something and none of the provided options are what they want, they can just create a new instance. This will happen via a modal, most probably, because our models generally require more than a name to be configured. This will not allow a duality in our selects, so conceptually it should be all good.

Thanks again and keep up the great work you're doing with this project!

**Comment by cibernox** [comment]
In that case check ember-power-select-with-create.
