### ISSUE TITLE
Q: latest stable 0.10.11 with ember 2.7.0

### ISSUE THREAD

**Issue by jankopriva** [cibernox/ember-power-select#603]
Hi,  I have a question regarding the version in the title. In DOM, I can see that the attribute that appears during hovering over the power select items is aria-current and not aria-current="true".
This breaks the styles and no item background is displayed.

On ember 2.6.1 it worked all right. Is this addressed in some of the beta releases?
Thanks.

**Comment by cibernox** [comment]
yes, there was a breaking change in Ember where aria-* attributes started to be treated as properties when its value was `true`. It is fixed in the latest beta.

**Comment by Kilowhisky** [comment]
It appears that the change made here https://github.com/cibernox/ember-power-select/commit/7c7a4588e712dd9b0805cd45b07af86b99f7c6b7  is also required for ember 2.7 as its breaking for me now. 

Is it safe to go to the latest beta? I can't find anything that says what is expected to change from 0.10.11 to 1.0.0.

**Comment by cibernox** [comment]
@Kilowhisky The Changelog is pretty exhaustive, any change will be there, and those that are breaking or potentially breaking are labeled as such.

The only one that has a high chance of bite people is:

- The trigger no longer has a wrapper with `.ember-power-select` around it (except if it's rendered  in-place), so if you customized styles by targeting that class you may need to change the selector in your CSS.


If you are replacing any of the sub-component with your own, the attributes have changed significantly, but if you aren't probably the one above is the only one.
