### ISSUE TITLE
Issues with ember 2.7

### ISSUE THREAD

**Issue by jcbvm** [cibernox/ember-power-select#607]
I've upgraded my project to Ember 2.7, but there seems to be some problems with this addon.

From what I can see things go wrong with `this.elementId` in `trigger.js`:

    var optionsList = document.getElementById(this.elementId + '-ember-power-select-multiple-options');

Which results in `-ember-power-select-multiple-options`.

Also the selected option is no longer having the `aria-selected` attribute, this might be the same problem.

Affected version: 0.10.11
Might be related to: https://github.com/emberjs/ember.js/issues/13627

**Comment by cibernox** [comment]
You need to update to 1.0.0. There was a change in ember (that I personally considered breaking but it wasn't treated as such) that broke many `aria-*` attributes

**Comment by jcbvm** [comment]
Ah ok, thanks, will try 1.0.0 and otherwise will downgrade ember till 1.0.0 is released

**Comment by cibernox** [comment]
The beta is very stable, I don't expect it to change much. If you are not creating your customized triggerComponent/optionsComponent you probably won't see any difference.

**Comment by jcbvm** [comment]
Ok thanks, will close this issue for now then.
