### ISSUE TITLE
would like an onclick option; onchange not doing what I need

### ISSUE THREAD

**Issue by 3-john-4** [cibernox/ember-power-select#609]
I'd like to be able to trigger an action on the currently selected power-select option, basically an `onclick()`. If a power-select option was previously selected on a page, then when I leave that page and then return, the option that was the last selected remains selected. However, when I click on that option the onchange is not triggered, for obvious reasons because the selection has not changed. I have to select a different option and then come back and select the original one I wanted to select in order to trigger the onchange(). Here's a sample. Everytime I click the same option I want to trigger the action `someAction`.

```javascript
        {{#power-select
          allowClear=true
          options=model
          selected=selection
          searchEnabled=false
          initiallyOpened=true
          onchange=(action 'someAction')
          as |someObj|
        }}
          {{someObj.someProp}}
        {{/power-select}}
      </div>

**Comment by cibernox** [comment]
That is a weird usage, given that as you mention, the selection didn't change.
Have you considered adding the event yourself in the block?

```hbs
{{#power-select ... as |opt|}}
  <span onclick={{action "my-action" opt}}>{{opt}}</span>
{{/power-select}}
```

Maybe this is enough. At the end, within the block you can do almost anything.

**Comment by 3-john-4** [comment]
Thanks for the suggestion but with onchange being required, when I click on a different option both the onchange and onclick are fired.  The only solution I see to that is the onchange triggering an action that does nothing. 
```javascript
{{#power-select ... 
  onchange=(action 'action-that-does-nothing')
  as |opt|}}
  <span onclick={{action "my-action" opt}}>{{opt}}</span>
{{/power-select}}

**Comment by cibernox** [comment]
I have the feeling that you are using ember-power-select to implement something that is closer to a "dropdown-menu" than to a select (you are not selecting anything).

In that case yes, make the `onchange` option be a noop action is the simplest solution.

If you want more freedom you can try to use `ember-basic-dropdown`, the component on top of which Ember Power Select is built. Is less opinionated, you can do almost anything.
