### ISSUE TITLE
Encounter import error when upgrade to ember 2.7

### ISSUE THREAD

**Issue by Argun** [cibernox/ember-power-select#612]
Uncaught Error: Could not find module `ember-owner/get` imported from `ember-basic-dropdown/components/basic-dropdown`.

How to resolve this issue? 

![screen shot 2016-08-02 at 12 46 03](https://cloud.githubusercontent.com/assets/1279340/17317400/dc27f9c6-58af-11e6-9660-bae816eba8c6.png)

**Comment by cibernox** [comment]
Try to update `ember-cli-shims` in your `bower.json` to the latest version.

**Comment by Argun** [comment]
Thank you for your reply. 
After upgrade ember-cli-shims to 0.1.3 version.
It seems produce another issue. like this [https://github.com/cibernox/ember-power-select/issues/606](url)

**Comment by cibernox** [comment]
Yes, I'm aware of that one. It's next on my list. 
In the meantime don't render the component in place if that error is causing a problem. 

Closing. Thanks for the report.
