### ISSUE TITLE
variables for overriding select box borders

### ISSUE THREAD

**Issue by jamesdixon** [cibernox/ember-power-select#615]
Hi,

I was going to take a shot at creating a rudimentary material theme. The first thing I needed to do was strip the top, left and right borders of the select box. Are there variables for overriding this or am I missing something?

Thanks for the great work!

**Comment by cibernox** [comment]
I think that the best place to all the sass variables is in the source: https://github.com/cibernox/ember-power-select/blob/master/app/styles/ember-power-select/variables.scss#L17-L37

In this case I think that there isn't a way customize top/left/right/bottom border individually. I'm open for a PR tho 😀

**Comment by jamesdixon** [comment]
Thanks, @cibernox!
