### ISSUE TITLE
Could not find module `ember-owner/get` imported from `ember-basic-dropdown/components/basic-dropdown`

### ISSUE THREAD

**Issue by Juraci** [cibernox/ember-power-select#618]
I'm getting this error everytime I go to the route that was suppose to render the power-select:

```
Could not find module `ember-owner/get` imported from `ember-basic-dropdown/components/basic-dropdown`
```

I just followed the Installation steps in the docs:

`$ ember install ember-power-select`

and added this to my app/styles/app.scss
`@import "ember-power-select";`

In my handlebars I have this:
```
{{#power-select options=model onchange=(action "onLocationChange") as |location| }}
    {{location.name}}
{{/power-select}}
```

the model variable holds a collection of the following objects:

`[ { name: 'Austin', id: '12345-ABC' } ]`

And I have this action defined in my controller:

```
import Ember from 'ember';

export default Ember.Controller.extend({
    actions: {
        onLocationChange(location) {
            Ember.Logger.warn(`Location name: ${location.name}, Location id: ${location.id}`);
        }
    }
});
```

I'm not sure, what I'm doing wrong.

I'm also using ember-cli-sass 5.3.1 and `"bootstrap": "^4.0.0-alpha.2"`

Ember Version: 2.6.2
jQuery Version: 2.2.4

**Comment by cibernox** [comment]
Duplicated of #612
