### ISSUE TITLE
Could not find module `ember-owner/get` imported from `ember-basic-dropdown...

### ISSUE THREAD

**Issue by bmfay** [cibernox/ember-power-select#619]
After a fresh install, I'm seeing the following error in the console:

Could not find module `ember-owner/get` imported from `ember-basic-dropdown/components/basic-dropdown`

Looking at the basic-dropdown component, I can see this import, but I don't see this dependency anywhere.  Any ideas?

**Comment by cibernox** [comment]
Duplicated of #612 and #618
