### ISSUE TITLE
1.0.0-beta.7 gives error "Could not find module `ember-owner/get` ..."

### ISSUE THREAD

**Issue by nelnico** [cibernox/ember-power-select#620]
In a new project I added this addon, and it was using version 1.0.0-beta.7

I then got this error in the console:
Could not find module `ember-owner/get` imported from `ember-basic-dropdown/components/basic-dropdown

When changing to beta.4, clearing out my node modules and doing a npm install all was fine again.

**Comment by p0562153** [comment]
Updating ember-cli-shims to 0.1.3 in your bower.json should fix it.

**Comment by cibernox** [comment]
Yes, that works.

Duplicated of #612, #618 and #619
