### ISSUE TITLE
With options as an ArrayProxy, select component is gone

### ISSUE THREAD

**Issue by pixelhandler** [cibernox/ember-power-select#623]
Example reproduction of the issue: [pixelhandler/power-select-selected-broken]

- See the [README.md] for description of expected/actual behavior and my steps to reproduce the issue. (I copied below as well.)

## Original issue in my app…

- The selected item wasn’t shown as the selected option even though `onchange` did update the selected item
- Works in v0.10.11 but not in newer version.

## When isolating the issue the result was worse - *the select box is just gone*.

- Example [Working Twiddle]
- Has a test as well, in the twiddle.json set `"enable-testing": true`
- You can change the addon version in the twiddle.json file
  - Behavior seems wonky after changing the version, perhaps just fork the twiddle then change the version.

### Expected Behavior

The select box uses options via an `Ember.ArrayProxy` instance with
`content` set using an `RSVP.Promise`. The options for the power select component
are objects.

- Select box works normally
- Click and choose an option
- Click then type to search and enter to select
- Click then focus in search and search to narrow down results
- Acceptance test for the placeholder text should pass

![example-app-with-array-proxy-options-v0 10 11](https://cloud.githubusercontent.com/assets/17178/17454565/c40c4156-5b4f-11e6-920f-6eadd9b4c7d9.png)

### Actual Behavior

After upgrading past v0.10.11, to current beta release v1.0.0-beta.8 …

- Acceptance test for the placeholder text fails
- Current browsers do not even render the power select component
  - The element is gone missing

- Using Ember LTS version v2.4.6 and Ember CLI 2.7.0, and Node 4.4.5
- Manual testing with current release of Chrome, Safari and Firefox

![example-app-with-array-proxy-options-v1 0 0-beta 8](https://cloud.githubusercontent.com/assets/17178/17454566/cd2c2f8a-5b4f-11e6-82a4-36ef9dcb69c4.png)

### Attempts to resolve the issue

Created a repository at [pixelhandler/power-select-selected-broken].

- Clone the addon [cibernox/ember-power-select], and `npm link`…
  - Example local file path for cloned repo: `~/code/cibernox/ember-power-select`

```
cd ~/code/cibernox/ember-power-select
git co -b last-working-release v0.10.11
npm link
```

- Clone the example code [pixelhandler/power-select-selected-broken] to demonstrate the issue…
  - Example local file path for cloned repo: `~/code/pixelhandler/power-select-selected-broken`

```
cd ~/code/pixelhandler/power-select-selected-broken
npm link ember-power-select
ember test
```

**The test should pass**

- Change the version of the addon to a newer version
```
cd ~/code/cibernox/ember-power-select
git co -b current-beta-release v1.0.0-beta.8
```

- Update `package.json` in the example app
```
cd ~/code/pixelhandler/power-select-selected-broken
vim package.json
```

Change version to the current beta release, 1.0.0-beta.8
```
-    "ember-power-select": "0.10.11",
+    "ember-power-select": "1.0.0-beta.8",
```

- Run the test

```
cd ~/code/pixelhandler/power-select-selected-broken
ember test
```

**The test should fail**

[pixelhandler/power-select-selected-broken]: https://gitlab.com/pixelhandler/power-select-selected-broken
[README.md]: https://gitlab.com/pixelhandler/power-select-selected-broken/blob/master/README.md
[Working Twiddle]: https://ember-twiddle.com/4963fe6f1749f434ab962ca70c8bb4c8?openFiles=twiddle.json%2C
[cibernox/ember-power-select]: https://github.com/cibernox/ember-power-select

**Comment by pixelhandler** [comment]
@cibernox I just tried this repo with 1.0.0-beta.12 and the test passes and the select box is visible again. I think the bug was resolved with 1.0.0-beta.12. I'll test in my apps as well.

**Comment by cibernox** [comment]
@pixelhandler Really? I don't recall doing any change on how the select works. If you check the changelog, changes see unrelated to the bug you mention.

**Comment by pixelhandler** [comment]
@cibernox well I didn't try earlier releases between 1.0.0-beta.8 and 1.0.0-beta.12

Still doing some testing in the actual apps. This repo was a test to isolate the issue I had using an arrayProxy for the options.

**Comment by cibernox** [comment]
Still surprised, but ¯\_(ツ)_/¯. Either way, this is good news. Closing 👍

**Comment by pixelhandler** [comment]
@cibernox Yeah good news, updated to latest 1.0 beta release in all my apps, works fine. One additional thing I did to was remove my matchers and use `searchField` instead. Multiselect component complained w/o `searchField` after removing all selected items. That's when I changed from custom matchers to use the search field prop.
