### ISSUE TITLE
Label / Value

### ISSUE THREAD

**Issue by zurnet** [cibernox/ember-power-select#625]
Unless I'm just missing it, I could not find any examples in the doc using an array of objects and setting the value. For example [{label: 'New York',value:'NY'}, {label: 'New Jersey',value:'NJ'}  ]

So then I can search or select 'New York', but the actual value set is 'NY' to be stored in the DB.

**Comment by jsvg** [comment]
Should be able to just call the object property in the item loop.
```
{{#power-select 
  options=cityData
  onchange=(action (mut selected))
  as |city|}}
  {{city.label}} ({{city.value}})
{{/power-select}}
```

**Comment by cibernox** [comment]
The docs explain that, when the options passes to the component are not strings but objects, you need to pass `searchField="label"` to hint EPS what field should be used for filter. (http://www.ember-power-select.com/docs/the-search)

About extracting the `value` field of the selected option, do it as you'd do with any other action in Ember. Use `value="value"` option of the action helper to extract it. I like to use [ember-composable-helpers](https://github.com/DockYard/ember-composable-helpers) to also make the selected option depend on that value.

```hbs
{{#power-select 
  options=options
  selected=(find-by "value" cityCode options)
  searchField="label"
  onchange=(action (mut cityCode) value="value") as |city|}}
  {{city.label}}
{{/power-select}}
```

**Comment by akursat** [comment]
> (find-by "value" cityCode options)

While we're using dropdown setting the id value to selected element is fundamental. Please, add this comment to the documentation especially onchange section.
