### ISSUE TITLE
multiple-select toggle disabled true/false does not render option remove button

### ISSUE THREAD

**Issue by darenyong** [cibernox/ember-power-select#629]
If you render a multiple-select, then disable it, then re-enable it, the remove option btn (the small x) appears to disappear from the options when the control is re-enabled after being disabled.

There are also issues with the background of the multiple-select still being drawn as grey when re-enabled.

I came up with a quick fix by wrapping the multiple-select in a component like so (unfortunately it renders the disabled state showing nothing as selected, but that is ok for my use-case):

{{#if disabled}}
  {{power-select
  disabled=true
  onchange=(action "change")
  triggerClass="form-control hover-not-allowed text-muted"}}
{{else}}
  {{#power-select-multiple
  selected=excluded
  options=options
  onchange=(action "change")
  renderInPlace=true
  triggerClass="form-control"
  as |genre|}}
    {{genre}}
  {{/power-select-multiple}}
{{/if}}

Ideally, a proper fix would handle muting the trigger text and setting the cursor for the trigger to not-allowed when the power-select control is disabled. This seems to be needed by both the single and multiple select controls when in the disabled state.

**Comment by cibernox** [comment]
Interesting case. I'll label it as a bug and investigate it over the week (I've been on holidays)

**Comment by darenyong** [comment]
No rush, my work around is ok.  Great work on this control BTW, thanks for developing this flexible control.

**Comment by cibernox** [comment]
@darenyong Fixed. Just waiting for CI

**Comment by cibernox** [comment]
Released in beta.9.
