### ISSUE TITLE
Cannot read property 'addEventListener' of null

### ISSUE THREAD

**Issue by josemarluedke** [cibernox/ember-power-select#630]
Hey there!  

I'm having a issue with ember 2.7.0 and ember-power-select 1.0.0-beta.8. 

```
trigger.js:43 Uncaught TypeError: Cannot read property 'addEventListener' of null
```

The stack trace points to https://github.com/cibernox/ember-power-select/blob/a6364c7fe1692817c4572e7623116757e470b170/addon/components/power-select-multiple/trigger.js#L46

With ember 2.6.1 this error does not happen.

**Comment by cibernox** [comment]
I've been using EPS in 2.7 and I haven't seen this error happening. Can you reproduce it in a twiddle?

**Comment by josemarluedke** [comment]
Here is the reproduction: https://ember-twiddle.com/71f6259cc2407fe0e814e2508de55d0d?numColumns=2&openFiles=controllers.application.js%2Ccontrollers.application.js

**Comment by andrei-zhidkov** [comment]
Stumbled upon the same bug on 0.10.11 & Ember 2.7.0.
Will try the latest beta tomorrow...

**Comment by jpaas** [comment]
I am having the same problem with Ember 2.7.0 and power-select 0.10.8

**Comment by acburdine** [comment]
I just reproduced it as well 😞 Ember 2.7.0 and EPS 0.10.11. Will try and create a reproduction case in ember-twiddle

**Comment by cibernox** [comment]
@acburdine 0.10 is not compatible with 2.7, but the 1.0.0 family should be fine.

Creating a reproduction in twiddle is impossible I believe, because it's broken with Ember 2.7.

**Comment by jpaas** [comment]
I upgraded to 1.0.0-beta.14 and its working nicely now. Thanks @cibernox for a very useful addon!

**Comment by msalahz** [comment]
@cibernox, I'm having the same issue with v1.0.0-beta.14 when I use power-select-multiple

**Comment by msalahz** [comment]
any updates on that ?

**Comment by corrspt** [comment]
Just want to say that I've upgraded to Ember 2.7.3 (from 2.6) and this started happening as well, I'll try to isolate the issue if I can.

It seems to happen only on power-select-multiple.

**Comment by cibernox** [comment]
I **might** I've fixed it while working in the glimmer2 compatibility. Let's see if I can publish it today.

**Comment by corrspt** [comment]
Let me post some of my findings: 

I had ember-power-select `v1.0.0-beta.17` installed and ember-power-select-with-create `v0.1.10`, when I updated to ember-power-select-with-create v0.2.0 it started working.

Long version:
I updated my package.json to reference the latest commit in Ember Power Select  like this
`"ember-power-select": "git://github.com/cibernox/ember-power-select.git#b43879f13f0d2b3e19999ec5275f53c3b05ffcf0",`

That didn't work (I did delete `node_modules` and `bower_components` and reinstalled), one thing that I found odd was that while navigating through the source in my project I had the following code in `trigger.js` for power-select-multiple.

`var optionsList = document.getElementById(this.elementId + '-ember-power-select-multiple-options');`

But looking for this line of code in EPS source code, I could only find a reference to this.elementId in the changelog saying that it was removed. Which means that I was somehow using an "older" power-select? 

That's when I remembered to update power-select-with-create which now has on its own package.json version 1.0.0-beta.14, but previously (on 0.1.10 has version 0.10.X of EPS).

Hope it helps someone.

**Comment by msalahz** [comment]
Thank @corrspt I will give it a try today.

**Comment by msalahz** [comment]
Thanks @corrspt I will give it a try today.

**Comment by cibernox** [comment]
Oh yes, the good ol' "hey! I'm NPM, i don't care about dependency conflicts, so I'll install both version and silently choose one" problem.

I'll update the readme of EPS-with-create to state that 0.2.0 is for use with EPS 1.0.

**Comment by msalahz** [comment]
@cibernox , I confirmed this fix, Thanks a gain @corrspt

**Comment by corrspt** [comment]
Glad I could help @msalahz !

**Comment by snewcomer** [comment]
@cibernox sorry to be a party pooper, but I am getting the same error.  Basically I have **one component** calling a model related function in the init method (add_many_to_many at the bottom of the stack trace).  In **another component**, I have an ember-power-select-multiple.  The top of the stack trace is referencing this multiple ps.  Remove the model related function in the init method (which has nothing to do with the model bindings to the multi select), then I am g2g.  I have an ember-power-select addon as well, but that is updated locally to beta.19 as well as my pkg.json.  There is a `revalidateTopLevelView` that seems a bit funky.

<img width="936" alt="screen shot 2016-09-28 at 2 03 34 pm" src="https://cloud.githubusercontent.com/assets/7374640/18932297/9e366c2c-8584-11e6-90b9-2389e3454bab.png">

**Comment by snewcomer** [comment]
I'll try to get a twiddle up
