### ISSUE TITLE
app installs styles/app.scss - but I am not using sass

### ISSUE THREAD

**Issue by bambery** [cibernox/ember-power-select#632]
I am not using sass, I am using less. When I installed the addon, styles/app.scss was added to my file system. The doc says that it should have just gone into vendor, so I'm confused as to what happened here. I have installed ember-bootstrap and ember-cli-less.

**Comment by cibernox** [comment]
This is a bug someone reported but I haven't had time to fix. Basically I try to detect if the user has `ember-cli-sass` sass installed to a line to `app.scss`. But at some point, I think that I detect a false positive and some people that is not using sass see that file appear.

You can delete it safely.
