### ISSUE TITLE
Deprecation error when attempting to extend v1.0.0-beta.9

### ISSUE THREAD

**Issue by sarus** [cibernox/ember-power-select#634]
I'm extending `v1.0.0-beta.9` to provide functionality similar to `ember-power-select-with-create`.  After updating to the latest beta version I started seeing this deprecation:

```
DEPRECATION: You modified (-join-classes (-normalize-class "concatenatedTriggerClasses" concatenatedTriggerClasses) "ember-view" "ember-basic-dropdown-trigger" (-normalize-class "inPlaceClass" inPlaceClass activeClass=undefined inactiveClass=undefined) (-normalize-class "hPositionClass" hPositionClass activeClass=undefined inactiveClass=undefined) (-normalize-class "vPositionClass" vPositionClass activeClass=undefined inactiveClass=undefined)) twice in a single render. This was unreliable in Ember 1.x and will be removed in Ember 3.0 [deprecation id: ember-views.render-double-modify]
```
It happens when you press backspace on a selected option (in power-select-mutliple) and the visual changes from a "tag" to plain text.  

Has anyone seen this before or have any pointers as to what I might be doing?  I'm not sure yet if this exists in vanilla ember-power-select-multiple.  Will setup a test on that version.

**Comment by sarus** [comment]
FYI couldn't reproduce this on ember-power-select-multiple `1.0.0-beta.9` using ember `2.7` so it must be something related to how I'm extending power select.

Will leave this open a little longer while I try to figure out the issue and will post the solution here once I figure it out in case it helps someone else in the future.

Thanks!

**Comment by sarus** [comment]
I was able to solve this by wrapping the `this.get('onchange')()` call in a scheduleOnce.

This was in a custom onChange function:

```
actions:{
   myOnChange(selection, select){
        Ember.run.scheduleOnce('afterRender', this, this.get('onchange'), selection);
   }
```

**Comment by cibernox** [comment]
I've seen that before, but I never got time to track the origin. You last comment can come handy for that.

**Comment by sarus** [comment]
So I thought it solved it but I still get the deprecation.  It just happens under a different scenario now.  This is on my list to figure out before Ember 3.0 haha.

**Comment by cibernox** [comment]
There enough time for that. I think it's not that you're doing anything wrong while stending the component tho. I've seen it before, I just can't remember how.
