### ISSUE TITLE
Prevent mouse click on input text from clearing text

### ISSUE THREAD

**Issue by sarus** [cibernox/ember-power-select#646]
In the example for `Create Custom Options` here (http://www.ember-power-select.com/cookbook/create-custom-options) if you start to type some text and then click on the text with the mouse (e.g., to edit it) then the text disappears.  

Is there a way to prevent this behavior so that a user can start typing (or paste in text), then use the mouse to change the cursor position to edit the text before pressing enter?

Thanks!

**Comment by cibernox** [comment]
Good point. I think that this shouldn't close the component. I'd call it a bug.

**Comment by cibernox** [comment]
In theory you could patch this in a couple ways. With a custom trigger component that has an `onmousedown` handler that stops the propagation of the event is one. Another could be to pass an `onclose(select, evt)` action that checks if the event that triggers the close has the searcbox as target, and `return false` to prevent cancel the close.

Either way those patches are less that ideal, I need to check how other select components do this.

**Comment by sarus** [comment]
Cool thanks for the tips.  I'm trying to extend the existing trigger component:

```
// components/ember-power-select/trigger.js
import PowerSelectMultipleTrigger from 'ember-power-select/components/power-select-multiple/trigger';

export default PowerSelectMultipleTrigger.extend({
  actions:{
    onMousedown(e){
      e.stopPropagation();
    }
  }
});
```

This works but I know I need to override the template as well.  As soon I drop the template into `templates/components/ember-power-select/trigger.hbs` I start getting lots of errors.  (I just copied and pasted the default template to start https://github.com/cibernox/ember-power-select/blob/master/addon/templates/components/power-select-multiple/trigger.hbs)

```
app.js:15 Uncaught TypeError: Cannot read property 'addEventListener' of null
didInsertElement @ trigger.js:40
```

Followed by lots and lots of `didInsertElement`  deprecations of the form:

```
DEPRECATION: A property of <app@view:-outlet::ember840> was modified inside the didInsertElement hook. You should never change properties on components, services or models during didInsertElement because it causes significant performance degradation. [deprecation id: ember-views.dispatching-modify-property]
```

Is there something special I have to do to reuse the existing template and/or trigger logic?

**Comment by sarus** [comment]
Just an FYI but the error I was getting above is also covered in this issue:

https://github.com/cibernox/ember-power-select/issues/630

Updating to the latest beta version (beta-14) fixed the issue.
