### ISSUE TITLE
Remove tabindex from the trigger when select is disabled

### ISSUE THREAD

**Issue by Dremora** [cibernox/ember-power-select#647]
Currently, if `{{power-select}}` or `{{power-select-multiple}}` is disabled, one can still focus it by clicking. It shouldn't be possible to activate disabled controls. If `tabindex` is passed as a option it should still be ignored.

I've tried to reproduce this in ember-twiddle but couldn't make it work with ember 2.7.0.

**Comment by cibernox** [comment]
Published in beta.14.
