### ISSUE TITLE
Add documentation for "holes"

### ISSUE THREAD

**Issue by frisco82** [cibernox/ember-power-select#653]
Currently it is documented the options to customize some components of EPS but there is no way to know what kind of information does receive each component and the properties that are setted by EPS.

Yesterday, I needed to spent a couple of hours browsing the repo and debugging to be able to create a simple working selectedItemComponent.

**Comment by cibernox** [comment]
It is kind of documented [here](http://www.ember-power-select.com/docs/api-reference), at the bottom. Precisely all the effort around 1.0 is standarize the API received by sub-components into one single big object named `select`.

If you didn't found this I think that I should promote that information to somewhere more visible.

**Comment by frisco82** [comment]
I must say that I found the page but missed that part, but anyway the text does not tell in which property the object is stored in the components, and in fact that object does not help for selectedItemComponent in multi selects, as you need the current item being rendered that it is sent as 'option'.
Also the example using selectedItemComponent does not show the code of the component being used so they only way to find it is digging on the repo or debugging.

So yup, that part needs some love :heart:
