### ISSUE TITLE
`disabled: true` within the options list does not disable in Ember 2.7.X

### ISSUE THREAD

**Issue by Aaronfischer** [cibernox/ember-power-select#654]
@cibernox Thanks for chatting over Slack to dig a bit more into this, here is a quick summary of what was discussed:

Ember 2.7.X
and Ember Power Select beta 13/14 (did not try any other versions)

Controller:

``` js
export default Ember.Controller.extend({
  statusContent: Ember.computed(function () {
    return [
      {
        label: 'Foo',
        id: 'foo',
      },
      {
        label: 'Bar',
        id: 'bar',
        disabled: true,
      },
    ];
  });
});
```

Template:

``` hbs
{{#power-select
  options=statusContent
  selected=(find-by statusContent 'id' model.status)
  searchEnabled=false
  searchField="label"
  placeholder="Select the status"
  class="status"
  onchange=(action (mut model.status) value="id")
  as |status|}}
    {{status.label}}
{{/power-select}}
```

Within my application this returns a list with the DOM:

``` html
<li class="ember-power-select-option" role="option" data-option-index="2" aria-current="">
  Foo
</li>
<li class="ember-power-select-option" role="option" aria-disabled="" data-option-index="3">
  Bar
</li>
```

The ember-power-select demo files seem to have `aria-disabled="true"` which all seems to be fine if this is the case.
# 

As a quick and dirty workaround if I was to set `disabled: 'true'` (as a string) the list items are disabled.

**Comment by cibernox** [comment]
I think that this has been fixed since then. It was because of a change (breaking in my opinion) in Ember that I've since then protected against.
