### ISSUE TITLE
Single select - when changing selection, "selected" class is not cleared on old selection

### ISSUE THREAD

**Issue by dbeusee** [cibernox/ember-power-select#655]
I am trying to write css to show selected and active and both.  I found out the selected class is never cleared on a previously selected item.  I verified this with inspect.  When selecting an item, first all items should be cleared of the "selected' class.  Then put 'selected' class on the selected item.

I'm using the latest chrome on windows 10 x64.

**Comment by cibernox** [comment]
I don't think this is the case. It's more than tested and the documentation page is a good live example of this. What combination of this addon + Ember are you using?
