### ISSUE TITLE
`undefined is not an object (evaluating 'target.dispatchEvent')` testing in Ember 2.8.x

### ISSUE THREAD

**Issue by Mr-TaylorHobbs** [cibernox/ember-power-select#660]
Just finished my update to Ember 2.8.0 and my app works correctly in the browser, but the tests that use `selectChoose` are failing with the error `undefined is not an object (evaluating 'target.dispatchEvent')`.

I am using `1.0.0-beta.14`.

**Comment by cibernox** [comment]
I haven't tried the component in 2.8 yet, but I'm not aware of any reason that could cause this. Can you create a failing example?

**Comment by Mr-TaylorHobbs** [comment]
My apologies, after I updated from 0.10.x to 1.0.0-beta.14, I did not have a `tagName` passed to the `power-select` component. Once I added this everything worked correctly.

**Comment by cibernox** [comment]
You can also target any ancestor and leave the component tagless. That is usually what I do.
