### ISSUE TITLE
Bootstrap 3, Mac OSX El Capitan - rendering issue in major 3 browsers at full screen

### ISSUE THREAD

**Issue by rmcsharry** [cibernox/ember-power-select#662]
Bootstrap 3
Mac OSX El Capitan 10.11.5
Chrome 52.0.2743
Firefox 43.05
Safari 9.1.1

When the browser is maximised (green button = full screen), the ember-power-select does not render correctly (see screenshot) when you first open it.

Note this only happens when it opens upwards (ie. the control is near the bottom of the page).

If the browser is not maximised, the issue does not occur (so possibly it could be related to scrollbars being present on the browser window?)

Once you move the mouse over the select, it fixes itself.

![image](https://cloud.githubusercontent.com/assets/1156100/18509686/31e09d78-7a7a-11e6-9d30-5a44c839b336.png)

Default setup, no customisation of the CSS for the power-select.

**Comment by cibernox** [comment]
@rmcsharry EPS (EBD actually, another addon used by this one) listens for several global window events (https://github.com/cibernox/ember-basic-dropdown/blob/master/addon/components/basic-dropdown/content.js#L162-L164). Particularly I'd expect entering full-screen mode to trigger a `resize` event in the window. 

Isn't that the case?

Are you aware if browsers trigger any kind of event when entering full screen mode that I can subscribe to?

**Comment by cibernox** [comment]
I just tried to reproduce it and it worked for me. What version of the component are you using?

**Comment by rmcsharry** [comment]
@cibernox I'm not aware of any even being triggered.

The version is "1.0.0-beta.15"

**Comment by rmcsharry** [comment]
I think it might be related to the control being inside a Bootstrap column. If I move it so its parent is not `class="col-xs-[number]"` for example, then it renders correctly.

**Comment by rmcsharry** [comment]
Let me cancel that last test, some other bootstrap class or page structure seems to be affecting it.

**Comment by rmcsharry** [comment]
Here is the html structure:

```

  </div>  <-- end of previous form-group
  <hr/>

  <div class="form-group">
    <label class="col-xs-2 col-md-2 control-label">
      Assign to team member(s)
    </label>
    <div class="col-xs-10 col-md-10">
      {{#power-select-multiple options=model.employees 
        searchPlaceholder="Type a name to search"
        searchField="fullName"
        selected=model.trail.employee placeholder="Select team members"
        onchange=(action (mut model.trail.employee)) as |employee| }}
        {{employee.fullName}}
      {{/power-select-multiple}}
      <small>Type to search by name - press ENTER or CLICK to select. Repeat to add more people.</small>
    </div>

```

If I insert a `&nbsp;` immediately after the `<hr/>` then the control renders correctly (but obviously I don't want that space there lol)

**Comment by rmcsharry** [comment]
If I remove the `<hr/> `and replace with one `<br/>` I see the issue, but with

`<br/><br/> ` or
`<hr/><br/>` 

I don't see it

This would imply it is something to do with calculating the space available above the control when it opens upwards.

**Comment by cibernox** [comment]
I don't see why the markup around would affect this because this uses `triggerElement.getBoundingClientRect` to find the X/Y coordinates, so I just trust the browser to do that. This is weird.

Can you create a reproduction (maybe using ember-twiddle)?
