### ISSUE TITLE
Error with ember 2.8.0

### ISSUE THREAD

**Issue by basz** [cibernox/ember-power-select#664]
Hi!

I'm seeying this error after upgrading.... Any idea

```
ember.debug.js:6778 Uncaught Error: Assertion Failed: You cannot use `attributeBindings` on a tag-less component: <panorapix@component:power-select::ember1325>
```

Updated ember from 2.6.2 to 2.8.0
Updated ember-power-select to beta15

```
// pods/application/controller.js
import Ember from "ember";

export default Ember.Controller.extend({
    names: ['Stefan', 'Miguel', 'Tomster', 'Pluto'],
    actions: {
         foo() { },
    }

// pods/application/template.hbs
{{#power-select options=names onchange=(action "foo") as |name|}}
    {{name}}
{{/power-select}}
```

**Comment by cibernox** [comment]
While that message makes sense (not using attributeBindings in tagless components), none of the components where this addon uses `attributeBindings` is tagless.

https://github.com/cibernox/ember-basic-dropdown/blob/b403d55bf4966bcef7da6e213b70f48957e0edb8/addon/components/basic-dropdown/trigger.js#L26

https://github.com/cibernox/ember-power-select/blob/035efe88726fbafe540cc34a2d4691dd2b325271/addon/components/power-select/options.js#L9-L10

I don't see how that component can trigger this error.

**Comment by basz** [comment]
hmm, after a ember init and only this project added the error is gone and a select box appears without problems. so it is something else in my project... back to upgrade hell. thx

**Comment by basz** [comment]
Just letting y know I found the problem;

```
{{#power-select selectedItemComponent="selected-event" ...
```

My 'selected-event' component did not have a tagName defined...

**Comment by cibernox** [comment]
🎊
