### ISSUE TITLE
Assertion Failed: You cannot use `attributeBindings` on a tag-less component

### ISSUE THREAD

**Issue by HenryVonfire** [cibernox/ember-power-select#666]
I'm getting this error with ember `2.8.1` and EPS `1.0.0-beta.15`:

> Assertion Failed: You cannot use `attributeBindings` on a tag-less component

**Comment by cibernox** [comment]
Can you check if this helps?#664

**Comment by HenryVonfire** [comment]
Not much :pensive: using it in the application template with a basic usage, when EPS is present I get that error and when I remove it, the app works fine

**Comment by cibernox** [comment]
No idea. Tests pass in 2.8. This addon, unless the user customizes some element, doesn't use `attributeBindings` on a tagless component.

**Comment by HenryVonfire** [comment]
Ok, thanks anyway. I'll come back if I found the answer. It can be helpful to someone else.

**Comment by HenryVonfire** [comment]
That was quick. I found it! there's a conflict between this addon and `ember-hammertime`. Just installing both generate the error.

**Comment by cibernox** [comment]
I don't see the relation between ember-hammertime and EPS 😕

**Comment by HenryVonfire** [comment]
Confirmed. I removed it from my project and now all the EPS work. Should I open an issue in that repository?

**Comment by corrspt** [comment]
I think there's already an issue for that in [Ember Hammer Time](https://github.com/runspired/ember-hammertime/issues/19)

**Comment by cibernox** [comment]
I'm closing this then 👌

**Comment by jakeleboeuf** [comment]
Any other known addons causing this same problem? I'm running into this issue but not using `ember-hammertime` on my project.

**Comment by jakeleboeuf** [comment]
@miguelcobain or perhaps a better question, how can I track down which addon is causing this issue?

**Comment by jakeleboeuf** [comment]
Maybe I'm not understanding this issue fully, but I just fixed my issue by replacing `tagName: ''` with `tagName: 'span'` in the _all_ of the following components:

[power-select.js](https://github.com/cibernox/ember-power-select/blob/master/addon/components/power-select.js)
[power-select/trigger.js](https://github.com/cibernox/ember-power-select/blob/master/addon/components/power-select/trigger.js)
[basic-dropdown.js](https://github.com/cibernox/ember-basic-dropdown/blob/master/addon/components/basic-dropdown.js)
[basic-dropdown/content.js](https://github.com/cibernox/ember-basic-dropdown/blob/master/addon/components/basic-dropdown/trigger.js)

Am I missing something here?

**Comment by jakeleboeuf** [comment]
After a little more time, I realized any interaction caused things to break again. I had to replace all instances of `tagName: ''` with `tagName: 'span'` in the _every_ component in both [ember-power-select](https://github.com/cibernox/ember-power-select/blob/master/addon/components/) and [ember-basic-dropdown](https://github.com/cibernox/ember-basic-dropdown/blob/master/addon/components), and things now appear to be working.

Surely this is not ideal, but I cannot figure out where that `attributeBinding` is coming from...

**Comment by jakeleboeuf** [comment]
Finally tracked down the culprit... Sorry for the issue spam @miguelcobain! 

For anybody experiencing this same issue, looks like [ticketfly/ember-hook](https://github.com/Ticketfly/ember-hook) was the source of that attributeBindings error.

Upgrading from v1.3.1 to v1.3.5 fixed this.

**Comment by ThemeSama** [comment]
You cannot add any attribute or class names for tagName is empty. You can choose a tagName for your extended component like this.

```javascript
export default EmberPowerSelect.extend({
  tagName: 'div',
  attributeBindings: ['selectValid:data-select-valid'],

  selectValid: computed(
 ...
```
