### ISSUE TITLE
How to p

### ISSUE THREAD

**Issue by eshtadc** [cibernox/ember-power-select#667]
I'm getting an error:  

> Assertion Failed: calling set on destroyed object: <lift3@component:power-select::ember1606>.publicAPI = [object Object]

This happens when I pick a new item from the drop down list.  I have to re-render the components when a change is made based on the available options changing.  I think that this is messing with ember-power-select's own expected timing of events.

This happens on the mouseUp event handler of findOptionAndPerform in options.js.  I'll see if I can figure out enough for a PR.

**Comment by eshtadc** [comment]
I adjusted my own code to run on the next run loop so that the select could have a chance to finish up it's own clean-up and that seems to be fine.

**Comment by cibernox** [comment]
Maybe doing `Ember.run.schedule('action', yourFunction)` works too, and is less hacky that `Ember.run.next`

**Comment by eshtadc** [comment]
@cibernox Thanks for the advice 👍

**Comment by rwwagner90** [comment]
@cibernox I am running into this issue in tests. Any suggestions?

**Comment by cibernox** [comment]
@rwwagner90 do you have a reproduction? How does it happen exactly?

**Comment by rwwagner90** [comment]
I'm using `selectChoose` in the test, then after the test it blows up.

**Comment by cibernox** [comment]
Interesting, I didn't experience that. Perhaps the test is ending before `selectChoose` gets a chance to run? If not, where would you put the `isDestroyed` check?

**Comment by rwwagner90** [comment]
@cibernox no, `selectChoose` chooses the option fine. What do you mean where would I put the `isDestroyed` check?

**Comment by cibernox** [comment]
I mean that that `calling set on destroyed object:` is being thrown somewhere. We should put a check for isDestroyed wherever that error is being thrown, right?

**Comment by rwwagner90** [comment]
@cibernox yeah, that sounds logical

**Comment by rwwagner90** [comment]
I have not tried the master branch or betas, but the only place in master that looks like it sets `publicAPI` is here https://github.com/cibernox/ember-power-select/blob/cfa45a31f4a91abb969128be5b14e4776e308cd6/addon/components/power-select.js#L76
