### ISSUE TITLE
Issue in placeholder in `power-select-multiple`

### ISSUE THREAD

**Issue by manoharank** [cibernox/ember-power-select#670]
I have encountered the following issue in `ember-power-select#1.0.0-beta.17`. It shows `true` in placeholder when there is no placeholder passed or any item selected in `power-select-multiple`.

![multi-select-placeholder](https://cloud.githubusercontent.com/assets/1687297/18606411/dad4ad94-7ccc-11e6-8c1f-f81f6be7bd19.jpg)

I have seen the below code for `maybePlaceholder` computed property in GitHub and in my `node_modules`

```js
return (!select.selected || get(select.selected, 'length') === 0) ? (this.get('placeholder') || '') : '';
```

But in devtools the same code looks like 

```js
return !select.selected || (0, _emberMetalGet['default'])(select.selected, 'length') === 0 ? this.get('placeholder') || '' : '';
```

There is no bracket around the condition in the above code. I am unsure that causes the issue. I am using `ember-cli#2.9.0-beta.1`

**Comment by manoharank** [comment]
I am using `ember#2.9.0-beta.2`. This is an issue with Glimmer, not in `ember-power-select`. Related issue  ember.js/issues#14290.

**Comment by cibernox** [comment]
Good thing. I've been working on glimmer compatibility yesterday and I saw this too.
