### ISSUE TITLE
How to access the selected objects in multiple-selection, when those objects are a Store collection?

### ISSUE THREAD

**Issue by rmcsharry** [cibernox/ember-power-select#673]
EmberJS 2.7 with **EPS 1.0.0.0-beta15**

I have gone through at least 2 or 3 pages of closed issues and cannot find this problem explained. I read [this entire issue](https://github.com/cibernox/ember-power-select/issues/102), which is more about filter and search, but makes the same point about the docs only showing how to use this with simple arrays.

_So to be clear, search/filter is not my issue, but how to use this with something more complex than simple arrays of strings._

I still think the docs need more info on this and I am more than happy to make that contribution, assuming I can find a solution. It should be easy, I am sure this is a common use case.

Model structure is this:
**Trail**
hasMany assignments

**Employee**
hasMany assignments

**Assignment** 
belongsTo Trail
belongsTo Employee

In my 'new Trail' route, I use the EPS to let the user select employees. On clicking 'save' I plan to iterate through the selected employees and then create the assignment records (and obviously save them, either before or after saving the Trail itself, not sure which is best yet).

So, here is the relevant EPS usage in my template:

in /app/templates/trails/new.js

```hbs
      {{#power-select-multiple options=model.currentEmployees 
        searchPlaceholder="Type a name to search"
        searchField="fullName"
        selected=staff placeholder="Select team member(s)"
        onchange=(route-action 'staffSelected') as |employee| 
      }}
      <block here template to display various employee data, not just 'fullName'/>
      {{/power-select-multiple}}
```
(route-action is a helper from Dockyard that just automatically sends the action to my route, works great)

Here is my model:

```js
  model: function () {
    let myFilter = {};
    myFilter.data = { filter: {status: [2,3] } }; // current employees
    return Ember.RSVP.hash({
      trail: this.store.createRecord('trail'),
      currentEmployees: this.store.query('employee', myFilter).then(function(data) {return data}),
    });
  },

  actions: {
    staffSelected (employee) {
      this.controller.get('staff').pushObject(employee);      
      console.log(this.controller.get('staff').length);
    },
  }
```
I only discovered today that we still need controllers, so this could be my problem! Here it is:

```js
import Ember from 'ember';

export default Ember.Controller.extend({
  staff: []
});
```

This works and I see one object is added to the array in the console. But then the EPS refuses to work because I get this error in the console:

```
trekclient.js:91 Uncaught TypeError: Cannot read property 'toString' of undefined(anonymous function) @ trekclient.js:91ComputedPropertyPrototype.get @ vendor.js:29285get @ 
....
```

Which is immediately follow by this:
```
vendor.js:16695 DEPRECATION: You modified (-join-classes (-normalize-class "concatenatedTriggerClasses" concatenatedTriggerClasses) "ember-view" "ember-basic-dropdown-trigger" (-normalize-class "inPlaceClass" inPlaceClass activeClass=undefined inactiveClass=undefined) (-normalize-class "hPositionClass" hPositionClass activeClass=undefined inactiveClass=undefined) (-normalize-class "vPositionClass" vPositionClass activeClass=undefined inactiveClass=undefined)) twice in a single render. This was unreliable in Ember 1.x and will be removed in Ember 3.0 [deprecation id: ember-views.render-double-modify]
        
```

So I imagine this is because the examples in the documentation just uses an array containing strings, not actual Ember.Objects. But I have no clue how to solve this.

So, I decided to throw away the controller (ha ha) and get creative. 

What if I added a property to the Trail model?  (the parent of employee) This property can  basically be a 'dummy' property that collected the selected employees.

in /app/models/trail.js
```js
selectedEmps: DS.hasMany('employee', async {false}) 
```

I set async to false since we will not persist them and before saving the new Trail I can just set this to null again.

in /app/templates/trails/new.js

```hbs
      {{#power-select-multiple options=model.currentEmployees 
        searchPlaceholder="Type a name to search"
        searchField="fullName"
        selected=model.selectedEmps placeholder="Select team member(s)"
        onchange=(action (mut model.selectedEmps)) as |employee| 
      }}
      <block here again/>
      {{/power-select-multiple}}
```

This works, it doesn't 'blow up' after selecting the first employee. I can select multiple and delete them from the template. The control seems to work fine, as it is mutating 'model.selectedEmps' directly.

Now, I think this is a hack because I have two problems with it:

1. If I change the 'mut' to an action, so I can add further logic, I cannot figure out how to access what is actually stored in the propery 'model.selectedEmps'
2. Even if I can figure out (1) I will have to always make sure that 'selectedEmps' is emptied when leaving this route, otherwise the next time this route is entered, it will remember what was selected before (since they are now in the Ember.Store)

The fundamental issue is that I can live with 'mut' but still have the problem that when the user hits 'Save' I have to figure out which employees were selected, so I can create the assignments for them. But I cannot seem to figure out how to access what is selected.

**Comment by cibernox** [comment]
Still reading the entire problem, but something I see that is off is this:

```js
  actions: {
    staffSelected (employee) {
      this.controller.get('staff').pushObject(employee);      
      console.log(this.controller.get('staff').length);
    },
  }
```

The `onchange` action doesn't receives the new selection. In single selects that is one object, in multiple selects that is an array of objects. Instead of pushing, you need to either replace the collection (like the `mut` helper does, and seems to work for you) or compare the existing collection with what it's already selected and add/remove whatever you need.

Makes sense?

**Comment by rmcsharry** [comment]
100 point bounty [up for grabs here](http://stackoverflow.com/questions/39506375/emberjs-2-7-has-many-configuration-for-ember-data-and-active-model-serializers) on SO.

**Comment by rmcsharry** [comment]
@cibernox Thank you for the fast response.

Yes I can see that makes sense - that the action is just coded to receive one object. I can work on that bit at least and make some headway.

However, to be honest I would rather use the mut option, as I'm sure that will be the path of least pain.

But I just have no idea how to get at whatever is selected - or indeed, where that collection should actually exist. Surely it should be a property on the controller of this route, but what kind of property?

A simple array is probably not sufficient is it? Wouldn't it need to be an array of 'employee' types? Something like this?

```
  staff: function () {
    return this.get('model.trail.????')
  }.property('model.trail.????.[]')

```

**Comment by rmcsharry** [comment]
Thanks, you were right about the action code.

I have managed to do the mutation by changing the action code to:

```js
  staffSelected(newList) {
      existing.forEach(function(me){
        if (!newList.includes(me)) {
          existing.removeObject(me); // if I exist but the newList doesn't have me, remove me
        }
      });
      newList.forEach(function(me){
        if (!existing.includes(me)) {
          existing.pushObject(me); // if I don't exist but the newList has me, add me
        }          
      });
  }
```

staff property in the controller is now staff: Emer.A() but not sure if that's really necessary.
