### ISSUE TITLE
Test helpers no longer allow "*" as a selector

### ISSUE THREAD

**Issue by mdentremont** [cibernox/ember-power-select#676]
It appears that with the latest >=1.0 betas/alphas, `selectChoose` and `selectSearch` have been modified in such a way that they longer perform a `find('.ember-power-select-trigger')` when trying to locate the power select fields using the passed in `cssPath`.

This is resulting in failure to find components when using a wildcard css specifiers such as '*'.

We found it helpful to use a `*` selector especially when testing smaller components which have just one power select component.

**Comment by cibernox** [comment]
Could you give me an example (call to `select*` + html/template) that used to work and now it doesn't? I have regression tests for helpers, so if this broke means there was one case I wasn't testing.

**Comment by mdentremont** [comment]
@cibernox something along these lines: https://github.com/cibernox/ember-power-select/pull/677
