### ISSUE TITLE
Error: File to import not found or unreadable: ember-power-select

### ISSUE THREAD

**Issue by LawreyTan** [cibernox/ember-power-select#688]
Error: File to import not found or unreadable: ember-power-select

import always fail, cant use! with 2.8.0

**Comment by cibernox** [comment]
Can you add more information to this? What are you doing, what version  of this addon, ect...

**Comment by mschwenk** [comment]
Unfortunately I have the same issue when I try to add ember-power-select to my addon as a dependency. 
To override the styles coming with ember-power-select, I add `@import 'ember-power-select';` to my addon.scss file. 

I'm using: 
"ember-power-select": "1.0.0-beta.23"
"ember-cli-sass": "5.5.2"

I also configured the index.js file with the following code.
```
module.exports = {
   name: '<addon-name>',
   included: function (app) {
     this._super.included.apply(this, arguments);
   }
};
```
This worked for the bootstrap @import in my addon.scss file but not for ember-power-select.

**Comment by cibernox** [comment]
@mschwenk I'm not entirely sure of how `addon.scss` works. I remember I tried to use it one year ago but I ran into issues, and I took a different approach.

Check how EPS in turn the styles of `ember-basic-dropdown`: https://github.com/cibernox/ember-power-select/blob/master/app/styles/ember-power-select.scss#L6
Note the the stylesheet is in `app/styles/name.scss`, not inside the addon folder.

**Comment by brunowego** [comment]
Same issue here... 👍

**Comment by cibernox** [comment]
I need steps to reproduce. Browser, versions, workflow, etc..

**Comment by Arunkumarvelu** [comment]
I am also facing this issue
File to import not found or unreadable: ember-power-select.
ember-cli: 2.12.1
node: 7.7.4
os: darwin x64

ember-power-select: 2.0.0-beta.3

**Comment by cibernox** [comment]
The only idea I have is a known issue with `@ember/test-helpers` in the latest version. Can you update to `ember-cli-qunit` 4.3?

**Comment by cibernox** [comment]
@Arunkumarvelu can you share a reproduction. I haven't faced this issue myself.
