### ISSUE TITLE
Infinite scroll for remote data sets (select2 like)

### ISSUE THREAD

**Issue by youroff** [cibernox/ember-power-select#689]
Is there possibility to implement infinite scroll with power-select? What I'd like to achieve is showing some selection right away (even when search haven't been used yet) for the case when user has no idea what keywords to use. What would be an approach here?

**Comment by cibernox** [comment]
Yes, it should be doable, although a bit involved. 

In short, ember-power-select is composed of several components, and all of them can be replaced. See http://www.ember-power-select.com/docs/architecture to know the components.

In this case you'd have to replace the `optionsComponent`  by some component created by you that handles infinite scroll. How you do it is not a concern of this addon, although reusing the same classes/attributes is advised, so the styles are consistent.

Inside all components there is a property named `select` that contains all the data and actions you'll need. The API is defined here, at the bottom: http://www.ember-power-select.com/docs/api-reference

If you come up with something that you want to open-source, let me know so I can link it here: http://www.ember-power-select.com/addons

**Comment by youroff** [comment]
Ok, I'll check that out.

However, shouldn't it be a core feature? Maybe paired with search functionality?
For example, this example in documentation shows only a couple of dozens of options when searching term is 'ember'. It doesn't look right and I believe it's a pretty common thing: http://www.ember-power-select.com/docs/custom-search-action

**Comment by cibernox** [comment]
The goal of the component is to provide the primitives that allow consumer to build any select they want (and at the same time direct the user toward good practices, like accesibility)

Infinite scrolling is on its own right a tricky business with quite a lot of edge cases to cover. I would be a shame to ship all that code to users that are not going to use that feature, thus the idea of `ember-power-select-addon`s (that without mention that each line of code added to a project is one more line to maintain)

The objective is that people that come across the need of some feature can built their own addon on top of this one and open source it. That addon might in turn leverage other battle tested addons that provide the desired functionality. [ember-power-select-sortable](https://ember-power-select-sortable.pagefrontapp.com/) is a good example of this. It uses `ember-power-select` and `ember-sortable`. If someone's project is already using EPS and ember-sortable the footprint of installing `ember-power-select-sortable` is extremely low.

In the case of the infinite scroll, you might compose EPS along with [ember-infinity](https://github.com/hhff/ember-infinity) to achieve your goal.

It has to be a boundary in the amount of features a project can add before becoming a monster, and EPS will not get (significant) new features anytime soon. Special cases like this (which I agree is a perfectly valid use case) can be solved with a different component.
