### ISSUE TITLE
Test helper for choosing grouped options

### ISSUE THREAD

**Issue by nucleartide** [cibernox/ember-power-select#691]
Hello! I noticed that there isn't a test helper for choosing grouped options, where two options might have the same text, but be under different group names. (For example, `Group 1 > Foo` and `Group 2 > Foo`.)

Here's a gist - I only changed the selector: [link](https://gist.github.com/nucleartide/3191ec93ea7efd45052f84f054be55b3#file-select-group-choose-js-L50)

What do you think? Should I proceed and make a PR (with tests) for it? 😄

**Comment by cibernox** [comment]
I agree that this should be possible but I think that a better solution would be to modify `selectChoose` to accept a selector as second argument apart from just text. What way you can do

```js
selectChoose('.my-select', 'James'); // Pass the text content, as today
selectChoose('.my-select', '.ember-power-select-option:eq(3)'); // The selector to the 4th option
```

This addition would work both with single or multiple selects, without the need of an extra helper. I'll add this to the backlog

**Comment by cibernox** [comment]
This is already in master. Over the weekend I'll release a new version.

**Comment by nucleartide** [comment]
awesome, thanks!!
