### ISSUE TITLE
Load options with pagination via API & preload options on opening select

### ISSUE THREAD

**Issue by pohodnya** [cibernox/ember-power-select#692]
After the opening of the select must load the first page of results (using data of pagination: page & per_page). Next need gradual loading data as scrolling. Search similar to.

For example:
**select2** send the first parameter to action **'query'**:

> Object {element: jQuery.fn.init[1], term: "", page: 1, context: null}

_This action works for onOpen and for onChange_

Example query action:

```coffeescript
search: (query, deferred) ->
    q = {'search_field': query.term}
      @get('store').query('model', {q: q, page: query.page, per_page: @get('perPage')}).then(
        ((result)->
          deferred.resolve({data: result, more: result.get('meta.has_more_pages')})
        ), deferred.reject
      );
```

**Comment by cibernox** [comment]
I'm sorry, what exactly is the issue here?

**Comment by pohodnya** [comment]
@cybernox because I want you to have added the ability to progressively download the data in ember-power-select

**Comment by cibernox** [comment]
You can but you have to do it yourself, implementing a custom `optionsComponent` with infinite scroll that calls `search` to get more pages.

I plan to do something similar soon using `smoke-and-mirrors` soon, but at the time this has to be done in userland.

**Comment by cibernox** [comment]
If you want further assistance, this looks a bit more like a question to stackoverflow than an issue in github.
