### ISSUE TITLE
Components animated with `transition` cannot be closed.

### ISSUE THREAD

**Issue by cibernox** [cibernox/ember-power-select#694]
Seems that, while adding CSS animations using `animation: my-animation;` works fine, doing the same using `transition: something 1s;` doesn't.

This issue probably lies in Ember-basic-dropdown. It might be related with some reported inconsistent behaviour of the `transitionend` event in browsers, but might as well be a real bug.

/cc @danmonroe

**Comment by miguelcobain** [comment]
Like I said, let's consider the usage of ember-css-transitions.
We don't want to bloat everyone's node_modules with more dependencies, but things seem to work pretty well for us. Shared solutions are powerful.

**Comment by cibernox** [comment]
I will consider it. I first need to diagnose what's going on.
