### ISSUE TITLE
defaultHighlighted prevents auto-highlighting on search

### ISSUE THREAD

**Issue by pauln** [cibernox/ember-power-select#711]
If you specify a value for `defaultHighlighted`, that option remains highlighted even when it's been filtered out.  For example, if you apply `defaultHighlighted="New York"` to the first example on the "Action handling" page of the docs, it highlights New York by default:
![image](https://cloud.githubusercontent.com/assets/574359/19224275/40458c74-8edf-11e6-907d-f7cef6b1396e.png)

But then if you start typing, it filters but doesn't highlight the first match:
![image](https://cloud.githubusercontent.com/assets/574359/19224280/59898d5c-8edf-11e6-8cd9-44b2d85532d0.png)

You then need to either click an option or press the down arrow to select one - pressing `enter` will select the `defaultHighlighted` item even though it's not visible, and pressing `tab` will leave the power-select without changing the current selection.

**Comment by cibernox** [comment]
Yes, if the highlighted option is static and you can filter, that would be broken, but you can pass a function, not just a static value. If you pass a function, you can do the right thing.

**Comment by pauln** [comment]
The new option is called "defaultHighlighted", which implies that it should control what's highlighted _by default_, i.e. when the select is opened (per the API docs) - I wasn't expecting it to prevent user input events (that is, typing in the filter/search box) from highlighting other items.

Thinking further about it, I think that when this was initially discussed, you suggested that it could be used to focus a "create new option"; I guess that use case makes this behaviour necessary, so perhaps the best thing to do here would be to improve the docs by making it clear that `defaultHighlighted` applies when the options are filtered as well as when the dropdown is initially opened.  I don't have the relevant project to hand right now, but I'll revisit it shortly and confirm that I can get the expected/desired behaviour out of it; if so, I'll see if I can whip up an example suitable for inclusion in either the docs or the cookbook.

**Comment by pauln** [comment]
As per our conversation on Slack, it does seem to work fine - the key thing is to `import { defaultHighlighted } from 'ember-power-select/utils/group-utils';` and use it to get default behaviour in cases where it doesn't need to be overridden.

**Comment by rinoldsimon** [comment]
@pauln how to get the `first option` on every search text highlighted by default? by not setting a static value to `defaultHighlighted`

**Comment by cibernox** [comment]
@rinoldsimon I probably didn't understand the question, because you've described the current behavior already.

**Comment by rinoldsimon** [comment]
i achieved by passing a function to `defaultHighlighted=(action "defaultHighlighted")`
what my function does is,

    defaultHighlighted(a) {
      if (a.results.length > 0) {
        return a.highlighted = a.results[0];
      }
    }

and the above code works perfectly. I just want to clarify if that is the right way of doing ?

**Comment by cibernox** [comment]
Yes, it is the right way to do it. Anything that is documented in http://ember-power-select.com/docs/api-reference is safe to use.

**Comment by rinoldsimon** [comment]
@cibernox we can't pass a helper to `defaultHighlighted` ?

**Comment by rinoldsimon** [comment]
I call a helper in my `defaultHighlighted=pw-default-highlight`. The helper `pw-default-highlight` does not been called

below is the helper code. Whats wrong with it?
`helpers/pw-default-highlight`

    import { helper } from '@ember/component/helper';
      export function pwDefaultHighlight(params) {
        if (params.results.length > 0) {
          return params.highlighted = params.results[0];
        }
      }
    export default helper(pwDefaultHighlight);

**Comment by cibernox** [comment]
Because that's not a helper returning a function. You want this:

`{{#power-select ... efaultHighlighted=(pw-default-highlight) as |opt|}}`

and the helper returns a function
```js
import { helper } from '@ember/component/helper';
export function pwDefaultHighlight(params) {
  return function() {
    if (params.results.length > 0) {
      return params.highlighted = params.results[0];
    }
  }
}
export default helper(pwDefaultHighlight);
```

**Comment by rinoldsimon** [comment]
but the helper is called just once on page on load.

**Comment by rinoldsimon** [comment]
slight modification to the above code works 
    
    import { helper } from '@ember/component/helper';
    export function pwDefaultHighlight() {
      return function(params) {
        if (params.results.length > 0) {
          return params.highlighted = params.results[0];
        }
      }
    }
    export default helper(pwDefaultHighlight);

**Comment by rinoldsimon** [comment]
@cibernox i want `defaultHighlighted=(pw-default-highlight)` to be used inside all power-select in my App. Is there any way to define it globally inside my `config/environment.js` ?
