### ISSUE TITLE
Acceptance Test Helper - Finding Selected Options

### ISSUE THREAD

**Issue by corrspt** [cibernox/ember-power-select#712]
Hi,

I think it would be useful to have a new `acceptance test helper` that allows to know which options are selected in a multi-select (and the single select as well). I have this situation where I have two `power-select` instances side by side, one is single-select, the other is multi-select.

I have a condition that when you select a value in the first select, it automatically fills some values in the other select.

I would like in my acceptance tests to check that things are wired correctly and calculations are correct (for what the values should be given my selection). For that I need to know which values are in the second select

I've tried hacking something (I'm using `ember-cli-page-object`) and I got to the point where I can "do that", something like this in a page-object `component`:

``` javascript
getCurrentValue() {
      let values = text('.ember-power-select-multiple-option', { multiple: true });
      if (values) {
        let options = values.get();
        return options.map((item) => {
          return item.replace('×', '').trim();
        });
      }
      return [];
    }
```

It works, but I kind of have to hack around the little "x" every item has in order to know the values that appear to the user.

Something like this would be nice:

`getSelectedValues(cssPath) // Returns a String array with the text of all options`

Thoughts? I'm open to other ideas (including a better way to test!). Once again, thanks a lot this wonderful component, saves me a ton of work 👍

**Comment by cibernox** [comment]
Given that there is no interaction, that sounds more like a custom assertion than as a helper. I used https://github.com/DockYard/ember-cli-custom-assertions in the past with good results.

Something `assert.selectValuesEqual(cssPath, ['one', 'three', 'five'])`.

I'm not against the idea, I just don't know if an addon can provide custom assertions. If so, I am +1 on this idea.

**Comment by corrspt** [comment]
Hum, that makes sense... anything we can do to workaround the `×` issue? Since it's rendered along side the content with no way to unselect it (at least with my low css-selector skills)?

**Comment by cibernox** [comment]
Custom assertions can do whatever they want. I imagine that in this case getting the text of the options and doing a `strings.map(str => str.replace('×', ''))` would suffice.
