### ISSUE TITLE
power-select doesn't close when clicking away from open component

### ISSUE THREAD

**Issue by hadsy** [cibernox/ember-power-select#714]
I have the simplest implementation of power-select, when you open the options and then click away from the component it doesn't close. I also noticed if you click away but inline or above the trigger component it closes as expected.

```
<div style="width: 300px">
    Multiple:
    {{#power-select-multiple options=model
                            selected=selectedThings
                            onchange=(action (mut selectedThings))
                            as |thing|}}
                            {{thing.name}}
    {{/power-select-multiple}}
</div>
```

I get the same behaviour in Chrome, IE11 & Edge.
Do I need to add anything to get the selector to close correctly when blurred?

**Comment by cibernox** [comment]
This feature is more than tested. I mean, check the documentation page by example (http://www.ember-power-select.com/). It's working there. 

Perhaps your app is not rendered in the body of the page?

**Comment by hadsy** [comment]
Pretty sure it's rendered in the right place, I've attached a screenshot below:

![power-select onblur click bug](https://cloud.githubusercontent.com/assets/1922001/19439122/df55620e-9474-11e6-98a2-2d34f75bc5b4.png)

Also I have created a [twiddle](https://ember-twiddle.com/b0b11c9b3cdb6c12a93fedf1c62eceed?openFiles=twiddle.json%2C) that shows the issue, one selector by itself 100% width, the other reduced to 300px in a div, both show the same issue, clicking anywhere below the open list of options does not close it. Cheers for any assistance.

**Comment by cibernox** [comment]
Yeah, I know what is going on. The components listen for clicks on the body to close itself. And in your case, the body ends up just after the select because it's the last thing in the document.

Make the body element be full height with this line of CSS and tell me if it works.

```css
body { min-height: 100vh; }
```

**Comment by hadsy** [comment]
Yep that fixes it! Thanks for the fast response, great component too!
