### ISSUE TITLE
clicking on option fires empty onchange action when search function returns DS.AdapterPopulatedRecordArray

### ISSUE THREAD

**Issue by clumsysnake** [cibernox/ember-power-select#719]
observed atleast on 1.0.0-beta.26

our search function returns groups in the following format:

```
[ { groupName: String, options: DS.AdapterPopulatedRecordArray }, ...]
```

However, when the user then clicks on an option the first argument to the action handler for onchange is null. When the user selects an option using arrow keys / return, the argument is present!

To work around the issue, we convert the DS.AdapterPopulatedRecordArray into a normal Array. I assume there's some difference in item lookup between the two array types that is the culprit.

**Comment by clumsysnake** [comment]
my guess is _optionFromIndex() in https://github.com/cibernox/ember-power-select/blob/master/addon/components/power-select/options.js needs to use objectAt() instead of [], if that function is present.

chasing down array incompatibility is my least favorite thing in js/ember :) but i think all Arrays are Ember.Arrays when using Ember at all, rite? so objectAt() is dependably there in this context?

**Comment by koryteg** [comment]
yup. I get this too. I am returning an array ember data models directly from a query and I have to call `toArray()` on them to make the trigger and hover work correctly. 
was doing: 

``` javascript
    _searchPromotions(query, resolve, reject) {
      this.store.query("campaign", { search_term: query }).then(function (campaigns) {
        resolve([{ groupName: "Campaigns", options: campaigns }]);
      }).catch(reject);
    },

```
now doing: 

``` javascript
    _searchPromotions(query, resolve, reject) {
      this.store.query("campaign", { search_term: query }).then(function (campaigns) {
        resolve([{ groupName: "Campaigns", options: campaigns.toArray() }]);
      }).catch(reject);
    },

```

**Comment by cibernox** [comment]
I see. I never anticipated the options to be anything other than an array, but perhaps it should be supported, if it doesn't hurt performance in the most common use case.

Can any of you provide a failing test?
