### ISSUE TITLE
Provide a hook to turn off trigger typing behavior

### ISSUE THREAD

**Issue by monovertex** [cibernox/ember-power-select#725]
I am working with a heavily enhanced ember-power-select component, that I extended via the public API and the various hooks to behave in different ways.

However, I have a hard time stopping the `triggerTypingTask` behavior in a correct manner. Before the switch to concurrent tasks, I was overriding the `_handleTriggerTyping` method, but now I have to override the `triggerTypingTask` to a dummy property, with a noop perform method.

I would greatly appreciate a hook into the `triggerTypingTask`, preferably an action, so I can decide if I want that behaviour or not.

The use case is as follows: I created a power select that can have the search input inside the trigger, based on a property. In this situation, with the `triggerTypingTask` as is, the two search methods clash and the power select behaves weirdly. I would like to turn off the trigger typing for power select instances that have the search input in the trigger.

PS: I'd be happy to provide a PR, if you could outline any requirements or guidelines for implementing this, so I don't break stuff.

**Comment by cibernox** [comment]
I'm on mobile, but one thing I do that might come handy is to stop the propagation of key down events in your custom trigger component. If they don't bubble, the default behavior is not triggered. Easy. 

Check ember-power-select-typeahead.

**Comment by monovertex** [comment]
Yeah, but that blocks off bubbling of the event. If I have other global listeners, let's say, a tooltip that has to disappear when the user clicks on another element (which is traditionally implemented via a document click listener), there is a chance that that event won't fire anymore, because HTML events have no guaranteed order of execution.

This is why preventing bubbling is bad practice for stopping other side effects. This should be only used when you specifically want to prevent the bubbling, not as a workaround.

**Comment by cibernox** [comment]
What I meant was just to prevent the building of keydown events in the A-Z range. Clicks and keydowns on other keys like arrows/enter do work. 

I'll see if a public API for that makes sejse

**Comment by monovertex** [comment]
Sorry, I meant clicks just as a general example, same goes for keyboard anyway. For example, I have a CTRL+<whatever key in A-Z range> shortcut on the page to save the current document. I have to make sure that triggers first (through more workarounds), otherwise the user won't be able to use that shortcut when they're focused in the input.

**Comment by monovertex** [comment]
This was no longer an issue in our codebase, I believe through further updates and changes on the component.
