### ISSUE TITLE
Flaky results when using an Ember Data relationship as options

### ISSUE THREAD

**Issue by fotinakis** [cibernox/ember-power-select#726]
Thanks for ember-power-select, it's awesome!

I noticed some flaky behavior when passing an Ember Data has-many relationship to `options`. I have something like this:

```handlebars
{{#power-select
  searchField="slug"
  options=organization.projects
  onchange=(action "chooseProject")
  as |project|
}}
...
```
...where `organization.projects` is an Ember Data relationship defined as `projects: DS.hasMany('project')` (which defaults to `{async: true}` which makes it a `DS.PromiseManyArray` underneath).

Now, ember-power-select renders correctly on first load, but if I navigate to a different page and come back it will show "No results found" in the dropdown. I have confirmed that the ember data relationships are not changing underneath (and rendering `{{organization.projects.length}}` into the template still shows 1 even when the select shows no results).

I am able to work around this by using `options=organization.projects.content` which uses the un-proxied result object, but `.content` is a private API that I would like to not rely on.

Perhaps this is something ember-power-select could handle natively?

**Comment by cibernox** [comment]
This is weird. I use has many relationships often and I haven't seen it. Are you using the latest version? If so, I'd love a reproduction so I can track it down.

**Comment by fotinakis** [comment]
Yup, this is with an ember + ember-data 2.8.0 app. I'll see if I can put together a reproduction this week.
