### ISSUE TITLE
Allow the selected value to be a key of the options objects

### ISSUE THREAD

**Issue by SirZach** [cibernox/ember-power-select#731]
My options look something like:
```
options: [ { id: 1, name: 'a' }, { id: 2, name: 'b' }]
```
and my selected value is just the id, so
```
selected: 1
```

However, when I do
```hbs
{{#power-select
  options=options
  selected=selected
  onchange=(action 'updateSelected')
  as |option|
}}
  {{option.name}}
{{/power-select}}
```

The power-select component doesn't show `a` as selected since `1` does not equal the first object in the options array. If there was a key I could use to match on then I could get around this problem. Thanks.

**Comment by cibernox** [comment]
This is by design. The selected value has to be one element of the list. 

Easy trick:

```hbs
{{#power-select options=options 
  selected=(find-by id selectedId options) 
  onchange=(action (mut selectedId) value="id") as |opt|}}
  {{opt.name}}
{{/power-select}}
```

**Comment by SirZach** [comment]
Will give it a whirl. Thanks!
