### ISSUE TITLE
Pulling up API-based suggestions on focus

### ISSUE THREAD

**Issue by eflorit** [cibernox/ember-power-select#733]
Hello,

I'm trying to trigger a search request when the user clicks the `power-select-multiple` box so that they get the most popular suggestions even before they start typing. Unfortunately I can't get it to work because the `search` action requires a non-empty string as its parameter. Is what I'm trying to achieve possible without hacking too much?

Thanks!

**Comment by cibernox** [comment]
In EPS you can combine `options=` and `search=`, they are not mutually exclusive, so you can pass the frequent options (and empty array at first) and populate it on focus so they are lazy.

```hbs
{{#power-select-multiple 
  options=frequentOptions 
  search=(action "searchStuff")
  onfocus=(action "initializeFrequentOptions") as |opt|}}
{{/power-select}}
```

```js
frequentOptions: null,
actions: {
  initializeFrequentOptions() {
    if (this.get('frequentOptions') === null) {
      let opts = this.get('store').query('whatever', { frequent: true }); 
      this.set('frequentOptions', opts);
    }
  }
}
```

**Comment by cibernox** [comment]
Let me know if it works for you.

**Comment by eflorit** [comment]
@cibernox Yep, that works. Thanks!
