### ISSUE TITLE
No options in Navigateable select example in Cookbook

### ISSUE THREAD

**Issue by chilicoder** [cibernox/ember-power-select#734]
when I open the page in Chrome and Safari
http://www.ember-power-select.com/cookbook/navigable-select

It shows this

<img width="719" alt="screen shot 2016-11-17 at 09 35 57" src="https://cloud.githubusercontent.com/assets/3491833/20381792/5a888f36-aca9-11e6-907d-7d337ccf5da1.png">

**Comment by cibernox** [comment]
Fixed. Some kind of incompatibility between glimmer2 and liquid-fire. Updating the latter fixed it.
