### ISSUE TITLE
textMeasurer undefined

### ISSUE THREAD

**Issue by mize85** [cibernox/ember-power-select#737]
Hi @cibernox ,

Just updated ember-power-select from  0.10.1 to 1.0.0-beta.31 which resulted in an unexpected error when using power-select-multiple

_"trigger.js:60 Uncaught TypeError: Cannot read property 'width' of undefined(…)
(anonymous function)	@	trigger.js:60"_

looks like "textMeasurer" service is injected, but there is no textMeasurer service in this version anymore (or i can't find it) :(

Any ideas how to fix that?

**Comment by cibernox** [comment]
No idea, that service still exists and its used. Do you depend on any other `ember-power-select-***` meta-addon?

**Comment by mize85** [comment]
Thx for fast reply @cibernox ,
re-installing node-packages solved it. Sry, my fault. 
Keep on the good work!
