### ISSUE TITLE
update docs/the-trigger#selected-option 

### ISSUE THREAD

**Issue by ngouy** [cibernox/ember-power-select#738]
I recently update ember-power-select from an old version to the one at master.
I didn't try for 'single' power-select, but for multiple-power-select with selectedItemComponent, the keyword to access the selected item into the component is no more 'selected' but 'option'.

looking at the file  addon/templates/components/power-select-multiple/trigger.hbs

'selected' removed first => https://github.com/cibernox/ember-power-select/commit/af45d724a73915fcf4e805a7355fba3c4051f5d8#

then replaced by 'option' => https://github.com/cibernox/ember-power-select/commit/28214cbf2f23cb669e1f049291942d4460aa8bf8

Thanks a lot for this addon. Cheerz

edit: 

looking at https://github.com/cibernox/ember-power-select/blob/master/addon/templates/components/power-select/trigger.hbs on master, it seems to be the same thing for 'single' power-select.

**Comment by cibernox** [comment]
Yep, the docs were outdated there. Fixed.

Thanks for the heads up.
