### ISSUE TITLE
onblur action not being invoked

### ISSUE THREAD

**Issue by algodave** [cibernox/ember-power-select#739]
The `onblur` action doesn't seem to be invoked. Just tried to add `onblur=(action "handleBlur")` to the example in [docs/action-handling](http://www.ember-power-select.com/docs/action-handling) and dummy actions like this:

```javascript
actions: {
    handleFocus() {
      Ember.Logger.debug('focus');
    },
    handleBlur() {
      Ember.Logger.debug('blur');
    }
}
```

I only have `focus` logged twice when clicking on the select, but no `blur` is logged when I click outside of the select. I've walked through your code but couldn't find where the bug is at a first glance.

**Comment by cibernox** [comment]
I'v just checked it and it seems to work. I've updated the demo page to also log the blur event so you it can also be seen in action: http://www.ember-power-select.com/docs/action-handling

**Comment by cibernox** [comment]
I've also tested in multiple selects and also seems to work. Can you provide a reproduction?

**Comment by algodave** [comment]
Thanks @cibernox for the prompt reply :)
I didn't have the time yet to provide you a full reproduction, the only difference I can see in my case is that I don't have any other form elements in my page together with the power-select.
I only have text, and I would expect the select to loose focus when I click on some text outside the select.
Thanks for updating the example in the docs as well!

**Comment by cibernox** [comment]
I don't see the number of elements in the page affecting the result. Just to check, are you up to date on the version?

**Comment by algodave** [comment]
Yes, I've also tried with master.
