### ISSUE TITLE
accesskey to shortcut to trigger?

### ISSUE THREAD

**Issue by ScottSmix** [cibernox/ember-power-select#741]
I have tried a few things with triggerComponent and before-options but can't seem to find success around "accesskey". I want to set focus to the trigger component via the access key. Am I missing something?

**Comment by cibernox** [comment]
I confess that I've never heard in my life of this `accesskey` thing. I suspect that this change would have to be done in `ember-basic-dropdown` (probably [here](https://github.com/cibernox/ember-basic-dropdown/blob/master/addon/components/basic-dropdown/trigger.js#L26)) and then this addon should just forward that attribute to the trigger.
