### ISSUE TITLE
With Ember 2.9.1: Could not find module `ember-component` imported from `ember-power-select/components/power-select` with Ember 2.9.1?

### ISSUE THREAD

**Issue by flyrev** [cibernox/ember-power-select#743]
I pasted the simple example (I did not expect it to actually work, but I expected it to only complain about the missing action/whatever):
                {{#power-select
                  search=(action "searchRepo")
                  selected=selected
                  onchange=(action (mut selected))
                  as |repo|
                  }}
                  {{repo.full_name}}
                {{/power-select}}

But I get:
loader.js:219 Uncaught Error: Could not find module `ember-component` imported from `ember-power-select/components/power-select`

**Comment by cibernox** [comment]
Do you have `"ember-cli-shims"` in your bower.json? It's added by default on all ember-cli projects, but seems that you don't have it.

**Comment by flyrev** [comment]
You are indeed correct! Deepest thanks.
