### ISSUE TITLE
Possible memory leak or race condition

### ISSUE THREAD

**Issue by Keeo** [cibernox/ember-power-select#744]
Selects tend to open/close slower and slower, especially ones with large amount of options. In one point it won't work correctly anymore - leaving options on left top corner of the screen. We were able reproduce it for at least few weeks. It is also happening in current build - ember 2.10.0 with ember-power-select v1.0.0-beta.31 and can be reproduced (after some time) on www.ember-power-select.com. Because there are only three options it will take some time - for me it took 2 mins of clicking while recording heap allocations in chrome to slow cpu down.
![power-select-bug](https://cloud.githubusercontent.com/assets/4613001/20761397/2b85ee2a-b723-11e6-867c-6532b3b899b7.png)

**Comment by cibernox** [comment]
Interesting. I tracked on memory leak a few weeks ago. I'll investigate this one.

**Comment by Keeo** [comment]
I did little more testing:
 - both bugs occur even in v1.0.0-beta.**1** (ember 2.10.0)
 - to force it to render options outside you have to open it while it is still closing

**Comment by cibernox** [comment]
I tried to reproduce it now, taking snapshots of the heap in dev tools and i don't see any evidence of leak. The memory starts consistent after thousands of open/closes.

Can you check that too?

**Comment by Keeo** [comment]
I tried it on our app and it was not able to `build dominator tree` in reasonable time after ~20 open/closes.

1. 1 open/close
2. +10 open/close
3. +5 open/close
4. just 10 minutes of waiting

EmptyObject root was the stronger one propagating up but most of them grew.

![snapshot](https://cloud.githubusercontent.com/assets/4613001/20776112/e57518f2-b75e-11e6-8352-7975b4fba138.png)

**Comment by Keeo** [comment]
I tried to measure it on www.ember.power-select.com and noticed that it may not be so good idea to test memory leaks in dev environment. So I retested it under production settings and it did not leak any memory nor it slowed down.
I think that leaves us just with `opening it while it is closing`.

**Comment by cibernox** [comment]
I'll build an example with a couple hundred items to see if I can reproduce it. Are you using as options anything special, like arrayproxys, promises or things alike?

**Comment by Keeo** [comment]
I removed stuff that is not required and this is still able reproduce issue in dev environment.

```js
{{#power-select
options=staticData.currencies //service
onchange=(action "propertyDidChange" "currency") //empty function
as |currency|}}
  {{currency.name}}
{{/power-select}}

export default Ember.Service.extend({
  load() {
    const currencies = this.get('store').peekAll('currency'); // length == 179
    this.set('currencies', currencies);
  },
});
```

**Comment by Keeo** [comment]
I created minimal repo that is able to reproduce the issue [power-select](https://github.com/Keeo/power-select-ml)

**Comment by cibernox** [comment]
I cloned the repo. While I see a small increase in the memory (from ~20mb to ~27mb after a minute clicking) nothing very dramatic. Not enough to make it crash.

I've tried to track the leak but I don't see anything. I'll ask for help for more expert debuggers than me to see if I find the issue.

**Comment by Keeo** [comment]
Thank you, do you want to create separate issue for the bug from screenshot?

**Comment by Keeo** [comment]
I am going to close this one since the memory leak issue which is small and present only in debug env is hardly a problem and having "memory leak" word in issue tracker is scary. I'll create new one because of the opening while closing bug tho.
