### ISSUE TITLE
Having to press enter twice when opening the dropdown automatically?

### ISSUE THREAD

**Issue by flyrev** [cibernox/ember-power-select#745]
On http://www.ember-power-select.com/docs/action-handling , in the section called "onfocus/onblur Actions", it works nicely to focus the text field, then TAB, and then type, but when the correct search result appears I have to press enter *twice*. Why is that? If it's intended, it seems rather buggy. :-)

**Comment by cibernox** [comment]
Good catch. Just open when the component gets the focus was too naive, it had to open when the component gets the focus and the previously focused element was not already inside the select. 

Thanks
