### ISSUE TITLE
allowClear=true does not clear properly

### ISSUE THREAD

**Issue by kdelvare** [cibernox/ember-power-select#746]
With this code :
```
{{#power-select selected=selected onchange=(action 'onchange') allowClear=true as |person|}}
	{{person.lastName}} {{person.firstName}} - {{person.company.name}}
{{/power-select}}
```

if I try clearing the selection, I'm left with the second part still there ("- companyName")

**Comment by cibernox** [comment]
Can you provide a reproducible example maybe using ember-twiddle? This is pretty tested, so if I had to guess I'd say that there is something odd in your `onchange` action. Can you paste it?

**Comment by kdelvare** [comment]
There was something odd with my selected item, where I build a hash to get the company value inside. I will have to do it cleaner.
