### ISSUE TITLE
I am not able to pass any variable to custom trigger component

### ISSUE THREAD

**Issue by amitkumarchauhan1987** [cibernox/ember-power-select#756]
Hi Guys,

I have written the custom trigger component.
I want to pass some variables value from power-select-multiple to this component,
Is It possible to do.

**Comment by cibernox** [comment]
Yes, check the`extra` option in de docs. It's a bag where you can pass anything. 

Also, you can do `triggerComponent=(component "my-trigger" foo=bar)`, like with any contextual component in Ember

**Comment by amitkumarchauhan1987** [comment]
Thanks :+1:
