### ISSUE TITLE
onkeydown example not working

### ISSUE THREAD

**Issue by andreiciceu** [cibernox/ember-power-select#758]
Hello,

The onkey down example provided on this page is not working
http://www.ember-power-select.com/docs/action-handling

Javascript throws the following error:
`Uncaught TypeError: this.get(...).pushObject is not a function(…)`

Replacing initialization of options with Ember.A() prevents the error.

**Comment by cibernox** [comment]
Good catch, fixed it. I forgot I've disabled prototype extensions.
