### ISSUE TITLE
Dropdown closes instantly on mobile

### ISSUE THREAD

**Issue by vladstanca** [cibernox/ember-power-select#760]
The dropdown disappears right away on  mobile browsers. I've tested it on Android Chrome and I've heard from someone that it's also not working in Safari. To verify, I tried loading the power select website and none of the examples work in Chrome on Android. Older versions worked fine on mobile.

**Comment by cibernox** [comment]
I have a fix waiting for travis. It will be released in ~15m

**Comment by cibernox** [comment]
@vladstanca The fix was performed in ember-basic-dropdown. The dependency of EPS in EBD is relaxed, so if you clean your node_modules folder and you'll get the new version and it should be fixed. 
If you are using yarn you have to run `yarn upgrade`
