### ISSUE TITLE
Does not work with ember-engines

### ISSUE THREAD

**Issue by dustinfarris** [cibernox/ember-power-select#771]
This is actually an issue with ember-wormhole—just leaving a reference.

See: https://github.com/yapplabs/ember-wormhole/issues/84

**Comment by mydea** [comment]
Just as a comment for anyone running into this, it does work when using `renderInPlace=true`.

**Comment by cibernox** [comment]
This is interesting. @mydea So when running in engines the placeholder doesn't gets added to the `index.html`?

I wonder if this is something engines should take care of. Perhaps they should detect at build time the hooks of all the addons and hoist them to the parent app.

**Comment by mydea** [comment]
Apparently not, I got an error that the DOM element couldn't be found.

**Comment by cibernox** [comment]
I just tested it. It does work if you explicitly pass (and receive) the `-document` service of the container app.
I asked in slack and they are considering automatically inject all private services into engines, which would solve this issue.

In the meanwhile, you can pass it yourself and seems to work.

**Comment by cibernox** [comment]
I'm closing this since it seems to be a fundamental issues with engines, not something the addon can do anything about.
