### ISSUE TITLE
Cannot create custom option with substring of existing options

### ISSUE THREAD

**Issue by musaffa** [cibernox/ember-power-select#772]
In the Cookbook example for [create-custom-options](http://www.ember-power-select.com/cookbook/create-custom-options), if I try want create a `york` option, it selects the existing `New York` option. This is problematic. For example, in my tag implementation, I search tags from the API server and create a tag if it doesn't exist. Say, I have a `ember-cli` tag already in my server. Now I want to create an `ember` tag. If I search for `ember`, it will return `ember-cli` as a possible candidate. But I hit enter it will select `ember-cli` instead of creating a new `ember` tag.

**Comment by cibernox** [comment]
Yes, that example is a bit naive and doesn't try cover all edge cases. In those cases I prefer to take an approach like https://github.com/cibernox/ember-power-select-with-create, which adds an fake option `Create "foobar"`. That would work for you?

**Comment by musaffa** [comment]
@cibernox It works! Thanks.

It would be helpful for others as well if you add a link to this addon in that Cookbook example.
