### ISSUE TITLE
multiple select allows you to select the same object twice when the underlying collection is generated again.

### ISSUE THREAD

**Issue by jackmatt2** [cibernox/ember-power-select#777]
I am using the multiple select on my page like this:

``` javascript
    {{#power-select-multiple
      class="groupSources"
      options=model.groupSources
      selected=queryFilters.groupSources
      placeholder=""
      onchange=(action (mut queryFilters.groupSources)) as |item|}}
      {{item.label}}
    {{/power-select-multiple}}
```

`queryFilters` is an Ember.Service that stores the selected filters so that when the user returns to the page their selection sticks around.

When I go to the page for the first time everything works, you can toggle selection by repeatedly selecting the option from the dropdown list.

When navigating away from the route and back again, the options are correctly displayed as selected but I am able to select the option again from the drop down.

I think this is because of the fact the the object reference has changed in the underlying collection so it thinks they are different.

I am not sure exactly the solution but maybe some sort of comparator function that determines equality.

![screen shot 2017-01-12 at 11 51 17 am](https://cloud.githubusercontent.com/assets/6348088/21872606/778b6c94-d8bd-11e6-87f4-05eb6c04496b.png)

**Comment by cibernox** [comment]
It is indeed because the object, although it has the same values, it's a different object.
If you can find a way of making those objects be the same you can dodge this problem, but I believe #773 is going to help you with this. I haven't had time to implement it.

**Comment by cibernox** [comment]
I've implemented that issue, so now instead of just using `===`, this addon will use the `isEqual(other){}` function on the object if available.

This will probably make easy for you to fix this.
