### ISSUE TITLE
Prevent input from being cleared when input is clicked out of

### ISSUE THREAD

**Issue by sarus** [cibernox/ember-power-select#786]
On the example page for "Creating Custom Options" if you start to type into the input and then click out of the input the text you already entered is cleared:

http://www.ember-power-select.com/cookbook/create-custom-options

Is there a way to prevent this behavior?  It seems unexpected to me when the use case for the input allows for a new entry to be created (e.g., if a user is typing something in like a name, then clicks out to copy or paste, selects another input etc. then clicks back the text is gone).

In older versions I saw a `handleClose` method on the trigger (https://github.com/cibernox/ember-power-select/commit/ceace2bd31a81229256e9e4fe2ab47fc70845326) that was clearing the search input but this seems to be old code that doesn't exist anymore.

I also saw this issue #436 but based on that alone wasn't able to figure out how I might create the behavior I'm looking for.

Best Regards,

Ed

**Comment by sarus** [comment]
okay so right after I posted this I came across `trigger.js` `didReceiveAttrs`.

```
   didReceiveAttrs: function didReceiveAttrs() {
      var oldSelect = this.get('oldSelect') || {};
      var select = this.set('oldSelect', this.get('select'));
      if (oldSelect.isOpen && !select.isOpen) {
        (0, _emberRunloop.scheduleOnce)('actions', null, select.actions.search, '');
      }
    }
```

If I override this method with a custom trigger then it does prevent the input from being cleared.  However, now when a new  custom "option" is created it doesn't clear the typed in text.  Investigating a bit more to see if I can come up with a way to clear the input only if a new option is created (not everytime the input loses focus)

**Comment by sarus** [comment]
Overriding `didReceiveAttrs()` on `power-select-multiple/trigger` seems to do what I want:

```
  didReceiveAttrs(){
    let oldSelect = this.get('oldSelect') || {};
    let oldSelectedCount = oldSelect.selected ? oldSelect.selected.length : 0;
    let select = this.set('oldSelect', this.get('select'));
    let selectedCount = select.selected ? select.selected.length : 0;
 
    if(oldSelectedCount !== selectedCount){
      scheduleOnce('actions', null, select.actions.search, '');
    }
  }
```

Still testing a bit to see if I inadvertently caused a bad side effect..

**Comment by cibernox** [comment]
Yes, the trigger of the multiple select it's created when the trigger gets cleared that way.

You can create your own trigger that has a different behaviour. As long as within the `didReceiveAttrs` you only use the properties and actions of the `select` object, which is 100% public API, you should be fine.

**Comment by sarus** [comment]
Awesome thank you!
