### ISSUE TITLE
clear-search button

### ISSUE THREAD

**Issue by ngouy** [cibernox/ember-power-select#787]
Hello,

Is there a way to get rid of this little grey cross button (used to clear search) ?

<img width="504" alt="screen shot 2017-01-19 at 13 06 09" src="https://cloud.githubusercontent.com/assets/12391171/22106303/6829fc80-de48-11e6-8840-1dfe85473fd7.png">

I'm not able to do it even after inspecting and DOM farming, it's inside the input but not in an :after :before selector, not in background-image etc ... 

and i need to remove it

**Comment by cibernox** [comment]
This is actually not something of ember-power-select. It's something your browser does with all `<input type="search">`. There is probably a way of hiding it with css. Perhaps `-webkit-appearance`?

**Comment by ngouy** [comment]
Thanks a lots for you so quick answer. I'll take a look at this. I suspected it but ember-power-select is the only place I see it.

**Comment by ngouy** [comment]
Solution here 
http://stackoverflow.com/questions/18856246/input-type-search-hide-the-icons

Thank you again.

**Comment by cibernox** [comment]
Good to know too! 👍
