### ISSUE TITLE
Extra in custom options component

### ISSUE THREAD

**Issue by balajimanoharan** [cibernox/ember-power-select#789]
In our application, we had built a custom options component that relied on the `extra` property passed in. We were using v0.10.11 until recently, when we had to upgrade ember. 

We could reopen the template and make the change. 
Was there a reason that the property was removed from the options component?

**Comment by cibernox** [comment]
@balajimanoharan No reason actually, I probably removed it by mistake.
I'd take a pull request to pass it again to the options component if you feel in the mood.

**Comment by balajimanoharan** [comment]
sure

**Comment by balajimanoharan** [comment]
@cibernox https://github.com/cibernox/ember-power-select/pull/790
