### ISSUE TITLE
How to use this with options as collection of Objects?

### ISSUE THREAD

**Issue by kishorekpoluri** [cibernox/ember-power-select#791]
I am trying to get this working with Collection of Objects as Options with id and label as properties in Object. But the selected one is never highlighted.

**Comment by cibernox** [comment]
Check this page of the docs (http://www.ember-power-select.com/docs/how-to-use-it), particularly this: **remember that in JS objects are compared by reference...**

The selected option has to be the exact same object contained in the collection of options. Not one with the same values, the **same** object.

**Comment by cibernox** [comment]
Closing this, let me know if the docs don't solve your question.
