### ISSUE TITLE
Is it possible to have a different HTM for options list and selected list in power-select-multiple?

### ISSUE THREAD

**Issue by masciugo** [cibernox/ember-power-select#792]
For example in the following case:

<img width="383" alt="screen shot 2017-01-20 at 15 56 20" src="https://cloud.githubusercontent.com/assets/454321/22153773/071ecad8-df29-11e6-8f97-2e344f468132.png">

I would like to only have the currency code in the selected list while keeping the whole description in the option list. Is it possible?

**Comment by cibernox** [comment]
Sure it is: http://www.ember-power-select.com/docs/the-trigger
