### ISSUE TITLE
Add html global attributes to power-select 

### ISSUE THREAD

**Issue by ykaragol** [cibernox/ember-power-select#795]
At least the following 2 [global attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes) are needed for use:

- title
- hidden

**Comment by cibernox** [comment]
The title should be easy, since ember-basic-dropdown already supports it. We just need to pass it forward. 
Hidden is not implemented, so it would require changes in both projects. While I don't oppose to this one, it find it rather useless, when you could just wrap the component in a `{{#if}}`
