### ISSUE TITLE
Upgrade guide

### ISSUE THREAD

**Issue by eddiesholl** [cibernox/ember-power-select#796]
I have recently run an upgrade of dependencies after rolling our ember version, this library was upgraded to clean up the ember-owner-polyfill deprecation warning. I ran into a couple of changes needed after the upgrade, and couldn't find them listed anywhere. I was upgrading from 0.8.6 to 1.4.0.

Is there any use in documenting these breaking changes? I haven't yet tracked the changes to which specific version introduced them. If it was before 1.0, i guess they were still considered unstable.

In my case the breaking changes were yielding the full options object instead of just lastSearchedText, and passing the selected item as option instead of selected to the custom selectedItemComponent.

**Comment by cibernox** [comment]
The changelog is what you're looking for.
