### ISSUE TITLE
Docs website didn't open 

### ISSUE THREAD

**Issue by AhmedShawkyPW** [cibernox/ember-power-select#798]
When i open docs website, the website didn't open, when i checked console i found below error 

```console
http://www.ember-power-select.com/assets/vendor-c9f712e7f5eb558985d69d7a1f48158a.js Failed to load resource: net::ERR_CONNECTION_RESET
```

**Comment by cibernox** [comment]
I don't know that might going on, but I can open it. Could you check again?

**Comment by cibernox** [comment]
This seems to work, so I'm closing it.
