### ISSUE TITLE
PhantomJS 1.9 acceptance tests fail

### ISSUE THREAD

**Issue by lan0** [cibernox/ember-power-select#80]
We tried out `ember-power-select` instead of `ember-cli-selectize` for one of our components today, but the acceptance tests fail with `TypeError: 'null' is not an object (evaluating 'dropdown.removeEventListener')`.

The Error happens here (there is only one big vendor.js when debugging with the PhantomJS debug port):

```
var dropdown = this.appRoot.querySelector('.ember-basic-dropdown-content');
dropdown.removeEventListener('DOMNodeInserted', this.repositionDropdown);
```

In Chrome everything runs fine.

**Comment by cibernox** [comment]
Interesting. Are you using phantom 1.9.X or 2.0?

**Comment by lan0** [comment]
1.9.X

**Comment by cibernox** [comment]
I've run the tests of this in phantomjs 2.0 so far. Perhaps phantomjs 1.9.X doesn't support `DOMNodeInserted`, I'll check it. 

Phantomjs 1.9.X is extremely buggy in general, so I'm not very surprised :disappointed:

**Comment by cibernox** [comment]
In the meanwhile, I suggest giving phantomjs 2.0 a try. It was worked much better for me.

I'll try to look at it next week.

**Comment by lan0** [comment]
Works in phantomjs 2.0 :+1:

**Comment by cibernox** [comment]
Yeah, phantomjs 2.0 works is waaay more reliable in every aspect for me, I don't understand why it's not the default in travis-ci.

I will investigate this anyway to see if it's a low hanging fruit

**Comment by wayne-o** [comment]
I've been getting the same issue and tried to ugrade phantom - Whats the best way to install phantom 2? ```npm install phantomjs2```  seems to break my testem runner in that the browser spins up and the tests pass but the terminal view seems to just hang there... 

https://www.npmjs.com/package/phantomjs2

**Comment by miguelcobain** [comment]
@wayne-o I would use homebrew to install it on osx or linux.

That npm wrapper was broken the last time I've tried it.

**Comment by wayne-o** [comment]
OK - that's what I ended up looking into - will give that a spin :)

**Comment by wayne-o** [comment]
Yeah - it still works in the browser but when I run ```ember test --server``` it never moves from ```Waiting for runners...```

**Comment by cibernox** [comment]
`phantomjs -v` outputs `2.0.0` ? Because perhaps the old phantomjs is taking precedence over the one you just installed now.

**Comment by wayne-o** [comment]
hmmm:

➜  sonatribe-ui git:(infinity) ✗ phantomjs -v
zsh: command not found: phantomjs

**Comment by cibernox** [comment]
I guess that you've found the problem :grin: 

I guess that either phantomjs is not installed or the directory where it's installed is not in your path. 
For me brew installed it properly:

```
$ which phantomjs
/usr/local/bin/phantomjs
```

**Comment by wayne-o** [comment]
I think this is my problem :
https://github.com/Homebrew/homebrew/issues/42249

:/

**Comment by felixkiss** [comment]
@wayne-o If you are on OS X 10.11 try this for now: https://github.com/Vitallium/phantomjs/releases/tag/2.0.1

Download it and place it somewhere in your $PATH (e.g. /usr/local/bin)

**Comment by wayne-o** [comment]
swoosh!! working! after a bit of a jigg and dance with brew and openssl :)

**Comment by luketheobscure** [comment]
It would be helpful leaving a notice in the documentation that this project requires PhantomJS >= 2.0. Just lost an afternoon trying to figure out why my tests were failing on our CI.

I did find [this polyfill](https://github.com/conversocial/phantomjs-polyfill) that helps with `.bind` in ember-power-select, but there's another bug in `ember-basic-dropdown` that I wasn't able to get past.

**Comment by felixkiss** [comment]
+1 for a warning. We solved it by migrating to PhantomJS 2.0

**Comment by cibernox** [comment]
@luketheobscure @felixkiss Actually there is already a warning in the readme, in the browser support section.

**Comment by felixkiss** [comment]
Can be closed then.

**Comment by luketheobscure** [comment]
I'm 0/3 for useful comments. I'll see myself out...

**Comment by cibernox** [comment]
@luketheobscure I'd take a PR to make it bold or something :rocket:
