### ISSUE TITLE
Passing costum classNames to power-select does not work

### ISSUE THREAD

**Issue by badazz91** [cibernox/ember-power-select#800]
When passing a custom classNames like this: 

```{{power-select classNames="some-class" ...}}``` the "some-class" class does not get added to the class attribute of the DOM-node.

Otherwise when doing the same thing with ```power-select-multiple``` - it works.

Is this intended? Or simply misusage from my side?

**Comment by cibernox** [comment]
The component is supposed to be tagless (the fact the the multiple select isn't it an error on my side that I have to fix). 
You are expected to use `triggerClass` or `dropdownClass`. 

The [API REFERENCE](http://www.ember-power-select.com/docs/api-reference) is the best reference for this.

**Comment by badazz91** [comment]
Ok thanks.
