### ISSUE TITLE
How to use the Bootstrap theme with less

### ISSUE THREAD

**Issue by mariowilde** [cibernox/ember-power-select#804]
Thank you for ember-power-select it's an indispensable component for our application.
Unfortunately am unable to get the new less Boostrap theme to work in ember-power-select 1.3.0 and 1.4.3.

In ember-power-select <=1.0.0 we had an app.scss file just for ember-power-select and declared the bootstrap theme in ember-cli-build.js. 

This stopped working in ember-power-select >= 1.3.0.
Thus we decided to switch to less completely and import ember-power-select in app.less instead of app.css.
The Cookbook states that non-SASS user should still declare the theme in ember-cli-build.js, but this seemed to have no effect.
After that we tried to import the bootstrap theme before ember-power-select in app.less, but the result was not as expected. For example, @ember-power-select-selected-background was still blue (#5897fb) instead of light gray (#f5f5f5).
Does variables.less (imported via ember-power-select.less) override themes/bootstrap.less?

This leads to my question:
What is the correct way to use the Bootstrap theme with less?

**Comment by cibernox** [comment]
I haven't tested the themes in less since I myself only use sass but I'll check it.

**Comment by cibernox** [comment]
I've just tested it, but because of how less works (as opposed to sass) the theme has to go AFTER the global styles

This thing worked for me.
```less
// app.less
@import 'ember-power-select';
@import 'ember-power-select/themes/material';
```

**Comment by cibernox** [comment]
I'm closing this, let me know if it works.

**Comment by mariowilde** [comment]
Thanks for the quick and helpful response.
I think technically your suggestion works .
The less Bootstrap theme plus our own styles in less still look a slightly different than the sass Bootstrap theme with modifications in less .
But I guess it is "more correct" now.
Thank you.
