### ISSUE TITLE
Code given for onfocus does not seem to be working anymore!

### ISSUE THREAD

**Issue by feanor07** [cibernox/ember-power-select#805]
Official [documentation page](http://www.ember-power-select.com/docs/action-handling) shows a good example to automatically open an EPS upon focus event. However, this does not seem to be working with latest release (1.4.3 as of 02.01.2017) anymore. See the [twiddle](https://ember-twiddle.com/0b92fae257f817943e595f78a0f8de11?openFiles=twiddle.json%2Ctemplates.components.modified-onfocusexample.hbs) I prepared to illustrate the case. I also modified the code a little bit to get it working; but I am not quite sure about it. Can you verify the documentation is indeed problematic with version 1.4.3 and can you update the example if possible.

Note: I tried with Chrome 55.0.2883.87 m (64-bit) version; in case it is important.

**Comment by cibernox** [comment]
Thank's for reporting. It's weird. It is working in the official docs, and the docs use the latest release.
But it is failing indeed in the twiddle. I don't know why in the twiddle it would behave differently and `event.relatedTarget` would be nil. Perhaps it doesn't work on iframes?

Have you encountered this outside twiddle?

**Comment by cibernox** [comment]
I've updated the docs with your approach.
