### ISSUE TITLE
Repeated open/close user actions increasingly slow down in Chrome (possible memory leak)

### ISSUE THREAD

**Issue by monovertex** [cibernox/ember-power-select#807]
I noticed the following situation while using a heavily modified version of EPS in our app. If the user repeatedly opens and closes the EPS dropdown, given a large number of options in the dropdown, the render time of the dropdown on each open will steadily increase.

For our customized EPS, the increase of lag duration feels almost exponential. Initially I was thinking there was some memory leak in our custom code, so I created a small, basic test, with the original EPS, no customizations.

Given a large enough list of options, the increase of the slowdown becomes noticeable with the basic EPS as well. 

This can also be observed with the Ember Inspector, in the Performance tab. The rendering time of the dropdown view becomes larger and larger. 

[Here is a really simple twiddle](https://ember-twiddle.com/a67adca04baac1fdd41a3b0226a89fb9). Note that you have to open it a few times until it starts lagging. I'd say around 10-15 times until the delay of the dropdown opening becomes noticeable.

A few notes and observations:
* It only happens on Chrome, Firefox does not have this issue.
* I tested this on the latest Chrome version, on a mid-range Windows laptop, high-end Windows PC and mid-range Linux laptop. It seems that platform or hardware performance are not affecting this issue.
* **It affects all EPS instances globally**, it is not particular to the instance that you repeatedly open. This means that, given enough time, our app can become increasingly slow while the user normally opens EPSs throughout the app.
* I tried to find a memory leak using the Chrome memory profiling tools, but I'm not too experienced with them and did not manage to find anything relevant. Furthermore, all the objects and constructs used by Ember significantly inhibit this process.
* Finally, I am not convinced that this is an EPS issue, but I'm stumped about it and don't know how to proceed. I am opening this issue hoping someone has any idea what's going on.

I would be more than happy to investigate this further and potentially help with a fix, if anyone has any idea on how to proceed.

**Comment by cibernox** [comment]
I've noticed this too. In my tests this issue was only in development but in production was fine, and had something to do with some a recent change in ember for using a weakmaps internally. 

Could you verify that such leak doesn't exist if you build the app in production?

**Comment by monovertex** [comment]
Well, now I feel stupid. I got so engrossed in the debugging that I didn't try that at all. Indeed, the slowdown doesn't occur in a production build.

I'm guessing this is some sort of issue in Chrome when dealing with weak maps. 

Would a note in the docs make sense to cover this? I know it's not an EPS issue, but maybe other people will hit this problem and at least they'd know what's causing it.

**Comment by cibernox** [comment]
Don't feel bad, I also spent a good part of an afternoon looking at memory profiles before @rwjblue pointer me to test it in production.

I don't think we should document bugs *in ember* in the docs of this addon (I also think I remember a fix was on its way. Docs are about API and usage.

The title of this issue is pretty descriptive. If anyone searches for "memory leak" in github they will read this.

**Comment by cibernox** [comment]
Thanks for caring!

**Comment by monovertex** [comment]
Thanks for pointing me in the right direction and the great work on this addon!
