### ISSUE TITLE
Document a suggestion to add test globals to test jshint

### ISSUE THREAD

**Issue by pdougall1** [cibernox/ember-power-select#809]
on [this page](http://www.ember-power-select.com/docs/test-helpers) it would save n * 20 minutes of frustration to suggest the globals  (selectChoose, selectSearch, removeMultipleOption and clearSelected) be added to the `test/.jshintrc`.  It might seem obvious to some but definitely not all 😄 

Thanks for all the great work and the great addon!

**Comment by cibernox** [comment]
If you fancy creating a PR with what you think would be the right explanation, the docs page is just part of this repo. This would be the place: https://github.com/cibernox/ember-power-select/blob/master/tests/dummy/app/templates/public-pages/docs/test-helpers.hbs

It also worth mentioning ESLint.

**Comment by bgentry** [comment]
For eslint I believe `tests/.eslintrc.js` looks like:

```js
module.exports = {
  env: {
    embertest: true
  },
  globals: {
    selectChoose: true,
    selectSearch: true,
    removeMultipleOption: true,
    clearSelected: true,
  },
};
```
