### ISSUE TITLE
power-select-multiple onfocus/onblur

### ISSUE THREAD

**Issue by wmlele** [cibernox/ember-power-select#816]
I am having issues with power-select-multiple, where, after the selected value has changed the first time, each subsequent click in the input area causes multiple calls of the onfocus/onblur actions.

My code is pretty much as the given example:

```
{{#power-select-multiple
  options=names
  selected=name
  placeholder="Select some names..."
  onchange=(action (mut name))
  onfocus=(action "onFocusAction")
  onblur=(action "onBlurAction")
  as |name|
}}
  {{name}}
{{/power-select-multiple}}
```

The issue seems not to happen if name is not mutated.

**Comment by cibernox** [comment]
can you create a twiddle to reproduce it? I guess that if the action is being called several times is because the focus event is really being fired that many times.
