### ISSUE TITLE
Clicking the Trigger does not show the List or Search

### ISSUE THREAD

**Issue by cottrellio** [cibernox/ember-power-select#83]
First off just wanted to say this addon looks awesome. Love the idea of "built from the ground up in Ember", but I need some help getting it to work.

I Just updated our app to use Ember 1.13.9 to try out ember-power-select.

**The Issue**
When I click the trigger nothing pops down. Here's a screenshot: http://d.pr/i/1kldg

I've tried passing an empty list with a `noMatchesMessage` which doesn't show either. Also tried the `{{else}}` method for an empty list. 

**Here's my code:**
template
```
{{#ember-power-select placeholder="Filter By Location"
                      options=options
                      selected=selectedLocation
                      noMatchesMessage="Type to Filter By Location"
                      search=(action "searchLocations")
                      onchange=(action "selectionChanged") as |location|}}
       {{location.name}}
{{else}}
       No Results
{{/ember-power-select}}
```
controller
```
options: ['Choice 1', 'Choice 2']
actions: {
    selectionChanged: ->
      debugger

    searchLocations: ->
      debugger
}
```

**Also**
I also noticed when inspecting the examples in the docs, the "No Results" text should be populating in the `ember-view` element that is the dropdown. Here is a screenshot showing mine has nothing in it:
http://d.pr/i/123mA

**Comment by cibernox** [comment]
Everything in this code looks fine, so my first guess is that everything is working and this is a z-index issue. 

Can you check if just inside your `<body>` tag you have `<div id="ember-basic-dropdown-wormhole">` and that when you click on the trigge,r the content the content is rendered inside that div?

If so, the problem is indeed a z-index issue.

In master I've increased the default z-index to 1000 (the same used by bootstrap dropdowns). I should release a new version on Monday.

**Comment by cottrellio** [comment]
Wow that's embarrassing :)

That fixed my issue, It needed `position: relative` and a higher z-index. Thanks

**Comment by cibernox** [comment]
I've fixed the z-index myself in the new version I released today, so perhaps you don't need it anymore. Can you update and check it?

**Comment by cottrellio** [comment]
Yeah, that fixed it. I removed my z-index and position relative and it works with that update. Thanks @cibernox

**Comment by cibernox** [comment]
Great. One less issue, only 3418329384 more to go
