### ISSUE TITLE
Just want some clarification on Trigger override

### ISSUE THREAD

**Issue by denchen** [cibernox/ember-power-select#831]
Not an issue, but I just wanted clarification. If I want to override the trigger with my own HTML markup, I have to create a new component, correct? Even if it's a simple change, like say replace the trigger with just the text "foo" or just an icon? I ask because in `ember-basic-dropdown`, I can override the trigger by simply:

    {{#basic-dropdown as |dd|}}
      {{#dd.trigger}}foo{{/dd.trigger}}
      {{#dd.content}}Stuff{{/dd.content}}
    {{/basic-dropdown}}

Seeing as `ember-power-select` builds on top of `ember-basic-dropdown`, why can't I create triggers within the same block instead of having to create and reference a whole new component? In my application, I'll pretty much be overriding the trigger for every instance of `ember-power-select`, but they won't all be the same. Some will be simple icons, others will be the option selected, just formatted differently. Yet another one, I'm overriding with a real-time clock. It seems like a bit of a pain to have to create a new component for every single instance, when in most cases, it's 1-2 lines of HTML with no other logic.

**Comment by cibernox** [comment]
I have in my plan to expose a lower-level API to allow different things. The tentative API would be something like

```hbs
{{#power-select-basic ... as |select|}}
  {{select.trigger}}
  {{#select.content}}
    {{select.searchbox}}
    {{#select.options as |opt|}}
      {{opt}}
    {{/select.options}}
  {{#select.content}}
{{#power-select-basic}}
```

So people have more fine-grained control over everything, but don't expect it soon. For now you do have to create a new component (the JS it can be just import and reexport the default trigger) and provide your own template (it can be a copy-paste of the original one with your tweaks).

**Comment by denchen** [comment]
Thanks for the clarification. Creating components for triggers does work for us currently, but I do look forward to the lower level API you have in mind.
