### ISSUE TITLE
Search and Options not working together

### ISSUE THREAD

**Issue by nmec** [cibernox/ember-power-select#833]
## Summary
When trying to use `options`, `search` and `searchField` together the list is not filtered correctly.

## Steps to reproduce
```
Ember: 2.11.0
Ember Data: 2.11.0
jQuery: 2.2.4
Ember Power Select: 1.5.0-beta.2
```
```hbs
{{#power-select
  searchEnabled=true
  search=(action "search")
  searchField="name"
  placeholder="All"
  options=locations
  selected=(find-by "id" location locations)
  onchange=(action "changeLocation")
  as |loc|
}}
  {{loc.name}}
{{/power-select}}
```
```js
import Ember from 'ember';

const { run, RSVP: { Promise } } = Ember;

export default Ember.Component.extend({
  location: null,

  store: Ember.inject.service(),

  locations: Ember.computed(function() {
    return this.get('store').peekAll('location');
  }),

  queryLocations(name, resolve) {
    return this.get('store')
      .query('location', { name })
      .then(resolve);
  },

  actions: {
    changeLocation(location) {
      if (!location) {
        this.set('location', null);
        return;
      }

      this.set('location', location.get('id'));
    },

    search(name) {
      return new Promise(resolve =>
        run.debounce(this, this.queryLocations, name, resolve, 500)
      );
    },
  },
});
```

## Expected behaviour
- Open drop down
- Observe list is populated with locations
- Begin typing in search
- Observe list begins filtering locations immediately
- AJAX request sent after debounce timeout
- Additional matching locations are added to the filtered list

## Actual behaviour
- Open drop down
- Observe list is populated with locations
- Begin typing in search
- Loading message is displayed, but list is not filtered
- AJAX request sent after debounce timeout
- Additional matching locations are appended the list
- Non-matching locations are not hidden from the list
- Either
  - Typing another matching character correctly filters the list
  - Removing the query then re-typing correctly filters the list

**Comment by cibernox** [comment]
I'd have to check, but I believe that if a search is passed, that takes absolute precedence. There is no such thing as a mix and max of filtering + search. I'm not even sure what the right behaviour would be.

Your use case is interesting, I'm not sure how to achieve it.

**Comment by nmec** [comment]
Tried a quick workaround that I thought might work, removing `searchField` and implementing filtering myself - but having the same issue with the items just being appended:
```js
search(name) {
  const regex = new RegExp(name, 'i');

  return new Promise(yay =>
    run.debounce(this, this.queryLocations, name, yay, 500)
  ).then(() =>
    this.get('locations').filter(loc => loc.get('name').match(regex))
  );
},
```

**Comment by cibernox** [comment]
Is this still relevant? Have you found a workaround? I've been busy with other stuff lately.

**Comment by mastastealth** [comment]
@cibernox Does `search` also override `matcher` or should those 2 work together?

**Comment by cibernox** [comment]
`search` trumps over anything else.

**Comment by Caltor** [comment]
I have found when using `search` and `options` together that if you use the keyboard only (i.e. no mouse clicks) to enter the items then as soon as you start typing it clears the selected items and then starts throwing errors such as `Uncaught TypeError: (select.selected || []).slice is not a function` in power-select-multiple.js. @cibernox Shall I update the docs to state that using `search` and `options` together is not currently a supported configuration. The docs curerntly intimate that you can use both. I was going to use `options` so that you a list to choose from straight away before typing anything into the search box.

**Comment by neeleshsaxena** [comment]
@nmec Were you able to figure out a workaround for it?

**Comment by nmec** [comment]
Unfortunately not, the best we got was removing the options and relying on search which wasn't ideal.
