### ISSUE TITLE
Fresh npm install gives beta release

### ISSUE THREAD

**Issue by rondale-sc** [cibernox/ember-power-select#838]
When I do `ember install ember-power-select` I get "^1.5.0-beta.2" as my version

```
ember-cli: 2.12.0-beta.1
node: 6.9.5
os: darwin x64
```

Not sure if that is intended or not.  :beers:

**Comment by cibernox** [comment]
Yes, it's perfectly usable. 
I only labeled it as beta because a some sensible a11y changes that nobody complained about. On a fresh install it's the version to use.

**Comment by rondale-sc** [comment]
Awesome.  :)
