### ISSUE TITLE
Scrolling on mobile

### ISSUE THREAD

**Issue by anthonycollini** [cibernox/ember-power-select#841]
Scrolling on mobile is not as fluid as a native select or other packages. It is choppy and hard to scroll through results. Is this on the radar at all?

**Comment by cibernox** [comment]
No, it wasn't. I used it several times and it was absolutely fluid for me. 
I just recorded this: https://www.youtube.com/watch?v=oizT8Xmj2UI&feature=youtu.be

In reality it's more fluid even, but this I can't record at 60fps with this software.

**Comment by cibernox** [comment]
What might take some time is to open selects with a lot of elements, but once opened scrolling should be as smooth as any other scroll on the page.

**Comment by anthonycollini** [comment]
Here is a .gif of an example on this page on iOS: 
http://www.ember-power-select.com/cookbook/material-theme


![scroll](https://cloud.githubusercontent.com/assets/933222/23532006/3a775f12-ff77-11e6-998f-63061aa641b2.gif)

**Comment by anthonycollini** [comment]
@cibernox Can you confirm this occurs for you on iOS. It looks like android is fine, which is what you are probably testing on.

**Comment by cibernox** [comment]
I haven't tested it in iOS, but I'll try to get a device. For what I see in your video, it's like the scroll didn't have inertia. No clue why.

**Comment by anthonycollini** [comment]
I will try later, but perhaps it's missing a webkit declaration?

https://css-tricks.com/snippets/css/momentum-scrolling-on-ios-overflow-elements/

**Comment by cibernox** [comment]
That sounds very reasonable. Is that something you can test yourself?

**Comment by cibernox** [comment]
@anthonycollini any update? Were you able to test that css property?

**Comment by leizhao4** [comment]
The link above says `overflow-y` needs to be `scroll`, not `auto`, which might be a problem. I believe the drop down is `overflow-y: auto`.

**Comment by cibernox** [comment]
I understand, I just want someone with an ios devise to test that it works and implement it.
