### ISSUE TITLE
async content in list

### ISSUE THREAD

**Issue by jamesdixon** [cibernox/ember-power-select#846]
Hi,

Once again, great addon!

I'm running into an issue where I can't seem to render async relationships within the list. The scenario is this, each customer has a primary staff member that works with them. In the EPS dropdown, I want to highlight these particular staff members based on whether or not the staff member is a primary for their account. Each `customer` has an `account`, which has a `primaryStaff` member -- `account` and `primaryStaff` are async relations.

I tried the following, but ultimately, it appears that EPS is rendering the select contents before the `primaryStaff` relation is resolved and hence, the content for that primary staff member is never rendered:

_`primaryStaff` is a computed alias for `model.customer.account.primaryStaff`_

```hbs
              {{#power-select
                class="{{componentCssClassName}}--staff-selector"
                disabled=hasCompleted
                onchange=(action (mut model.staff))
                onclose=startValidating
                options=(sort-by 'lastName' model.business.activeStaff)
                placeholder='Choose Staff...'
                renderInPlace=true
                searchField="lastName"
                selected=model.staff as |staff|}}
                  {{#if (await primaryStaff)}}
                    {{#if (eq staff.id primaryStaff.id)}}
                        {{paper-icon 'star rate' size=18 class="primary"}}
                    {{/if}}
                  {{/if}}
                  {{staff.reverseFullName}}
                {{/power-select}}
```

Here's what I'm expecting:

![image](https://cloud.githubusercontent.com/assets/110114/23582495/a26c90f2-00e8-11e7-89e9-e1fbafb10ee7.png)

Here's what I'm seeing:

![image](https://cloud.githubusercontent.com/assets/110114/23582497/bdc68ede-00e8-11e7-96fd-ac3b8df50b7b.png)

Note that the primary staff member isn't rendered whatsoever -- I would at least to expect to see the name, but not the star icon.

Thanks for your help! Pulling my hair out on this one 😄

**Comment by cibernox** [comment]
There is a lot to grock there. As you mention at the end, it doesn't make sense that there is one member missing. The only reason for that is that the missing member is not among the given options.

Can you confirm that `Marlin Dietrich` is part of `model.business.activeStaff`? That is the only think EPS cares about.
If so, can you check if there is no option between Roxanne and Eloise? Perhaps there is an empty option? (that would men there is an item, but its reverseFullName is empty.

**Comment by jamesdixon** [comment]
@cibernox thanks for taking a look. It turned out be something unrelated to EPS, but the weirdness of it had me coming back to EPS because I couldn't reproduce elsewhere. Apologies for bothering you. Keep up the great work!
