### ISSUE TITLE
How clear the selected value from controller action?

### ISSUE THREAD

**Issue by elendil1979** [cibernox/ember-power-select#857]
Hello, 

i need clear the selected value of a ember-power-select component in my template, after the controller complete a action.

For example:
run the save action in controller and i need clear all input data and ember-power-select too

I need help urgently, thanks

**Comment by cibernox** [comment]
Asuming your invocation is `{{#power-select selected=foo ...}}`, just do `this.set('foo', null)` and you'll clear the select.

**Comment by cibernox** [comment]
I'm going to close it, let me know if your question is not answered.
