### ISSUE TITLE
power-select-multiple able to add same options multiple times where Options as an array of objects.

### ISSUE THREAD

**Issue by rinoldsimon** [cibernox/ember-power-select#858]
hbs:
```
{{#power-select-multiple
  search=(action "selectMember")
  selected=model.members
  allowClear=true
  placeholder="Select Members..."
  onchange=(action (mut model.members))
  as |repo|
}}
 {{repo.first_name}} {{repo.last_name}}
{{/power-select-multiple}}
```
js:
```
selectMember: function(term) {
  if (Ember.isBlank(term)) { return []; }
  return this.get('ajax').request(...);
},
```
the return response for `selectMember` action 
```
[
 {"first_name":"Bhadraksh","last_name":"Mukhopadhyay","username":"toni.bogisich_1"},  
 {"first_name":"Bhadran","last_name":"Tandon","username":"tracy_2"},
 {"first_name":"Balaaditya","last_name":"Ahluwalia","username":"hiram.kaulke_4"}
]
```

**Comment by cibernox** [comment]
Read this section of the docs: http://www.ember-power-select.com/docs/how-to-use-it

Td;dr; `{ foo: 'bar' } !== { foo: 'bar' }`. If you want two options to be considered the same options they have to:

A) Be the exact same object (not an object with the same values)
B) Implement an `isEqual` function that tells `Ember.isEqual` how to compare them.

**Comment by rinoldsimon** [comment]
I'm able to select the same options multiple times. so there multiple entries with the same options. Do i need to manually check whether the selected option is already in the selected list of power-select-multiple?

**Comment by cibernox** [comment]
The key thing that you have to understand is that the second time you select it, it's not the same option, it's a different option that happens to have the same values. `{ foo: 'bar' } !== { foo: 'bar' }`

You need to make the option have an `isEqual` function to tell ember-power-select how to compare them, or alternatively ensure that you're returning the exact same objects.
