### ISSUE TITLE
Almost working!

### ISSUE THREAD

**Issue by Caltor** [cibernox/ember-power-select#860]
I have almost got the ember-power-select addon working in my project. The only problem I have is that on first load the trigger is empty. If I select an option it seems to update the trigger OK and it saves OK. However when I do a refresh on the page it loses the trigger again. Here are the relevant sections from my code:

HBS
{{#power-select
  options=families
  selected=model.family
  searchField="itemCode"
  onchange=(action "selectFamily")
  as |family|
 }}
    {{family.itemCode}}
{{/power-select}}

JS
selectFamily(newItem) {
    this.set('model.family', newItem);
    this.set('model.familyId', newItem.id)
},

Any idea why I am experiencing these problems please?
Thanks

**Comment by cibernox** [comment]
Unless I'm missing something, what you mention is perfectly normal. If you refresh you will loose any change you haven't saved.

**Comment by Caltor** [comment]
Ah I should have said, I have a Save button as follows:

HBS
`<button {{action "saveModel" model}} class="btn btn-success">Save</button>`

JS
```
saveModel(model) {
    model.save().then(this.transitionToRoute('list');
},
```

Interestingly a basic select as follows works fine:
HBS
```
<select id="family" class="form-control" onchange={{action "selectFamily" value="target.value"}}>
    <option value="">None</option>
    {{#each families as |family|}}
        <option value={{family.id}} selected={{eq family.id (to-string model.familyId)}}>{{family.itemCode</option>
    {{/each}}
</select>

```

JS
```
selectFamily(newValue) {
    this.set('model.familyId', newValue);
},

```

**Comment by cibernox** [comment]
If the trigger is empty means that `model.family` is empty/null/undefined too. Check that. If it's empty means the way you set the value is not working as you expect it to work.

**Comment by Caltor** [comment]
Hmmm model.family doesn't seem to be getting set properly. Thanks for your help!
