### ISSUE TITLE
Clearing multiple select

### ISSUE THREAD

**Issue by Caltor** [cibernox/ember-power-select#861]
I am currently using the power-select-multiple to choose items which will be added to a collection. How can I clear the selection when a user clicks the Add button please?

Here is my code:
.hbs
```
<button class="btn btn-primary btn-sm" {{action "addItems" apps model}}>Add</button>
{{#power-select-multiple
    options=applicators
    selected=apps
    onchange=(action (mut apps))
    as |name|
}}
    {{name.itemCode}}
{{/power-select-multiple}}
```

.js
```
actions: {
    addItems(apps, family) {
        let parent = this;
        apps.forEach(function(x) {
            parent.items.push(x);
        });
    }
}
```

**Comment by cibernox** [comment]
@Caltor Nothing special. Just do `this.set('apps', null)` and the select will be empty, since that is what you pass to `selected=`

**Comment by Caltor** [comment]
Haha brilliant! Thanks. I was overthinking it, trying to come up with ways to alter the selected property of the select.

**Comment by cibernox** [comment]
@erichonkanen You need to compare the previous value and the new value as check what is not there anymore.

I know it might seem convoluted but it is a conscious decision. The `onChange` action can be called for additions and for removals, and several items can be added or removed at once, so I decided to each time just invoke the action with the new collection of items. More often than not people can just assign the new collection with a simple `{{action (mut myList)}}`, and in those scenarios where you need to perform operations individually on the added/removed items, it's not too hard:

```
update(newItems) {
  let { oldItems } = this;
  this.oldItems = newItems;
  let addedItems = newItems.filter(e => !oldItems.include(e));
  let removedItems = oldItems.filter(e => !newItems.include(e));
  // perform individual operations with the added and removed items compared with the previous value.
}
```
