### ISSUE TITLE
action.close() not closing

### ISSUE THREAD

**Issue by maladon** [cibernox/ember-power-select#862]
I have a requirement where the user can only select at most 3 items. I'm following the example from here: https://github.com/cibernox/ember-power-select/issues/288

But, when I  do select.actions.close() nothing happens!

**Comment by snewcomer** [comment]
@maladon are you on Ember 2.12? I'm seeing this when trying to upgrade my fork of this.

For ex// this [test](https://github.com/cibernox/ember-power-select/blob/master/tests/integration/components/power-select/customization-with-compoments-test.js#L142)
