### ISSUE TITLE
Assertion Failed: You modified "concatenatedTriggerClasses" twice...

### ISSUE THREAD

**Issue by trumb1mj** [cibernox/ember-power-select#866]
I'm seeing the following error when I click a drop down and then click on a very specific component.  I thought maybe it had something to do with blur but I could not reproduce unless I clicked on this component.

Here's the message:

"Assertion Failed: You modified "concatenatedTriggerClasses" twice on <my-webapp@component:power-select::ember2561> in a single render. It was rendered in "component:basic-dropdown/trigger" and modified in "component:basic-dropdown/content". This was unreliable and slow in Ember 1.x and is no longer supported. See https://github.com/emberjs/ember.js/issues/13948 for more details."

**Comment by trumb1mj** [comment]
`
assert @ ember.debug.js:5700
assert @ ember.debug.js:17372
assertNotRendered @ ember.debug.js:23065
propertyDidChange @ ember.debug.js:21681
(anonymous) @ ember.debug.js:21759
Meta._forEachIn @ ember.debug.js:19786
forEachInDeps @ ember.debug.js:19759
iterDeps @ ember.debug.js:21747
dependentKeysDidChange @ ember.debug.js:21723
propertyDidChange @ ember.debug.js:21663
notify @ ember.debug.js:16443
chainsDidChange @ ember.debug.js:21773
propertyDidChange @ ember.debug.js:21666
set @ ember.debug.js:22072
updateState @ power-select.js:706
deactivate @ power-select.js:396
send @ ember.debug.js:40682
superWrapper @ ember.debug.js:40426
onBlur @ power-select.js:384
join @ ember.debug.js:770
run.join @ ember.debug.js:22289
(anonymous) @ ember.debug.js:9934
flaggedInstrument @ ember.debug.js:18475
(anonymous) @ ember.debug.js:9933
clear @ ember.debug.js:45122
reset @ ember.debug.js:45459
handleException @ ember.debug.js:54273
handleException @ ember.debug.js:54455
_throw @ ember.debug.js:54168
evaluate @ ember.debug.js:49537
execute @ ember.debug.js:54155
rerender @ ember.debug.js:54094
_this.render @ ember.debug.js:11854
runInTransaction @ ember.debug.js:23035
_renderRoots @ ember.debug.js:12115
_renderRootsTransaction @ ember.debug.js:12153
_revalidate @ ember.debug.js:12192
invoke @ ember.debug.js:336
flush @ ember.debug.js:404
flush @ ember.debug.js:528
end @ ember.debug.js:598
(anonymous) @ ember.debug.js:1164`

**Comment by brancusi** [comment]
Getting this as well. Trying to upgrade an app from 2.7 -> 2.8, bunch of changes, so can't easily say where it's coming from yet.

**Comment by daegun** [comment]
+1

We recently started seeing this issue as well, happens pretty often actually.

**Comment by trumb1mj** [comment]
I ended up upgrading to a pre release version `"ember-power-select": "v1.6.1"` and this has not come up again.

**Comment by cibernox** [comment]
To everyone with this issue, check updating to 1.6.1, since I might have fixed a while ago already. Please reopen if this persist.

**Comment by daegun** [comment]
thanks!

**Comment by daegun** [comment]
actually this problem is still occurring in the app I'm working on

we're using this in conjunction with power-select-with-create, and we've updated the versions for them - `1.6.1` and `0.3.1` respectively, and we're still seeing this issue occur.

I'm digging deeper to see why it's still happening.

**Comment by sauronnikko** [comment]
We're getting similar assertion errors in our project:

```
Error: Assertion Failed: You modified "concatenatedTriggerClasses" twice on <v2@component:power-select::ember36471> in a single render. It was rendered in "component:basic-dropdown/trigger" and modified in "component:file-upload". This was unreliable and slow in Ember 1.x and is no longer supported. See https://github.com/emberjs/ember.js/issues/13948 for more details

Error: Assertion Failed: You modified "publicAPI" twice on <v2@component:power-select::ember36471> in a single render. It was rendered in "component:power-select/trigger" and modified in "component:file-upload". This was unreliable and slow in Ember 1.x and is no longer supported. See https://github.com/emberjs/ember.js/issues/13948 for more details.
```

The conflict is happening between `ember-power-select` and a custom component, `file-upload`, which extends from [ember-uploader](https://github.com/benefitcloud/ember-uploader). Perhaps this isn't `ember-power-select`'s fault, but given that similar errors have been reported here, we thought it best to post this.

We're using version `1.6.1` with `ember-cli@2.12`

**Comment by alecho** [comment]
I'm seeing the same thing as @sauronnikko when upgrading to `2.12` except we're using EPS correctly and then extending the components for our use.

**Comment by cibernox** [comment]
So far all reporters were in older versions of the addon, 1.6.1 seems to be free of that bug. @alecho can you check?

**Comment by pawangiri** [comment]
```
ember.debug.js:18015 Assertion Failed: You modified "concatenatedTriggerClasses" twice on <ylo-fe@component:power-select::ember600> in a single render. It was rendered in "component:basic-dropdown/trigger" and modified in "component:add-location". This was unreliable and slow in Ember 1.x and is no longer supported. See https://github.com/emberjs/ember.js/issues/13948 for more details.
Error
    at assert (http://localhost:4200/assets/vendor.js:21543:13)
    at Object.assertNotRendered (http://localhost:4200/assets/vendor.js:39069:11)
    at propertyDidChange (http://localhost:4200/assets/vendor.js:37685:30)
    at http://localhost:4200/assets/vendor.js:37763:7
    at Meta._forEachIn (http://localhost:4200/assets/vendor.js:35663:11)
    at Meta.forEachInDeps (http://localhost:4200/assets/vendor.js:35633:19)
    at iterDeps (http://localhost:4200/assets/vendor.js:37751:10)
    at dependentKeysDidChange (http://localhost:4200/assets/vendor.js:37727:7)
    at propertyDidChange (http://localhost:4200/assets/vendor.js:37667:9)
    at ChainWatchers.notify (http://localhost:4200/assets/vendor.js:32355:9)
defaultDispatch	@	ember.debug.js:18015
dispatchError	@	ember.debug.js:17994
invokeWithOnError	@	ember.debug.js:349
flush	@	ember.debug.js:405
flush	@	ember.debug.js:529
end	@	ember.debug.js:599
run	@	ember.debug.js:713
hash.success	@	ajax-request.js:233
fire	@	jquery.js:3317
fireWith	@	jquery.js:3447
done	@	jquery.js:9272
(anonymous)	@	jquery.js:9514
```

I still see this error
I am using v1.7.0 with ember v2.12.1

**Comment by cibernox** [comment]
@pawangiri can you provide a reproduction? Seems to be fixed for others.

**Comment by MartinMalinda** [comment]
I just stumbled upon this issue and it seems to be caused by `tagName: ''` on the second component for me.

**Comment by alecho** [comment]
@cibernox I was still seeing the error blaming EPS but it was a result of a app specific component mixin that modified `classNames` on `init()`. I was seeing about 15 errors. 14 were blaming EPS but the real culprit was the first component using the mixin extending EPS.

@pawangiri I would take a look at your `add-location` component to see if it, a mixin, or a component it extends modifies `classNames`.

**Comment by Aaronfischer** [comment]
I'm also seeing this. 
@alecho Whats wrong with modifying `classNames`? I'm trying to understand how thats related and what I can do to solve this issue.

**Comment by cibernox** [comment]
@Aaronfischer I think that the error message is misleading. I think that what is really happening is that there is some error somewhere in your app and that causes EPS to break mid-render. But so far every time someone reported it, the error was actually in code outside EPS.

**Comment by Aaronfischer** [comment]
@cibernox Ahh, okay, interesting I'll keep debugging then, thanks.

**Comment by cibernox** [comment]
However I nave no clue why EPS appears in the trace, so there might be some relation I don't see. If you come to any conclusion let me know.

**Comment by Aaronfischer** [comment]
Okay, in my case, I am grabbing and `.filterBy(...)` the "options" I use in power-select AND trying to prepopulate the "selected" based on the filterBy... So I could see why in my case power-select would be "involved" in some way.
