### ISSUE TITLE
Test Helpers - pass a DOM element?

### ISSUE THREAD

**Issue by snewcomer** [cibernox/ember-power-select#868]
Now that selectSearch uses native-events, doing something like below does not work anymore, specifically b/c of this [line](https://github.com/cibernox/ember-power-select/blob/master/test-support/helpers/ember-power-select.js#L123).  What do you think about refactoring the selectSearch to also take a (potential) dom element?  I can submit a PR, but wanted to run it by you first before tackling.

```
  selectSearch('.t-address-country:eq(2)', keyword);
  selectChoose('.t-address-country:eq(2)', countryName);
```

The other option is to make sure it is open before doing `selectSearch` to bypass that if block, but then it seemed better to have selectSearch to also take a DOM element.

**Comment by cibernox** [comment]
It sounds reasonable to me to accept a HTMLElement instead of a CSS selector. 
I'd accept at PR like that.
