### ISSUE TITLE
Option for explicitly not importing default styles

### ISSUE THREAD

**Issue by ChrizzDF** [cibernox/ember-power-select#870]
Hi there,

I really love your addon and anywhere in my apps I have to use a select box, I use ember-power-select! 😀

Currently I'm implementing [ember-css-modules](https://github.com/salsify/ember-css-modules) in my Ember app and therefore I'd like to avoid importing the `ember-power-select`styles by default because at the end it generates CSS output that is not even used.

Is there any option to disable the importing of styles at all?
I only want them to be explicitly imported via `@import` statement in my `app.scss` file.

Hopefully you get my question 😄

Thanks!

**Comment by cibernox** [comment]
If you are using ember-cli-sass that is already how it works. 
If you don't add `@import 'ember-power-select'`, the component has no styles.

**Comment by ChrizzDF** [comment]
Thanks for your quick reply!

I just set up a new, clean Ember project to prove it.
You're right - obviously! 😄

The good thing is that I now know that something else causes styles to be imported automatically.

Thanks again!
