### ISSUE TITLE
Power select multiple won't update hasMany relationships

### ISSUE THREAD

**Issue by tinyweasel** [cibernox/ember-power-select#876]
Trying to use a select dropdown to update a model with a lot of hasMany relationships using JSON API. When you select a belongsTo relationship from the dropdown, it sends the request and updates fine, but it's not sending the data for hasMany. The dropdowns are populated with these properties and the current model properties are preselected, so it is getting the data from the server correctly, but it won't send it back.

**Comment by cibernox** [comment]
I think I'm going to need more information or an example so see what are you doing, but EPS's `onchange` callback is just invoked with an array of the selected values. Is not this component's concern what you do with it. If you want to set the value of a has-many relationship and send a request to the server you must do that yourself.

**Comment by cibernox** [comment]
I'm going to close to keep backlog tidy but feel free to reopen.
