### ISSUE TITLE
Id attribute for the options list, for acceptance testing?

### ISSUE THREAD

**Issue by monovertex** [cibernox/ember-power-select#883]
Is there any way to specify a custom id to be used on the options list?

We'd like this for easier implementation of acceptance tests, where we'd need to select a particular option for a dropdown.

I know a possible way would be to provide a triggerId, then get the trigger's parent ID and use that to compose the generated ID of the options list, but it feels fragile and hack-ish.

**Comment by NLincoln** [comment]
I think the `selectChoose` helper may do what you want 

http://www.ember-power-select.com/docs/test-helpers

**Comment by monovertex** [comment]
The problem is, we're writing acceptance tests in a 3rd-party framework, not in the Ember environment, so we can't really use the test helpers provided. That's why we'd need to be able to uniquely identify the list of options for a particular power select.

**Comment by joeypedicini92** [comment]
@monovertex how are you selecting options? I can't even register that tried all sorts of jquery and native event triggering can't seem to trigger asn option select

**Comment by monovertex** [comment]
@joeypedicini92, I've never tried that in a Javascript environment, honestly. We're using Java w/ Serenity for the acceptance tests and clicks seem to register there.

Have you tried this solution? https://github.com/cibernox/ember-native-dom-helpers

**Comment by joeypedicini92** [comment]
Thanks @monovertex ended up using the ember helpers, that worked.

**Comment by cibernox** [comment]
Sorry, I've been neglecting github lately. My excuse is that it was very sunny outside 😎 


No, there is no easy way of adding IDs to the specific options. You can add IDs/classes to the trigger and the dropdown only. Anything can be done if you customise the templates, but that is pretty involved, I tend to use selectors like `.ember-power-select-option:nth-child(1)` or `ember-power-select-option:contains('Robert')` if you use jQuery and it makes sense.

I'm glad this is seems resolved.

**Comment by monovertex** [comment]
@cibernox, I'm sorry, might've worded the initial question wrong. I need to place an ID on the dropdown itself, not on individual options. 

I still haven't found a way of placing an ID directly on the options list or the dropdown, for that matter.

**Comment by cibernox** [comment]
@monovertex I think that there isn't a way to set an ID, although there is a way of setting a class if that works for you. Does it?

**Comment by monovertex** [comment]
Ah, through the `dropdownClass`, correct? Yeah, that would do it. Thanks!
