### ISSUE TITLE
Dropdown's position is not adjusting automatically

### ISSUE THREAD

**Issue by selva-v** [cibernox/ember-power-select#886]
When I use `renderInPlace=true` the dropdown is not adjusting it's position. It's always bounds towards downward even though there is not enough space.

I'm using `renderInPlace=true` to avoid dropdown sticking Whenever the dropdown opens and one scrolls the body #456.

Thanks.

**Comment by cibernox** [comment]
That is a known limitation. 

In http://www.ember-basic-dropdown.com/docs/position this caveat is mentioned. You can, however, force it to render upwards passing `verticalPosition="above"`.

TBH, i don't remember the reason, I think that it's technically possible to do that but I never had time. If you want to give it a try using a custom positioning function (http://www.ember-basic-dropdown.com/docs/custom-position) and you find a way I'd be happy to incorporate it as default behaviour.

**Comment by selva-v** [comment]
Thanks for the quick response. I will try using the custom positioning.

BTW, I cant use `verticalPosition="above"`. since order of the select component may vary based on the form requirement, so I want the dropdown position should be adjusted based on available space.

**Comment by cibernox** [comment]
Check the implementation of the original reposition function for inspiration.
