### ISSUE TITLE
best practice for defaulting selected value if only 1 option

### ISSUE THREAD

**Issue by robneville73** [cibernox/ember-power-select#887]
This is a very common scenario in my app... a drop-down may only have one choice and in certain contexts, I'd want it to automatically select that one value. I'm not seeing an obvious path on how to accomplish that with power select...

If there is a way to do this please let me know, otherwise this might be a good idea to include somehow.

**Comment by cibernox** [comment]
That is not too hard. The key is that it's not this addons' responsability. The addon takes `options` and `selected`. It's your responsability to make `selected` default to the only option. A computed property could work.

```hbs
{{#power-select options=options selected=selected onchange=(action (mut selected)) as |opt|}}
...
```

```js
selected: Ember.computed('options.length', function() {
  if (this.get('options.length') === 1) {
    return this.get('options.firstObject');
  }
})
```
