### ISSUE TITLE
It is not possible to use eps 1.7.0 version with ember-cli-page-object

### ISSUE THREAD

**Issue by Sinled** [cibernox/ember-power-select#890]
As i understand the root of the problem is deprecation of `:eq()` selector

when using collections in `ember-cli-page-object` 
it generates selectors which looks something like this
`.some-collection .some-collection-item:eq(0) .power-select-container .ember-power-select-trigger`

and i pass this selector to `selectChoose` helper and it results error because selectChoose calls querySelector which does not support `:eq`

Any ideas how to solve this?

**Comment by cibernox** [comment]
You're right. 
This is because the addon stopped relying in jQuery. 

One improvement that it's easy enough and would "fix" your problem would be to improve the `selectChoose` helper to accept an `HTMLElement` as first argument instead of a string. What way you can still use jQuery specific stuff to find the trigger and pass it to the helper.

E.g:

```js
let $trigger = $('some-collection .some-collection-item:eq(0) .power-select-container .ember-power-select-trigger');
selectChoose($trigger.get(0), 'Dogs');
```

**Comment by cibernox** [comment]
Regardless of your problem I think that it's a good idea to allow helpers to receive DOM elements instead of the CSS selectors to find those DOM elements.

**Comment by cibernox** [comment]
@Sinled I've done that already. Now you can find the trigger using jQuery specific selectors and pass it to the `selectChoose` helper as above. Released in 1.7.1.

Will that help?

**Comment by Sinled** [comment]
Thanks, it helped!

**Comment by paulgoetze** [comment]
@cibernox Is there a plan to add support for passing DOM elements to other test helpers, such as `clickTrigger` and `typeInSearch`, as well? 

I just ran into the same problem as described above and got a respective error message when using the these helpers: 
```
#ember-testing [object HTMLDivElement] .ember-power-select-trigger' is not a valid selector
```

I use cli-page-objects and tried the approach you mentioned in https://github.com/cibernox/ember-power-select/issues/900#issuecomment-297169169:  
`$(buildSelector(this, selector, options))[0];` which results in the HTMLDivElement that is shown in the error message.

**Comment by cibernox** [comment]
@paulgoetze I had no plan, but i don't oppose to the idea. If you can put toguether a PR I will be happy to merge it.

**Comment by paulgoetze** [comment]
👍 Cool, I'll see what I can do.
