### ISSUE TITLE
Navigable select demo not working

### ISSUE THREAD

**Issue by Moxide** [cibernox/ember-power-select#893]
Hello,
It seems that the navigable select demo is not working any longer. Testing it with Firefox and Chromium, it just hangs, throwing some JS errors...
Thanks ;-)

**Comment by cibernox** [comment]
Crap. I suspect that is because I removed jQuery. The component doesn't use it but the animation library does.

**Comment by Moxide** [comment]
Indeed, the first error thrown is a JQuery one ;-)

**Comment by cibernox** [comment]
This is a tricky one. Apparently liquid-fire relies a lot in jQuery, so I might end up including jQuery in the deployed doc even if the addons is developend and tested without it.

**Comment by cibernox** [comment]
This should be closed now. I now include jQuery when I deploy the docs, but I don't include it when I run the tests so I ensure that the addon itself doesn't require jQuery.

Thanks for reporting

**Comment by Moxide** [comment]
It's all good, thanks !

**Comment by christophersansone** [comment]
@cibernox Hey there, looks like this issue is occurring again.  The console error also shows a jQuery related error, so I suspect it's the same root cause of jQuery not being included anymore.
