### ISSUE TITLE
Is there possibility to specify the `dropdownParent` option?

### ISSUE THREAD

**Issue by tsamsiyu** [cibernox/ember-power-select#898]
In some situations (in marcopus, bootstrap modal) a dropdown isn't displayed correctly. Is there possibility to specify the option like `dropdownParent` like it did in select2 jquery widget?

**Comment by cibernox** [comment]
Check the `destination` option: http://www.ember-power-select.com/docs/api-reference
You can also use `renderInPlace=true`

However if the problem is just the `z-index`, I'd just add a class to the dropdown to increate it to 1051.
