### ISSUE TITLE
Add selectize.js skin

### ISSUE THREAD

**Issue by cibernox** [cibernox/ember-power-select#9]
Epic task, but very valuable.
- [ ] Investigate and isolate differenced in markup and behavior that can be abstracted.
- [ ] Just Do It ™

**Comment by miguelcobain** [comment]
Maybe we are more successful if we just try to reproduce selectize's styles using the current markup.
Selectize isn't maintained anymore, so its styles won't change.

**Comment by cibernox** [comment]
It's simpler to start with.

I'm not sure how many people is concerned about theming. If theming is really a thing perhaps it makes sense to create a different template with different class names to permit theming. Perhaps it doesn't worth it.

I

**Comment by cimtico** [comment]
I'd be interested in a material design theme.
Even having a way to add a label and custom class names would make it possible to easily style the component according to one's needs

**Comment by cravindra** [comment]
+1 for the Material Design Theme.. Materialize CSS would be a good base to work off from?

**Comment by sdhull** [comment]
This would be really cool, I'm not sure why it got closed. Our designer is strongly in favor of the UX/UI of selectize and trying to reproduce that with ember power select has proven difficult. I'm sure it's possible I just have so far not been successful. So even just an example to follow would be super useful.

**Comment by sdhull** [comment]
Specifically, making the filter input & trigger be the _same element_ is what has proven challenging. So far we've been reverting to using basic-select but it just feels like power-select is _so close_ and maybe I'm just missing something 🤔
