### ISSUE TITLE
Default variable never used

### ISSUE THREAD

**Issue by samdemaeyer** [cibernox/ember-power-select#90]
Hi, I noticed that the scss variable `$ember-power-select-text-color` is set but never used. So at the moment, setting this in our app will not change the styles of the plugin.

**Comment by cibernox** [comment]
Probably the default value of that should be `inherit` too.

/cc @miguelcobain

**Comment by miguelcobain** [comment]
@cibernox using `inherit` as value seems a sensible default. I can imagine most people not needing to change the variable at all because of this default.

**Comment by cibernox** [comment]
Closed vía #92
