### ISSUE TITLE
Selectors with `:eq` cause exceptions with >= 1.7

### ISSUE THREAD

**Issue by pgengler** [cibernox/ember-power-select#900]
Since ember-power-select 1.7.0, passing a selector with `:eq` to `selectChoose` causes this error:

> SyntaxError: Failed to execute 'querySelector' on 'Document': '#ember-testing .test-element:eq(1) .ember-power-select-trigger' is not a valid selector.

I assume this is related to pulling out jquery but it seems like a big breaking change.

**Comment by cibernox** [comment]
@pgengler Yes, that is indeed a consequence of removing jQuery as `:eq` is not a valid CSS3 selector. 

For what it's worth, when removing this feature I reached the jQuery team and seems that [`:eq` is being removed anyway](https://github.com/jquery/sizzle/issues/398#issuecomment-284300485) so I decided to not care about it.

Although the helper doesn't accept jQuery pseudoselectors, you can still use them and pass the result:

```js
selectChoose($('.test-element:eq(1)')[0], 'Mary')
```

Or even better, using [ember-native-dom-helpers](https://github.com/cibernox/ember-native-dom-helpers) `findAll` method, which is what ember-power-select uses internally.

```js
selectChoose(findAll('.test-element')[1], 'Mary')
```

I think that I could test the selector for the presence of `:eq` and throw a more helpful error message help?

**Comment by pgengler** [comment]
I've worked around this by creating a wrapper helper that does that, but shouldn't this have really been saved for 2.0, since it breaks existing tests?

**Comment by cibernox** [comment]
You might be right. The test helpers are arguably public API too and I should have bumped a major version. 

Sorry about that, I'll be more careful next time.
