### ISSUE TITLE
regression in 1.8

### ISSUE THREAD

**Issue by dbinetti** [cibernox/ember-power-select#903]
I'm sorry I can't provide a failing test, but the reproducible steps (for me) are:

- using a `power-select` with an `ember-bootstrap` modal
- the `renderInPlace=true`flag renders the options on the right edge of the browser window instead of in place.

works on 1.7, fails on 1.8.

**Comment by cibernox** [comment]
Sorry for the delay. This has been fixed last week. It was a bug in ember-basic-dropdown actually. It was only related with the `renderInPlace`, the fact that it was in a modal I don't think that it's relevant. Can you check again?

**Comment by dbinetti** [comment]
Sorry for the late check!  

yes, works.  thanks!
