### ISSUE TITLE
Multiple w/ server side queries freeze up after 1 character typed

### ISSUE THREAD

**Issue by bakerac4** [cibernox/ember-power-select#91]
After I type one character in 'a', it shows results which works great. But then I try to filter it more by typing 'l' and it locks up the browser and I end up having to close the tab.
My normal template
```
{{#type-ahead modelName='friend' selection=taggedFriends multiple=true placeholder="Tag a friend" as |item|}}
{{item.name}}
{{/type-ahead}}
```

The component
```
import Ember from 'ember';
// import DS from 'ember-data';

export default Ember.Component.extend({
    selection: null,
    modelName: null,
    filter: null,
    optionLabelPath: 'name',
    multiple: false,
    placeholder: 'Select an item',
    actions: {
        getData: function(filter) {
            return this.store.query(this.get('modelName'), { name: filter });
        }
    }
});
```
The component template
```
 {{#power-select search=(action "getData") searchField=optionLabelPath multiple=multiple selected=selection onchange=(action (mut selection)) as |item|}}
      {{yield item}}
 {{/power-select}}
```

**Comment by cibernox** [comment]
Interesting. This component is not doing anything specially clever with promises returned from the `search` action, so I wonder what's going on.

Just for the sake of completeness, which version of the ember and ember-data are you using? How many items are your returning as an average for each search?

I'll try to reproduce it using just ember-cli-mirage.

**Comment by bakerac4** [comment]
```
Ember - 1.13.0
Ember Data - 1.13.8
```

Only 1 item is being returned for the 'a' search. That same item is the only item being returned for the 'al' call.

**Comment by cibernox** [comment]
should be easy to reproduce then. I'll check it this evening

**Comment by bakerac4** [comment]
Were you able to reproduce this? Im using an alternative solution for now but Im really curious to see if it was something I was doing or not

**Comment by cibernox** [comment]
@bakerac4 I've done many improvements targeted to avoid re-renders when async searches stack, so probably this should be fixed or at least better now.

I'm closing, let me know if you still see this in the latest version of the component.
