### ISSUE TITLE
Strange behaviors/interactions

### ISSUE THREAD

**Issue by maxwondercorn** [cibernox/ember-power-select#910]
I have two power-selects in a template that are behaving oddly and seem to be interacting with one another.  Code first:

observations.hbs

                    {{#power-select 
                        options=sortedStreams 
                        selected=selectedStream
                        onchange=(action "onSelectStream")
                        class="form-group pull-left selector"
                        tagName="div"
                        placeholder="Value Stream" 
                        as |stream|}} 
                            {{stream.name}} 
                    {{/power-select}}
                    
                    {{#power-select 
                        options=model.areas
                        selected=selectedArea
                        onchange=(action "onSelectArea")
                        class="form-group pull-left selector selector2"
                        tagName="div"
                        placeholder="Area" 
                        as |area|}} 
                            {{area.name}} 
                    {{/power-select}}`

routes/obeservations.js

    setupController(controller, model) {
        this._super(controller, model);

        controller.set('selectedArea');

        if (this.isEditing) {
            var name = model.obs.get('stream');

            // set selected to observation stream
            this.store.query('stream', { filter: { name: name } }).then(function (stream) {
                controller.set('selectedStream', stream.get('firstObject'));
            })
        }
        else
            controller.set('selectedStream')
    },`

controllers/observations.js

     export default Ember.Controller.extend( {
         isEditing: false,
         selectedStream: '',
         selectedArea: '',
         nameSort: ['name'],
         sortedStreams: Ember.computed.sort('model.streams', 'nameSort'),

         actions: {
             onSelectStream(stream) {

                 if (this.get('isEditing')) {
                     debugger
                     this.set('selectedStream', stream);
                     this.set('areasDisabled', false);
                 }
                 else {
                     this.set('selectedArea')
                 }
           },

          onSelectArea(area) {
              this.set('selectedArea', area);
          },
      }
    });`

I trimmed the code a bit so only the bare essentials are shown.  ember-validations is imported on the controller, but it is not being used in the logic.

If only the first power-select (sortedStreams) is in the template everything works as expected.  Selecting a value fires onchange to save the value.  When the second power-select is on the page, the first select will not fire it's onchange action.  If I initialize the streamSelected property (isEditing = true) the first select works normally.

The second power-select seems to work normally whether selected (areaSelected) is initialized or not.  But if the first power-select is not initialized, it will reset the 2nd power-select and will be selected.  If intialized and working properly, the first power-select does not interact with the second one. I have verified that the 2nd power-select's onchange event is not firing.

It all seems to be related to having more than one select in the template, which I'm sure is a common use case.  While I don't think it matters, this is an ember-electron project and I'm using  Ember 2.12.1

**Comment by cibernox** [comment]
Having many selects on the screen is the most normal thing ever, so I'm sure there is something specific on your logic. 
Can you replicate the problem in https://ember-twiddle.com ? Ember Power Select works perfectly there if you manually add the `<div id="ember-basic-dropdown-wormhole"></div>` somewhere in a template.

**Comment by maxwondercorn** [comment]
After some sleep, I walked through the code again and found the problem - actually two, in my controller code.  Almost embarrassed that I posted the issue but the lesson is sometimes you need to walk away.

When I wasn't loading a record into my form, I was setting my stream selected property to null, rather then the selected value and to compound it I was setting the area selected property instead.  Which explains the "interactions" I had.  Depending on the record sometimes and what selector was preloaded added to the confusion  Corrected controller code follows.

controllers/observations.js

         actions: {
            onSelectStream(stream) {
            
            if (this.get('isEditing')) {
                debugger
                this.set('selectedStream', stream);
                this.set('areasDisabled', false);
            }
            else {
                this.set('selectedStream', stream)
            }

        },

        onSelectArea(area) {
            this.set('selectedArea', area);
        },
`

**Comment by cibernox** [comment]
Glad you found it. I'm closing this then.
