### ISSUE TITLE
Invalid character error only in IE browser and only for production environment

### ISSUE THREAD

**Issue by kumkanillam** [cibernox/ember-power-select#915]
Due to some newer feature usage(I am not sure is it in my app folder or from addon) in my project, uglify.js is not working for minification, so I uninstalled `ember-cli-uglify` and included [ember-cli-babili](https://github.com/ember-cli/ember-cli-babili)  reference (http://rwjblue.com/2017/04/21/ember-cli-targets/). 

Here comes the issue,
In group-utils.js file,there is `const DIACRITICS = { 'Ａ':'A' }` 840 characters defined [here ](https://github.com/cibernox/ember-power-select/blob/master/addon/utils/group-utils.js#L118). 
In develpment environment,its working fine since key is in single quotes  `const DIACRITICS = { 'Ａ':'A' }` 
In production environment, it's minified as  `const DIACRITICS = { Ａ:'A' }`. this throws `Invalid character` error in IE-11 browser.

**Comment by cibernox** [comment]
Interesting. A new way Internet Explorer breaks the web. Yay!

I supposed that we can replace the non-utf8 chars by their escaped versions and babili will work. Let me see if I can find the source from where I took this initially.

**Comment by kumkanillam** [comment]
There is issue with PR already is in the progress in babili project. [Fix removal of quotes from property names](https://github.com/babel/babili/pull/543/files) . Thank you so much for your time :-) Thank you for this Power Packed Addon.
