### ISSUE TITLE
Option select issue on iOS introduced in v1.7.0

### ISSUE THREAD

**Issue by jdurand** [cibernox/ember-power-select#919]
*Issue introduced in **v1.7.0** and present in every subsequent versions*
*Reproduced on **iOS Safari***

The options wrapper `.ember-power-select-options` stays highlighted instead of immediately blurring out when an option is pressed. The option never selects unless it is carefully pressed for a few seconds and then released.

< 1.7.0:
![< 1.7.0](https://i.gyazo.com/a6279b450ab42307d283cd41ce70f403.gif)

\>= 1.7.0:
![>= 1.7.0](https://i.gyazo.com/8099071db7128f519f7513a2fe5f3bf8.gif)

Live example:
http://widgets.dev.libroreserve.com/booking/DEMO/DEMO

**Comment by cibernox** [comment]
Sorry for the delay, I was on holidays.

On the link you posted I cannot se that select, but other selects seem to work just fine in chrome and safari, but I don't own an iOS device. However from your gif seems that you are using a mouse.

How can I reproduce that error?

I can't think in any change in 1.8 that would case such a big regression.

**Comment by jdurand** [comment]
This works on most browsers and devices. The problem is only present on iOS devices.

I captured the gif Xcode's iPhone Simulator, that's why you see a mouse.

**Comment by jdurand** [comment]
And the problem was introduced in 1.7.0.
I'll try dig a little more today.

**Comment by cibernox** [comment]
Thanks. I'll also install xcode and the emulator. It's always good to have it.

**Comment by MatthewPringle** [comment]
I can confirm this is a bug on the newer iOS. What is really strange is that some of the demo pages do not work yet this page does http://www.ember-power-select.com/docs/action-handling

**Comment by MatthewPringle** [comment]
Ok think I might have figured this out. I can't test as I haven't ever used Power Select because of this bug.

So I wrote my own, and then had a bug, on device only, not simulator, where if focused on the input, clicking any of the list, with an action attached didn't seem to trigger the event. Seems like the same problem.

So anyway, my fix was to add an active class to the clickable options. That seems to get Safari's attention and everything works fine.

Can you try this @jdurand

**Comment by cibernox** [comment]
> my fix was to add an active class to the clickable options

Can you expand on what you mean by that?

**Comment by MatthewPringle** [comment]
OK, in my autocomplete, the code for the list / dropdown of results

```
{{#each results as |result|}}
        <li role="button" {{action "select" result.value result.label on="click"}}>{{result.label}}</li>
{{/each}}

```
The li has a hover class which highlights the items, clicking one fires an action selecting that item and populating the input with it.

Kinda standard, works in everything except on my active iPhone. The clicks on the individual items / li's wouldn't fire if the keyboard was showing and the user was focused on the input they were typing into.

Pretty much like the original bug above in terms of behaviour.

My solution was to, in the CSS, that targeted and styled the li,  give it an active state.

```
li:active {
background-color: grey;
}
```

**Comment by cibernox** [comment]
You say that if the `<li>` doesn't have a certain class the click events don't fire white an input is focused? 

That doesn't make much sense.

**Comment by jdurand** [comment]
@cibernox from what I understand, it's about the `active` pseudoclass being defined in CSS... I'm trying this out right now.

**Comment by cibernox** [comment]
@jdurand But afaik, only anchors, and maybe buttons have that `:active` pseudoclass. `<li>`s don't.

**Comment by MatthewPringle** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/:active
 It is commonly used on <a> and <button> elements, but may be used on other elements, too.

Anyway, I find that sometimes a bug on device, on iOS, can be solved by adding a background or an active state in the css. It just fixes some random bug.

But it just worked for me now, so I thought I would just see if jdurand could give it a simple test.

**Comment by jdurand** [comment]
@MatthewPringle it didn't fix this specific issue:
![](https://i.gyazo.com/e35b34804b6f08532c6c793e62e1a1fb.gif)

Still a nice find though 👍

**Comment by jdurand** [comment]
Ok, I narrowed it down to the jQuery-less implementation of `closest` in `addon/components/power-select/options.js`

The following fixes the issue:

```
(function(ElementProto) {
  if (typeof ElementProto.matches !== 'function') {
    ElementProto.matches = ElementProto.msMatchesSelector || ElementProto.mozMatchesSelector || ElementProto.webkitMatchesSelector;
  }

  if (typeof ElementProto.closest !== 'function') {
    ElementProto.closest = function closest(selector) {
      $(this).closest(selector);
    };
  }
})(window.Element.prototype);
```

I'm working on fixing this without jQuery and will submit a PR.

**Comment by cibernox** [comment]
many browsers have `element.closest` implemented natively. If there is some sort of polyfill I'd happily use it

**Comment by jdurand** [comment]
right... so the issue here is not that `closest` (and/or `matches`) is not implemented correctly; it's that the native function is not implemented correctly.

I can either (1) conditionally override the native functions (even if they exist) or (2) simply define them as isolated functions...
I'm in favor of 2.

@cibernox what's your call?

**Comment by jdurand** [comment]
ok... I no I'm wrong the polyfill function still doesn't work like the jQuery one... I'll dig a little deeper.

**Comment by cibernox** [comment]
I find that weird because desktop and iphone safari are essentially the same browser and if it was something like `Element#closest` being buggy (which would be a pretty big fail by the safari team) i'd expect to also fail in desktop.

**Comment by jdurand** [comment]
Yeah... I also expected every other Webkit browser to handle this the same way, but apparently, there's some iOS specific issue here.

**Comment by jdurand** [comment]
So... The problem is far simpler.

The `touchend` event listener was still expecting `optionItem` to be an array (as is the case with jQuery functions) but the native `closest` returns an element.

The following check doesn't take this into account and returns prematurely:

```
if (!optionItem || !(0 in optionItem)) {
  return;
}
```

and this fails:

````
let optionIndex = optionItem[0].getAttribute('data-option-index');
````

I'm submitting a PR for this.
