### ISSUE TITLE
Disable few options from selected list in power-select-multiple

### ISSUE THREAD

**Issue by arparthasarathi** [cibernox/ember-power-select#922]
I would like to **disable a few options** from a list of options in power-select-multiple. For example, if there are **10 option**s in the selected list of power-select-multiple, I would like to **disable the first three options** i.e., there should be **no option to remove** the first three option from the list.

Currently there is a functionality to disable the entire power-select-multiple. But I couldn't find out a way to disable a particular option alone.

In the screenshot below, I would like to disable the selected option **Tomster** i.e., there should be no option to remove the option from the power-select-multiple box but I should be able to remove **Miguel**

![image](https://cloud.githubusercontent.com/assets/5359707/26580717/f95d115e-4556-11e7-9c09-b55e57d2fb94.png)

![image](https://cloud.githubusercontent.com/assets/5359707/26580723/ffab20be-4556-11e7-8e24-a06888cabd3b.png)

![image](https://cloud.githubusercontent.com/assets/5359707/26580726/044d1a46-4557-11e7-9099-237d132a504c.png)

Thanks in advance.

**Comment by gentlefox** [comment]
`option.set('disabled', true);`
Visit this page and scroll down to:
[Disabling specific options or groups](http://www.ember-power-select.com/docs/the-list)

**Comment by arparthasarathi** [comment]
Sorry for not being clear. I have updated the issue with screenshots and further details. Hope that explains the scenario.

**Comment by cibernox** [comment]
The way to implement this is with a custom triggerComponent. I'm triaging old issues. 
Feel free to reopen if you need help with the custom `triggerComponent`.

**Comment by jevanlingen** [comment]
There is a much easier way to make this work.

Just give the options you want to stick `disabled: true` + add following css:
```
.ember-power-select-multiple-option--disabled {
	opacity: 0.6;
	pointer-events: none;
}

```

**Comment by BMahabir** [comment]
> There is a much easier way to make this work.
> 
> Just give the options you want to stick `disabled: true` + add following css:
> 
> ```
> .ember-power-select-multiple-option--disabled {
>     opacity: 0.6;
>     pointer-events: none;
> }
> 
> .ember-power-select-multiple-option--disabled .ember-power-select-multiple-remove-btn {
>     display: none;
> }
> ```

Just wanted to say @jevanlingen your reply here helped me with this very issue today!  Cheers
