### ISSUE TITLE
selected changes Ember Array to normal array on item delete

### ISSUE THREAD

**Issue by mastastealth** [cibernox/ember-power-select#928]
I have a parent component with a `currentItems` property. I define it as an `Ember.A([])`. Within that parent component I have a dropdown of "predefined items", that upon selection, will trigger an action in the parent to `this.get(currentItems).pushObject(newThing)`.

This works great, as the parent component then pushes `currentItems` as the `selected` for my EPS. However, when I remove the items so that there's none left, then try to readd from the filters, I get a `this.get(...).pushObject is not a function` error. What I use the inspector to check what happens I notice currentItems turned into a "normal" array. 

Alternatively, just trying to use `currentItems` as a normal array, and then `this.get(currentItems).push(newThing)` will also not work as expected, since I have to _click_ the EPS input before the new item actually shows up, it won't just update live like the other method.

Which method should I stick with, and how would I go about either issue?

**Comment by cibernox** [comment]
TBH I'm a bit lost on the issue. Generally speaking, if you want push/pops to be tracking by Ember in general (this is non EPS specific) you must always use `push/popObject` or replace the array entirely.

That said, I don't really grok the issue. If you could provide an example, perhaps using ember-twiddle, that would be helpful.

**Comment by mastastealth** [comment]
@cibernox Welp, looks like this one is on me since the [example](https://gist.github.com/mastastealth/ce78144540a7f639e2c270fa6f1f5770) does work as expected. Never mind. 😅
