### ISSUE TITLE
Placeholder not showing (1.8.4)

### ISSUE THREAD

**Issue by mitchiru** [cibernox/ember-power-select#939]
Everything works but the Placeholder for the select field. it is just emtpy before selecting any option.

`{{#power-select
  search=(action "searchZips")
  placeholder="Ort oder PLZ"
  loadingMessage="Postleitzahlen werden geladen"
  noMatchesMessage="Es wurden keine Postleitzahl gefunden"
  searchMessage="Suche Postleitzahlen"
  ariaLabel="Suche Postleitzahlen"

  selected=zipSelect
  renderInPlace=true
  onchange=(action (mut zipSelect))

  as |found|
}}{{found.id}} {{found.city}}{{/power-select}}`

![screen shot 2017-06-19 at 11 35 07](https://user-images.githubusercontent.com/892231/27279002-6b7885f2-54e3-11e7-915b-5da582dc0615.png)

**Comment by cibernox** [comment]
I might need more information. As you can see from the docs (http://www.ember-power-select.com/docs/the-trigger) the placeholder option works, so there must be something particular of your example that makes it fail.

Can you provide a reproduction?

**Comment by mitchiru** [comment]
Hey, thx for asking. I guess I know what's wrong. In my case the value for selected is an empty string. When its null, it shows the placeholder.
