### ISSUE TITLE
selectedItemComponent rendering on 2 lines when using power-select-multiple

### ISSUE THREAD

**Issue by matthellstrom** [cibernox/ember-power-select#942]
When I use a selectedItemComponent on an ember-power-select-multiple it wraps the component value in a div which makes it display on a second line.
<img width="269" alt="screen shot 2017-07-01 at 6 45 45 am" src="https://user-images.githubusercontent.com/14794936/27762552-fce010fc-5e28-11e7-85e4-52857dd7b459.png">
<img width="708" alt="screen shot 2017-07-01 at 6 45 20 am" src="https://user-images.githubusercontent.com/14794936/27762555-04cc3dd6-5e29-11e7-8098-2745035e0d6a.png">

**Comment by matthellstrom** [comment]
I'm using ember-power-select-with-create.

**Comment by matthellstrom** [comment]
Without the selectedItemComponent

<img width="507" alt="screen shot 2017-07-01 at 8 43 35 am" src="https://user-images.githubusercontent.com/14794936/27763496-8f0ee682-5e39-11e7-86a7-baa990f8c5aa.png">
<img width="515" alt="screen shot 2017-07-01 at 8 44 06 am" src="https://user-images.githubusercontent.com/14794936/27763497-90c1e920-5e39-11e7-8f29-e6a4b1a2ec26.png">

**Comment by matthellstrom** [comment]
Component

<img width="202" alt="screen shot 2017-07-01 at 8 45 59 am" src="https://user-images.githubusercontent.com/14794936/27763513-c04ca6e4-5e39-11e7-97c3-5df7af9177da.png">

**Comment by cibernox** [comment]
@matthellstrom Can you add `tagName: ''` to your component so it doesn't have a wrapper div?

**Comment by matthellstrom** [comment]
Would I put that in the components .js file?

**Comment by cibernox** [comment]
Yes.

**Comment by matthellstrom** [comment]
Yes! Perfect! Thank you!

**Comment by cibernox** [comment]
👍
