### ISSUE TITLE
1.9.1 SyntaxError: ember-power-select/components/power-select-multiple.js: @ember/utils does not have a isEqual import

### ISSUE THREAD

**Issue by urbany** [cibernox/ember-power-select#951]
Hi @cibernox 

Just installed ember-power-select@1.9.1 and I'm getting an error on build:

```
SyntaxError: ember-power-select/components/power-select-multiple.js: @ember/utils does not have a isEqual import
  1 | import Component from '@ember/component';
  2 | import { computed } from '@ember/object';
> 3 | import { isEqual } from '@ember/utils';
...
```

Using: ember-source@2.14.0

**Comment by cibernox** [comment]
@urbany Update to babel 6.6.0. I'm working of a fix so people don't require this.

**Comment by urbany** [comment]
Just checked to make sure with `npm list` and I'm using `ember-cli-babel@6.6.0` already

**Comment by cibernox** [comment]
`npm list` list also dependencies  of sub dependencies. Is *your app* using this? i'd just suggest wipe nodemodules just in case.

**Comment by urbany** [comment]
Yeah, i checked with `npm list --depth=0` (an on my deps I have: `"ember-cli-babel": "^6.6.0"`) actually, i'll `rm -rf node_modules` and try again

**Comment by urbany** [comment]
After `rm -rf node_modules` + updating all in-repo addons to `ember-cli-babel@6.6.0 ` it's working now. Thanks 👍
