### ISSUE TITLE
item was not render after select

### ISSUE THREAD

**Issue by marendra** [cibernox/ember-power-select#956]
ember-power-select didn't render after select, i mean that the result was not shown in box eventhough the selected property already updated with the data.

This is my javascript in controller:
                   businessCategory:'',
                   actions:{
                                    setCategory(value){
                                            const category = value.get("category")
                                             this.set("businessCategory",category);
                                             console.log(this.get("businessCategory"))  }
                                          }

and the template:
                      {{#power-select  class="input" selected=setCategory options=model onchange=
                                   (action "setCategory") as |category|}}
                                  {{category.category}}
                      {{/power-select}}

with model of :
                       category:DS.attr('string')

im using ember version 2.13.3

**Comment by kumkanillam** [comment]
@marendra For `selected` attribute you need to provide property, and you need to provide action for `onchange` .
```
selectedCategory:'', //to maintain the selected state.
businessCategory:'',
actions:{
setCategory(value){
const category = value.get("category")
this.set("businessCategory",category);
this.set('selectedCategory',value); //we need to set the selected property as its.
console.log(this.get("businessCategory")) }
}
```
and the template,
```
{{#power-select class="input" selected=selectedCategory options=model onchange=(action "setCategory") as |category|}}
{{category.category}}
{{/power-select}}
```

**Comment by marendra** [comment]
thanks for quick reply @kumkanillam , 
but i tried your solution by adding  selectedCategory on the controller, still not render

**Comment by kumkanillam** [comment]
I tried it in[ twiddle](https://ember-twiddle.com/aec0439e009dcf5fbd1de6546428a607?openFiles=controllers.application.js%2C) it's working. if you can provide the not working ember-twiddle it would great identify the issue.

**Comment by cibernox** [comment]
@marendra I believe you are misunderstanding how to use the action and pass in the selected value. Perhaps the examples in this section can help you: http://www.ember-power-select.com/docs/action-handling

**Comment by marendra** [comment]
@kumkanillam okay my mistake i put this.set("selectedCategory",value.category), it suppose to be this.set("selectedCategory",value) , thanks you so much
