### ISSUE TITLE
'selectChoose' integration test is not working

### ISSUE THREAD

**Issue by raphaelns-developer** [cibernox/ember-power-select#957]
When i use 'selectChoose('.t-select-user', '.ember-power-select-option', 3); // Third option' on my integration test i received this message:

`Uncaught (in promise) Error: You called "selectChoose('.test-role-selector', '.ember-power-select-option')" but ".ember-power-select-option" didn't match any option
    at selectChoose$ (http://localhost:4200/assets/tests.js:1631:17)
    at tryCatch (http://localhost:4200/assets/vendor.js:8619:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (http://localhost:4200/assets/vendor.js:8886:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (http://localhost:4200/assets/vendor.js:8652:21)
    at GeneratorFunctionPrototype.invoke (http://localhost:4200/assets/vendor.js:8694:37)
    at <anonymous>
`

I managed to resolve this problem just calling `clickTrigger('.test-role-selector');` before call 'selectChoose', but accordly to the documentation the 'selectChoose' was suposed to care of the entire process of opening a select and choosing.
My test looks like this:

```js
clickTrigger('.test-role-selector');
selectChoose('.test-role-selector', '.ember-power-select-option', 0);
```

I'm doing something wrong? Why i have to call 'clickTrigger'?

**Comment by cibernox** [comment]
`selectChoose` used as a global is an acceptance test helper, not integration. You can however do `import { selectChoose } from 'ember-power-select/helpers'.

Check if that is the reason.

**Comment by raphaelns-developer** [comment]
I'm using integration test helper:

`import { clickTrigger, selectChoose } from '../../../helpers/ember-power-select';`

**Comment by cibernox** [comment]
I don't know then, if you can provide me with a failing test I can look at it, but it looks like it should work.

**Comment by raphaelns-developer** [comment]
I created a repo with a test project using the last version of Power Select and a test that fail because use 'select Choose'.
https://github.com/raphaelns-developer/power-select-test

**Comment by cibernox** [comment]
Ok, that is clear now. Your misconception is that the helper is asynchronous and you need to await for it to finish before asserting the result.

```diff
diff --git a/tests/integration/components/my-component-test.js b/tests/integration/components/my-component-test.js
index 14a31e7..2f8196e 100644
--- a/tests/integration/components/my-component-test.js
+++ b/tests/integration/components/my-component-test.js
@@ -6,11 +6,11 @@ moduleForComponent('my-component', 'Integration | Component | my component', {
   integration: true
 });

-test('it renders', function(assert) {
+test('it renders', async function(assert) {

   this.render(hbs`{{my-component}}`);

-  selectChoose('.test-trigger', '.ember-power-select-option', 0);
+  await selectChoose('.test-trigger', '.ember-power-select-option', 0);

   assert.equal(this.$('.selected-role').text().trim(), 'role1');
 });
diff --git a/typings/ember/ember.d.ts b/typings/ember/ember.d.ts
old mode 100755
new mode 100644
```

**Comment by cibernox** [comment]
I'm going to close, let me know if you need more explanation or if you think the docs can be improved so this is clearer. The docs are in this very same repo, inside the dummy app.

**Comment by williamhaley** [comment]
I'm seeing the same issue after updating a package in my `yarn.lock`

```diff
 ember-native-dom-helpers@^0.5.4:
-  version "0.5.8"
-  resolved "https://registry.yarnpkg.com/ember-native-dom-helpers/-/ember-native-dom-helpers-0.5.8.tgz#34635c891474c640a63c4c4cf95a491b250edd6c"
+  version "0.5.9"
+  resolved "https://registry.yarnpkg.com/ember-native-dom-helpers/-/ember-native-dom-helpers-0.5.9.tgz#30ba3e8085d56a95951590eadcb4935b8534f293"
```

Even though I'm using `await` on my `render` and on my power select helpers, I get this error. I don't know if this is a race condition and the assertions are running before the power select renders or what.

I'm not sure why updating this package is causing this issue. My only failing test is around `power-select` after this update.

If I revert `ember-native-dom-helpers` everything works fine again.

A workaround I found is to use `renderInPlace=true` on the select, that seems to get things going without affecting my functionality.

**Comment by cibernox** [comment]
If you update again to get 0.5.10 it should be fixed

**Comment by williamhaley** [comment]
You're right. I was able to remove `renderInPlace=true` after upgrading to `0.5.10` and things seem fine now. Thanks @cibernox!

**Comment by BryanCrotaz** [comment]
@cibernox I just got stuck on this one too. The docs are misleading:

```
selectChoose(cssPath, optionTextOrOptionSelector, index?)
This async helper allows you to select an option of a select by it's text, without worrying about if the select is single or multiple or if it is opened or closed.

fillIn('.username', 'Tomster');
selectChoose('.city-selector', 'Rome');
// ...
click('.submit-btn');
```

should be
```
await fillIn('.username', 'Tomster');
await selectChoose('.city-selector', 'Rome');
// ...
click('.submit-btn');
```
