### ISSUE TITLE
easier way to customize selected-item display

### ISSUE THREAD

**Issue by jamesarosen** [cibernox/ember-power-select#958]
### Use Case

I have a number of different uses of `{{#power-select}}`. Each has a fairly rich yielded block for rendering the options, but I want a simple text summary for the selected value. The gotcha is that each instance uses a different path for how to get the selected text. Currently, I need to create a one-off component for each of the `{{#power-select}}` instances.

### Idea 1: pass extra to selectedItemComponent

```hbs
{{#power-select
  content=people
  selectedItemComponent='power-select-selected-item'
  extra=(hash selectedTextPath='name') as |person|}}
  Some rich stuff using {{person}}
{{//power-select}}
```

That would work with
```js
// component:power-select-selected-item
export default Ember.Component.extend({
  tagName: '',
  extra: undefined,
  select: undefined,
  layout: hbs`{{get select.selected extra.selectedTextPath}}`
})
```

### Idea 2: First-Class Support for `selectedTextPath`

`template:power-select/trigger` has

```hbs
{{#if selectedItemComponent}}
  {{component selectedItemComponent option=(readonly select.selected) select=(readonly select)}}
{{else}}
  <span class="ember-power-select-selected-item">{{yield select.selected select}}</span>
{{/if}}
```

We could add a special property, like `selectedTextPath` directly to `component:power-select`, pass it down to `component:power-select/trigger`, and add change its template:
```hbs
{{#if selectedItemComponent}}
  {{component selectedItemComponent option=(readonly select.selected) select=(readonly select)}}
{{else if selectedTextPath}}
  <span class="ember-power-select-selected-item">{{get select.selected selectedTextPath}}</span>
{{else}}
  <span class="ember-power-select-selected-item">{{yield select.selected select}}</span>
{{/if}}
```

### Idea 3: yield an "is selected" flag

This would let me do something like

```hbs
{{#power-select
  content=people
  extra=(hash selectedTextPath='name') as |person select isSelected|}}
  {{#if isSelected}}
    {{person.name}}
  {{else}}
    Some rich stuff using {{person}}
  {{/if}}
{{//power-select}}
```

### Idea 4: accept an inverse yield

It would be lovely if we could use an `{{else}}` directly in `{{#power-select}}`:

```hbs
{{#power-select
  content=people
  extra=(hash selectedTextPath='name') as |person select|}}
    Some rich stuff using {{person}}
{{else}}
  {{person.name}}
{{//power-select}}
```

Unfortunately, this won't work because an `{{else}}` can't have any block parameters.

**Comment by cibernox** [comment]
The one I want to encourage is the first one. Create a `selectedItemComponent` and pass it. The main reason why I favour that is because it allows you to do anything you want (even add images, bold text, you name it) with a single option, unlike something like a property like `selectedTextPath` that only works for text-only.

The downside is obviously that you have to create a component, but it will be a trivial one. Probably you only need the template. Once we have the multi-block proposed on an RFC recently this nuance will go away and you will be able to specify a second block in the same template, but for now separate components is what we have.

**Comment by jamesarosen** [comment]
I can do this now with
```js
// component:power-select-selected-item
export default Ember.Component.extend({
  classNames: [ 'ember-power-select-selected-item' ],
  option: undefined,
  layout: hbs`{{get option selectedTextPath}}`,
  tagName: 'span',

  selectedTextPath: Ember.computed(function() {
    return this.nearestWithProperty('selectedTextPath').get('selectedTextPath');
  })
})
```
I don't love reaching _up_ to find that property, though.

**Comment by cibernox** [comment]
Reach out? Why can't you pass it from outside?

**Comment by cibernox** [comment]
```
{{#power-select options=options selected=selected selectedItemComponent=(component 'my-component' selectedTextPath="nickname") as |opt|}}
  {{opt.name}}
{{/opt}}```

**Comment by jamesarosen** [comment]
Ohh! Using `helper:component` to _curry_! Brilliant :)
