### ISSUE TITLE
onhighlight action

### ISSUE THREAD

**Issue by aalimovs** [cibernox/ember-power-select#961]
Is there a way to observe changes and/or fire action on highlight/hover of each item?

**Comment by cibernox** [comment]
No, there isn't. 
The reasons are:
- I never needed it
- I thought about it, but I thought that it could be somewhat expensive, as highlighting can happen at very high speed.
- An option can be highlighted by many different things. Hovering. Keyboard up/down. Even just opening the select already highlights one option (the selected value or the first one if none). Searching also does it. I wasn't sure what the right thing to do was, so I decided to do nothing. 

You still can add hover events, as at the end you are in control of the template:
```hbs
{{#power-select ... as |opt|}}
  <div onmouseover={{action "my-action" opt}}>{{opt}}</div>
{{/power-select}}
```

**Comment by aalimovs** [comment]
Perfect, that'll work! Thanks
