### ISSUE TITLE
Nothing is Displayed When the value of the selected Object is 0

### ISSUE THREAD

**Issue by batosi175** [cibernox/ember-power-select#962]
I happen to be using power select with some enumerators that include flags that have values: [0,1,2]
but if the value of 0 happens to be selected then nothing is shown in the selected field even if the option is visible in the dropdown. 

I assume this is due to the way that the ember-power-select-true-string-if-present.js helper does it's evaluations. 
```

import { helper } from '@ember/component/helper';

export function emberPowerSelectTrueStringIfPresent([bool]/* , hash*/) {
  return bool ? 'true' : false;
}

export default helper(emberPowerSelectTrueStringIfPresent);
```

My Code: 

controller.js
```
export default Ember.Controller.extend({
  aaa: [-3,-2,-1,0,1,2,3,4],
  aa: 0,
)}
```

index.hbs
```
{{#power-select
  searchEnabled=false
  selected=aa
  options=aaa
  onchange=(action (mut aa))
  as |name|
}}
  {{name}}
{{/power-select}}
```

here is what the dropdown with a set of numbers looks like
![image](https://user-images.githubusercontent.com/9507793/29144384-66ed9b18-7d1e-11e7-8f08-1f4a836794c8.png)

if any number but 0 get selected it will render normally. 
![image](https://user-images.githubusercontent.com/9507793/29144442-a588ad86-7d1e-11e7-8371-d5bf11f80820.png)

if the number selected happens to be 0 then renders nothing in the selection box
![image](https://user-images.githubusercontent.com/9507793/29144395-716b7c22-7d1e-11e7-83f3-c15866582fe3.png)

Possibly using an Ember.IsNone evaluation instead would allow for things like 0 to render still. Guess its just a side effect of having a truthy evaluation.

**Comment by cibernox** [comment]
This is a know issue. The value 0 in javascript is falsey and somewhere something doesn't let you select it. 

Although known, I never had time to track it.

**Comment by cibernox** [comment]
As a workaround, i'd suggest you use strings instead of number, and convert them to numbers again doing `parseInt` if you have to.

**Comment by batosi175** [comment]
Thanks for the quick reply. I ended up just comparing to an object itself { value: 0 },.... I'll try to dive in and see if I can find the source of the bug this weekend.

**Comment by cibernox** [comment]
Since there is several workarounds and they are all so simple (strings, objects with `value: number`) I'd consider it very very low priority.

**Comment by cibernox** [comment]
I decided not to fix this for now.
