### ISSUE TITLE
selectedItemComponent container?

### ISSUE THREAD

**Issue by mastastealth** [cibernox/ember-power-select#975]
I just noticed that the `selectedItemComponent` doesn't actually encompass the whole "component" that I want. I was looking to style the li item `.ember-power-select-multiple-option` which contains the remove button `span` and the `selectedItemComponent`. Is there a way to tweak that? 

Specifically, I was looking to do some color changes, based off clicking the tag itself, but noticed my class was binding to the div inside instead of the li, as I was envisioning it would.

**Comment by snewcomer** [comment]
@mastastealth the `selectedItemComponent`, `clear-btn`, and the dropdown icon are all child components of `.ember-power-select-trigger`.  I believe unfortunately there isn't a way to tweak that.  I would just target anything under `.ember-power-select-trigger`.  Does this help?

Regarding your comment about the `li`, are you referring to the dropdown options?  If so, I believe that `selectedItemComponent` should not have any affect there.

http://www.ember-power-select.com/docs/the-trigger

**Comment by cibernox** [comment]
Yep, that is a concious decission I made at the beginning. 90% of the time, people want to modify the content of the pills, not the pills themselves, and if they do usually they want to make the kind of cosmetic changes that can be done with CSS, like changing the remove button to the right, change colors or border radius and things alike.

If I had made the `selectedItemComponent` be the entire pill, people on that 90% would have to copy/paste a default template and inherit from a default class just to keep the default behaviour, so I  decided to make the most common use case the less annoying. 

You might be on the other 10% tho.

In your case, you need to customize the entire trigger. For that, you have to define your component that extends from `import EPSTrigger from 'ember-power-select/components/power-select/trigger';` and copy [the default template](https://github.com/cibernox/ember-power-select/blob/master/addon/templates/components/power-select/trigger.hbs) on yours, making the adjustments you want on the pills.
