### ISSUE TITLE
Select Choose fails due to change in findAll return type

### ISSUE THREAD

**Issue by igbopie** [cibernox/ember-power-select#977]
https://github.com/cibernox/ember-power-select/blob/master/addon-test-support/helpers.js

Line 99.

findAll is using native js, so the return is an array-like object but not array. It does not contain a filter function.

Need to do:
`Array.from(findAll(...)).filter....`

**Comment by snewcomer** [comment]
@igbopie I believe ember-native-dom helpers coerces to array [here](https://github.com/cibernox/ember-native-dom-helpers/blob/master/addon-test-support/find-all.js#L23)

**Comment by igbopie** [comment]
That is right... somehow my helpers don't seem align with the version required here. Maybe add some warning, or peer dependency?

**Comment by snewcomer** [comment]
@igbopie ah I see.  What version are you using for `ember-native-dom-helpers`?  Do you have that installed along side `ember-power-select`?

**Comment by snewcomer** [comment]
Any version `> 0.5.0` for `ember-native-dom-helpers` should work

**Comment by igbopie** [comment]
"version": "0.3.12" haha, I guess I have to update, but I don't have a direct dependency with this one. In my case comes from ember-basic-dropdown.

**Comment by igbopie** [comment]
I see, it is my issue because I am using this dependency thru a wrapper that we have, but I have another ember-basic-dropdown dependency, which is probably older than the one `ember-power-select` requires and it fails. Good to know anyway. Thanks!

**Comment by cibernox** [comment]
Glad it was fixed by the time I actually look at this!
Thanks @snewcomer !
