### ISSUE TITLE
Upgrading to 1.9.4 leads to chrome test failure w/ selectChoose

### ISSUE THREAD

**Issue by snewcomer** [cibernox/ember-power-select#979]
https://github.com/cibernox/ember-power-select/commit/f6a9ad41b892c15ee61a258d46cdf8a209d755b7

Will investigate further today on Chrome (firefox is a-ok) and tomorrow, but just wanted to throw it out there first.

**Comment by snewcomer** [comment]
I have narrowed it down to this [line](https://github.com/cibernox/ember-power-select/blob/master/addon-test-support/helpers.js#L86) and this [line](https://github.com/cibernox/ember-power-select/blob/master/addon/components/power-select.js#L281).

@cibernox this is a rather edge case, but where I select the EPS option is < 2px from where I opened the dropdown after being triggered to scroll into view.  I'll keep evaluating what options we have.

**Comment by snewcomer** [comment]
Ref https://github.com/cibernox/ember-power-select/pull/960

**Comment by cibernox** [comment]
I'm closing this. Feel free to reopen if you can reproduce it.
