### ISSUE TITLE
Not working with addon

### ISSUE THREAD

**Issue by jeffrey008** [cibernox/ember-power-select#981]
I am developing an addon which uses EPS. I did the following in `addon/styles/addon.less`:
``` css
// addon/styles/addon.less
@import 'ember-power-select';
```

However I got the following error:
```
FileError: 'ember-power-select.less' wasn't found. 
Tried - 
/Users/jcheung/workspace/repo/isnc/fbm/tmp/less_compiler-input_base_path-IKSqQKDt.tmp/0/ember-power-select.less,
/Users/jcheung/workspace/repo/isnc/fbm/tmp/less_compiler-input_base_path-IKSqQKDt.tmp/0/ember-power-select.less,
/Users/jcheung/workspace/repo/isnc/fbm/tmp/less_compiler-input_base_path-IKSqQKDt.tmp/0/ember-power-select.less,
ember-power-select.less in /Users/jcheung/workspace/repo/isnc/fbm/tmp/less_compiler-input_base_path-IKSqQKDt.tmp/0//addon.less on line 3, column 1:
2
3 @import 'ember-power-select';
4
```

**Comment by jeffrey008** [comment]
Here is how I fix this:

1. Make a file `addon/styles/ember-power-select.less`

1. Copy everything from https://github.com/cibernox/ember-power-select/blob/master/vendor/ember-power-select.css to that file

1. Done

This is a real bad hack. Can anyone show me a proper way to do this? Please.

**Comment by cibernox** [comment]
Personally I always placed my addon's styles in `/app/styles`, not in `addon/styles`, and from there it works just fine.

Is there any reason place them there?

**Comment by jeffrey008** [comment]
Hi @cibernox, what preprocessor are you using? I'm using `ember-cli-less`, and this addon will only compile `addon/styles/addon.less` to `vendor.css` and ignore everything in `app/styles`. Do you have any idea why the compiler cannot find the right path of `ember-power-select.less`?

**Comment by cibernox** [comment]
I also use that. Check this simple example: https://github.com/cibernox/nested-eps-addon-demo

**Comment by sumeetattree** [comment]
Facing a similar issue where ember cli cannot find the scss files. I am using this inside an engine and compiling everything into addon.scss. For engines it doesn't make any sense to put the styles in app/styles. Is there any way this can be resolved keeping the styles under addon directory? Thanks!

**Comment by cibernox** [comment]
@sumeetattree Unsure, I'm not very familiar with engines beyond the basics. If the styles were in `/addon` would that make any difference. I'm open to fix this.

**Comment by sumeetattree** [comment]
@cibernox I have no idea. I am trying to whip up a new app to test this out. I am not particularly familiar with the underlying workings of the build process either. Based on my finding I might have to report this to ember-engines repo. I'll post my updates when I can. Thank you for a quick response!

**Comment by sumeetattree** [comment]
@cibernox Take a look at this:
https://github.com/aexmachina/ember-cli-sass/issues/107#issuecomment-333700671

Involves manually passing the style path to the sassOptions. May be this will work?

**Comment by sumeetattree** [comment]
Diving a little bit deeper in, I found that adding the styles directory to the `sassOptions` of `ember-cli-sass` works.

Adding these lines to the `included` hook.

```
      const path = require('path');
      ......
      if (app.options.sassOptions && app.options.sassOptions.includePaths) {
        app.options.sassOptions.includePaths = app.options.sassOptions.includePaths.concat([path.join(__dirname, 'app/styles')]);
      }
```

Would you like me to send in a pull request?
