### ISSUE TITLE
How to get the object that contain the public API?

### ISSUE THREAD

**Issue by GrreyWang** [cibernox/ember-power-select#984]
could you provide a demo to show how to use the object that contain the public API?

**Comment by cibernox** [comment]
The object is an argument in all the hooks (onchange, oninput, onopen, onclose....) of the addon.

Check the `onfocus/onblur Actions` example in http://www.ember-power-select.com/docs/action-handling

**Comment by cibernox** [comment]
You can also see the full API of that public API object at the end of this page: http://www.ember-power-select.com/docs/api-reference

I'm closing this but feel free to open again if you need anything else.

**Comment by GrreyWang** [comment]
ok

**Comment by GrreyWang** [comment]
as read the page. there is description --> **All actions, subcomponents and blocks of Ember Power Select receive an object containing the public API of the component. That object contains (some of) the state of the component and some actions to interact with it.**

I guess the "All actions" refers the action that introduced in "Action Handling", I can get the object that contain the public api from the second argrument.

But what about the subcomponents and the blocks of Ember Power Select

**Comment by GrreyWang** [comment]
thanks for your patience.  please fix the description
