### ISSUE TITLE
Option groups from async search

### ISSUE THREAD

**Issue by adambedford** [cibernox/ember-power-select#988]
Is it possible to structure options in groups when performing an async search? The docs state that the search must return a collection or a promise that resolved to a collection, so I'm unclear whether groups are supported / how groups are supported.

One way I can think of would be to wait for the promise to resolve and map the results into groups in the search action but I think it would be cleaner if the API returned the results grouped and this library supported that.

**Comment by cibernox** [comment]
Your guess is correct. The collection of results can have groups inside, the only restriction is that because of simplicity, the options of each group can't be promises themselves. Other than that, whatever you return from `search` becomes the new list of options. With or without groups.
