### ISSUE TITLE
passing triggerClass to basic dropdown

### ISSUE THREAD

**Issue by ahmetemrekilinc** [cibernox/ember-power-select#993]
passing triggerClass to basic dropdown can be useful. Because we cannot change style of basic drop down elements of a certain power select element.

**Comment by cibernox** [comment]
`triggerClass` It is already passed to `dropdown.trigger` as `class`: https://github.com/cibernox/ember-power-select/blob/master/addon/templates/components/power-select.hbs#L22

**Comment by ahmetemrekilinc** [comment]
I think I was looking at the wrong place for what I was looking for. What I was looking for was `dropdownClass`. It is also passed to the `dropdown.content` https://github.com/cibernox/ember-power-select/blob/master/addon/templates/components/power-select.hbs#L50

Thank you, cibernox 👍
